select 
    COMPANY,
    ITEM_CODE_SEGMENT1||'.'||ITEM_CODE_SEGMENT2||'.'||ITEM_CODE_SEGMENT3 ITEM_CODE,
    ITEM_CATEGORY_SEGMENT1
from apps.xxakg_gl_details_statement_mv 
where 
    COMPANY='2110'
    and ITEM_CODE_SEGMENT1||'.'||ITEM_CODE_SEGMENT2||'.'||ITEM_CODE_SEGMENT3 in ('..',
'DRCT.LIME.0001',
'INDI.BOBN.0001',
'INDI.BOBN.0002',
'INDI.FABF.0001',
'INDI.FABF.0002',
'INDI.FABF.0003',
'INDI.FABF.0004',
'INDI.FABF.0008',
'INDI.FABF.0009',
'INDI.FABF.0010',
'INDI.FABF.0011',
'INDI.TFAB.0001',
'INDI.TFAB.0003',
'INDI.TFAB.0005',
'INDI.TFAB.0006',
'INDI.TFAB.0007',
'SCRP.BTRY.0010',
'SCRP.HYJK.0001')
group by
    COMPANY,
    ITEM_CODE_SEGMENT1,ITEM_CODE_SEGMENT2,ITEM_CODE_SEGMENT3,
    ITEM_CATEGORY_SEGMENT1


select
    distinct ITEM_CODE_SEGMENT1||'.'||ITEM_CODE_SEGMENT2||'.'||ITEM_CODE_SEGMENT3 ITEM_CODE
from apps.xxakg_gl_details_statement_mv 
where 
    COMPANY='2110'
    and ITEM_CATEGORY_SEGMENT1='INGREDIENT'
order by 1    



select
    distinct ITEM_CODE_SEGMENT1||'.'||ITEM_CODE_SEGMENT2||'.'||ITEM_CODE_SEGMENT3 ITEM_CODE,
    NVL(ITEM_CATEGORY_SEGMENT1,'X') Category
from apps.xxakg_gl_details_statement_mv 
where 
    COMPANY='2110'
    and account in (2050101)
    and NVL(ITEM_CATEGORY_SEGMENT1,'X') not in ('INGREDIENT')
order by 2 desc 
