SELECT
    PHA.SEGMENT1 PO_NUMBER,
    PHA.CLOSED_CODE,
    MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
    MC.SEGMENT1||'|'||MC.SEGMENT2 ITEM_CATG,
    DECODE(MSI.ITEM_TYPE,
        'FG', 'Finished Good',
        'P', 'Purchased Item',
        'NS','Non Stockable Item') ITEM_TYPE
FROM 
    PO.PO_HEADERS_ALL PHA,
    PO.PO_LINES_ALL PLA,
    INV.MTL_SYSTEM_ITEMS_B MSI,
    INV.MTL_ITEM_CATEGORIES MIC,
    INV.MTL_CATEGORIES_B MC
WHERE
    PHA.PO_HEADER_ID=PLA.PO_HEADER_ID
    AND PLA.ITEM_ID=MSI.INVENTORY_ITEM_ID
    AND MSI.INVENTORY_ITEM_ID=MIC.INVENTORY_ITEM_ID
    AND MSI.ORGANIZATION_ID=MIC.ORGANIZATION_ID
    AND MIC.CATEGORY_ID=MC.CATEGORY_ID
    AND PHA.SEGMENT1 IN ('I/SCOU/000447')
GROUP BY
    PHA.SEGMENT1,
    PHA.CLOSED_CODE,
    MSI.SEGMENT1,MSI.SEGMENT2,MSI.SEGMENT3,
    MC.SEGMENT1,MC.SEGMENT2,
    MSI.ITEM_TYPE
ORDER BY
    MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3
