SELECT 
          H.ORG_ID,
          XXAKG_COM_PKG.GET_ORGANIZATION_NAME (H.ORG_ID) OPERATING_UNIT,
          APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (H.SOLD_TO_ORG_ID) REGION, 
          H.SOLD_TO_ORG_ID CUSTOMER_ID,
          APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (H.SOLD_TO_ORG_ID) CUSTOMER_NUMBER, 
          APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (H.SOLD_TO_ORG_ID) CUSTOMER_NAME,
          H.ORDER_NUMBER,
          H.ORDERED_DATE,
          H.BOOKED_DATE,
          H.HEADER_ID,
          L.LINE_ID,
          L.INVENTORY_ITEM_ID,
          L.ORDERED_ITEM ITEM_CODE,
          (SELECT DESCRIPTION FROM INV.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=L.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID= L.SHIP_FROM_ORG_ID) ITEM_DESCRIPTION,
          L.ORDER_QUANTITY_UOM UOM_CODE,
          L.ORDERED_QUANTITY,
          (CASE 
            WHEN  L.ORDERED_ITEM='CMNT.OBAG.0004' THEN (L.ORDERED_QUANTITY*1000)/50
            ELSE DECODE (ORDER_QUANTITY_UOM,'MTN', NVL (ORDERED_QUANTITY, 0) * 20,NVL (ORDERED_QUANTITY, 0))
          END) CONVERT_BAG_QTY,
          L.SHIPPED_QUANTITY,
          (CASE 
            WHEN  L.ORDERED_ITEM='CMNT.OBAG.0004' THEN (L.SHIPPED_QUANTITY*1000)/50
            ELSE DECODE (ORDER_QUANTITY_UOM, 'MTN', NVL (L.SHIPPED_QUANTITY, 0) * 20, NVL (L.SHIPPED_QUANTITY, 0))
          END) CONVERT_SHIPPED_BAG_QTY,
          L.ACTUAL_SHIPMENT_DATE,
          L.UNIT_SELLING_PRICE,
          L.PRICING_DATE,
          L.PRICE_LIST_ID,
          L.ATTRIBUTE10 PRICE_LOCATION,
          L.ATTRIBUTE11 TRANSPORT_MODE,
          L.ATTRIBUTE13 DELIVERY_MODE,
          L.SHIP_TO_ORG_ID,
          XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION (L.SHIP_TO_ORG_ID) DELIVERY_SITE,
          L.SHIP_FROM_ORG_ID WAREHOUSE_ORG_ID,
          XXAKG_COM_PKG.GET_ORGANIZATION_NAME (L.SHIP_FROM_ORG_ID) WAREHOUSE_ORG_NAME,
/*         (SELECT DISTINCT NVL(HCP.PHONE_NUMBER,0)
            FROM APPS.HZ_PARTIES HP,APPS.HZ_RELATIONSHIPS HR,APPS.HZ_PARTIES H_CONTACT ,APPS.HZ_CONTACT_POINTS HCP,APPS.HZ_CUST_ACCOUNTS CUST,APPS.AR_CONTACTS_V ARC
            WHERE CUST.CUST_ACCOUNT_ID=H.SOLD_TO_ORG_ID AND ARC.CUSTOMER_ID=CUST.CUST_ACCOUNT_ID AND HR.SUBJECT_ID = H_CONTACT.PARTY_ID AND HR.OBJECT_ID = HP.PARTY_ID
            AND HCP.OWNER_TABLE_ID(+) = HR.PARTY_ID AND CUST.PARTY_ID = HP.PARTY_ID AND HCP.CONTACT_POINT_TYPE ='PHONE' AND HCP.STATUS = 'A' AND ARC.JOB_TITLE='Owner' 
            AND HR.RELATIONSHIP_ID=ARC.PARTY_RELATIONSHIP_ID) Owner_PHONE_NO,*/
            (SELECT DISTINCT NVL(HOC.PHONE_NUMBER,0)
            FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='PHONE' AND ARC.JOB_TITLE='Owner') Owner_PHONE_NO,
            (SELECT DISTINCT NVL(HOC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC  WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=H.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='EMAIL' AND ARC.JOB_TITLE='Owner') Owner_EMAIL,
--          (SELECT ARC.EMAIL_ADDRESS EMAIL FROM APPS.AR_CONTACTS_V ARC,APPS.HZ_CUST_ACCOUNTS ACCT WHERE ARC.CUSTOMER_ID=ACCT.CUST_ACCOUNT_ID AND ACCT.ACCOUNT_NUMBER=D.CUSTOMER_NUMBER AND ARC.JOB_TITLE='Owner' AND ARC.STATUS='A')  Owner_EMAIL,
/*          (SELECT DISTINCT NVL(HCP.PHONE_NUMBER,0)
            FROM APPS.HZ_PARTIES HP,APPS.HZ_RELATIONSHIPS HR,APPS.HZ_PARTIES H_CONTACT ,APPS.HZ_CONTACT_POINTS HCP,APPS.HZ_CUST_ACCOUNTS CUST,APPS.AR_CONTACTS_V ARC
            WHERE CUST.CUST_ACCOUNT_ID=H.SOLD_TO_ORG_ID AND ARC.CUSTOMER_ID=CUST.CUST_ACCOUNT_ID AND HR.SUBJECT_ID = H_CONTACT.PARTY_ID AND HR.OBJECT_ID = HP.PARTY_ID
            AND HCP.OWNER_TABLE_ID(+) = HR.PARTY_ID AND CUST.PARTY_ID = HP.PARTY_ID AND HCP.CONTACT_POINT_TYPE ='PHONE' AND HCP.STATUS = 'A' AND ARC.JOB_TITLE='Manager'
            AND HR.RELATIONSHIP_ID=ARC.PARTY_RELATIONSHIP_ID) Manager_PHONE_NO,*/
            (SELECT DISTINCT NVL(HOC.PHONE_NUMBER,0)
            FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='PHONE' AND ARC.JOB_TITLE='Manager') Manager_PHONE_NO,
            (SELECT DISTINCT NVL(HOC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC  WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=H.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='EMAIL' AND ARC.JOB_TITLE='Manager') Manager_EMAIL,
            /*
          (SELECT DISTINCT NVL(HOC.PHONE_NUMBER,0)
            FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='PHONE' AND ARC.JOB_TITLE='Manager') Manager_PHONE_NO,
          (SELECT NVL(HOC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC  WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='EMAIL' AND ARC.JOB_TITLE='Manager') Manager_EMAIL,
            (SELECT DISTINCT NVL(HOC.PHONE_NUMBER,0)
            FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='PHONE' AND ARC.JOB_TITLE='Owner') Owner_PHONE_NO,
          (SELECT NVL(HOC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC ,APPS.HZ_ORG_CONTACTS_V HOC  WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID AND HOC.STATUS = 'A' AND HOC.CONTACT_STATUS='A' AND HOC.CONTACT_PRIMARY_FLAG='Y'
            AND HOC.CONTACT_POINT_TYPE ='EMAIL' AND ARC.JOB_TITLE='Owner') Owner_EMAIL,
          (SELECT NVL(HOC.PHONE_NUMBER,0) FROM APPS.AR_CONTACTS_V ARC,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CONTACT_ID=H.SOLD_TO_CONTACT_ID AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID 
            AND HOC.CONTACT_POINT_TYPE ='PHONE') CONTACT_PHONE_NO,
          (SELECT NVL(HOC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC,APPS.HZ_ORG_CONTACTS_V HOC WHERE ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER AND ARC.CONTACT_ID=H.SOLD_TO_CONTACT_ID AND ARC.CUSTOMER_ID=L.SOLD_TO_ORG_ID 
           AND HOC.CONTACT_POINT_TYPE ='EMAIL') CONTACT_EMAIL,
           */
          XXAKG_ONT_PKG.GET_RETAILER_PHONE_NO (L.SHIP_TO_ORG_ID) RETAILER_PHONE_NO,
          (SELECT NVL(ARC.EMAIL_ADDRESS,0) FROM APPS.AR_CONTACTS_V ARC WHERE ARC.CUSTOMER_ID = H.SOLD_TO_ORG_ID AND ARC.CONTACT_ID = H.SOLD_TO_CONTACT_ID) EMAIL_ADDRESS,
          (SELECT NVL(HCA.ATTRIBUTE9,0) FROM APPS.HZ_CUST_ACCOUNTS HCA WHERE HCA.CUST_ACCOUNT_ID=H.SOLD_TO_ORG_ID) OFFICER_PHONE_NO
          ,H.FLOW_STATUS_CODE ORDER_STATUS
     FROM
        APPS.OE_ORDER_LINES_ALL L,
        APPS.OE_ORDER_HEADERS_ALL H
     WHERE H.ORG_ID = 85
        AND H.HEADER_ID=L.HEADER_ID
--        AND H.SOLD_TO_ORG_ID='3071'
--        AND H.ORDER_NUMBER IN ('1623002') --='1511361'  --1623021
        
        
        
        
        SELECT
            HOC.PHONE_NUMBER
            ,HOC.EMAIL_ADDRESS
--            ,ARC.*
--            ,HOC.*
            FROM
            APPS.AR_CONTACTS_V ARC
            ,APPS.HZ_ORG_CONTACTS_V HOC
            WHERE 1=1
--            AND ARC.CONTACT_ID='251171'
            AND ARC.CUSTOMER_ID='5028'
            AND ARC.CONTACT_NUMBER=HOC.CONTACT_NUMBER
--            AND ARC.JOB_TITLE=HOC.JOB_TITLE
            AND ARC.JOB_TITLE='Owner'
--            AND HOC.STATUS = 'A'
--            AND HOC.CONTACT_STATUS='A'
--            AND HOC.CONTACT_PRIMARY_FLAG='Y'
--            AND HOC.CONTACT_POINT_TYPE ='PHONE'


------------------------------------------------------------------------------------------------

SELECT
ORG_ID
,OPERATING_UNIT
,REGION
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,ORDER_NUMBER
,ORDERED_DATE
,BOOKED_DATE
,LISTAGG(ITEM_DESCRIPTION||'-'||QUANTITY||'-'||UOM_CODE, ',') WITHIN GROUP (ORDER BY ITEM_CODE,UOM_CODE) AS QTY
FROM
(
SELECT
ORG_ID
,OPERATING_UNIT
,REGION
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,ORDER_NUMBER
,ORDERED_DATE
,BOOKED_DATE
,SUM(ORDERED_QUANTITY) QUANTITY
,ITEM_CODE
,ITEM_DESCRIPTION
,UOM_CODE
--,LISTAGG(ITEM_DESCRIPTION||'-'||ORDERED_QUANTITY||'-'||UOM_CODE, ',') WITHIN GROUP (ORDER BY ITEM_CODE,UOM_CODE) AS QTY
--,V.*
FROM
APPS.XXAKG_SCIL_ORDER_SMS_V V
WHERE ORDER_STATUS='BOOKED'
AND ITEM_CODE NOT IN ('EBAG.SBAG.0001','EBAG.SBAG.0002','EBAG.PBAG.0001','EBAG.PBAG.0002','EBAG.OBAG.0001','EBAG.CBAG.0001','EBAG.JBAG.0001')
AND TO_CHAR(ORDERED_DATE,'DD-MON-YYYY')>='29-APR-2019'
--AND ORDER_NUMBER='1746797'
GROUP BY
ORG_ID
,OPERATING_UNIT
,REGION
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,ORDER_NUMBER
,ORDERED_DATE
,BOOKED_DATE
,ITEM_CODE
,ITEM_DESCRIPTION
,UOM_CODE) ORD
WHERE 1=1
GROUP BY
ORG_ID
,OPERATING_UNIT
,REGION
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,ORDER_NUMBER
,ORDERED_DATE
,BOOKED_DATE

-------------------------------------------ITEM-----------------------------------------------
 SELECT ORDER_NUMBER 
,RTRIM(
         REGEXP_REPLACE(
           (LISTAGG(ITEM_DESCRIPTION||'-'||ORDERED_QUANTITY,',') WITHIN GROUP (ORDER BY ITEM_CODE) ),' ', ' '), ' ') AS SMS
--  ,RTRIM(
--         REGEXP_REPLACE(
--           (listagg(ITEM_DESCRIPTION||'-'||ORDERED_QUANTITY,',') WITHIN GROUP (ORDER BY ITEM_CODE) ), 
--           '([^,]*)(,\1)+($|,)', 
--           '\1\3'),
--         ',') as v2group
  FROM APPS.XXAKG_SCIL_ORDER_SMS_V
  WHERE  ORDER_NUMBER='1748419'
  GROUP BY ORDER_NUMBER
 