SELECT SHIPMENT_PRIORITY_CODE, ACTUAL_SHIPMENT_DATE,
  extract(month from ACTUAL_SHIPMENT_DATE) AS MONTH_NO,
  DECODE (EXTRACT(MONTH FROM ACTUAL_SHIPMENT_DATE), 1, 'JAN', 
                             2, 'FEB', 
                             3, 'MAR', 
                             4, 'APR',
                             5, 'MAY',
                             6, 'JUN', 
                             7, 'JUL', 
                             8, 'AUG', 
                             9, 'SEP',
                             10, 'OCT', 
                             11, 'NOV', 
                             12, 'DEC', 
                                'Not Defined') "Month", 
  TRUNC(ACTUAL_SHIPMENT_DATE, 'MM') AS HIRE_RATE
FROM APPS.OE_ORDER_LINES_ALL