    SELECT
    DBM.REGION_NAME,
    DOH.CUSTOMER_NUMBER,
    DOH.CUSTOMER_NAME,
    OOH.ORDER_NUMBER,
    TO_CHAR(OOH.ORDERED_DATE,'DD-MON-YYYY HH24:MI:SS') ORDERED_DATE,
    OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--    OOD.ORGANIZATION_NAME,
    OOD.ORGANIZATION_CODE,
    MOH.MOV_ORDER_NO,
    MOH.VEHICLE_NO,
--    OOL.ORDERED_ITEM,
    WSHD.ITEM_DESCRIPTION,
    NVL (OOL.ORDERED_QUANTITY, 0) DO_QUANTITY,
    NVL(WPB.NAME,0) BATCH_NO,
--    NVL(TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE),0) INVOICE_DATE,
--    NVL(MODT.VAT_CHALLAN_NO,0) VAT_CHALLAN_NO,
--    TO_CHAR(MODT.VAT_CHALLAN_DATE) VAT_CHALLAN_DATE,
    OOL.FLOW_STATUS_CODE ORDER_LINE_STATUS,
    WSHD.RELEASED_STATUS_NAME DELIVERY_STATUS
--    DOH.DO_STATUS,
--    MOH.MOV_ORDER_STATUS
    FROM APPS.OE_ORDER_HEADERS_ALL OOH,
    APPS.OE_ORDER_LINES_ALL OOL, 
    APPS.XXAKG_DEL_ORD_HDR DOH,
      APPS.XXAKG_MOV_ORD_DTL MODT,
      APPS.XXAKG_MOV_ORD_HDR MOH,
      APPS.WSH_DELIVERABLES_V WSHD,
      APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
      APPS.WSH_PICKING_BATCHES WPB,
     APPS.ORG_ORGANIZATION_DEFINITIONS OOD
      WHERE    1=1
      AND OOH.HEADER_ID=OOL.HEADER_ID
      AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
      AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
      AND MOH.ORG_ID = DOH.ORG_ID
      AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
      AND MOH.ORG_ID = OOL.ORG_ID
      AND DBM.ORG_ID = OOL.ORG_ID
      AND OOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
      AND OOL.LINE_ID = WSHD.SOURCE_LINE_ID
      AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
      AND WSHD.BATCH_ID=WPB.BATCH_ID(+)
      AND OOL.SHIP_FROM_ORG_ID=OOD.ORGANIZATION_ID
      AND     (:P_ORG_ID IS NULL OR (DOH.ORG_ID=:P_ORG_ID))
      AND     (:P_WAREHOUSE IS NULL OR (OOD.ORGANIZATION_CODE = :P_WAREHOUSE))
      AND     (:P_REGION_NAME_EXCLUDE IS NULL OR (DBM.REGION_NAME <> :P_REGION_NAME_EXCLUDE))
      AND     (:P_STATUS IS NULL OR (OOL.FLOW_STATUS_CODE = :P_STATUS))
      AND     (:P_DO_NUMBER IS NULL OR (DOH.DO_NUMBER = :P_DO_NUMBER))
      AND TRUNC(DOH.DO_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(DOH.DO_DATE)) AND NVL(:P_DATE_TO,TRUNC(DOH.DO_DATE))

