SELECT
LOOKUP_TYPE,
LOOKUP_CODE,
MEANING,
DESCRIPTION
,FLV.*
FROM
APPS.FND_LOOKUP_VALUES FLV
WHERE 1=1
--AND DESCRIPTION=:P_DESCRIPTION
AND LOOKUP_TYPE like '%XXAKG_RMC_CELL%'
--AND LOOKUP_CODE like '%IND%'
--AND MEANING LIKE '%Md. Arifuzzaman -35789%'
AND END_DATE_ACTIVE IS NULL