SELECT
--RBC.REGION_NAME,
ORD.PERIOD,
RBC.BLOCK_NAME TEAM,
SUM(SHIPPING_QUANTITY) SHIPPING_QUANTITY,
SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
--RBC.CELL_NAME CELL,
--TO_CHAR(HCA.CREATION_DATE,'DD-MON-YYYY') CREATION_DATE,
--RBC.CUSTOMER_NUMBER CUSTOMER_ID,
--RBC.CUSTOMER_NAME CUSTOMER_NAME,
--RBC.STATUS,
--RBC.REAILER ADDRESS
--RBC.*
FROM
APPS.XXAKG_REGION_BLOCK_CELL_V RBC
,APPS.XXAKG_HEADER_DETAIL_V ORD
--,APPS.HZ_CUST_ACCOUNTS HCA
WHERE 1=1
AND RBC.ORG_ID=ORD.ORG_ID
AND RBC.CUSTOMER_ID=ORD.SOLD_TO_ORG_ID
AND RBC.SHIP_SITE_LOCATION_ID=ORD.SHIP_TO_ORG_ID
--AND RBC.CUSTOMER_ID=HCA.CUST_ACCOUNT_ID
AND RBC.ORG_ID=84
--AND RBC.CUSTOMER_NUMBER IN ('18542')
--AND ORGANIZATION_CODE='RMT'
--AND PERIOD='OCT-18'
--AND DELIVERY_DATE BETWEEN '20-MAR-18' AND '22-MAR-18'
AND TO_CHAR(ORD.DELIVERY_DATE,'RRRR')='2018'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
RBC.BLOCK_NAME,
PERIOD
ORDER BY PERIOD


-----------------------------------***************-------------------------------------

SELECT
--RBC.REGION_NAME,
ORD.PERIOD,
RBC.BLOCK_NAME TEAM,
SUM(SHIPPING_QUANTITY) SHIPPING_QUANTITY,
SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
,OPEN_BALANCE
,DR_AMOUNT
,CR_AMOUNT
,CLOSING_BALANCE
--,SUM(OPEN_BALANCE) OPEN_BALANCE
--,SUM(DR_AMOUNT) DR_AMOUNT
--,SUM(CR_AMOUNT) CR_AMOUNT
--,SUM(CLOSING_BALANCE) CLOSING_BALANCE
--RBC.CELL_NAME CELL,
--TO_CHAR(HCA.CREATION_DATE,'DD-MON-YYYY') CREATION_DATE,
--RBC.CUSTOMER_NUMBER CUSTOMER_ID,
--RBC.CUSTOMER_NAME CUSTOMER_NAME,
--RBC.STATUS,
--RBC.REAILER ADDRESS
--RBC.*
FROM
APPS.XXAKG_REGION_BLOCK_CELL_V RBC
,APPS.XXAKG_HEADER_DETAIL_V ORD
,(WITH XX_CUSTOMER_SUMMARY_TAB
     AS (  SELECT CB.ORG_ID, APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CB.CUSTOMER_ID) REGION,
                  CUSTOMER_ID,
                  APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_WITH_NUMBER (CB.CUSTOMER_ID) CUSTOMER,
                  APPS.XXAKG_AR_PKG.GET_CUSTOMER_ADDRESS (CB.CUSTOMER_ID) ADDRESS,
                  NVL (SUM (NVL (DR_AMOUNT, 0) - NVL (CR_AMOUNT, 0)), 0) OPEN_BALANCE,
                  0 DR_AMOUNT,
                  0 CR_AMOUNT
             FROM APPS.XXAKG_AR_CUSTOMER_LEDGER_V CB
            WHERE     (:P_ORG_ID IS NULL OR ORG_ID = :P_ORG_ID)
                  AND (:P_CUSTOMER_ID_FROM IS NULL OR CUSTOMER_ID >= :P_CUSTOMER_ID_FROM)
                  AND (:P_CUSTOMER_ID_TO IS NULL OR CUSTOMER_ID <= :P_CUSTOMER_ID_TO)
                  AND GL_DATE < :P_DATE_FROM
--                  AND (:P_REGION IS NULL OR APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CB.CUSTOMER_ID) = :P_REGION)
--                  AND EXISTS(SELECT 1 FROM APPS.HZ_CUST_ACCOUNTS HCA WHERE CB.CUSTOMER_ID=HCA.CUST_ACCOUNT_ID AND (:P_CUSTOMER_STATUS IS NULL OR (HCA.STATUS = DECODE(:P_CUSTOMER_STATUS,'Active','A','Inactive','I'))))
         GROUP BY CUSTOMER_ID, CB.ORG_ID
         UNION ALL
           SELECT PS.ORG_ID, APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (PS.CUSTOMER_ID) REGION,
                  CUSTOMER_ID,
                  APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_WITH_NUMBER (PS.CUSTOMER_ID) CUSTOMER,
                  APPS.XXAKG_AR_PKG.GET_CUSTOMER_ADDRESS (PS.CUSTOMER_ID) ADDRESS,
                  0 OPEN_BALANCE,
                  SUM (GREATEST (PS.AMOUNT_DUE_ORIGINAL, 0)) DR_AMOUNT,
                  (0 - SUM (LEAST (PS.AMOUNT_DUE_ORIGINAL, 0))) CR_AMOUNT
             FROM APPS.XXAKG_AR_PAYMENT_SCHEDULES_V PS
            WHERE     NOT EXISTS
                             (SELECT 1
                                FROM APPS.AR_CASH_RECEIPTS_ALL CR
                               WHERE     PS.CASH_RECEIPT_ID = CR.CASH_RECEIPT_ID
                                     AND PS.ORG_ID = CR.ORG_ID
                                     AND NVL (CR.STATUS, 'AKG') IN ('CCRR', 'CC_CHARGEBACK_REV', 'NSF', 'REV', 'STOP'))
                  AND PS.ORG_ID = :P_ORG_ID
                  AND (:P_CUSTOMER_ID_FROM IS NULL OR PS.CUSTOMER_ID BETWEEN :P_CUSTOMER_ID_FROM AND :P_CUSTOMER_ID_TO)
                  AND PS.GL_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
--                  AND (:P_REGION IS NULL OR APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (PS.CUSTOMER_ID) = :P_REGION)
--                  AND EXISTS(SELECT 1 FROM APPS.HZ_CUST_ACCOUNTS HCA WHERE PS.CUSTOMER_ID=HCA.CUST_ACCOUNT_ID AND (:P_CUSTOMER_STATUS IS NULL OR (HCA.STATUS = DECODE(:P_CUSTOMER_STATUS,'Active','A','Inactive','I'))))
         GROUP BY PS.ORG_ID, PS.CUSTOMER_ID)
  SELECT ORG_ID, REGION,
         CUSTOMER_ID,
         CUSTOMER,
         ADDRESS,
         SUM (OPEN_BALANCE) OPEN_BALANCE,
         SUM (DR_AMOUNT) DR_AMOUNT,
         SUM (CR_AMOUNT) CR_AMOUNT
         ,(SUM (OPEN_BALANCE)+SUM (DR_AMOUNT)-SUM (CR_AMOUNT)) CLOSING_BALANCE 
    FROM APPS.XX_CUSTOMER_SUMMARY_TAB
GROUP BY ORG_ID, REGION,
         CUSTOMER_ID,
         CUSTOMER,
         ADDRESS
ORDER BY 1) LEDG
--,APPS.HZ_CUST_ACCOUNTS HCA
WHERE 1=1
AND RBC.ORG_ID=LEDG.ORG_ID
AND RBC.CUSTOMER_ID=LEDG.CUSTOMER_ID
AND RBC.ORG_ID=ORD.ORG_ID
AND RBC.CUSTOMER_ID=ORD.SOLD_TO_ORG_ID
AND RBC.SHIP_SITE_LOCATION_ID=ORD.SHIP_TO_ORG_ID
--AND RBC.CUSTOMER_ID=HCA.CUST_ACCOUNT_ID
AND RBC.ORG_ID=:P_ORG_ID
AND (:P_CUSTOMER_ID_FROM IS NULL OR RBC.CUSTOMER_ID BETWEEN :P_CUSTOMER_ID_FROM AND :P_CUSTOMER_ID_TO)
--AND RBC.CUSTOMER_NUMBER IN ('18542')
--AND ORGANIZATION_CODE='RMT'
--AND PERIOD='OCT-18'
--AND DELIVERY_DATE BETWEEN '20-MAR-18' AND '22-MAR-18'
--AND TO_CHAR(ORD.DELIVERY_DATE,'RRRR')='2018'
AND ORD.DELIVERY_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
RBC.BLOCK_NAME,
PERIOD
,OPEN_BALANCE
,DR_AMOUNT
,CR_AMOUNT
,CLOSING_BALANCE
ORDER BY PERIOD


