/* Formatted on 7/28/2019 5:58:48 PM (QP5 v5.287) */
SELECT FAT.APPLICATION_NAME,
       FLV.LOOKUP_TYPE,
       FLV.LOOKUP_CODE,
       FLV.MEANING,
       FLV.DESCRIPTION
       --,FLV.*
  FROM APPS.FND_LOOKUP_VALUES FLV,
       APPS.FND_LOOKUP_TYPES FLT,
       APPS.FND_APPLICATION_TL FAT
 WHERE     1 = 1
       AND FLT.APPLICATION_ID = FAT.APPLICATION_ID
       AND FLT.LOOKUP_TYPE = FLV.LOOKUP_TYPE
       AND FLT.SECURITY_GROUP_ID = FLV.SECURITY_GROUP_ID
       AND FLT.VIEW_APPLICATION_ID = FLV.VIEW_APPLICATION_ID
       AND FLV.LANGUAGE = USERENV ('LANG')
       AND FLT.LOOKUP_TYPE = 'XXAKG_DO_VEHICLE_LOAD_CAPACITY';

--------------------------------------------------------------------------------
SELECT FLEX_VALUE_ID,
       FLEX_VALUE,
       FLEX_VALUE_MEANING,
       DESCRIPTION,
       FFVV.*
  FROM APPS.FND_FLEX_VALUES_VL FFVV
 WHERE 1 = 1
--AND FLEX_VALUE_MEANING LIKE '%Viet%'
and FLEX_VALUE LIKE 'FG'
;


SELECT
*
FROM
APPS.FND_FLEX_VALUES FFV
WHERE 1=1
AND FLEX_VALUE LIKE 'NS'