/* Formatted on 11/16/2019 11:49:27 AM (QP5 v5.287) */
SELECT SUM (SHIPPED_BAG_QTY) SHIPPED_QUANTITY,
       MAX (LAST_UPDATE_DATE) LAST_REPORT_UPDATED
  FROM (SELECT --SUM(SHIPPED_QUANTITY) SHIPPED_QUANTITY
               (CASE
                   WHEN INVENTORY_ITEM_ID = 1024565
                   THEN
                      (NVL (SHIPPED_QUANTITY, 0) * 1000) / 50
                   --WHEN INVENTORY_ITEM_ID IN (24402,24408,206570,992039) THEN (NVL(SHIPPED_QUANTITY, 0)) * 20
                   ELSE
                      NVL (SHIPPED_QUANTITY, 0)
                END)
                  SHIPPED_BAG_QTY,
               DC.LAST_UPDATE_DATE
          FROM APPS.XXAKG_DISTRIBUTION_COST DC,
               APPS.XXAKG_DISTRIBUTOR_BLOCK_M R,
               APPS.ORG_ORGANIZATION_DEFINITIONS OD
         WHERE     1 = 1
               AND DC.CUSTOMER_ID = R.CUSTOMER_ID
               AND DC.ORG_ID = R.ORG_ID
               --AND      INVENTORY_ITEM_ID='206570'-- IN (24402,24408,206570,992039,1024565)
               AND DC.FROM_WAREHOUSE_ID = OD.ORGANIZATION_ID
               AND ACTUAL_SHIPMENT_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
               AND EXISTS
                      (SELECT 1
                         FROM INV.MTL_SYSTEM_ITEMS_B MSI
                        WHERE     DC.FROM_WAREHOUSE_ID = MSI.ORGANIZATION_ID
                              AND DC.INVENTORY_ITEM_ID =
                                     MSI.INVENTORY_ITEM_ID
                              AND MSI.SEGMENT1 = 'CMNT')
--GROUP BY INVENTORY_ITEM_ID
--HAVING NVL (R.REGION_NAME, 'Not Defined') = :P_REGION
--AND DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME) = :P_GHAT
       );


--------------------------------------------------------------------------------

  SELECT (CASE
             WHEN INVENTORY_ITEM_ID = 1024565
             THEN
                (NVL (SHIPPED_QUANTITY, 0) * 1000) / 50
             --WHEN INVENTORY_ITEM_ID IN (24402,24408,206570,992039) THEN (NVL(SHIPPED_QUANTITY, 0)) * 20
             ELSE
                NVL (SHIPPED_QUANTITY, 0)
          END)
            SHIPPED_BAG_QTY,
         DC.*
    FROM APPS.XXAKG_DISTRIBUTION_COST DC,
         APPS.XXAKG_DISTRIBUTOR_BLOCK_M R,
         APPS.ORG_ORGANIZATION_DEFINITIONS OD
   WHERE     1 = 1
         AND DC.CUSTOMER_ID = R.CUSTOMER_ID
         AND DC.ORG_ID = R.ORG_ID
         AND DC.FROM_WAREHOUSE_ID = OD.ORGANIZATION_ID
         --AND DC.CUSTOMER_ID = :P_CUSTOMER_ID
         --AND APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (DC.CUSTOMER_ID) = :P_CUSTOMER_NUMBER
         AND ORGANIZATION_CODE = :P_WAREHOUSE_ORG_CODE
         --AND ACTUAL_SHIPMENT_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
         AND TO_CHAR (ACTUAL_SHIPMENT_DATE, 'MON-RR') = :P_PERIOD
         --AND INVENTORY_ITEM_ID=1024565
         --AND INVENTORY_ITEM_ID IN (206570--,1024565
         --,24402,24408,992039)
         --AND CUSTOMER_ID='137156'
         --AND DC.MOV_ORDER_NO='MO/SCOU/1245372'
         AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_MOV_ORD_HDR MOV WHERE MOV.MOV_ORDER_NO=DC.MOV_ORDER_NO)
         AND EXISTS
                (SELECT 1
                   FROM INV.MTL_SYSTEM_ITEMS_B MSI
                  WHERE     DC.FROM_WAREHOUSE_ID = MSI.ORGANIZATION_ID
                        AND DC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
                        AND MSI.SEGMENT1 = 'CMNT')
--         AND NVL (R.REGION_NAME, 'Not Defined') = :P_REGION
--,ORDER_NUMBER
--HAVING NVL (R.REGION_NAME, 'Not Defined') = :P_REGION
--AND DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME) = :P_GHAT
ORDER BY 1, 3                                                            --, 4