select DOH.org_id,DOH.operating_unit,DODL.order_number,DOH.DO_NUMBER,MOH.MOV_ORDER_NO,
         DODL.ITEM_DESCRIPTION,sum(dodl.line_quantity)Line_Quantity,
         MOH.VEHICLE_NO,MOH.TRANSPORT_MODE,MOH.VEHICLE_TYPE,
         MOH.TRANSPORTER_NAME,MOH.WAREHOUSE_ORG_CODE,
         MOH.FINAL_DESTINATION,
         line_number,order_line_id,do_status,MOH.MOV_ORDER_STATUS,
         MOH.GATE_IN,MOH.GATE_IN_DATE,MOH.INITIAL_GATE_IN,
         MOH.INITIAL_GATE_IN_DATE,MOH.EMPTY_TRUCK_WT,
         MOH.EMPTY_TRUCK_WT_DATE,MOD.TRANSFER_LOADING_FLAG,
         MOD.TRUCK_LOADING_FLAG,MOD.VAT_IN_FLAG,
         MOD.VAT_RECEIVED_FLAG,MOD.VAT_CHALLAN_NO,
         MOH.GATE_OUT,MOH.DRIVER_NAME,MOH.DRIVER_MOBILE
 from XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
         XXAKG.XXAKG_DEL_ORD_HDR DOH,
         XXAKG.XXAKG_MOV_ORD_DTL MOD,
         XXAKG.XXAKG_MOV_ORD_HDR MOH
where 1=1
      and order_number=13102653
      and DODL.DO_HDR_ID=DOH.DO_HDR_ID
      and DOH.DO_HDR_ID=MOD.DO_HDR_ID(+)
      and MOD.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID(+)
      and do_status='GENERATED'
      and MOH.MOV_ORDER_STATUS='GENERATED'
group by DOH.DO_NUMBER,DODL.order_number,
       DODL.line_number,order_line_id,do_status,
       DODL.ITEM_DESCRIPTION,MOH.MOV_ORDER_NO,
       MOH.MOV_ORDER_STATUS,DOH.org_id,DOH.operating_unit,
       MOH.GATE_IN,MOH.GATE_IN_DATE,MOH.INITIAL_GATE_IN,
       MOH.INITIAL_GATE_IN_DATE,MOH.EMPTY_TRUCK_WT,
       MOH.EMPTY_TRUCK_WT_DATE,MOD.TRANSFER_LOADING_FLAG,
       MOD.TRUCK_LOADING_FLAG,MOD.VAT_IN_FLAG,
       MOD.VAT_RECEIVED_FLAG,MOD.VAT_CHALLAN_NO,
       MOH.VEHICLE_NO,MOH.TRANSPORT_MODE,
       MOH.FINAL_DESTINATION,MOH.GATE_OUT,
       MOH.WAREHOUSE_ORG_CODE,MOH.VEHICLE_TYPE,
       MOH.TRANSPORTER_NAME,
       MOH.DRIVER_NAME,MOH.DRIVER_MOBILE
       order by sum(dodl.line_quantity)
