-------------------------------SHAH CEMENT OPERATING UNIT----------------------------
SELECT  TH.ORGANIZATION_NAME OPERATING_UNIT,
M_FROM_LOCATION||'-'||OOD.ORGANIZATION_CODE FROM_LOCATION,
TO_LOCATION,
TRANSPORT_MODE,
PAYABLE_RATE,
DISTANCE,
TO_CHAR(START_DATE_ACTIVE) START_DATE_ACTIVE,
END_DATE_ACTIVE
,(SELECT FU.USER_NAME||'-'||PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TH.CREATED_BY=FU.USER_ID AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) CREATED_BY_USER
,(SELECT FU.USER_NAME||'-'||PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TH.LAST_UPDATED_BY=FU.USER_ID AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) LAST_UPDATED_BY_USER
--,TH.*
FROM
APPS.XXAKG_TRANSPORT_HIRERATE  TH
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 1=1
AND ORG_ID=85
AND TRANSPORT_MODE IN ('Company Truck','Company Bulk Carrier','Company District Truck','Company Barge')
AND TRANSPORT_MODE LIKE 'Company %'  --'Rental%'
AND END_DATE_ACTIVE IS NULL
AND FROM_LOCATION=OOD.ORGANIZATION_ID
AND OOD.ORGANIZATION_CODE='SCI'
--AND DISTANCE IS NOT NULL
--AND PAYABLE_RATE IS NOT NULL
--AND PAYABLE_RATE>=50
--AND TO_LOCATION='Ashulia'
--AND EXISTS (SELECT 1 FROM APPS.FND_USER FU WHERE FU.USER_ID=TH.CREATED_BY AND FU.USER_NAME='32053')


-------------------------------LONG STEEL OPERATING UNIT------------------------------
SELECT 
* 
FROM 
APPS.XXAKG_BIEE_TRANSPORT_HIRERATE BTH
WHERE 1=1
AND BTH.ORG_ID=87

------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.XXAKG_DIST_COST_MOV_V
WHERE 1=1
AND TRANSPORT_MODE='Company Truck'
AND ROWNUM<=2
