SELECT
MOH.MOV_ORDER_NO MOVE_NUMBER
,HIRE_RATE_AP HIRE_RATE
,READY_FOR_INVOICE
,MOH.TRANSPORTER_NAME
FROM
XXAKG.XXAKG_MOV_ORD_HDR MOH
WHERE 1=1
AND HIRE_RATE_AP=0
AND READY_FOR_INVOICE='Y'
AND TO_CHAR (MOH.MOV_ORDER_DATE, 'RRRR') = '2018'
AND MOH.ORG_ID=85
AND MOH.TRANSPORT_MODE='Rental Truck'
AND MOH.MOV_ORDER_TYPE='RELATED'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.MOV_ORDER_NO='MO/SCOU1031302'