SELECT *
                   FROM APPS.FND_LOOKUP_VALUES b
                  WHERE     b.lookup_type = 'CEMENT_COMPANY_REGION_USER'
                  
                  
SELECT 
LOOKUP_TYPE,
ATTRIBUTE_CATEGORY,
ATTRIBUTE13 REGION_NAME,
START_DATE_ACTIVE
--,FLV.*
FROM APPS.FND_LOOKUP_VALUES FLV
WHERE 1=1
AND FLV.LOOKUP_TYPE = 'CEMENT_COMPANY_REGION_USER'
AND END_DATE_ACTIVE IS NULL          
--AND  ATTRIBUTE13='Corporate North'