SELECT
ORG_ID
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,ADDRESS1 ADDRESS
,PARTY_SITE_NUMBER
--,REAILER||'-'||REAILER_ADDRESS "RETAILER LOCATION"
,LOCATION--||'-'||LOCATION_ADDRESS "Location"
--,ACSV.*
FROM
APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND ORG_ID=85
AND STATUS='A'
AND SITE_USE_CODE='BILL_TO'
--AND SITE_USE_CODE='SHIP_TO'
AND SITE_USE_STATUS='A'
AND ACCT_USE_STATUS='A'
AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE 1=1 AND  ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER )
--AND CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER

SELECT
*
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M
WHERE 1=1
--AND REGION_NAME='Held'
--AND CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER 


select
*
from
apps.XXAKG_AR_CUSTOMER_SITE_V
