SELECT 
         C.PERIOD_NAME,
         C.ATTRIBUTE_CATEGORY,
         B.PO_NUMBER,
         B.LC_NUMBER,
         A.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
         C.ATTRIBUTE5 GRN_NUMBER,
        TO_CHAR(RT.TRANSACTION_DATE,'MON-YY') GRN_PERIOD,
         SUM (NVL(C.AMOUNT,C.BASE_AMOUNT)) AMOUNT
FROM APPS.XXAKG_LC_DETAILS B,
         AP.AP_INVOICE_DISTRIBUTIONS_ALL C,
         AP.AP_INVOICES_ALL A,
         PO.RCV_SHIPMENT_HEADERS RSH,
        PO.RCV_TRANSACTIONS RT
   WHERE 
         C.ATTRIBUTE1 = TO_CHAR (B.LC_ID)
         AND C.INVOICE_ID = A.INVOICE_ID
         AND C.ATTRIBUTE5=RSH.RECEIPT_NUM
        AND RT.ORGANIZATION_ID IN (99)
         AND RSH.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
        AND RT.TRANSACTION_TYPE='RECEIVE'
         AND B.PO_NUMBER IN ('I/COU/000255')
         AND EXISTS
                (SELECT 1
                   FROM GL.GL_CODE_COMBINATIONS D
                  WHERE     D.CODE_COMBINATION_ID = C.DIST_CODE_COMBINATION_ID
                        AND D.SEGMENT3 IN ('2050107')
                        AND D.SEGMENT1 IN ( '2110','2120','2200','2300','2400')
                )
GROUP BY 
        C.PERIOD_NAME,
         B.PO_NUMBER,
         B.LC_NUMBER,
         A.DOC_SEQUENCE_VALUE,
         C.ATTRIBUTE_CATEGORY,
         C.ATTRIBUTE5,
         TO_CHAR(RT.TRANSACTION_DATE,'MON-YY')
ORDER BY 
    TO_DATE (C.PERIOD_NAME, 'MON-YY'),
    B.PO_NUMBER