/* Formatted on 10/16/2019 10:37:48 AM (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW APPS.XXAKG_CER_ORDER_SMS_V
(
   ORG_ID,
   OPERATING_UNIT,
   REGION,
   CUSTOMER_ID,
   CUSTOMER_NUMBER,
   CUSTOMER_NAME,
   ORDER_NUMBER,
   ORDERED_DATE,
   BOOKED_DATE,
   HEADER_ID,
   LINE_ID,
   INVENTORY_ITEM_ID,
   ITEM_CODE,
   ITEM_DESCRIPTION,
   UOM_CODE,
   ORDERED_QUANTITY,
   SHIPPED_QUANTITY,
   ACTUAL_SHIPMENT_DATE,
   UNIT_SELLING_PRICE,
   PRICING_DATE,
   PRICE_LIST_ID,
   PRICE_LOCATION,
   TRANSPORT_MODE,
   DELIVERY_MODE,
   SHIP_TO_ORG_ID,
   DELIVERY_SITE,
   WAREHOUSE_ORG_ID,
   WAREHOUSE_ORG_NAME,
   AM_PHONE_NO,
   DEALER_PHONE_NO,
   RETAILER_PHONE_NO,
   OFFICER_PHONE_NO,
   ORDER_STATUS,
   ORDER_LINE_STATUS,
   CANCELLED_QUANTITY,
   LAST_UPDATE_DATE
)
   BEQUEATH DEFINER
AS
   SELECT H.ORG_ID,
          XXAKG_COM_PKG.GET_ORGANIZATION_NAME (H.ORG_ID) OPERATING_UNIT,
          APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (H.SOLD_TO_ORG_ID) REGION,
          H.SOLD_TO_ORG_ID CUSTOMER_ID,
          APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (H.SOLD_TO_ORG_ID)
             CUSTOMER_NUMBER,
          APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (H.SOLD_TO_ORG_ID)
             CUSTOMER_NAME,
          H.ORDER_NUMBER,
          H.ORDERED_DATE,
          H.BOOKED_DATE,
          H.HEADER_ID,
          L.LINE_ID,
          L.INVENTORY_ITEM_ID,
          L.ORDERED_ITEM ITEM_CODE,
          (SELECT DESCRIPTION
             FROM INV.MTL_SYSTEM_ITEMS_B MSI
            WHERE     MSI.INVENTORY_ITEM_ID = L.INVENTORY_ITEM_ID
                  AND MSI.ORGANIZATION_ID = L.SHIP_FROM_ORG_ID)
             ITEM_DESCRIPTION,
          L.ORDER_QUANTITY_UOM UOM_CODE,
          L.ORDERED_QUANTITY,
          L.SHIPPED_QUANTITY,
          L.ACTUAL_SHIPMENT_DATE,
          L.UNIT_SELLING_PRICE,
          L.PRICING_DATE,
          L.PRICE_LIST_ID,
          L.ATTRIBUTE10 PRICE_LOCATION,
          L.ATTRIBUTE11 TRANSPORT_MODE,
          L.ATTRIBUTE13 DELIVERY_MODE,
          L.SHIP_TO_ORG_ID,
          XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION (L.SHIP_TO_ORG_ID)
             DELIVERY_SITE,
          L.SHIP_FROM_ORG_ID WAREHOUSE_ORG_ID,
          XXAKG_COM_PKG.GET_ORGANIZATION_NAME (L.SHIP_FROM_ORG_ID)
             WAREHOUSE_ORG_NAME,
          (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
             FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
            WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
                  AND ARC.CUSTOMER_ID = L.SOLD_TO_ORG_ID
                  AND HOC.STATUS = 'A'
                  AND HOC.CONTACT_STATUS = 'A'
                  AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
                  AND HOC.CONTACT_POINT_TYPE = 'PHONE'
                  AND ARC.JOB_TITLE = 'AM'
                  AND ROWNUM = 1)
             AM_PHONE_NO,
          (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
             FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
            WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
                  AND ARC.CUSTOMER_ID = L.SOLD_TO_ORG_ID
                  AND HOC.STATUS = 'A'
                  AND HOC.CONTACT_STATUS = 'A'
                  AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
                  AND HOC.CONTACT_POINT_TYPE = 'PHONE'
                  AND ARC.JOB_TITLE = 'Dealer'
                  AND ROWNUM = 1)
             Dealer_PHONE_NO,
          XXAKG_ONT_PKG.GET_RETAILER_PHONE_NO (L.SHIP_TO_ORG_ID)
             RETAILER_PHONE_NO,
          (SELECT NVL (HCA.ATTRIBUTE9, 0)
             FROM APPS.HZ_CUST_ACCOUNTS HCA
            WHERE HCA.CUST_ACCOUNT_ID = H.SOLD_TO_ORG_ID)
             OFFICER_PHONE_NO,
          H.FLOW_STATUS_CODE ORDER_STATUS,
          L.FLOW_STATUS_CODE ORDER_LINE_STATUS,
          L.CANCELLED_QUANTITY,
          L.LAST_UPDATE_DATE
     FROM APPS.OE_ORDER_LINES_ALL L, APPS.OE_ORDER_HEADERS_ALL H
    WHERE     H.ORG_ID = 83
          AND H.HEADER_ID = L.HEADER_ID
          AND H.ORDER_TYPE_ID = 1173
          AND L.ORDER_QUANTITY_UOM = 'PCS';
