/* Formatted on 7/27/2019 2:32:32 PM (QP5 v5.287) */
SELECT DBM.REGION_NAME,
       --HCA.CUST_ACCOUNT_ID Customer_ID,
       HCA.ACCOUNT_NUMBER "Customer No",
       NVL (HCA.ATTRIBUTE7, 'No DreamApps ID') "Old Legacy Number",
       HP.PARTY_NAME CUSTOMER_NAME,
       CSUA.LOCATION,
       (SELECT ARC.FIRST_NAME || ' ' || ARC.LAST_NAME
          FROM APPS.AR_CONTACTS_V ARC
         WHERE     ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND ARC.JOB_TITLE = 'Owner')
          "Owner Name",
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
               AND ARC.JOB_TITLE = 'Owner')
          Owner_PHONE_NO,
       (SELECT DISTINCT NVL (HOC.EMAIL_ADDRESS, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'EMAIL'
               AND ARC.JOB_TITLE = 'Owner')
          Owner_EMAIL,
       HP.CATEGORY_CODE CUSTOMER_CATEGORY,
       HCA.ATTRIBUTE10 "Bank Name",
       HCA.ATTRIBUTE4 "Instrument Type",
       (SELECT ARC.FIRST_NAME || ' ' || ARC.LAST_NAME
          FROM APPS.AR_CONTACTS_V ARC
         WHERE     ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND ARC.JOB_TITLE = 'Manager')
          BUSINESS_MANAGER,
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
               AND ARC.JOB_TITLE = 'Manager')
          Manager_PHONE_NO,
          (SELECT JOB_TITLE_CODE_MEANING 
          FROM APPS.AR_CONTACTS_V ARC
         WHERE     ARC.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
               AND ARC.JOB_TITLE = 'Manager')
          JOB_TITLE,
       AED.EMPLOYEE_NUMBER "Officer ID",
       AED.FULL_NAME "Assigned Officer of SCIL",
       AED.DESIGNATION "Job Title",
       HCA.ATTRIBUTE9 OFFICER_PHON_NO,
       TO_CHAR (HCA.CREATION_DATE, 'DD-MON-YYYY') CREATION_DATE,
       HCA.STATUS ACCOUNT_STATUS
  --,HCA.*
  FROM APPS.HZ_CUST_ACCOUNTS HCA,
       APPS.HZ_PARTIES HP,
       APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
       APPS.HZ_CUST_SITE_USES_ALL CSUA,
       APPS.HZ_CUST_ACCT_SITES_ALL CASA,
       APPS.PER_PHONES PP,
       APPS.AKG_EMPLOYEE_DETAILS AED
 WHERE     1 = 1
       AND CSUA.CUST_ACCT_SITE_ID = CASA.CUST_ACCT_SITE_ID
       AND HCA.CUST_ACCOUNT_ID = CASA.CUST_ACCOUNT_ID
       AND DBM.CUSTOMER_NUMBER = HCA.ACCOUNT_NUMBER
       AND HP.PARTY_ID = HCA.PARTY_ID
       AND HCA.ACCOUNT_NUMBER = '20072'
       AND SITE_USE_CODE = 'BILL_TO'
       AND PRIMARY_FLAG = 'Y'
       AND PP.PHONE_NUMBER(+) = HCA.ATTRIBUTE9
       AND AED.PERSON_ID(+) = PP.PARENT_ID
       AND NVL (AED.PERSON_STATUS, NULL) = 'Active Assignment'