SELECT 
OOH.ORG_ID,
APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (OOH.ORG_ID) OPERATING_UNIT,
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (OOH.SOLD_TO_ORG_ID) REGION, 
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NUMBER, 
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NAME,
SUM(OOL.ORDERED_QUANTITY) QTY,
--(CASE 
--WHEN  OOL.ORDERED_ITEM='CMNT.OBAG.0004' THEN (SUM(OOL.ORDERED_QUANTITY)*1000)/50
--ELSE DECODE (ORDER_QUANTITY_UOM,'MTN', NVL (SUM(ORDERED_QUANTITY), 0) * 20,NVL (SUM(ORDERED_QUANTITY), 0))
--END) BAG_QTY,
--(CASE 
--WHEN  OOL.ORDERED_ITEM='CMNT.OBAG.0004' THEN (SUM(OOL.SHIPPED_QUANTITY)*1000)/50
--ELSE DECODE (ORDER_QUANTITY_UOM, 'MTN', NVL (SUM(OOL.SHIPPED_QUANTITY), 0) * 20, NVL (SUM(OOL.SHIPPED_QUANTITY), 0))
--END) CONVERT_SHIPPED_BAG_QTY,
--SUM(OOL.SHIPPED_QUANTITY)QUANTITY
--,TRUNC(OOH.ORDERED_DATE) ORDERED_DATE
--,TRUNC(OOL.ACTUAL_SHIPMENT_DATE) INVOICE_DATE
TO_CHAR(DOH.DO_DATE,'DD-MON-RR') DO_DATE
--,OOH.*
--,OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1 
AND OOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOH.SOLD_TO_ORG_ID=DBM.CUSTOMER_ID
--AND DBM.REGION_NAME=:P_REGION_NAME
--AND DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')
AND DBM.CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = :P_PERIOD
--AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = :P_PERIOD
AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = :P_PERIOD
AND TO_CHAR (DOH.DO_DATE, 'DD-MON-RR') = :P_DO_DATE
--AND TO_CHAR(ORDERED_DATE,'RRRR')=:DATE_REQUIRED
--AND OOL.FLOW_STATUS_CODE=:LINE_STATUS
--AND OOH.ORDER_NUMBER=:ORDER_NUMBER
--AND OOL.SHIPMENT_PRIORITY_CODE=:DO_NUMBER
AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER 
--AND EXISTS(SELECT 1 FROM APPS.XXAKG_MOV_ORD_HDR MOH ,APPS.XXAKG_MOV_ORD_DTL MODT WHERE MOH.MOV_ORDER_NO=:MOVE_NUMBER AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER  )
--AND ROWNUM<=2
GROUP BY 
--OOL.ACTUAL_SHIPMENT_DATE
--OOH.ORDERED_DATE
TO_CHAR(DOH.DO_DATE,'DD-MON-RR')
,OOH.ORG_ID
,OOH.SOLD_TO_ORG_ID
--,OOL.ORDERED_ITEM
--,OOL.ORDER_QUANTITY_UOM
ORDER BY 
--OOL.ACTUAL_SHIPMENT_DATE 
--OOH.ORDERED_DATE
OOH.SOLD_TO_ORG_ID,
TO_CHAR(DOH.DO_DATE,'DD-MON-RR')
ASC

--------------------------------------------------------------------------------


SELECT
DBM.REGION_NAME
,DOH.CUSTOMER_NUMBER 
,DOH.CUSTOMER_NAME
,TO_CHAR(DOH.DO_DATE,'DD-MON-RR') DO_DATE
,SUM(DODL.LINE_QUANTITY) DO_QTY
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
--AND DBM.REGION_NAME=:P_REGION_NAME
AND DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')
--AND DBM.CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = :P_PERIOD
--AND TO_CHAR (DOH.DO_DATE, 'DD-MON-RR') = :P_DO_DATE
--AND DODL.ORDERED_ITEM_ID='206571'
--AND substr(DODL.ITEM_NUMBER,0,3)='TLH'
--AND DODL.ITEM_NUMBER='MPNA.ORCW.0001'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND DODL.ORDER_NUMBER IN ('1417741')
--AND DOH.DO_NUMBER IN ('DO/SCOU/1230161')
--AND DOH.DO_STATUS IN ('GENERATED')--CONFIRMED
--AND DOH.DO_DATE<='31-MAY-2019'
--AND TO_CHAR(DOH.DO_DATE,'DD-MON-RR')='23-JUL-19'
--AND DOH.DO_DATE BETWEEN '01-JAN-2010' and '30-APR-2018'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'DEC-17'
--AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2018'
--AND DOH.CUSTOMER_NUMBER='20059'
AND DOH.ORG_ID=85
GROUP BY
DBM.REGION_NAME
,DOH.CUSTOMER_NUMBER 
,DOH.CUSTOMER_NAME
,TO_CHAR(DOH.DO_DATE,'DD-MON-RR')
ORDER BY  
TO_CHAR(DOH.DO_DATE,'DD-MON-RR') 
ASC

--------------------------------------------------------------------------------

SELECT
--ORGANIZATION_NAME,
--ORGANIZATION_CODE,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
--ORDERED_QUANTITY,
--SUM(INVOICED_QUANTITY) INVOICED_QUANTITY,
--SUM(SHIPPED_QUANTITY) SHIPPED_QUANTITY
--SUM(INVOICED_QUANTITY) QUANTITY,
--SUM(ORDERED_AMT) AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--DO_NUMBER,
--PERIOD
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (OOH.SOLD_TO_ORG_ID) REGION, 
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NUMBER, 
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NAME,
ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
WHERE 1=1
AND ORG_ID=85
AND TO_CHAR (ORD.DELIVERY_DATE, 'DD-MON-RR') = :P_DO_DATE
AND PERIOD='JUN-19'
--AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
AND ROWNUM<=2