SELECT 
HCA.ACCOUNT_NAME, 
HCA.ACCOUNT_NUMBER
,RCTA.TRX_NUMBER 
,RCTL.EXTENDED_AMOUNT 
,RCTL.GROSS_EXTENDED_AMOUNT
,RCTD.GL_DATE 
FROM 
APPS.HZ_CUST_ACCOUNTS HCA
,APPS.RA_CUSTOMER_TRX_ALL RCTA
,APPS.RA_CUSTOMER_TRX_LINES_ALL RCTL 
,APPS.RA_CUST_TRX_LINE_GL_DIST_ALL RCTD 
WHERE 1=1
AND HCA.CUST_ACCOUNT_ID=RCTA.BILL_TO_CUSTOMER_ID
AND RCTA.CUSTOMER_TRX_ID=RCTL.CUSTOMER_TRX_ID
AND RCTL.CUSTOMER_TRX_LINE_ID=RCTD.CUSTOMER_TRX_LINE_ID


SELECT 
ORG_ID,
CUSTOMER_TRX_LINE_ID,
CUSTOMER_TRX_ID,
WAREHOUSE_ID,
INVENTORY_ITEM_ID,
DESCRIPTION,
SALES_ORDER,
UOM_CODE,
QUANTITY_ORDERED,
QUANTITY_INVOICED,
UNIT_SELLING_PRICE,
SALES_ORDER_DATE,
EXTENDED_AMOUNT,
SHIP_TO_CUSTOMER_ID,
SHIP_TO_SITE_USE_ID
FROM
APPS.RA_CUSTOMER_TRX_LINES_ALL
WHERE 1=1
AND ORG_ID=85
AND WAREHOUSE_ID=101
ORDER BY SALES_ORDER_DATE DESC


SELECT
ORG_ID,
CUSTOMER_TRX_ID,
TRX_NUMBER,
TRX_DATE,
CUST_TRX_TYPE_ID,
BILL_TO_CUSTOMER_ID,
BILL_TO_SITE_USE_ID,
SHIP_TO_CUSTOMER_ID,
SHIP_TO_SITE_USE_ID,
SHIP_DATE_ACTUAL,
INTERFACE_HEADER_ATTRIBUTE1 "ORDER NUMBER",
INTERFACE_HEADER_ATTRIBUTE2 "ORDER_TYPE",
INTERFACE_HEADER_ATTRIBUTE10 "WAREHOUSE_ID",
DOC_SEQUENCE_VALUE
FROM
APPS.RA_CUSTOMER_TRX_ALL RCTA
WHERE 1=1

SELECT
RCTLA.ORG_ID,
RCTLA.CUSTOMER_TRX_LINE_ID,
RCTLA.CUSTOMER_TRX_ID,
RCTLA.WAREHOUSE_ID,
RCTLA.INVENTORY_ITEM_ID,
RCTLA.DESCRIPTION,
RCTLA.SALES_ORDER,
RCTLA.UOM_CODE,
RCTLA.QUANTITY_ORDERED,
RCTLA.QUANTITY_INVOICED,
RCTLA.UNIT_SELLING_PRICE,
RCTLA.SALES_ORDER_DATE,
RCTLA.EXTENDED_AMOUNT,
RCTLA.SHIP_TO_CUSTOMER_ID,
RCTLA.SHIP_TO_SITE_USE_ID,
RCTA.ORG_ID,
RCTA.CUSTOMER_TRX_ID,
RCTA.TRX_NUMBER,
RCTA.TRX_DATE,
RCTA.CUST_TRX_TYPE_ID,
RCTA.BILL_TO_CUSTOMER_ID,
RCTA.BILL_TO_SITE_USE_ID,
RCTA.SHIP_TO_CUSTOMER_ID,
RCTA.SHIP_TO_SITE_USE_ID,
RCTA.SHIP_DATE_ACTUAL,
RCTA.INTERFACE_HEADER_ATTRIBUTE1 "ORDER NUMBER",
RCTA.INTERFACE_HEADER_ATTRIBUTE2 "ORDER_TYPE",
RCTA.INTERFACE_HEADER_ATTRIBUTE10 "WAREHOUSE_ID",
RCTA.DOC_SEQUENCE_VALUE
FROM
APPS.RA_CUSTOMER_TRX_ALL RCTA,
APPS.RA_CUSTOMER_TRX_LINES_ALL RCTLA
WHERE 1=1
AND RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID
