SELECT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
MOH.MOV_ORDER_NO,
MOH.WAREHOUSE_ORG_CODE,
AIA.INVOICE_NUM,
AIA.INVOICE_AMOUNT,
TO_CHAR (AIA.CREATION_DATE, 'DD-MON-YYYY') INVOICE_DATE
--,AIA.DOC_SEQUENCE_VALUE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.AP_INVOICES_ALL AIA
WHERE 1=1
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND MOH.MOV_ORDER_NO=AIA.INVOICE_NUM
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
AND MOH.WAREHOUSE_ORG_CODE='G10'
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
--AND AIA.CREATION_DATE BETWEEN '15-OCT-2017' and '16-OCT-2017'
--AND DOH.CUSTOMER_NUMBER IN ('20107','20770','184363')
GROUP BY
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.WAREHOUSE_ORG_CODE,
AIA.INVOICE_NUM,
AIA.INVOICE_AMOUNT,
AIA.CREATION_DATE
--,AIA.DOC_SEQUENCE_VALUE