SELECT
ORGANIZATION_NAME,
ORGANIZATION_CODE,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
(SELECT MSI.DESCRIPTION FROM APPS.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=ORD.ORDERED_ITEM_ID AND MSI.ORGANIZATION_ID=ORD.SHIP_FROM_ORG_ID) ITEM_NAME,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
--SUM(ORDERED_AMT) ORDERED_AMOUNT,
--SUM(ORDERED_QUANTITY) ORDERED_QUANTITY,
SUM(SHIPPING_QUANTITY) SHIPPING_QUANTITY,
SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
--,(SUM(INVOICED_QUANTITY)*UNIT_SELLING_PRICE) INVOICE_AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--DO_NUMBER,
--PERIOD
--ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
WHERE 1=1
AND ORG_ID=85
AND PERIOD='JUN-18'
AND ORGANIZATION_CODE='G10'
--AND DELIVERY_DATE BETWEEN '20-MAR-18' AND '22-MAR-18'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
ORGANIZATION_NAME
,ORGANIZATION_CODE
,ORD.ORDERED_ITEM_ID
,ORD.SHIP_FROM_ORG_ID
--,(SUM(INVOICED_QUANTITY)*UNIT_SELLING_PRICE)


------------------------------------------------------------------------------------------------

SELECT
OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
OOL.ORDER_QUANTITY_UOM UOM,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOH.ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
OOD.ORGANIZATION_CODE,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*SUM(OOL.ORDERED_QUANTITY)) AMOUNT
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
,APPS.MTL_SYSTEM_ITEMS_B MSIB
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=MSIB.INVENTORY_ITEM_ID
AND OOL.SHIP_FROM_ORG_ID=MSIB.ORGANIZATION_ID
AND OOD.ORGANIZATION_ID=MSIB.ORGANIZATION_ID
AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
--AND OOH.ORDER_TYPE_ID=1105--1099
--AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND OOL.FULFILLMENT_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND TO_CHAR (OOL.FULFILLMENT_DATE, 'MON-RR') = 'FEB-18'
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JUN-18'
--AND TO_CHAR (DOH.ACTUAL_SHIPMENT_DATE, 'RRRR') = '2017'
--AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
--AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
AND OOH.ORG_ID=85
AND OOD.ORGANIZATION_CODE='G10'
AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER
GROUP BY
OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE ,
OOH.ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ,
OOD.ORGANIZATION_CODE,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY