/* Formatted on 5/21/2019 2:22:57 PM (QP5 v5.287) */
  SELECT MODT.CUSTOMER_NUMBER,
         APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOL.SOLD_TO_ORG_ID)
            CUSTOMER_NAME,
         MODT.DO_NUMBER,
         SUM (OOL.ORDERED_QUANTITY) DO_QUANTITY,
         MOH.VEHICLE_NO,
         MOH.MOV_ORDER_NO,
         MOH.MOV_ORDER_STATUS,
         MOH.WAREHOUSE_ORG_CODE,
         TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE) INVOICE_DATE,
         MOH.FINAL_DESTINATION,
         MOH.TRANSPORT_MODE,
         MOH.TRANSPORTER_NAME,
         MOH.INITIAL_GATE_IN,
         MOH.GATE_OUT,
         MOH.GATE_IN,
         MOH.READY_FOR_INVOICE,
         --MOH.GATE_PASS_NO,
         --MOH.EMPTY_TRUCK_WT,
         --MOH.SCALE_IN_WT,
         MOH.AP_FLAG,
         TO_CHAR (MOH.CONFIRMED_DATE) CONFIRMED_DATE
    FROM APPS.XXAKG_MOV_ORD_HDR MOH,
         APPS.XXAKG_MOV_ORD_DTL MODT,
         APPS.OE_ORDER_LINES_ALL OOL
   WHERE     1 = 1
         AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
         AND OOL.SHIPMENT_PRIORITY_CODE = MODT.DO_NUMBER
         AND OOL.ACTUAL_SHIPMENT_DATE <= '30-SEP-2019'
         --AND TO_CHAR (MOH.CONFIRMED_DATE, 'MON-RR') = 'MAY-18'
         --AND TO_CHAR (MOH.CONFIRMED_DATE, 'RRRR') = '2017'
         --AND MOH.CONFIRMED_DATE<='02-DEC-2018'
         --AND TRANSPORT_MODE='Company Truck'
         AND MOH.VEHICLE_TYPE = 'Owned By Company'
         --AND MOH.GATE_OUT IS NULL
         AND MOH.VEHICLE_NO IN ('SCIL-SCM-0001',
                                'SCIL-SCM-0002',
                                'SCIL-SCM-0003',
                                'SCIL-SCM-0004')
         AND MOH.ORG_ID = 85
         --AND MOH.WAREHOUSE_ORG_CODE!='SCI'
         AND MOH.MOV_ORDER_STATUS IN ('GENERATED', 'CONFIRMED')
        --AND GATE_PASS_NO IS NULL
        --AND SCALE_OUT_WT IS NULL
        --AND MOH.MOV_ORDER_NO='MO/SCOU/941032'
GROUP BY MODT.CUSTOMER_NUMBER,
         MODT.DO_NUMBER,
         MOH.VEHICLE_NO,
         MOH.MOV_ORDER_NO,
         MOH.MOV_ORDER_STATUS,
         MOH.WAREHOUSE_ORG_CODE,
         MOH.FINAL_DESTINATION,
         MOH.TRANSPORT_MODE,
         MOH.TRANSPORTER_NAME,
         MOH.INITIAL_GATE_IN,
         MOH.GATE_OUT,
         MOH.GATE_IN,
         MOH.READY_FOR_INVOICE,
         --MOH.GATE_PASS_NO,
         --MOH.EMPTY_TRUCK_WT,
         --MOH.SCALE_IN_WT,
         MOH.AP_FLAG,
         MOH.CONFIRMED_DATE,
         OOL.SOLD_TO_ORG_ID
         ,OOL.ACTUAL_SHIPMENT_DATE
ORDER BY MOH.CONFIRMED_DATE DESC;

------------------------------------------------------------------------------------------------


  SELECT MODT.CUSTOMER_NUMBER,
         (SELECT HP.PARTY_NAME
            FROM APPS.HZ_PARTIES HP, APPS.HZ_CUST_ACCOUNTS HC
           WHERE     HP.PARTY_ID = HC.PARTY_ID
                 AND HC.ACCOUNT_NUMBER = MODT.CUSTOMER_NUMBER)
            CUSTOMER_NAME,
         MODT.DO_NUMBER,
         SUM (DODL.LINE_QUANTITY) DO_QUANTITY,
         MOH.VEHICLE_NO,
         MOH.MOV_ORDER_NO,
         MOH.MOV_ORDER_STATUS,
         MOH.WAREHOUSE_ORG_CODE,
         MOH.FINAL_DESTINATION,
         MOH.TRANSPORT_MODE,
         MOH.TRANSPORTER_NAME,
         MOH.INITIAL_GATE_IN,
         MOH.GATE_OUT,
         MOH.GATE_IN,
         MOH.READY_FOR_INVOICE,
         --MOH.GATE_PASS_NO,
         --MOH.EMPTY_TRUCK_WT,
         --MOH.SCALE_IN_WT,
         MOH.AP_FLAG,
         TO_CHAR (MOH.CONFIRMED_DATE) CONFIRMED_DATE
    FROM APPS.XXAKG_MOV_ORD_HDR MOH,
         APPS.XXAKG_MOV_ORD_DTL MODT,
         APPS.XXAKG_DEL_ORD_DO_LINES DODL
   WHERE     1 = 1
         AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
         AND DODL.DO_NUMBER = MODT.DO_NUMBER
         --AND TO_CHAR (MOH.CONFIRMED_DATE, 'MON-RR') = 'MAY-18'
         --AND TO_CHAR (MOH.CONFIRMED_DATE, 'RRRR') = '2017'
         AND TRUNC (MOH.CONFIRMED_DATE) <= '31-MAR-2019'
         AND MOH.VEHICLE_TYPE = 'Owned By Company'
         --AND TRANSPORT_MODE='Company Truck'
         AND MOH.GATE_OUT IS NULL
         AND MOH.VEHICLE_NO IN ('SCIL-SCM-0001',
                                'SCIL-SCM-0002',
                                'SCIL-SCM-0003',
                                'SCIL-SCM-0004')
         AND MOH.ORG_ID = 85
         AND MOH.MOV_ORDER_STATUS IN ('GENERATED', 'CONFIRMED')
--AND GATE_PASS_NO IS NULL
--AND SCALE_OUT_WT IS NULL
--AND MOH.MOV_ORDER_NO='MO/SCOU/941032'
GROUP BY MODT.CUSTOMER_NUMBER,
         MODT.DO_NUMBER,
         MOH.VEHICLE_NO,
         MOH.MOV_ORDER_NO,
         MOH.MOV_ORDER_STATUS,
         MOH.WAREHOUSE_ORG_CODE,
         MOH.FINAL_DESTINATION,
         MOH.TRANSPORT_MODE,
         MOH.TRANSPORTER_NAME,
         MOH.INITIAL_GATE_IN,
         MOH.GATE_OUT,
         MOH.GATE_IN,
         MOH.READY_FOR_INVOICE,
         --MOH.GATE_PASS_NO,
         --MOH.EMPTY_TRUCK_WT,
         --MOH.SCALE_IN_WT,
         MOH.AP_FLAG,
         MOH.CONFIRMED_DATE
ORDER BY MOH.CONFIRMED_DATE DESC