SELECT 13 UNION_PART,
       707 APPLICATION_ID,
       'CST' JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       MMT.TRANSACTION_ID VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ENTERED_DR ENTERED_DEBITS,
       XAL.ENTERED_CR ENTERED_CREDITS,
       XAL.ACCOUNTED_DR DEBITS,
       XAL.ACCOUNTED_CR CREDITS,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       XAE.EVENT_TYPE_CODE TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       ORG.ORGANIZATION_ID,
       ORG.ORGANIZATION_CODE,
       ORG.ORGANIZATION_NAME,
       MST.INVENTORY_ITEM_ID,
       MST.SEGMENT1 ITEM_CODE_SEGMENT1,
       MST.SEGMENT2 ITEM_CODE_SEGMENT2,
       MST.SEGMENT3 ITEM_CODE_SEGMENT3,
       MST.DESCRIPTION INVENTORY_ITEM_NAME,
       MCB.SEGMENT1 ITEM_CATEGORY_SEGMENT1,
       MCB.SEGMENT2 ITEM_CATEGORY_SEGMENT2,
       MTRH.REQUEST_NUMBER MOVE_ORDER_NO,
       MMT.TRANSACTION_ID
  FROM 
       XLA.XLA_EVENTS XAE,
       XLA.XLA_DISTRIBUTION_LINKS XDL,
       XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       GL.gl_code_combinations cc,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       APPS.MTL_TRANSACTION_ACCOUNTS MTA,
       APPS.MTL_MATERIAL_TRANSACTIONS MMT,
       APPS.MTL_TXN_REQUEST_HEADERS MTRH,
       INV.MTL_SYSTEM_ITEMS_B MST,
       APPS.XXAKG_ORG_DEF_T ORG,       
       INV.MTL_CATEGORIES_B MCB,
       INV.MTL_ITEM_CATEGORIES MIC
 WHERE 1=1
       AND GJH.DOC_SEQUENCE_VALUE = '119017226'
       AND XDL.EVENT_ID = XAE.EVENT_ID
       AND XDL.source_distribution_type = 'MTL_TRANSACTION_ACCOUNTS'
       AND XDL.APPLICATION_ID = XAH.APPLICATION_ID
       AND XDL.APPLICATION_ID = 707
       AND XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.NUL.2010501.9999.00'
       AND XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = MTA.INV_SUB_LEDGER_ID
       AND MTA.TRANSACTION_ID = MMT.TRANSACTION_ID
--       AND MMT.TRANSACTION_SOURCE_ID = MTA.TRANSACTION_SOURCE_ID(+)
       AND MMT.TRANSACTION_SOURCE_ID = MTRH.HEADER_ID(+)
       AND MMT.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND MMT.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MMT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND MCB.STRUCTURE_ID = 101
       AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
       AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND FLEX.LANGUAGE = USERENV ('LANG')