SELECT 1 SL,
       NULL COMPANY,
       NULL ACCOUNTING_DATE,
       XXAKG_AP_PKG.GET_VENDOR_NUMBER_FROM_ID (:P_VENDOR_ID) PARTY_NUM,
       XXAKG_AP_PKG.GET_VENDOR_NAME (:P_VENDOR_ID) PARTY_NAME,
       VENDOR_SITE_CODE PARTY_SITE,
       NULL INVOICE_NUM,
       NULL VOUCHER,
       'Opening Balance' DESCRIPTION,
       NULL GL_CODE_AND_DESC,
       NULL DR_AMOUNT,
       NULL CR_AMOUNT,
       (NVL (SUM (DR_AMOUNT), 0) - NVL (SUM (CR_AMOUNT), 0)) BALANCE
  FROM XXAKG_AP_SUPPLIER_LEDGER_SV
 WHERE     ORG_ID = :P_ORG_ID
       AND (:P_BAL_SEG IS NULL OR BAL_SEG = :P_BAL_SEG)
       AND VENDOR_ID = :P_VENDOR_ID
       AND VENDOR_SITE_ID=:P_VENDOR_SITE_ID
       AND ACCOUNTING_DATE < :P_DATE_FROM
UNION ALL
SELECT 2 SL,
       XXAKG_COM_PKG.GET_FLEX_VALUES_FROM_FLEX_ID (BAL_SEG, 1) COMPANY,
       ACCOUNTING_DATE,
       PARTY_NUM,
       XXAKG_AP_PKG.GET_VENDOR_NAME (:P_VENDOR_ID) PARTY_NAME,
       VENDOR_SITE_CODE PARTY_SITE,
       INVOICE_NUM,
       VOUCHER,
       DESCRIPTION,
       GL_CODE_AND_DESC,
       DR_AMOUNT,
       CR_AMOUNT,
       (NVL (DR_AMOUNT, 0) - NVL (CR_AMOUNT, 0))
  FROM XXAKG_AP_SUPPLIER_LEDGER_SV
 WHERE     ORG_ID = :P_ORG_ID
       AND (:P_BAL_SEG IS NULL OR BAL_SEG = :P_BAL_SEG)
       AND VENDOR_ID = :P_VENDOR_ID
       AND VENDOR_SITE_ID=:P_VENDOR_SITE_ID
       AND ACCOUNTING_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
ORDER BY SL, ACCOUNTING_DATE, VOUCHER