select *
from
(SELECT 1 UNION_PART,
       101 APPLICATION_ID,
       SRC.USER_JE_SOURCE_NAME JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
       GJL.DESCRIPTION,
       NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
       NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
       NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
       NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
       GJL.ATTRIBUTE2 CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTY_CODE,
       CAST (NULL AS VARCHAR2 (100)) PARTY_NAME,
       'MANUAL_JV' TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       GJL.CONTEXT DFF_CONTEXT,
       GJL.ATTRIBUTE1,
       GJL.ATTRIBUTE2,
       GJL.ATTRIBUTE3,
       GJL.ATTRIBUTE4,
       GJL.ATTRIBUTE5,
       CAST (NULL AS NUMBER) ORGANIZATION_ID,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_CODE,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_NAME,
       CAST (NULL AS NUMBER) INVENTORY_ITEM_ID,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT2,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT3,
       CAST (NULL AS VARCHAR2 (100)) INVENTORY_ITEM_NAME,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT2,
       CAST (NULL AS VARCHAR2 (100)) GOODS_RECEIPT_NUM,
       CAST (NULL AS NUMBER) TRANSACTION_ID
  FROM GL.GL_JE_HEADERS GJH,
       GL.GL_JE_LINES GJL,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       GL.GL_JE_SOURCES_TL SRC,
       GL.GL_CODE_COMBINATIONS CC,
       APPLSYS.FND_FLEX_VALUES_TL FLEX                                     --,
 --DATABASE_PROPERTIES DB
 WHERE     GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
       AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
       --AND NVL (NVL (GJL.ACCOUNTED_DR, GJL.ACCOUNTED_CR), 0) <> 0 #Bug - Journal Line Debit and Credit both column has value
       AND (NVL (GJL.ACCOUNTED_DR, 0) <> 0 OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
       AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.PRJCT.2030101.9999.00'
       AND GJH.JE_SOURCE NOT IN ('Payables',
                                 'Receivables',
                                 'Cash Management',
                                 'Assets',
                                 'Inventory',
                                 'Cost Management')
       --AND GJH.JE_FROM_SLA_FLAG IS CAST(NULL AS VARCHAR2(100))
       AND GJL.STATUS = 'P'
       AND GJH.ACTUAL_FLAG = 'A'
       AND FLEX.LANGUAGE = USERENV ('LANG')
--AND DB.PROPERTY_NAME = 'DEFAULT_EDITION'
--AND FLEX.ZD_EDITION_NAME = DB.PROPERTY_VALUE
UNION ALL
-- Manual Journals in Sub Ledgers
SELECT 2 UNION_PART,
       APP.APPLICATION_ID,
       DECODE (APP.APPLICATION_SHORT_NAME,
               'SQLAP', 'AP',
               'CE', 'CM',
               'GMF', 'INV',
               APP.APPLICATION_SHORT_NAME)
          JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ACCOUNTED_DR ENTERED_DR,
       XAL.ACCOUNTED_CR ENTERED_CR,
       XAL.ACCOUNTED_DR,
       XAL.ACCOUNTED_CR,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTY_CODE,
       CAST (NULL AS VARCHAR2 (100)) PARTY_NAME,
       CAST (NULL AS VARCHAR2 (100)) TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       CAST (NULL AS NUMBER) ORGANIZATION_ID,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_CODE,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_NAME,
       CAST (NULL AS NUMBER) INVENTORY_ITEM_ID,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT2,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT3,
       CAST (NULL AS VARCHAR2 (100)) INVENTORY_ITEM_NAME,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT2,
       CAST (NULL AS VARCHAR2 (100)) GOODS_RECEIPT_NUM,
       CAST (NULL AS NUMBER) TRANSACTION_ID
  FROM XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       GL.gl_code_combinations cc,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       APPLSYS.FND_APPLICATION APP                                         --,
 --DATABASE_PROPERTIES DB
 WHERE     XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.je_header_id = GJL.je_header_id
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.PRJCT.2030101.9999.00'
       AND XAH.APPLICATION_ID = APP.APPLICATION_ID
       AND EVENT_TYPE_CODE = 'MANUAL'
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND FLEX.LANGUAGE = USERENV ('LANG')
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
-- AND DB.PROPERTY_NAME = 'DEFAULT_EDITION'
-- AND FLEX.ZD_EDITION_NAME = DB.PROPERTY_VALUE
UNION ALL
-- Payable (Debit Line)
SELECT 6 UNION_PART,
       200 APPLICATION_ID,
       'AP' JE_SOURCE,
       GJH.JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       XAL.DESCRIPTION PARTICULARS,
       NVL (DLN.UNROUNDED_ENTERED_DR, 0) ENTERED_DEBITS,
       NVL (DLN.UNROUNDED_ENTERED_CR, 0) ENTERED_CREDITS,
       DLN.UNROUNDED_ACCOUNTED_DR ACCOUNTED_DR,
       DLN.UNROUNDED_ACCOUNTED_CR ACCOUNTED_CR,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       APS.SEGMENT1 PARTY_CODE,
       APS.VENDOR_NAME PARTY_NAME,
       XTE.ENTITY_CODE TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       API.ATTRIBUTE_CATEGORY DFF_CONTEXT,
       API.ATTRIBUTE1,
       API.ATTRIBUTE2,
       API.ATTRIBUTE3,
       API.ATTRIBUTE4,
       API.ATTRIBUTE5,
       CAST (NULL AS NUMBER) ORGANIZATION_ID,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_CODE,
       CAST (NULL AS VARCHAR2 (100)) ORGANIZATION_NAME,
       CAST (NULL AS NUMBER) INVENTORY_ITEM_ID,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT2,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CODE_SEGMENT3,
       CAST (NULL AS VARCHAR2 (100)) INVENTORY_ITEM_NAME,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT1,
       CAST (NULL AS VARCHAR2 (100)) ITEM_CATEGORY_SEGMENT2,
       RECEIPT_NUM GOODS_RECEIPT_NUM,
       APID.RCV_TRANSACTION_ID TRANSACTION_ID
  FROM AP.AP_SUPPLIERS APS,
       AP.AP_INVOICES_ALL API,
       AP.AP_INVOICE_DISTRIBUTIONS_ALL APID,
       XLA.XLA_TRANSACTION_ENTITIES XTE,
       XLA.XLA_AE_HEADERS XAH,
       XLA.XLA_AE_LINES XAL,
       GL.GL_IMPORT_REFERENCES GIR,
       GL.GL_JE_HEADERS GJH,
       GL.GL_JE_LINES GJL,
       GL.GL_CODE_COMBINATIONS CC,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       XLA.XLA_DISTRIBUTION_LINKS DLN,
       PO.RCV_TRANSACTIONS RT,
       PO.RCV_SHIPMENT_HEADERS RSH,
       PO.RCV_SHIPMENT_LINES RSL                                           --,
 --DATABASE_PROPERTIES DB
 WHERE     NVL (APS.VENDOR_ID(+), -222) = API.VENDOR_ID
       AND API.INVOICE_ID = XTE.SOURCE_ID_INT_1
       AND XTE.ENTITY_ID = XAH.ENTITY_ID
       AND XTE.ENTITY_CODE = 'AP_INVOICES'
       AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
       AND XAH.APPLICATION_ID = 200
       AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
       AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
       AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
       AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
       AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       --AND API.DOC_SEQUENCE_VALUE = '211076816'
       -- AND APID.RCV_TRANSACTION_ID = 55252
       --and RSH.SHIPMENT_HEADER_ID = 48963
       -----Add Distributions----------------
       AND API.INVOICE_ID = APID.INVOICE_ID
       AND DLN.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND DLN.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND DLN.SOURCE_DISTRIBUTION_ID_NUM_1 = APID.INVOICE_DISTRIBUTION_ID
       --AND APID.REVERSAL_FLAG = 'N'
       --AND DLN.line_definition_code = 'AKG_ACCRUAL_INVOICES_ALL'
       --   AND DLN.ref_ae_header_id = XAH.AE_HEADER_ID
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.PRJCT.2030101.9999.00'
       AND APID.RCV_TRANSACTION_ID = RT.TRANSACTION_ID(+)
       AND RSH.SHIPMENT_HEADER_ID(+) = RSL.SHIPMENT_HEADER_ID
       AND RSL.SHIPMENT_LINE_ID(+) = RT.SHIPMENT_LINE_ID
       AND FLEX.LANGUAGE = USERENV ('LANG')
--AND DB.PROPERTY_NAME = 'DEFAULT_EDITION'
--AND FLEX.ZD_EDITION_NAME = DB.PROPERTY_VALUE
UNION ALL
SELECT 10 UNION_PART,
       555 APPLICATION_ID,
       'INV' JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       geh.TRANSACTION_ID VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ACCOUNTED_DR ENTERED_DEBITS,
       XAL.ACCOUNTED_CR ENTERED_CREDITS,
       XAL.ACCOUNTED_DR DEBITS,
       XAL.ACCOUNTED_CR CREDITS,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       APS.SEGMENT1 PARTY_CODE,
       APS.VENDOR_NAME PARTY_NAME,
       ENTITY_CODE TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       ORG.ORGANIZATION_ID,
       ORG.ORGANIZATION_CODE,
       ORG.ORGANIZATION_NAME,
       MST.INVENTORY_ITEM_ID,
       MST.SEGMENT1 ITEM_CODE_SEGMENT1,
       MST.SEGMENT2 ITEM_CODE_SEGMENT2,
       MST.SEGMENT3 ITEM_CODE_SEGMENT3,
       MST.DESCRIPTION INVENTORY_ITEM_NAME,
       MCB.SEGMENT1 ITEM_CATEGORY_SEGMENT1,
       MCB.SEGMENT2 ITEM_CATEGORY_SEGMENT2,
       RSH.RECEIPT_NUM GOODS_RECEIPT_NUM,
       RT.TRANSACTION_ID
  FROM XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       GL.gl_code_combinations cc,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       INV.MTL_SYSTEM_ITEMS_B MST,
       APPS.XXAKG_ORG_DEF_T ORG,           --ORG_ORGANIZATION_DEFINITIONS ORG,
       INV.MTL_ITEM_CATEGORIES MIC,
       INV.MTL_CATEGORIES_B MCB,
       GMF.gmf_xla_extract_headers geh,
       GMF.gmf_xla_extract_lines gel,
       XLA.XLA_DISTRIBUTION_LINKS xdl,
       PO.RCV_TRANSACTIONS RT,
       PO.RCV_SHIPMENT_HEADERS RSH,
       PO.RCV_SHIPMENT_LINES RSL,
       AP.AP_SUPPLIERS APS                                                 --,
 --DATABASE_PROPERTIES DB
 WHERE     XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.je_header_id = GJL.je_header_id
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.PRJCT.2030101.9999.00'
       AND geh.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND geh.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND geh.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND MCB.STRUCTURE_ID = 101
       AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND geh.header_id = gel.header_id
       AND geh.event_id = gel.event_id
       AND geh.entity_code = 'PURCHASING'
       /*            AND geh.entity_code IN
                          ('PRODUCTION',
                           'PURCHASING',
                           'REVALUATION',
                           'ORDERMANAGEMENT',
                           'INVENTORY') */
       AND xdl.source_distribution_type = geh.entity_code
       AND xdl.event_id = geh.event_id
       AND xdl.source_distribution_id_num_1 = gel.line_id
       AND xdl.APPLICATION_ID = 555
       AND GEH.SOURCE_LINE_ID = RT.TRANSACTION_ID
       AND RSH.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
       AND RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
       AND RSL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID
       AND APS.VENDOR_ID = RSH.VENDOR_ID
       AND FLEX.LANGUAGE = USERENV ('LANG')
--AND DB.PROPERTY_NAME = 'DEFAULT_EDITION'
--AND FLEX.ZD_EDITION_NAME = DB.PROPERTY_VALUE
UNION ALL
SELECT 13 UNION_PART,
       707 APPLICATION_ID,
       'CST' JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       RCVT.TRANSACTION_ID VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ENTERED_DR ENTERED_DEBITS,
       XAL.ENTERED_CR ENTERED_CREDITS,
       XAL.ACCOUNTED_DR DEBITS,
       XAL.ACCOUNTED_CR CREDITS,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       APS.SEGMENT1 PARTY_CODE,
       APS.VENDOR_NAME PARTY_NAME,
       XAE.EVENT_TYPE_CODE TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       ORG.ORGANIZATION_ID,
       ORG.ORGANIZATION_CODE,
       ORG.ORGANIZATION_NAME,
       MST.INVENTORY_ITEM_ID,
       MST.SEGMENT1 ITEM_CODE_SEGMENT1,
       MST.SEGMENT2 ITEM_CODE_SEGMENT2,
       MST.SEGMENT3 ITEM_CODE_SEGMENT3,
       MST.DESCRIPTION INVENTORY_ITEM_NAME,
       MCB.SEGMENT1 ITEM_CATEGORY_SEGMENT1,
       MCB.SEGMENT2 ITEM_CATEGORY_SEGMENT2,
       RCVH.RECEIPT_NUM GOODS_RECEIPT_NUM,
       RCVT.TRANSACTION_ID
  FROM AP.AP_SUPPLIERS APS,
       PO.PO_LINES_ALL POL,
       PO.RCV_SHIPMENT_HEADERS RCVH,
       PO.RCV_TRANSACTIONS RCVT,
       XLA.XLA_TRANSACTION_ENTITIES XATE, --XLA.XLA_TRANSACTION_ENTITIES_UPG XATE,
       XLA.XLA_EVENTS XAE,
       XLA.XLA_DISTRIBUTION_LINKS XDL,
       XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       GL.gl_code_combinations cc,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       INV.MTL_SYSTEM_ITEMS_B MST,
       APPS.XXAKG_ORG_DEF_T ORG,           --ORG_ORGANIZATION_DEFINITIONS ORG,
       INV.MTL_CATEGORIES_B MCB,
       INV.MTL_ITEM_CATEGORIES MIC                                         --,
 --DATABASE_PROPERTIES DB
 WHERE     APS.VENDOR_ID = RCVH.VENDOR_ID
       AND POL.PO_LINE_ID = RCVT.PO_LINE_ID
       AND RCVH.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
       AND RCVT.TRANSACTION_ID = XATE.SOURCE_ID_INT_1
       AND XATE.ENTITY_ID = XAE.ENTITY_ID
       AND XDL.EVENT_ID = XAE.EVENT_ID
       AND XDL.source_distribution_type = 'RCV_RECEIVING_SUB_LEDGER'
       AND XDL.APPLICATION_ID = XAH.APPLICATION_ID
       AND XDL.APPLICATION_ID = 707
       AND XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2110.PRJCT.2030101.9999.00'
       AND RCVT.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND POL.ITEM_ID = MST.INVENTORY_ITEM_ID
       AND RCVT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND MCB.STRUCTURE_ID = 101
       AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
       AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND FLEX.LANGUAGE = USERENV ('LANG'))
where 1=1
--and VOUCHER_DATE between '01-AUG-2018' and '10-AUG-2018'
and VOUCHER_NUMBER in ('218247112')