  SELECT OOD.OPERATING_UNIT,
         OOD.ORGANIZATION_NAME,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_ID,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION SUBINVENTORY_NAME,
         OHQD.LOT_NUMBER,
         MSIB.SEGMENT1 || '.' || MSIB.SEGMENT2 || '.' || MSIB.SEGMENT3
            ITEM_CODE,
         MSIB.DESCRIPTION,
         MIL.SEGMENT1 || '.' || MIL.SEGMENT2 || '.' || MIL.SEGMENT3 INV_LOCATOR,
         --OHQD.INVENTORY_ITEM_ID,
         SUM (OHQD.PRIMARY_TRANSACTION_QUANTITY) AS "ONHAND_QUANTITY",
         OHQD.TRANSACTION_UOM_CODE UOM_CODE
         --,MIL.*
    FROM APPS.MTL_ONHAND_QUANTITIES_DETAIL OHQD,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
         --APPS.MTL_SECONDARY_INVENTORIES MSI,
         APPS.MTL_SYSTEM_ITEMS_B MSIB
         ,INV.MTL_ITEM_LOCATIONS MIL
   WHERE     1 = 1
         AND MSIB.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         --AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
         AND OHQD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
         AND OHQD.LOCATOR_ID=MIL.INVENTORY_LOCATION_ID(+)
         --AND OOD.OPERATING_UNIT IN (83,84,85,605)
         --AND OOD.ORGANIZATION_CODE IN ('SCI')
         --AND OHQD.ORGANIZATION_ID IN ('101','113','1345','1346')
         --AND OHQD.SUBINVENTORY_CODE!='DUMMY FG'
         --AND MSIB.INVENTORY_ITEM_ID IN (55605)
         --AND MSIB.SEGMENT1='BRND'
         --AND MSIB.SEGMENT1='GIFT'
         AND (   :P_OPERATING_UNIT IS NULL
              OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
         AND (   :P_SUBINVENTORY_CODE IS NULL
              OR (OHQD.SUBINVENTORY_CODE = :P_SUBINVENTORY_CODE))
         AND (   :P_ORGANIZATION_CODE IS NULL
              OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
         AND (   :P_ITEM_CODE IS NULL
              OR (MSIB.SEGMENT1 || '.' || MSIB.SEGMENT2 || '.' || MSIB.SEGMENT3 =
                     :P_ITEM_CODE))
--         AND (MIL.SEGMENT1  IS NOT NULL) OR (MIL.SEGMENT2 IS NOT NULL) OR (MIL.SEGMENT3 IS NOT NULL)
--AND MSIB.SEGMENT1||'.'||MSIB.SEGMENT2||'.'||MSIB.SEGMENT3 IN ('CMNT.SBAG.0001','CMNT.SBAG.0003','CMNT.PBAG.0001','CMNT.PBAG.0003','CMNT.OBAG.0001','CMNT.SBLK.0001','CMNT.PBLK.0001','CMNT.OBLK.0001','CMNT.CBAG.0001','CMNT.CBLK.0001','CMNT.CBAG.0003')
GROUP BY OOD.OPERATING_UNIT,
         MSIB.SEGMENT1 || '.' || MSIB.SEGMENT2 || '.' || MSIB.SEGMENT3,
         MIL.SEGMENT1 || '.' || MIL.SEGMENT2 || '.' || MIL.SEGMENT3,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         OHQD.LOT_NUMBER,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION,
         OHQD.TRANSACTION_UOM_CODE,
         OOD.ORGANIZATION_ID,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_NAME
ORDER BY ORGANIZATION_CODE;

---------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT OOD.OPERATING_UNIT,
       OOD.ORGANIZATION_NAME,
       OOD.ORGANIZATION_CODE,
       OOD.ORGANIZATION_ID,
       MSI.SECONDARY_INVENTORY_NAME SUBINVENTORY_CODE,
       MSI.DESCRIPTION SUBINVENTORY_NAME,
       OOD.BUSINESS_GROUP_ID,
       OOD.SET_OF_BOOKS_ID,
       OOD.CHART_OF_ACCOUNTS_ID
  --,OOD.*
  --,MSI.*
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
       APPS.MTL_SECONDARY_INVENTORIES MSI
 WHERE 1 = 1 AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID 
 --OPERATING UNIT: LEDGER_ID--MASTER_ORG
 --ORGANIZATION_NAME--ORGANIZATION_CODE
 --ORGANIZATION_ID: SUB-LEDGER_ID
 --BUSINESS_GROUP_ID: INVENTORY_ID
 AND OOD.ORGANIZATION_ID = :P_ORGANIZATION_ID                     
--AND ORGANIZATION_CODE=:P_ORGANIZATION_CODE--'SCI'
--AND OPERATING_UNIT=:P_OPERATING_UNIT--85
AND MSI.DISABLE_DATE IS NULL;

----------------------------------------------------------------------------------------------------------------------------------

SELECT *
  FROM APPS.MTL_SECONDARY_INVENTORIES MSI