/* Formatted on 10/30/2019 11:20:44 AM (QP5 v5.287) */
SELECT OOD.OPERATING_UNIT ORG_ID,
       HOU.NAME OPERATING_UNIT,
       OOD.ORGANIZATION_NAME WAREHOUSE_NAME,
       OOD.ORGANIZATION_CODE WAREHOUSE_ORG_CODE,
       OOD.ORGANIZATION_ID WAREHOUSE_ID,
       --MSI.SECONDARY_INVENTORY_NAME SUBINVENTORY_CODE,
       --MSI.DESCRIPTION SUBINVENTORY_NAME,
       OOD.BUSINESS_GROUP_ID,
       OOD.SET_OF_BOOKS_ID,
       OOD.CHART_OF_ACCOUNTS_ID
  --,OOD.*
  --,MSI.*
  FROM APPS.HR_OPERATING_UNITS HOU, APPS.ORG_ORGANIZATION_DEFINITIONS OOD
 --,APPS.MTL_SECONDARY_INVENTORIES MSI
 WHERE     1 = 1
       AND HOU.ORGANIZATION_ID = OOD.OPERATING_UNIT
       --AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
       AND (   :P_OPERATING_UNIT IS NULL
            OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
       AND (   :P_ORGANIZATION_CODE IS NULL
            OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
       AND     (:P_ORG_NAME IS NULL OR (UPPER(OOD.ORGANIZATION_NAME) LIKE UPPER('%'||:P_ORG_NAME||'%') ))
--AND OOD.ORGANIZATION_ID=:P_ORGANIZATION_ID--101
--AND ORGANIZATION_CODE=:WAREHOUSE_ORG_CODE  --
--AND OOD.OPERATING_UNIT=:P_OPERATING_UNIT--85
--------------------------------------------------------------------------------
--AND MSI.DISABLE_DATE IS NULL
--OPERATING UNIT: LEDGER_ID--MASTER_ORG
--ORGANIZATION_NAME--ORGANIZATION_CODE
--ORGANIZATION_ID: SUB-LEDGER_ID
--BUSINESS_GROUP_ID: INVENTORY_ID
;


--------------------------------------------------------------------------------


SELECT ORG_INFORMATION2 LEGAL_ENTITY,
       ORG_INFORMATION1 SET_OF_BOOKS,
       ORG_INFORMATION3 ORG_ID,
       PM.ORGANIZATION_CODE WAREHOUSE_ORG_CODE,
       PM.ORGANIZATION_ID WAREHOUSE_ID,
       SECONDARY_INVENTORY_NAME,
       DESCRIPTION
  --,(SELECT FFV.FLEX_VALUE FROM APPS.FND_FLEX_VALUE_SETS VSET,APPS.FND_FLEX_VALUES FFV WHERE FFV.FLEX_VALUE=PM.ORGANIZATION_CODE AND VSET.FLEX_VALUE_SET_NAME='AKG_CostCentre' AND VSET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID) Cost_Centre
  --,PM.*
  --,MSI.*
  --,HOI.*
  FROM INV.MTL_PARAMETERS PM,
       APPS.MTL_SECONDARY_INVENTORIES MSI,
       APPS.HR_ORGANIZATION_INFORMATION HOI,
       APPS.MTL_INTERORG_PARAMETERS MIP
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = PM.ORGANIZATION_ID
       AND HOI.ORGANIZATION_ID = PM.ORGANIZATION_ID
       AND MIP.FROM_ORGANIZATION_ID = PM.ORGANIZATION_ID
       AND PM.ORGANIZATION_CODE = 'SCI'
       AND ORG_INFORMATION_CONTEXT = 'Accounting Information'
       AND ORG_INFORMATION3 = '85'                                 --:P_ORG_ID
;


--------------------------------------------------------------------------------

SELECT *
  FROM APPS.HR_OPERATING_UNITS
 WHERE 1 = 1 AND ORGANIZATION_ID = :OPERATING_UNIT;


SELECT *
  FROM APPS.XXAKG_INV_ORG_HIERARCHY
 WHERE 1 = 1 AND OU_ID = 85;


SELECT * FROM APPS.ORG_ORGANIZATION_DEFINITIONS;

SELECT * FROM APPS.HR_OPERATING_UNITS;

SELECT *
  FROM INV.MTL_PARAMETERS
 WHERE ORGANIZATION_ID = 101;

SELECT * FROM APPS.HR_ORGANIZATION_INFORMATION;