 SELECT
 A.FROM_ORGANIZATION_NAME
 ,A.FROM_ORGANIZATION_CODE
 ,A.TO_ORGANIZATION_CODE
 ,A.TO_ORGANIZATION_NAME
--,A.*
 FROM
 APPS.MTL_SHIPPING_NETWORK_VIEW A
 ,APPS.GL_CODE_COMBINATIONS_KFV B
WHERE 1=1
AND A.INTERORG_TRANSFER_CR_ACCOUNT = B.CODE_COMBINATION_ID
AND FROM_ORGANIZATION_CODE='G35'

--------------------------------------------------------------------------------
SELECT NET.ROWID ROW_ID,
          MP1.ORGANIZATION_CODE FROM_ORGANIZATION_CODE,
          HOU1.NAME FROM_ORGANIZATION_NAME,
          MP1.PRIMARY_COST_METHOD FROM_PRIMARY_COST_DUMMY,
          MP1.INTERORG_TRNSFR_CHARGE_PERCENT FROM_CHARGE_PERCENT_DUMMY,
          MP2.ORGANIZATION_CODE TO_ORGANIZATION_CODE,
          HOU2.NAME TO_ORGANIZATION_NAME,
          MP2.PRIMARY_COST_METHOD TO_PRIMARY_COST_DUMMY,
          NET.FROM_ORGANIZATION_ID,
          NET.TO_ORGANIZATION_ID,
          NET.LAST_UPDATE_DATE,
          NET.LAST_UPDATED_BY,
          NET.CREATION_DATE,
          NET.CREATED_BY,
          NET.LAST_UPDATE_LOGIN,
          NET.INTRANSIT_TYPE,
          NET.DISTANCE_UOM_CODE,
          NET.TO_ORGANIZATION_DISTANCE,
          NET.MATL_INTERORG_TRANSFER_CODE,
          NET.INTERORG_TRNSFR_CHARGE_PERCENT,
          NET.FOB_POINT,
          NET.ROUTING_HEADER_ID,
          NET.INTERNAL_ORDER_REQUIRED_FLAG,
          NET.INTRANSIT_INV_ACCOUNT,
          NET.INTERORG_TRANSFER_CR_ACCOUNT,
          NET.INTERORG_RECEIVABLES_ACCOUNT,
          NET.INTERORG_PAYABLES_ACCOUNT,
          NET.INTERORG_PRICE_VAR_ACCOUNT,
          NET.ATTRIBUTE_CATEGORY,
          NET.ATTRIBUTE1,
          NET.ATTRIBUTE2,
          NET.ATTRIBUTE3,
          NET.ATTRIBUTE4,
          NET.ATTRIBUTE5,
          NET.ATTRIBUTE6,
          NET.ATTRIBUTE7,
          NET.ATTRIBUTE8,
          NET.ATTRIBUTE9,
          NET.ATTRIBUTE10,
          NET.ATTRIBUTE11,
          NET.ATTRIBUTE12,
          NET.ATTRIBUTE13,
          NET.ATTRIBUTE14,
          NET.ATTRIBUTE15,
          DECODE (NET.ELEMENTAL_VISIBILITY_ENABLED,
                  NULL, 'N',
                  NET.ELEMENTAL_VISIBILITY_ENABLED)
             ELEMENTAL_VISIBILITY_ENABLED,
          NET.MANUAL_RECEIPT_EXPENSE,
          NET.PROFIT_IN_INV_ACCOUNT,
          NET.SUBCONTRACTING_TYPE,
          NET.SHIKYU_DEFAULT_ORDER_TYPE_ID,
          NET.SHIKYU_OEM_VAR_ACCOUNT_ID,
          NET.SHIKYU_TP_OFFSET_ACCOUNT_ID,
          NET.PRICELIST_ID,
          NET.INTERORG_PROFIT_ACCOUNT,
          HOU1.LOCATION_ID FROM_LOCATION_ID,
          HOU2.LOCATION_ID TO_LOCATION_ID
     FROM APPS.MTL_PARAMETERS MP1,
          APPS.MTL_PARAMETERS MP2,
          APPS.HR_ORGANIZATION_UNITS HOU1,
          APPS.HR_ORGANIZATION_UNITS HOU2,
          APPS.MTL_INTERORG_PARAMETERS NET
    WHERE     MP1.ORGANIZATION_ID = NET.FROM_ORGANIZATION_ID
          AND MP2.ORGANIZATION_ID = NET.TO_ORGANIZATION_ID
          AND HOU1.ORGANIZATION_ID = MP1.ORGANIZATION_ID
          AND HOU2.ORGANIZATION_ID = MP2.ORGANIZATION_ID;