SELECT
*
FROM
APPS.XXAKG_AR_CUSTOMER_LEDGER_V CL
WHERE 1=1
--      AND     (:P_ORG_ID IS NULL OR (CL.ORG_ID=:P_ORG_ID))
--      AND     (:P_CUSTOMER_NUMBER IS NULL OR (CL.CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER))
--      AND     (:P_ORDER_NUMBER IS NULL OR (CL.CO_NUMBER = :P_ORDER_NUMBER))
--      AND     (:P_DO_NUMBER IS NULL OR (CL.DO_NUMBER = :P_DO_NUMBER))
--      AND     (:P_VOUCHER_NO IS NULL OR (CL.VOUCHER=:P_VOUCHER_NO))
--      AND     (:P_STATUS IS NULL OR (CL.STATUS = :P_STATUS))
--      AND TRUNC(CL.GL_DATE) BETWEEN NVL(:P_GL_DATE_FROM,TRUNC(CL.GL_DATE)) AND NVL(:P_GL_DATE_TO,TRUNC(CL.GL_DATE))
      AND VOUCHER IN ('417390440')
--      AND CL.DO_NUMBER='DO/SCOU/1039380'