SELECT
HCA.ACCOUNT_NUMBER CUTOMER_NUMBER,
HP.PARTY_NAME CUSTOMER_NAME,
TO_CHAR(MAX(OOL.ACTUAL_SHIPMENT_DATE)) LAST_SHIPMENT_DATE
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.HZ_CUST_ACCOUNTS_ALL HCA,
APPS.HZ_PARTIES HP
WHERE 1=1
AND OOL.SOLD_TO_ORG_ID=HCA.CUST_ACCOUNT_ID
AND HCA.PARTY_ID=HP.PARTY_ID
 -- AND NVL(HCA.STATUS, 'A') = 'A'
-- AND HCA.ACCOUNT_NUMBER=:P_CUSTOMER_NUMBER
AND OOL.ORG_ID=85
AND OOL.ACTUAL_SHIPMENT_DATE< (SELECT MAX(ORD.ACTUAL_SHIPMENT_DATE) FROM APPS.OE_ORDER_LINES_ALL ORD )
GROUP BY
 HCA.ACCOUNT_NUMBER
 ,HP.PARTY_NAME