SELECT
MOH.MOV_ORDER_NO,
DOH.DO_NUMBER,
MOH.FINAL_DESTINATION "FINAL_DESTINATION_IN_MOVE",
DOH.FINAL_DESTINATION "FINAL_DESTINATION_IN_DO"
FROM
--APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
--AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.FINAL_DESTINATION!=MOH.FINAL_DESTINATION