SELECT
--MAX(DODL.LINE_QUANTITY) QTY
DOH.DO_NUMBER
FROM
APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.ORG_ID=85
AND TO_CHAR(DOH.DO_DATE,'MON-RR')='AUG-18'
AND 2=(SELECT DISTINCT(DOL.LINE_QUANTITY) FROM APPS.XXAKG_DEL_ORD_DO_LINES DOL WHERE DODL.LINE_QUANTITY<DOL.LINE_QUANTITY)
--GROUP BY
--DOH.DO_NUMBER

SELECT Salary FROM (
SELECT e.Salary, 
ROW_NUMBER() OVER (ORDER BY salary DESC) rn 
FROM Employee e
)
WHERE rn = 2;

SELECT QTY,ITEM,DO_N,CUST_NUM,CUST_NAME FROM (
SELECT DODL.LINE_QUANTITY QTY, DOH.DO_NUMBER DO_N , DOH.CUSTOMER_NUMBER CUST_NUM, DOH.CUSTOMER_NAME CUST_NAME,DODL.ITEM_NUMBER ITEM, 
ROW_NUMBER() OVER (ORDER BY DODL.LINE_QUANTITY DESC) RN 
FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL,APPS.XXAKG_DEL_ORD_HDR DOH WHERE 1=1 AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.ORG_ID=85
AND TO_CHAR(DOH.DO_DATE,'MON-RR')='AUG-18'
AND DODL.ITEM_NUMBER IN ('CMNT.SBAG.0001','CMNT.SBAG.0003','CMNT.PBAG.0001','CMNT.PBAG.0003','CMNT.OBAG.0001','CMNT.SBLK.0001','CMNT.PBLK.0001','CMNT.OBLK.0001','CMNT.CBAG.0001','CMNT.CBLK.0001','CMNT.CBAG.0003')
)
WHERE RN <= 3;



SELECT
    DODL.LINE_QUANTITY QTY, DOH.DO_NUMBER DO_N , DOH.CUSTOMER_NUMBER CUST_NUM, DOH.CUSTOMER_NAME CUST_NAME,DODL.ITEM_NUMBER ITEM
FROM
    APPS.XXAKG_DEL_ORD_DO_LINES DODL,APPS.XXAKG_DEL_ORD_HDR DOH 
    WHERE 1=1 AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.ORG_ID=85
AND TO_CHAR(DOH.DO_DATE,'MON-RR')='AUG-18'
ORDER BY
    LINE_QUANTITY DESC 
    FETCH NEXT 8 ROWS WITH TIES
    
    
--OFFSET 8 ROWS
--FETCH FIRST 1 PERCENT ROWS ONLY;
--    LIMIT 5;
--FETCH NEXT 10 ROWS WITH TIES;
--FETCH NEXT 5 ROWS ONLY;


