SELECT --DISTINCT
--OOH.TP_ATTRIBUTE15 APPROVED_BY_USER_ID
OOH.ORG_ID
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,OOH.ORDER_NUMBER
,TO_CHAR(OOH.ORDERED_DATE,'DD-MON-YYYY HH24:MI:SS') ORDERED_DATE
,TO_CHAR(OOH.BOOKED_DATE,'DD-MON-YYYY HH24:MI:SS') BOOKED_DATE
,TO_CHAR(OOH.ORDERED_DATE) ORDERED_DATE
,TO_CHAR (OOH.CREATION_DATE) CREATION_DATE
,(SELECT MSI.DESCRIPTION FROM INV.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID AND OOL.SHIP_FROM_ORG_ID=MSI.ORGANIZATION_ID) ITEM
,OOL.ORDERED_QUANTITY QUANTITY
--,OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER
--,OOL.FLOW_STATUS_CODE STATUS
--,ADDRESS1 ADDRESS
--,PARTY_SITE_NUMBER
--,REAILER||'-'||REAILER_ADDRESS "RETAILER LOCATION"
--,LOCATION||'-'||LOCATION_ADDRESS "Location"
,(SELECT PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE OOH.CREATED_BY=FU.USER_ID AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) CREATED_BY_USER
,(SELECT PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE OOH.LAST_UPDATED_BY=FU.USER_ID AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) LAST_UPDATED_BY_USER
--570
--,ACSV.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND ACSV.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND ACSV.SHIP_TO_ORG_ID=OOL.SHIP_TO_ORG_ID
AND TO_CHAR (OOH.BOOKED_DATE, 'DD-MON-RR') = '10-APR-19'
--AND TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR') = '14-MAR-18'
AND OOH.ORG_ID=85
AND OOH.FLOW_STATUS_CODE IN ('BOOKED','CLOSED')
--AND OOH.ORDER_NUMBER='1693024'
--AND ACSV.STATUS='A'
--AND ACSV.SITE_USE_CODE='BILL_TO'
--AND ACSV.SITE_USE_CODE='SHIP_TO'
--AND ACSV.PRIMARY_FLAG='Y'
--AND ACSV.SITE_USE_STATUS='A'
--AND ACSV.ACCT_USE_STATUS='A'
--AND EXISTS (SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE 1=1 AND  ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER and DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES'))
--AND CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
--AND ROWNUM<=10