SELECT  'Move Confirm' Order_Status,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
(CASE 
          WHEN  DODL.ACTUAL_RETAILER_SHIP_TO IS NOT NULL  THEN DODL.ACTUAL_RETAILER_SHIP_TO
            ELSE CUST_SITE.LOCATION
            || ', '
            || CUST_SITE.LOCATION_ADDRESS
END) CUSTOMER_SITE
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1 
AND DODL.ORDER_LINE_ID=OOL.LINE_ID
AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND DODL.ORDERED_ITEM_ID=OOL.INVENTORY_ITEM_ID
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1683735')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,DODL.ACTUAL_RETAILER_SHIP_TO
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
--ORDER BY OOH.ORDERED_DATE DESC
UNION ALL
SELECT 'DO Created' Order_Status,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(DOD.LINE_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
(CASE 
          WHEN  DOD.ACTUAL_RETAILER_SHIP_TO IS NOT NULL  THEN DOD.ACTUAL_RETAILER_SHIP_TO
            ELSE CUST_SITE.LOCATION
            || ', '
            || CUST_SITE.LOCATION_ADDRESS
END) CUSTOMER_SITE
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
,APPS.XXAKG_DEL_ORD_DO_LINES DOD
WHERE 1=1 
AND DOD.SHIP_TO_ORG_ID=OOL.SHIP_TO_ORG_ID
AND DOD.ORDER_NUMBER=OOH.ORDER_NUMBER
AND DOD.ORDER_LINE_ID IS NULL
AND DOD.ORDER_HEADER_ID IS NOT NULL
AND DOD.ORDERED_ITEM_ID=OOL.INVENTORY_ITEM_ID
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1706069')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
--AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,DOD.ACTUAL_RETAILER_SHIP_TO
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
--ORDER BY OOH.ORDERED_DATE DESC
UNION ALL
SELECT 'Pending DO' Order_Status,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
CUST_SITE.LOCATION|| ', '|| CUST_SITE.LOCATION_ADDRESS CUSTOMER_SITE
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
WHERE 1=1 
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1706068')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
--ORDER BY OOH.ORDERED_DATE DESC





------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


SELECT 
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
--SUM(OOL.ORDERED_QUANTITY) RETAILER_WISE_QTY,
(CASE 
          WHEN  DODL.ACTUAL_RETAILER_SHIP_TO IS NOT NULL  THEN DODL.ACTUAL_RETAILER_SHIP_TO
            ELSE CUST_SITE.LOCATION
            || ', '
            || CUST_SITE.LOCATION_ADDRESS
END) CUSTOMER_SITE
--,OOH.*
--,OOL.*
--,CUST.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1 
AND DODL.ORDER_LINE_ID=OOL.LINE_ID
AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND DODL.ORDERED_ITEM_ID=OOL.INVENTORY_ITEM_ID
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1683735')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,DODL.ACTUAL_RETAILER_SHIP_TO
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
ORDER BY OOH.ORDERED_DATE DESC


------------------------------------------------------------------------------------------------

SELECT 
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(DOD.LINE_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
--SUM(OOL.ORDERED_QUANTITY) RETAILER_WISE_QTY,
(CASE 
          WHEN  DOD.ACTUAL_RETAILER_SHIP_TO IS NOT NULL  THEN DOD.ACTUAL_RETAILER_SHIP_TO
            ELSE CUST_SITE.LOCATION
            || ', '
            || CUST_SITE.LOCATION_ADDRESS
END) CUSTOMER_SITE
--,OOH.*
--,OOL.*
--,CUST.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
,APPS.XXAKG_DEL_ORD_DO_LINES DOD
WHERE 1=1 
AND DOD.SHIP_TO_ORG_ID=OOL.SHIP_TO_ORG_ID
AND DOD.ORDER_NUMBER=OOH.ORDER_NUMBER
AND DOD.ORDER_LINE_ID IS NULL
AND DOD.ORDER_HEADER_ID IS NOT NULL
--AND DODL.ORDER_LINE_ID(+)=OOL.LINE_ID
--AND DODL.ORDER_HEADER_ID(+)=OOH.HEADER_ID
AND DOD.ORDERED_ITEM_ID=OOL.INVENTORY_ITEM_ID
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1706069')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
--AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,DOD.ACTUAL_RETAILER_SHIP_TO
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
ORDER BY OOH.ORDERED_DATE DESC



------------------------------------------------------------------------------------------------

SELECT 
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
CUST.REAILER RETAILER,
CUST_SITE.LOCATION|| ', '|| CUST_SITE.LOCATION_ADDRESS CUSTOMER_SITE
--,OOH.*
--,OOL.*
--,CUST.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST_SITE
WHERE 1=1 
AND CUST.CUSTOMER_ID=CUST_SITE.CUSTOMER_ID
AND CUST.SHIP_SITE_LOCATION_ID=CUST_SITE.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1706068')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1099
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
GROUP BY 
CUST.REAILER,
CUST.REGION_NAME,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME
,CUST_SITE.LOCATION
,CUST_SITE.LOCATION_ADDRESS
,OOH.ORDERED_DATE 
ORDER BY OOH.ORDERED_DATE DESC
