select 
OOH.ORG_ID
,'CERAMIC OPERATING UNIT' ORGANIZATION
,APPS.XXAKG_COM_PKG.GET_EMP_NAME_FROM_USER_ID(OOH.CREATED_BY)||' ('||APPS.XXAKG_COM_PKG.GET_USER_NAME(OOH.CREATED_BY)||')' CREATED_BY
,COUNT(OOH.ORDER_NUMBER) NO_OF_ORDER
--,COUNT(OOL.LINE_ID) NO_OF_LINE
--,SUM(OOL.ORDERED_QUANTITY) NO_OF_QTY
,TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR') ORDERED_DATE
FROM
--APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
--,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
WHERE 1=1 
--AND OOH.HEADER_ID=OOL.HEADER_ID
AND ((:P_ORG_ID IS NULL AND OOH.ORG_ID IN (83,84,85,605))  OR (OOH.ORG_ID=:P_ORG_ID))
AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-19'
GROUP BY
OOH.CREATED_BY
,OOH.ORG_ID
,TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR')
ORDER BY COUNT(OOH.ORDER_NUMBER) DESC

-------------------------------------------------------------------------------- LINE WISE

select DISTINCT
OOH.ORG_ID
,'CERAMIC OPERATING UNIT' ORGANIZATION
,APPS.XXAKG_COM_PKG.GET_EMP_NAME_FROM_USER_ID(OOH.CREATED_BY)||' ('||APPS.XXAKG_COM_PKG.GET_USER_NAME(OOH.CREATED_BY)||')' CREATED_BY
--,COUNT(OOH.HEADER_ID) NO_OF_ORDER
,COUNT(OOH.LINE_ID) NO_OF_LINE
--,SUM(OOL.ORDERED_QUANTITY) NO_OF_QTY
,TO_CHAR (OOH.CREATION_DATE, 'DD-MON-RR') ORDERED_DATE
FROM
--(SELECT COUNT(OOL.LINE_ID) FROM APPS.OE_ORDER_LINES_ALL OOL WHERE OOH.HEADER_ID=OOL.HEADER_ID ) NO_OF_LINE,
APPS.OE_ORDER_LINES_ALL OOH
--,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
WHERE 1=1 
AND ((:P_ORG_ID IS NULL AND OOH.ORG_ID IN (83,84,85,605))  OR (OOH.ORG_ID=:P_ORG_ID))
AND TO_CHAR (OOH.CREATION_DATE, 'MON-RR') = 'SEP-19'
GROUP BY
OOH.CREATED_BY
,OOH.ORG_ID
,TO_CHAR (OOH.CREATION_DATE, 'DD-MON-RR')
ORDER BY 
--COUNT(OOH.HEADER_ID) 
COUNT(OOH.LINE_ID)
DESC


-------------------------------------------------------------------------------- QTY WISE

select --DISTINCT
OOH.ORG_ID
,'CERAMIC OPERATING UNIT' ORGANIZATION
,APPS.XXAKG_COM_PKG.GET_EMP_NAME_FROM_USER_ID(OOH.CREATED_BY)||' ('||APPS.XXAKG_COM_PKG.GET_USER_NAME(OOH.CREATED_BY)||')' CREATED_BY
--,COUNT(OOH.HEADER_ID) NO_OF_ORDER
--,COUNT(OOH.LINE_ID) NO_OF_LINE
,SUM(OOH.ORDERED_QUANTITY) NO_OF_QTY
,TO_CHAR (OOH.CREATION_DATE, 'DD-MON-RR') ORDERED_DATE
FROM
--(SELECT COUNT(OOL.LINE_ID) FROM APPS.OE_ORDER_LINES_ALL OOL WHERE OOH.HEADER_ID=OOL.HEADER_ID ) NO_OF_LINE,
APPS.OE_ORDER_LINES_ALL OOH
--,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
WHERE 1=1 
AND ((:P_ORG_ID IS NULL AND OOH.ORG_ID IN (83,84,85,605))  OR (OOH.ORG_ID=:P_ORG_ID))
AND TO_CHAR (OOH.CREATION_DATE, 'MON-RR') = 'SEP-19'
GROUP BY
OOH.CREATED_BY
,OOH.ORG_ID
,TO_CHAR (OOH.CREATION_DATE, 'DD-MON-RR')
ORDER BY 
--COUNT(OOH.HEADER_ID) 
--COUNT(OOH.LINE_ID)
SUM(OOH.ORDERED_QUANTITY)
DESC