SELECT DISTINCT
DOH.ORG_ID,
OOH.ORDER_NUMBER,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DOH.OPERATING_UNIT,
MOH.WAREHOUSE_ORG_CODE,
DOH.DO_NUMBER,
DOH.DO_DATE,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_DATE ,
DOH.MODE_OF_TRANSPORT,
MOH.VEHICLE_NO,
OOL.ORDERED_QUANTITY,
OOL.CANCELLED_QUANTITY,
--DODL.LINE_QUANTITY DO_QUANTITY,
--WDD.DELIVERED_QUANTITY, 
OOL.SHIPPING_QUANTITY,
OOL.SHIPPED_QUANTITY, 
OOL.INVOICED_QUANTITY,
--SUM(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY,
--SUM(OOL.SHIPPING_QUANTITY) TOTAL_SHIPPING_QUANTITY,
--SUM(OOL.SHIPPED_QUANTITY) TOTAL_SHIPPED_QUANTITY,
--SUM(OOL.INVOICED_QUANTITY) TOTAL_ORDERED_QUANTITY,
OOL.FLOW_STATUS_CODE,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
DOH.DO_STATUS,
MOH.MOV_ORDER_STATUS,
MOH.CONFIRMED_DATE,
OOL.ACTUAL_SHIPMENT_DATE,
DODL.SHIP_TO_LOCATION,
DOH.FINAL_DESTINATION,
MODT.VAT_CHALLAN_NO,
MOH.GATE_PASS_NO,
WDD.SUBINVENTORY,
MOH.INITIAL_GATE_IN,
MOH.GATE_OUT,
MOH.GATE_IN,
MOH.HIRE_RATE_AP
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_DEL_ORD_HDR DOH,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
WSH.WSH_DELIVERY_DETAILS WDD
WHERE 1=1 
AND OOH.HEADER_ID(+)=DODL.ORDER_HEADER_ID
AND DODL.DO_HDR_ID=DOH.DO_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID(+)
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID(+)
AND WDD.SHIPMENT_PRIORITY_CODE(+)=DOH.DO_NUMBER
AND OOL.HEADER_ID=OOH.HEADER_ID
--AND DOH.CUSTOMER_NUMBER='20075'
--AND OOH.ORDER_NUMBER='1639185'
--AND DOH.DO_NUMBER='DO/SCOU/1015006'
--AND MOH.MOV_ORDER_NO='MO/SCOU/934887'
--AND MOH.VEHICLE_NO='D.M.AU-11-4262'
AND DOH.ORG_ID=85
--AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JUL-17')
--AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-JUL-2017' AND '01-AUG-2017'
--AND MOH.INITIAL_GATE_IN='Y'
--AND MOH.GATE_OUT='Y'
--AND MOH.GATE_IN='N'
--AND ROWNUM<=2
--GROUP BY
--DOH.ORG_ID,
--OOH.ORDER_NUMBER,
--DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--DOH.OPERATING_UNIT,
--MOH.WAREHOUSE_ORG_CODE,
--DOH.DO_NUMBER,
--MOH.MOV_ORDER_NO,
--DOH.MODE_OF_TRANSPORT,
--MOH.VEHICLE_NO,
--DOH.DO_DATE,
--OOL.FLOW_STATUS_CODE,
--DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
--OOL.ORDER_QUANTITY_UOM,
--DOH.DO_STATUS,
--MOH.MOV_ORDER_STATUS,
--DODL.SHIP_TO_LOCATION
--OOL.ACTUAL_SHIPMENT_DATE,
--DOH.FINAL_DESTINATION,
--MODT.VAT_CHALLAN_NO,
--MOH.GATE_PASS_NO,
--WDD.SUBINVENTORY,
--MOH.INITIAL_GATE_IN
--MOH.GATE_OUT
--MOH.GATE_IN,
--MOH.HIRE_RATE_AP,
--DODL.SHIP_TO_LOCATION,
--OOL.ORDERED_QUANTITY,
--OOL.CANCELLED_QUANTITY,
----DODL.LINE_QUANTITY DO_QUANTITY,
----WDD.DELIVERED_QUANTITY, 
--OOL.SHIPPING_QUANTITY,
--OOL.SHIPPED_QUANTITY, 
--OOL.INVOICED_QUANTITY
--ORDER BY 
--MOH.MOV_ORDER_DATE DESC