SELECT
*
FROM
APPS.XXAKG_ORD_TO_DO_DTL_V
WHERE 1=1
--AND ORDER_NUMBER IN ('1609136')
AND DO_NUMBER IN ('DO/SCOU/923222')

SELECT 
OOH.ORG_ID,
OOH.HEADER_ID,
OOL.LINE_ID,
OOH.ORDER_NUMBER,
OOH.ORDER_TYPE_ID,
OOH.ORDERED_DATE,
OOL.ORDERED_QUANTITY,
OOL.INVOICED_QUANTITY,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOL.FLOW_STATUS_CODE
,OOL.ACTUAL_SHIPMENT_DATE
--,(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
--,OOH.*
,OOL.*
--,CUST.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
--,APPS.XXAKG_REGION_BLOCK_CELL_V CUST
WHERE 1=1 
--AND CUST.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
--AND CUST.SHIP_SITE_LOCATION_ID=OOL.SHIP_TO_ORG_ID
--AND CUST.CUSTOMER_NUMBER='188686'
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1697832')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
--AND OOH.FLOW_STATUS_CODE='CLOSED'--'BOOKED'
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
--AND HCA.CUST_ACCOUNT_ID=OOL.SOLD_TO_ORG_ID
--AND ORDER_TYPE_ID=1101
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
ORDER BY OOH.ORDERED_DATE DESC