SELECT 
OOH.ORG_ID,
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (HCA.CUST_ACCOUNT_ID) REGION,
HCA.ACCOUNT_NUMBER
,HP.PARTY_NAME CUSTOMER_NAME,
OOH.ORDER_NUMBER,
(SELECT OTTL.NAME FROM APPS.OE_TRANSACTION_TYPES_TL OTTL WHERE OOH.ORDER_TYPE_ID=OTTL.TRANSACTION_TYPE_ID) ORDER_TYPE_NAME,
OOH.ORDERED_DATE,
OOL.ORDERED_QUANTITY,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOL.FLOW_STATUS_CODE
,OOL.ACTUAL_SHIPMENT_DATE
--,(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
,CSUA.LOCATION
--,OOH.*
--,OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.HZ_CUST_ACCOUNTS HCA
,APPS.HZ_PARTIES HP
,APPS.HZ_CUST_SITE_USES_ALL CSUA
,APPS.HZ_CUST_ACCT_SITES_ALL CASA
WHERE 1=1 
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SOLD_TO_ORG_ID=HCA.CUST_ACCOUNT_ID
AND OOH.ORG_ID=CSUA.ORG_ID
--AND OOL.SHIP_TO_ORG_ID=CASA.CUST_ACCOUNT_ID
AND HP.PARTY_ID=HCA.PARTY_ID
AND CASA.ORG_ID=CSUA.ORG_ID
AND CSUA.CUST_ACCT_SITE_ID=CASA.CUST_ACCT_SITE_ID
AND HCA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID
AND CSUA.SITE_USE_CODE='SHIP_TO'--'BILL_TO'--
AND HCA.STATUS='A'
AND CSUA.STATUS='A'
AND CSUA.PRIMARY_FLAG='Y'
AND OOH.ORDER_NUMBER IN ('6403543','6403544')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND HCA.ACCOUNT_NUMBER=:P_CUSTOMER_NUMBER
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOL.FLOW_STATUS_CODE='BOOKED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE IS NULL--=:P_SHIPMENT_PRIORITY_CODE
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'MAR-18'
--AND OOL.SHIPMENT_PRIORITY_CODE IN ('DO/MOU/13984')
--AND HCA.CUST_ACCOUNT_ID=OOL.SOLD_TO_ORG_ID
--AND ORDER_TYPE_ID=1101
--AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
ORDER BY OOH.ORDERED_DATE DESC

-----------------------------------------------------------------------------------------------------------------------------------------

SELECT
OOH.ORG_ID
,CUSTOMER_NUMBER
,CUSTOMER_NAME
,OOH.ORDER_NUMBER
,OOH.ORDERED_DATE
,OOL.ORDERED_QUANTITY
,OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER
,OOL.FLOW_STATUS_CODE
,ADDRESS1 ADDRESS
,PARTY_SITE_NUMBER
--,REAILER||'-'||REAILER_ADDRESS "RETAILER LOCATION"
,LOCATION||'-'||LOCATION_ADDRESS "Location"
,ACSV.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND ACSV.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND ACSV.SHIP_TO_ORG_ID=OOL.SHIP_TO_ORG_ID
AND OOH.ORDER_NUMBER IN ('1659352')
AND OOH.ORG_ID=85
AND ACSV.STATUS='A'
--AND ACSV.SITE_USE_CODE='BILL_TO'
AND ACSV.SITE_USE_CODE='SHIP_TO'
--AND ACSV.PRIMARY_FLAG='Y'
AND ACSV.SITE_USE_STATUS='A'
AND ACSV.ACCT_USE_STATUS='A'
--AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE 1=1 AND  ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER )
--AND CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
