SELECT 
LOOKUP_TYPE,
FND.LOOKUP_CODE,
FND.MEANING
,(SELECT PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TO_CHAR(FND.LOOKUP_CODE)=TO_CHAR(FU.USER_NAME) AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) APPROVED_BY_USER
,(SELECT FU.USER_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TO_CHAR(FND.LOOKUP_CODE)=TO_CHAR(FU.USER_NAME) AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) APPROVED_BY_USER_ID
FROM APPS.FND_LOOKUP_VALUES FND
WHERE 1=1
AND FND.LOOKUP_TYPE='SO_CREDIT_APPROVER_LEVEL1' 
 
SELECT 
LOOKUP_TYPE,
FND.LOOKUP_CODE,
FND.MEANING
,(SELECT PPF.FULL_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TO_CHAR(FND.LOOKUP_CODE)=TO_CHAR(FU.USER_NAME) AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) APPROVED_BY_USER
,(SELECT FU.USER_NAME FROM APPS.FND_USER FU, APPS.PER_PEOPLE_F PPF WHERE TO_CHAR(FND.LOOKUP_CODE)=TO_CHAR(FU.USER_NAME) AND PPF.PERSON_ID=FU.EMPLOYEE_ID
AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) APPROVED_BY_USER_ID
FROM APPS.FND_LOOKUP_VALUES FND
WHERE FND.LOOKUP_TYPE='SO_CREDIT_APPROVER_LEVEL2' 
 
 
SELECT 
LOOKUP_TYPE,
FND.LOOKUP_CODE,
FND.MEANING
 FROM APPS.FND_LOOKUP_VALUES FND
WHERE FND.LOOKUP_TYPE LIKE '%APPROVER%' -- '%aprrover%'


------------------------------------------------------------------------------------------------

XXAKG_SET_SO_APPROVER_ID


select
*
from
ALL_TRIGGERS
where 1=1
and TRIGGER_NAME='XXAKG_SET_SO_APPROVER_ID'


select TO_CLOB(trigger_body)
from ALL_TRIGGERS