SELECT 
SUM(SHIPPED_BAG_QTY) SHIPPED_QUANTITY 
,MAX(LAST_UPDATE_DATE) LAST_REPORT_UPDATED
FROM
(SELECT 
--SUM(SHIPPED_QUANTITY) SHIPPED_QUANTITY
(CASE 
    WHEN INVENTORY_ITEM_ID=1024565 THEN (NVL(SHIPPED_QUANTITY,0)*1000)/50
    --WHEN INVENTORY_ITEM_ID IN (24402,24408,206570,992039) THEN (NVL(SHIPPED_QUANTITY, 0)) * 20
    ELSE  NVL(SHIPPED_QUANTITY, 0)
END) SHIPPED_BAG_QTY 
,DC.LAST_UPDATE_DATE
FROM APPS.XXAKG_DISTRIBUTION_COST DC
    ,APPS.XXAKG_DISTRIBUTOR_BLOCK_M R
    ,APPS.ORG_ORGANIZATION_DEFINITIONS OD
WHERE 1=1
AND DC.CUSTOMER_ID = R.CUSTOMER_ID
AND      DC.ORG_ID = R.ORG_ID 
--AND      INVENTORY_ITEM_ID='206570'-- IN (24402,24408,206570,992039,1024565)
AND      DC.FROM_WAREHOUSE_ID = OD.ORGANIZATION_ID
AND ACTUAL_SHIPMENT_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
AND EXISTS (SELECT 1 FROM INV.MTL_SYSTEM_ITEMS_B MSI WHERE DC.FROM_WAREHOUSE_ID=MSI.ORGANIZATION_ID AND DC.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID AND MSI.SEGMENT1='CMNT')
--GROUP BY INVENTORY_ITEM_ID
--HAVING NVL (R.REGION_NAME, 'Not Defined') = :P_REGION
--AND DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME) = :P_GHAT
);


--------------------------------------------------------------------------------
SELECT NVL (R.REGION_NAME, 'Not Defined') REGION_NAME, DC.FROM_WAREHOUSE_ID,
DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME) WAREHOUSE, --ORDER_NUMBER,
SUM(SHIPPED_QUANTITY) SHIPPED_QUANTITY 
FROM APPS.XXAKG_DISTRIBUTION_COST DC,
          APPS.XXAKG_DISTRIBUTOR_BLOCK_M R,
          APPS.ORG_ORGANIZATION_DEFINITIONS OD
WHERE DC.CUSTOMER_ID = R.CUSTOMER_ID
AND      DC.ORG_ID = R.ORG_ID 
AND      DC.FROM_WAREHOUSE_ID = OD.ORGANIZATION_ID
AND ACTUAL_SHIPMENT_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
GROUP BY NVL (R.REGION_NAME, 'Not Defined'), DC.FROM_WAREHOUSE_ID, DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME)
--,ORDER_NUMBER
--HAVING NVL (R.REGION_NAME, 'Not Defined') = :P_REGION
--AND DECODE(DC.FROM_WAREHOUSE_ID, 101, OD.ORGANIZATION_CODE, OD.ORGANIZATION_NAME) = :P_GHAT
ORDER BY 1, 3--, 4
;