SELECT ITEM_CODE,DESCRIPTION,USER_ITEM_TYPE,PLANNER_CODE,MAKE_BUY,UOM_CONVERSION,
SAFETY_STOCK_METHOD,SAFETY_STOCK_BUCKET,SAFETY_STOCK_PERCENT,PLANNING_METHOD,
FORECAST_CONTROL,PEGGING_ENABLED,--PREPROCESSING_LT,PROCESSING_LT,POSTPROCESSING_LT,
--FIXED_LT,VARIABLE_LT,
PM_SUBINVEN,PM_YIELD_SUBINVEN,
--MIN_ORDER_QTY,MAX_ORDER_QTY,
--FIXED_LOT_MULTIPLIER,
FIXED_ORDER_QTY,
FIXED_DAYS_SUPPLY
FROM
XXAKG_ITEM_ATTRI_STG
WHERE
ITEM_CODE IN ('UAPA.LINW.0001','UAPA.LINB.0001')
