SELECT ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,USER_ITEM_TYPE ,PLANNER_CODE,SAFETY_STOCK_BUCKET,SAFETY_STOCK_METHOD,MAKE_BUY,PLANNER_CODE,PLANNING_METHOD,FORECAST_CONTROL,PEGGING_ENABLED,PM_SUBINVEN,PM_YIELD_SUBINVEN
FROM XXAKG_ITEM_ATTRI_STG
wherE ORGANIZATION_CODE='CER'
--and USER_ITEM_TYPE= 'FG'
and PLANNER_CODE='KILN'
--and ITEM_CODE= 'CPAP.LOTS.0001'
