SELECT MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE, MSI.DESCRIPTION, MC.SEGMENT1||'|'||MC.SEGMENT2 ITEM_CATEGORY, MIC.ORGANIZATION_ID
FROM APPS.MTL_SYSTEM_ITEMS_B MSI,
          APPS.MTL_ITEM_CATEGORIES MIC,
          APPS.MTL_CATEGORIES_B MC
WHERE MSI.ORGANIZATION_ID=MIC.ORGANIZATION_ID
AND     MSI.INVENTORY_ITEM_ID=MIC.INVENTORY_ITEM_ID
AND     MIC.CATEGORY_ID=MC.CATEGORY_ID
AND     MIC.ORGANIZATION_ID=99
--AND     MC.SEGMENT1 = 'FINISH GOODS'
--AND     MC.SEGMENT2 LIKE 'PD%'
--AND     MSI.DESCRIPTION LIKE '%YELLOW%'
--AND     MSI.SEGMENT1 LIKE 'RFWC%'
and msi.segment1||'.'||msi.segment2||'.'||msi.segment3 in ('CPAP.LOTS.0001')
--AND     MSI.SEGMENT2 = 'LILY'
--AND     MSI.SEGMENT1 LIKE 'PANA%'
