/* Formatted on 7/2/2019 3:11:44 PM (QP5 v5.287) */
SELECT PPF.PERSON_ID,
       PPF.EMPLOYEE_NUMBER,
       PPF.FULL_NAME EMPLOYEE_NAME,
       PPF.EFFECTIVE_START_DATE,
       PPF.MARITAL_STATUS MARITAL_STATUS_CODE,
       (SELECT MEANING
          FROM APPS.HR_LOOKUPS
         WHERE     LOOKUP_CODE = PPF.MARITAL_STATUS
               AND LOOKUP_TYPE = 'MAR_STATUS')
          MARITAL_STATUS,
       DECODE (PPF.SEX,  'M', 'MALE',  'F', 'FEMALE',  'OTHERS') GENDER,
       PPF.NATIONAL_IDENTIFIER,
       PPF.DATE_OF_BIRTH,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_DIFF_ALL (CURRENT_DATE,
                                                PPF.DATE_OF_BIRTH)
          AGE,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_YEAR_CAL_YEAR (CURRENT_DATE,
                                                     PPF.DATE_OF_BIRTH)
          AGE_YEAR,
       PPF.ATTRIBUTE1 BLOOD_GROUP,
       PPF.ATTRIBUTE2 RELIGN,
       PPF.ATTRIBUTE7 HIGHT,
       APPS.XXAKG_ORACLE_PKG.GET_HIGHEST_QUALIFICATION (PPF.PERSON_ID)
          HIGHEST_QUALIFICATION,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_YEAR_CAL_YEAR (
          CURRENT_DATE,
          PPF.EFFECTIVE_START_DATE)
          TENURE_YEAR,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_DIFF_ALL (CURRENT_DATE,
                                                PPF.EFFECTIVE_START_DATE)
          TENURE,
       APPS.XXAKG_ORACLE_PKG.GET_TOTAL_EXPERIENCE (PPF.PERSON_ID)
          TOTAL_EXPERIENCE,
       APPS.XXAKG_ORACLE_PKG.GET_PREVIOUS_JOB_DETAILS (PPF.PERSON_ID)
          PREVIOUS_JOB_DETAILS,
       APPS.XXAKG_ORACLE_PKG.GET_PERSON_TYPE (PPF.PERSON_ID) PERSON_TYPE,
       APPS.XXAKG_ORACLE_PKG.GET_PERSON_NAME (PPF.PERSON_ID) PERSON_NAME,
       APPS.XXAKG_ORACLE_PKG.GET_ENAME_FRM_ENUM (PPF.EMPLOYEE_NUMBER)
          GET_ENAME_FRM_ENUM,
       PAAF.SUPERVISOR_ID,
       PPX.EMPLOYEE_NUMBER SUPERVISOR_EMP_NUM,
       NVL (PPX.FULL_NAME, 'NONE') SUPERVISOR_EMP_NAME,
       (SELECT PPDS.SEGMENT2
          FROM APPS.PER_POSITION_DEFINITIONS PPDS,
               APPS.HR_ALL_POSITIONS_F HAPFS,
               APPS.PER_ALL_ASSIGNMENTS_F PAAFS
         WHERE     SYSDATE BETWEEN PAAFS.EFFECTIVE_START_DATE
                               AND PAAFS.EFFECTIVE_END_DATE
               AND NVL (PAAFS.POSITION_ID, 1) = HAPFS.POSITION_ID(+)
               AND HAPFS.POSITION_DEFINITION_ID =
                      PPDS.POSITION_DEFINITION_ID(+)
               AND PAAFS.ASSIGNMENT_NUMBER = PPX.EMPLOYEE_NUMBER)
          SUPERVISOR_DESIGNATION,
       APPS.XXAKG_ORACLE_PKG.GET_SUPERVISOR_NAME (PPF.PERSON_ID)
          SUPERVISOR_NAME,
       PJD.SEGMENT1 Department,
       PJD.SEGMENT2 SUB_DEPARTMENT,
       PPSF.PAYROLL_NAME,
       HRL.LOCATION_CODE,
       POU.NAME ORGANIZATION_NAME,
       PPD.SEGMENT2 EMP_DESIGNATION,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'M')
          PERSONAL_NUMBER,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'C1')
          OFFICE_NUMBER,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'H1')
          HOME_NUMBER,
       PPF.EMAIL_ADDRESS,
       (SELECT MEANING
          FROM APPS.HR_LOOKUPS
         WHERE LOOKUP_CODE = PPF.NATIONALITY AND LOOKUP_TYPE = 'NATIONALITY')
          NATIONALITY,
       PA.ADDRESS_LINE1 || ',' || PA.DERIVED_LOCALE PERMANENT_ADDRESS,
       PPF.COUNTRY_OF_BIRTH,
       (SELECT MEANING
          FROM APPS.HR_LOOKUPS
         WHERE     LOOKUP_CODE = PPF.COUNTRY_OF_BIRTH
               AND LOOKUP_TYPE = 'GHR_US_POSTAL_COUNTRY_CODE')
          COUNTRY_BY_BIRTH,
       PAAF.EMPLOYMENT_CATEGORY EMPLOYMENT_CATEGORY_CODE,
       (SELECT MEANING
          FROM APPS.HR_LOOKUPS
         WHERE     LOOKUP_CODE = PAAF.EMPLOYMENT_CATEGORY
               AND LOOKUP_TYPE = 'EMP_CAT')
          EMPLOYMENT_CATEGORY
  --,PPF.*
  --,PJD.*
  --,PPSF.*
  --,HRL.*
  --,POU.*
  --,PPD.*
  --,HAPF.*
  FROM APPS.PER_PEOPLE_F PPF,
       APPS.PER_ALL_ASSIGNMENTS_F PAAF,
       APPS.PER_PEOPLE_X PPX,
       APPS.PER_JOBS PJ,
       APPS.PER_JOB_DEFINITIONS PJD,
       APPS.PAY_PAYROLLS_F PPSF,
       APPS.HR_LOCATIONS HRL,
       APPS.PER_ORGANIZATION_UNITS POU,
       APPS.PER_POSITION_DEFINITIONS PPD,
       APPS.HR_ALL_POSITIONS_F HAPF,
       APPS.PER_ADDRESSES PA
 WHERE     1 = 1
       AND PPF.PARTY_ID = PA.PARTY_ID
       AND PA.PRIMARY_FLAG = 'Y'
       AND HAPF.LOCATION_ID(+) = HRL.LOCATION_ID
       AND NVL (PAAF.POSITION_ID, 1) = HAPF.POSITION_ID(+)
       AND HAPF.POSITION_DEFINITION_ID = PPD.POSITION_DEFINITION_ID(+)
       AND PAAF.ORGANIZATION_ID = POU.ORGANIZATION_ID
       AND NVL (PAAF.LOCATION_ID, 1) = HRL.LOCATION_ID(+)
       AND NVL (PAAF.PAYROLL_ID, 1) = PPSF.PAYROLL_ID(+)
       AND PJD.JOB_DEFINITION_ID = PJ.JOB_DEFINITION_ID
       AND NVL (PAAF.JOB_ID, 1) = PJ.JOB_ID
       AND PPF.PERSON_ID = PAAF.PERSON_ID
       AND PAAF.SUPERVISOR_ID = PPX.PERSON_ID(+)
       AND PPF.EMPLOYEE_NUMBER = :P_EMPLOYEE_NUMBER
       AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE
                       AND PPF.EFFECTIVE_END_DATE
       AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE
                       AND PAAF.EFFECTIVE_END_DATE;