/* Formatted on 11/6/2019 12:00:35 PM (QP5 v5.287) */
SELECT SOURCE,
       DOC_SEQUENCE_VALUE VOUCHER_NO
       ,AIA.DESCRIPTION INV_DESC
       ,AIA.INVOICE_NUM INVOICE_NUMBER
       ,AIA.INVOICE_AMOUNT INV_AMOUNT
       ,AILA.AMOUNT INV_LINE_AMNT
--       ,APPS.AP_INVOICES_PKG.GET_DISTRIBUTION_TOTAL (AIA.INVOICE_ID) DIST_INV_AMOUNT
--       CANCELLED_AMOUNT,
--       CANCELLED_DATE,
--       HP.PARTY_NAME CUTSOMER_NAME,
--       HCA.ACCOUNT_NUMBER CUSTOMER_NUMBER
       ,AIA.*
--       ,AILA.*
  FROM APPS.AP_INVOICES_ALL AIA
       ,APPS.AP_INVOICE_LINES_ALL AILA
       ,APPS.AP_INVOICE_DISTRIBUTIONS_ALL AIDA
--       ,APPS.AP_INVOICE_PAYMENTS_ALL AIPA
--       ,APPS.HZ_PARTIES HP
--       ,APPS.HZ_CUST_ACCOUNTS HCA
 WHERE     1 = 1
       AND AIA.INVOICE_ID = AILA.INVOICE_ID(+)
--       AND AIA.PARTY_ID = HCA.PARTY_ID
--       AND AIA.PARTY_ID = HP.PARTY_ID
       and AIA.INVOICE_ID=AIDA.INVOICE_ID(+)
--       AND AIA.INVOICE_ID = AIPA.INVOICE_ID(+)
       AND     (:P_INVOICE_NUMBER IS NULL OR (AIA.INVOICE_NUM = :P_INVOICE_NUMBER))
       AND TRUNC(AIA.INVOICE_DATE) BETWEEN NVL(:P_INVOICE_DATE_FROM,TRUNC(AIA.INVOICE_DATE)) AND NVL(:P_INVOICE_DATE_TO,TRUNC(AIA.INVOICE_DATE))
       --AND DOC_SEQUENCE_VALUE = 218008929
       AND ((:P_ORG_ID IS NULL AND AIA.ORG_ID IN (83,84,85,605)) OR (AIA.ORG_ID=:P_ORG_ID));