SELECT
*
FROM
APPS.PO_APPROVAL_LIST_HEADERS PALH
,APPS.PO_APPROVAL_LIST_LINES PALL
WHERE 1=1
AND PALL.APPROVAL_LIST_HEADER_ID=PALH.APPROVAL_LIST_HEADER_ID


SELECT
*
FROM
APPS.PO_APPROVAL_LIST_LINES PALL
WHERE 1=1
--JOINED BY APPROVAL_LIST_HEADER_ID,
--PALL.APPROVER_ID, PALL.RESPONDER_ID, PALL.FORWARD_TO_ID, PALL.STATUS, PALL.CREATED_BY

SELECT
*
FROM
APPS.PO_APPROVAL_LIST_HEADERS PALH
--PALH.APPROVAL_LIST_HEADER_ID, PALH.DOCUMENT_ID, PALH.DOCUMENT_TYPE, PALH.DOCUMENT_SUBTYPE, PALH.FIRST_APPROVER_ID, PALH.APPROVAL_PATH_ID
--FIND OUT RIVISION, CURRENT_SEQUENCE_NUM, WF_ITEM_TYPE, WT_ITEM_KEY,




SELECT
*
FROM
APPS.PO_HEADERS_INTERFACE PHI
WHERE 1=1
--PHI.PO_HEADER_ID, PHI.INTERFACE_HEADER_ID, PHI.BATCH_ID, PHI.GROUP_CODE/PHI.DOCUMENT_NUM, PHI.ORG_ID, PHI.DOCUMENT_TYPE_CODE,
--PHI.AGENT_ID, PHI.VENDOR_ID, PHI.VENDOR_SITE_ID, PHI.APPROVAL_STATUS, 

SELECT
*
FROM
APPS.PO_LINES_INTERFACE PLI
WHERE 1=1
--PLI.INTERFACE_LINE_ID, PLI.INTERFACE_HEADER_ID, PLI.GROUP_CODE, PLI.PO_LINE_ID, PLI.ITEM_ID, PLI.UNIT_OF_MEASURE, PLI.QUANTITY, PLI.UNIT_PRICE, PLI.SHIP_TO_ORGANIZATION_ID, , PLI.SHIPMENT_ATTRIBUTE_CATEGORY, PLI.PROCESS_CODE, PLI.PROCESSING_ID, 



SELECT
*
FROM
APPS.PO_CONTROL_RULES


PER_POS_STRUCTURE_ELEMENTS_V,
PER_POSITIONS,
PER_POS_STRUCTURE_VERSIONS,
PER_ALL_ASSIGNMENTS_F,
PER_ALL_PEOPLE_F
PO_POSITION_CONTROLS_ALL,
PO_CONTROL_GROUPS_ALL,
PO_CONTROL_RULES PCR
