SELECT DISTINCT          
PHA.SEGMENT1 PO_NUMBER,          
AIA.INVOICE_NUM INVOICE_NUMBER,          
RSH.RECEIPT_NUM RECEIPT_NUMBER     
FROM APPS.PO_HEADERS_ALL PHA,          
APPS.PO_DISTRIBUTIONS_ALL PDA,          
APPS.AP_INVOICE_DISTRIBUTIONS_ALL AIDA,          
APPS.AP_INVOICES_ALL AIA,          
APPS.RCV_SHIPMENT_LINES RSL,          
APPS.RCV_SHIPMENT_HEADERS RSH    
WHERE 1=1
--AND AIA.ORG_ID=83    
AND PHA.PO_HEADER_ID = PDA.PO_HEADER_ID         
AND AIDA.PO_DISTRIBUTION_ID = PDA.PO_DISTRIBUTION_ID          
AND AIA.INVOICE_ID = AIDA.INVOICE_ID          
AND RSL.PO_HEADER_ID = PHA.PO_HEADER_ID          
AND RSL.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID          
AND PHA.SEGMENT1 = NVL (:P_PO_NUM, PHA.SEGMENT1) 
--AND AIA.INVOICE_NUM=NVL(:P_INVOICE_NUM,AIA.INVOICE_NUM) 
--AND RSH.RECEIPT_NUM=NVL(:P_RECEIPT_NUM,RSH.RECEIPT_NUM) 
ORDER BY 3




