SELECT
*
FROM
APPS.AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
APPS.PO_DISTRIBUTIONS_ALL PDA,
APPS.RCV_TRANSACTIONS RT
WHERE 1=1
AND AIDA.PO_DISTRIBUTION_ID=PDA.PO_DISTRIBUTION_ID
--AND AIDA.RCV_TRANSACTION_ID=RT.RCV_TRANSACTION_ID
AND PDA.PO_HEADER_ID=RT.PO_HEADER_ID
