SELECT
DOH.ORG_ID,
OOH.ORDER_NUMBER,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DOH.OPERATING_UNIT,
MOH.WAREHOUSE_ORG_CODE,
DOH.DO_NUMBER,
DOH.DO_DATE,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_DATE ,
DOH.MODE_OF_TRANSPORT,
MOH.VEHICLE_NO,
OOL.ORDERED_QUANTITY,
OOL.CANCELLED_QUANTITY, 
OOL.SHIPPING_QUANTITY,
OOL.SHIPPED_QUANTITY, 
OOL.INVOICED_QUANTITY,
OOL.FLOW_STATUS_CODE,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
DOH.DO_STATUS,
MOH.MOV_ORDER_STATUS,
MOH.CONFIRMED_DATE,
OOL.ACTUAL_SHIPMENT_DATE,
DODL.SHIP_TO_LOCATION,
DOH.FINAL_DESTINATION,
MODT.VAT_CHALLAN_NO,
MOH.GATE_PASS_NO,
MOH.INITIAL_GATE_IN,
MOH.GATE_OUT,
MOH.GATE_IN,
MOH.HIRE_RATE_AP,
--DODL.DO_NUMBER,
--MIC.ORGANIZATION_ID,
MC.SEGMENT1 ITEM_CATEGORY,
MC.SEGMENT2 ITEM_TYPE,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.UOM_CODE,
DODL.LINE_QUANTITY
--DODL.WAREHOUSE_ORG_CODE,
--MIC.INVENTORY_ITEM_ID
FROM
APPS.MTL_ITEM_CATEGORIES MIC,
APPS.MTL_CATEGORIES MC,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.XXAKG_DEL_ORD_HDR DOH,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND MIC.CATEGORY_ID=MC.CATEGORY_ID
AND DODL.WAREHOUSE_ORG_ID=MIC.ORGANIZATION_ID
AND MIC.INVENTORY_ITEM_ID=DODL.ORDERED_ITEM_ID
AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND DODL.ORDER_LINE_ID=OOL.LINE_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER
AND MC.SEGMENT1='FINISH GOODS'
AND MC.SEGMENT2='PEDESTAL-SILVANA-A'
AND DODL.DO_NUMBER='DO/COU/ 00002'
