SELECT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
DODL.UOM_CODE,
MOH.MOV_ORDER_NO,
MODT.VAT_CHALLAN_NO,
NVL(MODT.CHALLAN_NO,MOH.GATE_PASS_NO) "Delivery Challan NO",
TO_CHAR (MOH.CONFIRMED_DATE, 'DD-MON-YYYY') MOVE_CONFIRM_DATE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
and exists (select 1 from apps.oe_order_lines_all ol,apps.oe_order_headers_all oh where 1=1
AND oh.header_id=ol.header_id 
and ol.header_id=dODl.order_header_id 
and ol.shipment_priority_code=dOh.do_number and ol.org_id=dOh.org_id and ol.flow_status_code IN ('CLOSED','SHIPPED') and oh.order_type_id=1099) --AND OL.ACTUAL_SHIPMENT_DATE<='17-NOV-2017')
--AND DODL.WAREHOUSE_ORG_CODE='SCI'
and MOH.MOV_ORDER_STATUS='CONFIRMED'
AND DOH.DO_STATUS='CONFIRMED'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.CONFIRMED_DATE BETWEEN '05-NOV-2016' and '16-JUL-2017'
----AND TO_CHAR (MOH.CONFIRMED_DATE, 'MON-RR') = 'SEP-17'
AND DOH.CUSTOMER_NUMBER IN ('188161')
GROUP BY
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
DODL.UOM_CODE,
MOH.MOV_ORDER_NO,
MODT.VAT_CHALLAN_NO,
MOH.GATE_PASS_NO,
MOH.CONFIRMED_DATE
,MODT.CHALLAN_NO
ORDER BY MOH.CONFIRMED_DATE DESC


---------------------------------New----------------------------------------------------------
SELECT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
OOH.ORDER_NUMBER,
DOH.DO_NUMBER,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT,
OOL.ORDER_QUANTITY_UOM UOM_CODE,
MOH.MOV_ORDER_NO,
MODT.VAT_CHALLAN_NO,
NVL(MODT.CHALLAN_NO,MOH.GATE_PASS_NO)  "Delivery Challan NO"
,TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'DD-MON-YYYY') INVOICE_DATE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND DOH.ORG_ID=85
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND OOH.HEADER_ID=OOL.HEADER_ID 
AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER 
AND OOL.ORG_ID=DOH.ORG_ID   
AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-JAN-2017' and '31-JAN-2019'
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'SEP-17'
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'RRRR') = '2019'
--AND DODL.WAREHOUSE_ORG_CODE='SCI'
and MOH.MOV_ORDER_STATUS='CONFIRMED'
AND DOH.DO_STATUS='CONFIRMED'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.CONFIRMED_DATE BETWEEN '05-NOV-2016' and '16-JUL-2017'
AND DOH.CUSTOMER_NUMBER IN ('33571')
AND OOH.ORDER_TYPE_ID=1099
AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
OOH.ORDER_NUMBER,
DOH.DO_NUMBER,
OOL.ORDER_QUANTITY_UOM,
MOH.MOV_ORDER_NO,
MODT.VAT_CHALLAN_NO,
MOH.GATE_PASS_NO
,(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY)
,MODT.CHALLAN_NO
,OOL.ACTUAL_SHIPMENT_DATE
ORDER BY OOL.ACTUAL_SHIPMENT_DATE DESC
