/* Formatted on 5/22/2019 3:13:57 PM (QP5 v5.287) */
  SELECT DOH.ORG_ID,
         DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         DODL.ORDER_NUMBER,
         DOH.DO_NUMBER,
         DODL.LINE_QUANTITY DO_QUANTITY,
         TO_CHAR (DOH.DO_DATE, 'DD-MON-YYYY') DO_DATE,
         DOH.DO_STATUS,
         DODL.ITEM_NUMBER,
         DODL.ITEM_DESCRIPTION,
         DODL.UOM_CODE UOM,
         DODL.WAREHOUSE_ORG_CODE
    FROM APPS.XXAKG_DEL_ORD_HDR DOH, APPS.XXAKG_DEL_ORD_DO_LINES DODL
   WHERE     1 = 1
         AND DOH.DO_HDR_ID = DODL.DO_HDR_ID
         AND DOH.DO_STATUS IN ('CONFIRMED')
         AND DOH.ORG_ID IN (83,84,85,605) 
         AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2019'
         AND DODL.ORDER_LINE_ID IS NULL
ORDER BY DOH.DO_DATE DESC;

---------------------------LINE STATUS NEW-----------------------------------------------

  SELECT DOH.ORG_ID,
         DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         DODL.ORDER_NUMBER,
         DODL.DO_NUMBER,
         DODL.LINE_QUANTITY DO_QUANTITY,
         TO_CHAR (DOH.DO_DATE, 'DD-MON-YYYY') DO_DATE,
         DOH.DO_STATUS,
         DODL.ITEM_NUMBER,
         DODL.ITEM_DESCRIPTION,
         DODL.UOM_CODE UOM,
         DODL.WAREHOUSE_ORG_CODE ORG_CODE,
         DODL.RECORD_STATUS,
         DODL.ERROR_MSG
    --,DODL.*
    FROM APPS.XXAKG_DEL_ORD_HDR DOH, APPS.XXAKG_DEL_ORD_DO_LINES DODL
   WHERE     1 = 1
         AND DOH.DO_HDR_ID = DODL.DO_HDR_ID
         AND DOH.DO_STATUS IN ('CANCELLED')
         AND DOH.ORG_ID IN (83,84,85,605)
         AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2019'
         AND DODL.RECORD_STATUS = 'NEW'
--AND DOH.DO_NUMBER='DO/SCOU/1422740'
--AND DODL.ERROR_MSG IS NOT NULL
ORDER BY DOH.DO_DATE DESC