/* Formatted on 5/21/2019 12:26:52 PM (QP5 v5.287) */
  SELECT DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         (SELECT OOH.ORDER_NUMBER
            FROM APPS.OE_ORDER_HEADERS_ALL OOH
           WHERE     DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
                 AND OOH.HEADER_ID = OOL.HEADER_ID)
            ORDER_NO,
         OOL.ORDERED_QUANTITY,
         OOL.ORDER_QUANTITY_UOM UOM,
         OOL.FLOW_STATUS_CODE STATUS,
         OOL.ACTUAL_SHIPMENT_DATE,
         DOH.DO_NUMBER,
         TO_CHAR (DOH.DO_DATE, 'DD-MON-RR') DO_DATE,
         FLV.DESCRIPTION MOVE_ORDER_NUMBER
    FROM APPS.XXAKG_DEL_ORD_HDR DOH,
         APPS.OE_ORDER_LINES_ALL OOL,
         APPS.FND_LOOKUP_VALUES FLV
   WHERE     1 = 1
         AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
         AND OOL.SHIPMENT_PRIORITY_CODE = FLV.MEANING
         AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2019'
         --AND DOH.DO_NUMBER IN ('DO/SCOU/1271831')
         AND DOH.DO_STATUS = 'CONFIRMED'
         --AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
         --AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
         AND DOH.ORG_ID = 85
         AND NOT EXISTS
                (SELECT 1
                   FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL
                  WHERE DOH.DO_HDR_ID = DODL.DO_HDR_ID) -- AND OOL.HEADER_ID=DODL.ORDER_HEADER_ID)
ORDER BY OOL.FLOW_STATUS_CODE, DOH.DO_DATE DESC;

---------------------------------------------------------------------------------------------------

  SELECT DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         (SELECT OOH.ORDER_NUMBER
            FROM APPS.OE_ORDER_LINES_ALL OOL, APPS.OE_ORDER_HEADERS_ALL OOH
           WHERE     DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
                 AND OOH.HEADER_ID = OOL.HEADER_ID)
            ORDER_NO,
         (SELECT ACTUAL_SHIPMENT_DATE
            FROM APPS.OE_ORDER_LINES_ALL OOL
           WHERE DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE)
            INVOICE_DATE,
         DOH.DO_NUMBER,
         MOH.MOV_ORDER_NO
    FROM APPS.XXAKG_DEL_ORD_HDR DOH,
         XXAKG.XXAKG_MOV_ORD_HDR MOH,
         XXAKG.XXAKG_MOV_ORD_DTL MODT
   WHERE     1 = 1
         AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
         AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
         AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2019'
         --AND DOH.DO_NUMBER=:P_DO_NUMBER
         AND DOH.DO_STATUS = 'CONFIRMED'
         AND DOH.ORG_ID = 85
         AND NOT EXISTS
                (SELECT 1
                   FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL
                  WHERE DOH.DO_NUMBER = DODL.DO_NUMBER)
         AND EXISTS
                (SELECT 1
                   FROM APPS.OE_ORDER_LINES_ALL OOL
                  WHERE DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE)
ORDER BY DOH.DO_DATE DESC