/* Formatted on 5/29/2019 9:45:52 AM (QP5 v5.287) */
SELECT ORG_ID,
       (SELECT ORGANIZATION_CODE
          FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD
         WHERE OOD.ORGANIZATION_ID = WDV.ORGANIZATION_ID)
          ORGANIZATION_CODE,
       SHIPMENT_PRIORITY_CODE DO_NUMBER,
       (SELECT MH.CONFIRMED_DATE
          FROM XXAKG.XXAKG_MOV_ORD_HDR MH, XXAKG.XXAKG_MOV_ORD_DTL ML
         WHERE     ML.DO_NUMBER = WDV.SHIPMENT_PRIORITY_CODE
               AND ML.MOV_ORD_HDR_ID = MH.MOV_ORD_HDR_ID)
          MOVE_CONFIRM_DATE,
       --(SELECT D.DO_DATE FROM APPS.XXAKG_DEL_ORD_HDR D WHERE D.DO_NUMBER = WDV.SHIPMENT_PRIORITY_CODE) DO_DATE,
       ITEM_DESCRIPTION,
       SHIPPED_QUANTITY,
       RELEASED_STATUS_NAME STATUS,
       RELEASED_STATUS RELEASED_STATUS_CODE,
       DELIVERY_ID,
       OE_INTERFACED_FLAG,
       INV_INTERFACED_FLAG
  --,WDV.*
  FROM APPS.WSH_DELIVERABLES_V WDV
 WHERE     1 = 1
       AND RELEASED_STATUS_NAME = 'Shipped'
       --AND RELEASED_STATUS
       --AND SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
       --AND SHIPMENT_PRIORITY_CODE='DO/RMCOU/182177'
       --AND SOURCE_LINE_ID='10702768'
       --AND SOURCE_HEADER_ID='3727754'
       AND OE_INTERFACED_FLAG = 'N'
       AND INV_INTERFACED_FLAG = 'N'
       --AND TO_CHAR(CREATION_DATE,'MON-YY')='NOV-18'
       --AND TO_CHAR(CREATION_DATE,'RRRR')='2018'
       AND ((:P_ORG_ID IS NULL AND WDV.ORG_ID IN (82,83,84,85,605))  OR (WDV.ORG_ID=:P_ORG_ID))
--AND ORGANIZATION_ID=201
--AND NOT EXISTS(SELECT 1 FROM APPS.RA_INTERFACE_LINES_ALL RILA WHERE WDV.SOURCE_LINE_ID=RILA.INTERFACE_LINE_ATTRIBUTE6)
ORDER BY ORG_ID