SELECT 
DBM.REGION_NAME REGION,
TO_CHAR(FM.MO_DATE) MOVE_ORDER_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER CUSTOMER_ID,
DOH.DO_NUMBER DO_NO,
MOH.MOV_ORDER_NO MOV_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO Truck_No,
FM.MO_QUANTITY QTY,
FM.NUMBER_OF_POINT No_of_Delivery_Point,
NVL (dodl.ACTUAL_RETAILER_SHIP_TO,apps.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(dodl.SHIP_TO_ORG_ID))DELIVERY_LOCATION,
FM.ACCTUAL_KM "Total KM"
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_FUEL_MAINTANANCE FM
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.DO_HDR_ID=DOH.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=MODT.CUSTOMER_NUMBER
AND DOH.ORG_ID=DBM.ORG_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND MOH.MOV_ORDER_NO=FM.MOVE_ORDER_NO
AND MOH.VEHICLE_NO=FM.VEHICLE_NUMBER
AND MOV_ORDER_STATUS='CONFIRMED'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND MOH.TRANSPORT_MODE='Company Truck'
--AND TO_CHAR (FM.MO_DATE, 'RRRR') = '2017'
--AND FM.NUMBER_OF_POINT IS NOT NULL
AND TO_CHAR (FM.MO_DATE, 'MON-RR') = 'NOV-17'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
UNION ALL
SELECT 
DBM.REGION_NAME REGION,
TO_CHAR(MOH.MOV_ORDER_DATE) MOVE_ORDER_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER CUSTOMER_ID,
DOH.DO_NUMBER DO_NO,
MOH.MOV_ORDER_NO MOV_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO Truck_No,
SUM(DODL.LINE_QUANTITY) QTY,
FM.NUMBER_OF_POINT No_of_Delivery_Point,
NVL (DODL.ACTUAL_RETAILER_SHIP_TO,APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DODL.SHIP_TO_ORG_ID))DELIVERY_LOCATION,
FM.ACCTUAL_KM "Total KM"
--,FM.*
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_FUEL_MAINTANANCE FM
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.DO_HDR_ID=DOH.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=MODT.CUSTOMER_NUMBER
AND DOH.ORG_ID=DBM.ORG_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND MOH.MOV_ORDER_NO=FM.MOVE_ORDER_NO(+)
AND MOH.VEHICLE_NO=FM.VEHICLE_NUMBER(+)
AND MOV_ORDER_STATUS='CONFIRMED'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND MOH.TRANSPORT_MODE IN ('Rental Truck')
--AND TO_CHAR (MOH.MOV_ORDER_DATE, 'RRRR') = '2017'
--AND FM.NUMBER_OF_POINT IS NOT NULL
--AND TO_CHAR (FM.MO_DATE, 'MON-RR') = 'NOV-17'
AND TO_CHAR (MOH.MOV_ORDER_DATE, 'MON-RR') = 'NOV-17'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
GROUP BY
DBM.REGION_NAME,
MOH.MOV_ORDER_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER,
DOH.DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO,
FM.NUMBER_OF_POINT,
NVL (DODL.ACTUAL_RETAILER_SHIP_TO,APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DODL.SHIP_TO_ORG_ID)),
FM.ACCTUAL_KM




---------------------------------------------------------------------Company Truck-------------------------------------------------------------
SELECT 
DBM.REGION_NAME REGION,
TO_CHAR(MOH.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER CUSTOMER_ID,
DOH.DO_NUMBER DO_NO,
MOH.MOV_ORDER_NO MOV_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO Truck_No,
FM.MO_QUANTITY QTY,
FM.NUMBER_OF_POINT No_of_Delivery_Point,
NVL (dodl.ACTUAL_RETAILER_SHIP_TO,apps.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(dodl.SHIP_TO_ORG_ID))DELIVERY_LOCATION
--,FM.ACCTUAL_KM "Total KM"
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_FUEL_MAINTANANCE FM
WHERE 1=1
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.DO_HDR_ID=DOH.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=MODT.CUSTOMER_NUMBER
AND DOH.ORG_ID=DBM.ORG_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND MOH.MOV_ORDER_NO=FM.MOVE_ORDER_NO
AND MOH.VEHICLE_NO=FM.VEHICLE_NUMBER
AND MOV_ORDER_STATUS='CONFIRMED'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND MOH.TRANSPORT_MODE='Company Truck'
AND TO_CHAR (MOH.CONFIRMED_DATE, 'RRRR') = '2018'
AND TO_CHAR (FM.MO_DATE, 'DD-MON-RR') >= '01-AUG-18'
AND FM.NUMBER_OF_POINT IS NOT NULL
AND FM.NUMBER_OF_POINT='1'
AND FM.MO_QUANTITY>=400
--AND TO_CHAR (FM.MO_DATE, 'MON-RR') = 'NOV-17'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO

---------------------------------------------------------------------Rental Truck-------------------------------------------------------------

SELECT 
DBM.REGION_NAME REGION,
TO_CHAR(MOH.MOV_ORDER_DATE) MOVE_ORDER_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER CUSTOMER_ID,
DOH.DO_NUMBER DO_NO,
MOH.MOV_ORDER_NO MOV_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO Truck_No,
SUM(DODL.LINE_QUANTITY) QTY,
FM.NUMBER_OF_POINT No_of_Delivery_Point,
NVL (DODL.ACTUAL_RETAILER_SHIP_TO,APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DODL.SHIP_TO_ORG_ID))DELIVERY_LOCATION,
FM.ACCTUAL_KM "Total KM"
--,FM.*
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_FUEL_MAINTANANCE FM
WHERE 1=1
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.DO_HDR_ID=DOH.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=MODT.CUSTOMER_NUMBER
AND DOH.ORG_ID=DBM.ORG_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND MOH.MOV_ORDER_NO=FM.MOVE_ORDER_NO(+)
AND MOH.VEHICLE_NO=FM.VEHICLE_NUMBER(+)
AND MOV_ORDER_STATUS='CONFIRMED'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND MOH.TRANSPORT_MODE IN ('Rental Truck')
--AND TO_CHAR (MOH.MOV_ORDER_DATE, 'RRRR') = '2017'
--AND FM.NUMBER_OF_POINT IS NOT NULL
--AND TO_CHAR (FM.MO_DATE, 'MON-RR') = 'NOV-17'
AND TO_CHAR (MOH.MOV_ORDER_DATE, 'MON-RR') = 'NOV-17'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
GROUP BY
DBM.REGION_NAME,
MOH.MOV_ORDER_DATE,
DOH.CUSTOMER_NAME,
DOH.CUSTOMER_NUMBER,
DOH.DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.TRANSPORT_MODE,
MOH.VEHICLE_NO,
FM.NUMBER_OF_POINT,
NVL (DODL.ACTUAL_RETAILER_SHIP_TO,APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DODL.SHIP_TO_ORG_ID)),
FM.ACCTUAL_KM

