/* Formatted on 5/23/2019 1:39:23 PM (QP5 v5.287) */
  SELECT APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (OOL.SOLD_TO_ORG_ID) REGION,
         DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         MOH.MOV_ORDER_NO,
         OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
         NVL (OOL.ORDERED_QUANTITY, 0) DO_QUANTITY,
         --OOL.ORDERED_ITEM,
         (SELECT MSI.DESCRIPTION
            FROM INV.MTL_SYSTEM_ITEMS_B MSI
           WHERE     MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
                 AND OOL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID)
            ITEM_DESC,
         OOD.ORGANIZATION_CODE,
         OOL.FLOW_STATUS_CODE DELIVERY_STATUS,
         MOH.VEHICLE_NO,
         MOH.TRANSPORT_MODE,
         TO_CHAR (MOH.CONFIRMED_DATE, 'DD-MON-RR') MOVE_CONFIRMED_DATE
    --,MOH.*
    --,MODT.*
    FROM XXAKG.XXAKG_MOV_ORD_HDR MOH,
         XXAKG.XXAKG_MOV_ORD_DTL MODT,
         APPS.OE_ORDER_LINES_ALL OOL,
         APPS.XXAKG_DEL_ORD_HDR DOH,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD
   WHERE     1 = 1
         AND OOL.SHIP_FROM_ORG_ID = OOD.ORGANIZATION_ID
         AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
         AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
         AND OOL.SHIPMENT_PRIORITY_CODE = MODT.DO_NUMBER
         AND DOH.DO_STATUS = 'CONFIRMED'
         AND MOH.MOV_ORDER_STATUS = 'CONFIRMED'
         AND OOL.FLOW_STATUS_CODE = 'AWAITING_SHIPPING' -- IN ('CLOSED','SHIPPED')  --='AWAITING_SHIPPING'
         AND MOH.ORG_ID = 85
         --AND WAREHOUSE_ORG_CODE='SCI'
         AND OOL.ORDER_QUANTITY_UOM IN ('MTN', 'BAG')
         --AND MOH.TRANSPORT_MODE IN ('Company Bulk Carrier','Company Truck')
         --AND MOH.VEHICLE_NO LIKE '%2369%' --IN ('D.M.U-12-1695')
         --AND MOH.MOV_ORDER_NO IN ('MO/SCOU/1220918')
         --AND MOV_ORDER_STATUS IN ('CONFIRMED')
         --AND TO_CHAR(MOH.CONFIRMED_DATE,'DD-MON-RR')='31-DEC-18'
         --AND TO_CHAR(MOH.CONFIRMED_DATE,'MON-RR')='DEC-18'
         --AND TO_CHAR(MOH.CONFIRMED_DATE,'RRRR')='2018'
         AND MOH.CONFIRMED_DATE <= '31-JUL-2019'
        --AND DOH.DO_DATE BETWEEN '01-JAN-2010' and '30-APR-2018'
        --AND TRUNC(MOH.MOV_ORDER_DATE) BETWEEN '28-NOV-2018' and '29-NOV-2018'
        --AND MODT.DO_NUMBER IN ('DO/SCOU/1152730')
        --AND MODT.CUSTOMER_NUMBER IN ('20058')
        --AND MOH.FINAL_DESTINATION='Norshindi'
        --AND MOH.GATE_PASS_NO='693452'
        --AND MODT.VAT_IN_FLAG='Y'
        --AND MODT.CHALLANED_FLAG!='Y'
        --AND MOH.GATE_OUT IS NULL
        --AND MOH.GATE_IN IS NULL
        --AND MOH.SCALE_IN_WT!='0'
        --AND MOH.EMPTY_TRUCK_WT!='0'
        --AND TO_CHAR(MOH.GATE_OUT_DATE,'YYYY/MON/DD HH24:MI:SS') BETWEEN '2018/NOV/28 06:00:00' AND '2018/NOV/29 09:40:00'--HH:MI:SS--12:00:00
        --AND EXISTS(SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OL WHERE 1=1 AND OL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER AND OL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED'))
ORDER BY MOH.MOV_ORDER_DATE DESC