/* Formatted on 7/14/2019 1:43:35 PM (QP5 v5.287) */
SELECT *
  FROM APPS.FND_LOOKUP_VALUES
 WHERE 1 = 1 AND LOOKUP_TYPE LIKE '%AKG%SUB'
--AND MEANING like 'Modern%'
;

SELECT FFV.FLEX_VALUE
  --,FFV.*
  FROM APPS.FND_FLEX_VALUE_SETS VAL_SET, APPS.FND_FLEX_VALUES FFV
 WHERE     1 = 1
       AND VAL_SET.FLEX_VALUE_SET_ID = FFV.FLEX_VALUE_SET_ID
       AND VAL_SET.FLEX_VALUE_SET_NAME LIKE '%AKG%SUB'
--AND FFV.FLEX_VALUE='Dhaka'
;


SELECT VL.*
  FROM APPS.FND_FLEX_VALUE_SETS VS, apps.FND_FLEX_VALUES_VL VL
 WHERE     1 = 1
       AND VS.FLEX_VALUE_SET_ID = VL.FLEX_VALUE_SET_ID
       AND FLEX_VALUE_SET_NAME = 'AKG_ITEM_SUB_GROUP'
       
--------------------------------------------------------------------------------
SELECT *                                          --MEANING "EXECUTION_METHOD"
  FROM APPS.FND_LOOKUP_VALUES
 WHERE LOOKUP_TYPE = 'CP_EXECUTION_METHOD_CODE' AND ENABLED_FLAG = 'Y';