/* Formatted on 10/15/2019 4:30:44 PM (QP5 v5.287) */
SELECT DH.ORG_ID,
       C.CUSTOMER_NUMBER,
       C.CUSTOMER_NAME,
       C.ATTRIBUTE9 OFFICER_PHONE_NO,
       XXAKG_ONT_PKG.GET_RETAILER_PHONE_NO (DL.SHIP_TO_ORG_ID)
          RETAILER_PHONE_NO,
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = C.CUSTOMER_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
               AND ARC.JOB_TITLE = 'AM'
               AND ROWNUM = 1)
          AM_PHONE_NO,
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = C.CUSTOMER_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
               AND ARC.JOB_TITLE = 'Dealer'
               AND ROWNUM = 1)
          DEALER_PHONE_NO,
       DL.ORDER_NUMBER,
       DH.DO_NUMBER,
       DL.ORDERED_ITEM_ID,
       DL.ITEM_NUMBER,
       DL.ITEM_DESCRIPTION,
       NVL (DL.LINE_QUANTITY, 0) QUANTITY,
       DL.UOM_CODE,
       DL.SHIP_TO_LOCATION,
       DL.ACTUAL_RETAILER_SHIP_TO,
       MH.MOV_ORDER_NO,
       MH.MOV_ORDER_STATUS,
       TRUNC (MH.CONFIRMED_DATE) MOV_CONFIRMED_DATE,
       MH.FINAL_DESTINATION,
       MH.HIRE_RATE_AP,
       MH.VEHICLE_NO,
       MH.DRIVER_NAME,
       MH.DRIVER_MOBILE
  FROM XXAKG_DEL_ORD_HDR DH,
       XXAKG_DEL_ORD_DO_LINES DL,
       XXAKG_MOV_ORD_HDR MH,
       XXAKG_MOV_ORD_DTL ML,
       APPS.AR_CUSTOMERS C
 WHERE     MH.MOV_ORD_HDR_ID = ML.MOV_ORD_HDR_ID
       AND DH.DO_HDR_ID = DL.DO_HDR_ID
       AND DH.DO_HDR_ID = ML.DO_HDR_ID
       AND DH.ORG_ID = MH.ORG_ID
       AND DH.ORG_ID = 83
       AND DH.CUSTOMER_NUMBER = C.CUSTOMER_NUMBER
       AND MH.MOV_ORDER_STATUS = 'CONFIRMED'
       AND DL.UOM_CODE = 'PCS'
       AND DH.CUSTOMER_NUMBER = '35055'
       AND DH.DO_NUMBER = 'DO/COU/57909';
       
       SELECT
       *
       FROM
       APPS.XXAKG_CER_DO2MOVE_SMS
       WHERE CUSTOMER_NUMBER = '35055'
       AND DO_NUMBER = 'DO/COU/57909'