/* Formatted on 10/21/2019 2:21:31 PM (QP5 v5.287) */
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NUMBER,
       C.CUSTOMER_NAME CUSTOMER,
       APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (C.CUSTOMER_ID) REGION,
       C.ATTRIBUTE9 OFFICER_PHONE_NO,
       --        APPS.XXAKG_ONT_PKG.GET_RETAILER_PHONE_NO (L.SHIP_TO_ORG_ID)
       --             RETAILER_PHONE_NO,
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = C.CUSTOMER_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
--               AND HOC.PHONE_NUMBER IS NOT NULL
               AND ARC.JOB_TITLE = 'AM')
          AM_PHONE_NO,
       (SELECT DISTINCT NVL (HOC.PHONE_NUMBER, 0)
          FROM APPS.AR_CONTACTS_V ARC, APPS.HZ_ORG_CONTACTS_V HOC
         WHERE     ARC.CONTACT_NUMBER = HOC.CONTACT_NUMBER
               AND ARC.CUSTOMER_ID = C.CUSTOMER_ID
               AND HOC.STATUS = 'A'
               AND HOC.CONTACT_STATUS = 'A'
               AND HOC.CONTACT_PRIMARY_FLAG = 'Y'
               AND HOC.CONTACT_POINT_TYPE = 'PHONE'
--               AND HOC.PHONE_NUMBER IS NOT NULL
               AND ARC.JOB_TITLE = 'Dealer')
          DEALER_PHONE_NO
  --,C.*
  FROM APPS.AR_CUSTOMERS C
 WHERE     (   :P_CUSTOMER_NUMBER IS NULL
            OR (C.CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER))
       AND ( :P_CUSTOMER_STATUS IS NULL OR (C.STATUS = :P_CUSTOMER_STATUS))
       --AND C.ATTRIBUTE9 IS NOT NULL
       AND EXISTS
              (SELECT 1
                 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M R
                WHERE     R.ORG_ID = 83
                      AND C.CUSTOMER_ID = R.CUSTOMER_ID
                      AND (   :P_REGION_NAME IS NULL
                           OR (R.REGION_NAME = :P_REGION_NAME)))