SELECT 
--DO_NUMBER,
COUNT(DO_DTL.DO_NUMBER) "NO_OF_DO's",
DO_DTL.APX_QTY "Approximate Quantity"
FROM
(SELECT
DODL.DO_NUMBER,
--SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) QUANTITY,
(CASE
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 1 AND 104 THEN 100
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 105 AND 208 THEN 200
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 209 AND 312 THEN 300
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 313 AND 416 THEN 400
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 417 AND 520 THEN 500
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 521 AND 623 THEN 600
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 624 AND 728 THEN 700
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 725 AND 832 THEN 800
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 833 AND 900 THEN 900
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 901 AND 1000 THEN 1000
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 1001 AND 1500 THEN 1500
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 1501 AND 2000 THEN 2000
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 2001 AND 3000 THEN 3000
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 3001 AND 4000 THEN 4000
        ELSE SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY)))
END) "APX_QTY"
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
,APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1
AND DOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.LINE_ID=DODL.ORDER_LINE_ID
AND DODL.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'OCT-17'
AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '15-NOV-2017' and '19-NOV-2017'
GROUP BY
DODL.DO_NUMBER) DO_DTL
WHERE 1=1
GROUP BY
DO_DTL.APX_QTY
--,DO_NUMBER
ORDER BY
DO_DTL.APX_QTY ASC


------------------------------------------------------------------------------------------------
SELECT 
--DO_NUMBER,
COUNT(DO_DTL.DO_NUMBER) NO_OF_DOs,
DO_DTL.APX_QTY
FROM
(SELECT
DODL.DO_NUMBER,
--SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) QUANTITY,
(CASE
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 1 AND 104 THEN 100
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 105 AND 208 THEN 200
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 209 AND 312 THEN 300
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 313 AND 416 THEN 400
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 417 AND 520 THEN 500
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 521 AND 623 THEN 600
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 624 AND 728 THEN 700
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) BETWEEN 725 AND 832 THEN 800
        ELSE SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY))
END) "APX_QTY"
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
,APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1
AND DOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.LINE_ID=DODL.ORDER_LINE_ID
AND DODL.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'OCT-17'
AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '15-NOV-2017' and '19-NOV-2017'
GROUP BY
DODL.DO_NUMBER) DO_DTL
WHERE 1=1
GROUP BY
DO_DTL.APX_QTY
--,DO_NUMBER
ORDER BY
DO_DTL.APX_QTY ASC


------------------------------------------------------------------------------------------------

SELECT
DODL.DO_NUMBER,
SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,'BAG', DODL.LINE_QUANTITY)) QUANTITY
,
(CASE
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 1 AND 104 THEN 100
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 105 AND 208 THEN 200
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 209 AND 312 THEN 300
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 313 AND 416 THEN 400
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 417 AND 520 THEN 500
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 521 AND 728 THEN 700
        WHEN SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY))) BETWEEN 725 AND 832 THEN 800
        ELSE SUM(DECODE (DODL.UOM_CODE, 'MTN', CEIL(DODL.LINE_QUANTITY*20),'BAG', CEIL(DODL.LINE_QUANTITY)))
END) "APX_QTY"
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
,APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1
AND DOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.LINE_ID=DODL.ORDER_LINE_ID
AND DODL.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND DODL.UOM_CODE IN ('MTN','BAG')
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'OCT-17'
AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '15-NOV-2017' and '19-NOV-2017'
GROUP BY
DODL.DO_NUMBER
