SELECT 
OLA.ORG_ID, 
--OLA.HEADER_ID, 
ACSV.CUSTOMER_NUMBER,
ACSV.CUSTOMER_NAME,
OLA.ORDERED_ITEM, 
OLA.FLOW_STATUS_CODE,
sum(OLA.ORDERED_QUANTITY),
SUM(OLA.CANCELLED_QUANTITY),
SUM(OLA.SHIPPED_QUANTITY),
sum(OLA.SHIPPING_QUANTITY),
SUM(OLA.INVOICED_QUANTITY)
FROM 
APPS.OE_ORDER_LINES_ALL OLA,
APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV
WHERE 1=1
--AND OLA.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')
AND ACSV.CUSTOMER_NUMBER='187887'
AND OLA.ACTUAL_SHIPMENT_DATE<='19-DECEMBER-2018'
--AND OLA.ACTUAL_SHIPMENT_DATE BETWEEN '01-JULY-2017' and '31-JULY-2017'
--AND OLA.SOLD_TO_ORG_ID=10311
AND ACSV.SHIP_TO_ORG_ID=OLA.SHIP_TO_ORG_ID
GROUP BY OLA.ORG_ID, 
--OLA.HEADER_ID, 
OLA.ORDERED_ITEM, 
OLA.ORDER_QUANTITY_UOM, 
OLA.FLOW_STATUS_CODE,
ACSV.CUSTOMER_NUMBER,
ACSV.CUSTOMER_NAME
ORDER BY ACSV. CUSTOMER_NUMBER