SELECT 
  DECODE (EXTRACT(MONTH FROM ACTUAL_SHIPMENT_DATE), 1, 'JAN', 
                             2, 'FEB', 
                             3, 'MAR', 
                             4, 'APR',
                             5, 'MAY',
                             6, 'JUN', 
                             7, 'JUL', 
                             8, 'AUG', 
                             9, 'SEP',
                             10, 'OCT', 
                             11, 'NOV', 
                             12, 'DEC', 
                                'Not Defined') "Month", 
  EXTRACT(YEAR FROM ACTUAL_SHIPMENT_DATE) AS YEAR
FROM APPS.OE_ORDER_LINES_ALL


SELECT 
--OOL.ORG_ID,
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--WDD.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
OOL.ORDERED_ITEM,
--WDD.ITEM_DESCRIPTION,
--ORG.ORGANIZATION_NAME,
ORG.ORGANIZATION_CODE,
SUM(DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,
                                        'BAG', DODL.LINE_QUANTITY,
                                'Not Defined')) "QUANTITY",
DODL.UOM_CODE,
DECODE (EXTRACT(MONTH FROM OOL.ACTUAL_SHIPMENT_DATE), 1, 'JAN', 
                             2, 'FEB', 
                             3, 'MAR', 
                             5, 'MAY',
                             6, 'JUN', 
                             7, 'JUL', 
                             8, 'AUG', 
                             9, 'SEP',
                             10, 'OCT', 
                             11, 'NOV', 
                             12, 'DEC', 
                                'Not Defined') "Month", 
  EXTRACT(YEAR FROM OOL.ACTUAL_SHIPMENT_DATE) AS YEAR
--,OOL.ACTUAL_SHIPMENT_DATE
FROM 
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
WSH.WSH_DELIVERY_DETAILS WDD,
APPS.ORG_ORGANIZATION_DEFINITIONS ORG,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.XXAKG_DEL_ORD_HDR DOH,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 
OOH.ORG_ID=OOL.ORG_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND OOH.HEADER_ID=WDD.SOURCE_HEADER_ID
AND OOL.LINE_ID=WDD.SOURCE_LINE_ID
AND ORG.ORGANIZATION_ID= OOL.SHIP_FROM_ORG_ID
AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
AND WDD.RELEASED_STATUS='C'
AND OOL.ORG_ID=85
AND OOL.ORDERED_ITEM NOT IN ('EBAG.SBAG.0001','EBAG.SBAG.0002','EBAG.SBAG.0003')
AND DODL.UOM_CODE IN ('BAG','MTN')
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'AUG-17'
--AND DOH.DO_DATE BETWEEN '01-JAN-2011' and '31-OCT-2017'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'AUG-17'
GROUP BY
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--WDD.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
OOL.ORDERED_ITEM,
--WDD.ITEM_DESCRIPTION,
--ORG.ORGANIZATION_NAME,
ORG.ORGANIZATION_CODE,
DODL.UOM_CODE,
OOL.ACTUAL_SHIPMENT_DATE
--,DOH.DO_DATE
ORDER BY OOL.ACTUAL_SHIPMENT_DATE DESC


SELECT ORDER_NUMBER,
DECODE (DODL.UOM_CODE, 'MTN', DODL.LINE_QUANTITY*20,
                                        'BAG', DODL.LINE_QUANTITY,
                                'Not Defined') "QUANTITY"
FROM
APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND UOM_CODE='MTN'
--AND DO_NUMBER='DO/SCOU/ 03854'
AND ORG_ID=85

SELECT ORDER_NUMBER,
DECODE (DODL.UOM_CODE, 'MTN', 'BAG' ,
                                        'BAG', 'BAG',
                                'Not Defined') "NEW UOM CODE"
FROM
APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND UOM_CODE='MTN'
--AND DO_NUMBER='DO/SCOU/ 03854'
AND ORG_ID=85
