SELECT DISTINCT
DD.CUSTOMER_NUMBER,
DD.CUSTOMER_NAME,
OD.ORDER_NUMBER,
OD.TOTAL_ORDERED_QUANTITY,
OD.FLOW_STATUS_CODE,
DD.DO_NUMBER,
DD.DO_DATE,
DD.DO_STATUS,
DD.TOTAL_DO_QUANTITY,
DD.ITEM_NUMBER,
DD.ITEM_DESCRIPTION,
DD.UOM_CODE,
DD.WAREHOUSE_ORG_CODE
FROM
(SELECT DISTINCT
OOH.HEADER_ID,
OOH.ORDER_NUMBER,
SUM(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY,
OOL.ORDERED_ITEM_ID,
OOL.LINE_ID
,OOL.FLOW_STATUS_CODE
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
GROUP BY OOH.HEADER_ID,
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM_ID,
OOL.LINE_ID
,OOL.FLOW_STATUS_CODE
) OD
,(SELECT DISTINCT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DODL.DO_NUMBER,
TO_CHAR (DOH.DO_DATE, 'DD-MON-YYYY') DO_DATE,
DOH.DO_STATUS,
SUM(DODL.LINE_QUANTITY) TOTAL_DO_QUANTITY,
DODL.ORDER_LINE_ID,
DODL.ORDER_HEADER_ID,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.ORDERED_ITEM_ID,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_STATUS='GENERATED'
AND DOH.DO_DATE BETWEEN '01-JUN-2017' and '01-OCT-2017'
GROUP BY DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DODL.DO_NUMBER,
DO_DATE,
DOH.DO_STATUS,
DODL.ORDER_LINE_ID,
DODL.ORDER_HEADER_ID,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.ORDERED_ITEM_ID,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE
) DD
WHERE 1=1
AND OD.ORDER_NUMBER=DD.ORDER_NUMBER
AND OD.HEADER_ID=DD.ORDER_HEADER_ID
AND OD.ORDERED_ITEM_ID=DD.ORDERED_ITEM_ID
AND DD.UOM_CODE='BAG'
--AND OD.ORDERED_QUANTITY>=DD.DO_QUANTITY
