SELECT DISTINCT
DO_DTL.CUSTOMER_NUMBER,
DO_DTL.CUSTOMER_NAME,
OD_DTL.ORDER_NUMBER,
OD_DTL.TOTAL_ORDERED_QUANTITY,
OD_DTL.REMAIN_QUANTITY,
OD_DTL.TOTAL_INVOICED_QUANTITY,
--OD_DTL.FLOW_STATUS_CODE,
DO_DTL.DO_NUMBER,
DO_DTL.DO_DATE,
DO_DTL.DO_STATUS,
DO_DTL.TOTAL_DO_QUANTITY,
DO_DTL.ITEM_NUMBER,
DO_DTL.ITEM_DESCRIPTION,
DO_DTL.MODE_OF_TRANSPORT,
DO_DTL.UOM_CODE,
DO_DTL.WAREHOUSE_ORG_CODE
FROM
(SELECT DISTINCT
OOH.ORG_ID,
OOH.ORDER_NUMBER,
SUM(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY,
SUM(OOL.ORDERED_QUANTITY)-SUM(OOL.SHIPPED_QUANTITY) REMAIN_QUANTITY,
SUM(OOL.INVOICED_QUANTITY) TOTAL_INVOICED_QUANTITY,
OOL.ORDERED_ITEM,
OOL.ORDERED_ITEM_ID
--,OOL.FLOW_STATUS_CODE
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOH.ORDER_NUMBER=1633463
GROUP BY 
OOH.ORG_ID,
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM_ID,
OOL.ORDERED_ITEM
--,OOL.FLOW_STATUS_CODE
) OD_DTL,
(SELECT DISTINCT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER ORDER_NO,
DODL.DO_NUMBER,
TO_CHAR (DOH.DO_DATE, 'DD-MON-YYYY') DO_DATE,
DOH.DO_STATUS,
SUM(DODL.LINE_QUANTITY) TOTAL_DO_QUANTITY,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.ORDERED_ITEM_ID,
DOH.MODE_OF_TRANSPORT,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
--AND DOH.DO_STATUS IN (/*'GENERATED',*/'CONFIRMED')
AND DODL.UOM_CODE='BAG'
AND DOH.DO_DATE BETWEEN '01-JUN-2017' and '01-OCT-2017'
GROUP BY DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DODL.DO_NUMBER,
DO_DATE,
DOH.DO_STATUS,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.ORDERED_ITEM_ID,
DOH.MODE_OF_TRANSPORT,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE
) DO_DTL
WHERE 1=1
AND OD_DTL.ORDER_NUMBER=DO_DTL.ORDER_NO
AND OD_DTL.ORDERED_ITEM_ID=DO_DTL.ORDERED_ITEM_ID
AND OD_DTL.ORG_ID=85
ORDER BY DO_DTL.DO_DATE DESC
--CASE WHEN  