SELECT
--DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
--DOH.DO_NUMBER,
--MOH.MOV_ORDER_NO,
MOH.TRANSPORT_MODE, 
APS.SEGMENT1 TRANSPORTER_NUMBER,
APS.VENDOR_NAME TRANSPORTER_NAME,
AIA.INVOICE_NUM,
SUM(DODL.LINE_QUANTITY) QUANTITY,
MOH.HIRE_RATE_AP HIRE_RATE,
AIA.INVOICE_AMOUNT,
TO_CHAR (AIA.INVOICE_DATE, 'DD-MON-YYYY') INVOICE_DATE
--,MOH.WAREHOUSE_ORG_CODE
--,AIA.DOC_SEQUENCE_VALUE
FROM
--APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.AP_INVOICES_ALL AIA,
APPS.AP_SUPPLIERS APS
WHERE 1=1
--AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
--AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND MOH.MOV_ORDER_NO=AIA.INVOICE_NUM
AND DODL.DO_HDR_ID=MODT.DO_HDR_ID
AND MOH.TRANSPORTER_VENDOR_ID=APS.VENDOR_ID
--AND MOH.WAREHOUSE_ORG_CODE='SCI'
AND MOH.TRANSPORT_MODE='Company Truck'--'Rental Truck'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND AIA.PAYMENT_STATUS_FLAG='N'--'Y'
--AND MOH.MOV_ORDER_DATE>='01-JAN-2012'
AND MOH.ORG_ID=85
--AND AIA.INVOICE_DATE BETWEEN '15-OCT-2017' and '16-OCT-2017'
--AND TO_CHAR (AIA.INVOICE_DATE, 'RRRR') = '2011'
--AND TO_CHAR (AIA.INVOICE_DATE, 'MON-RR') = 'SEP-17'
GROUP BY
--DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
--DOH.DO_NUMBER,
--MOH.MOV_ORDER_NO,
MOH.TRANSPORT_MODE, 
APS.SEGMENT1,
APS.VENDOR_NAME,
--MOH.WAREHOUSE_ORG_CODE,
MOH.HIRE_RATE_AP,
AIA.INVOICE_NUM,
AIA.INVOICE_AMOUNT,
AIA.INVOICE_DATE
--,AIA.DOC_SEQUENCE_VALUE
ORDER BY AIA.INVOICE_DATE DESC