/* Formatted on 11/17/2019 6:01:24 PM (QP5 v5.287) */
  SELECT APS.SEGMENT1 TRANSPORTER_NUMBER,
         --MOH.TRANSPORTER_NAME,
         APSA.ADDRESS_LINE1 SUPPLIER_SITE,
         --DOH.CUSTOMER_NUMBER,
         --DOH.CUSTOMER_NAME,
         --MOH.TRANSPORT_MODE,
         AIA.INVOICE_NUM,
         --SUM(DODL.LINE_QUANTITY) QUANTITY,
         AIA.INVOICE_AMOUNT,
         --MTO.MOV_ORDER_NO MTO_NUMBER,
         --MTO.QUANTITY MTO_QUANTITY,
         TO_CHAR (AIA.CREATION_DATE, 'DD-MON-YYYY') INVOICE_DATE,
         fndu.user_name user_id--,MOH.WAREHOUSE_ORG_CODE
         ,
         AIA.INVOICE_TYPE_LOOKUP_CODE
    FROM --APPS.XXAKG_DEL_ORD_HDR DOH,
         --APPS.XXAKG_DEL_ORD_DO_LINES DODL,
         --APPS.XXAKG_MOV_ORD_DTL MODT,
         --APPS.XXAKG_MOV_ORD_HDR MOH,
         APPS.AP_INVOICES_ALL AIA,
         APPS.AP_SUPPLIERS APS,
         APPS.AP_SUPPLIER_SITES_ALL APSA,
         apps.fnd_user fndu
   --,APPS.XXAKG_TO_MO_DETAIL_CEMENT MTO
   WHERE     1 = 1
         --AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
         --AND DOH.DO_NUMBER=MODT.DO_NUMBER
         --AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
         --AND MOH.MOV_ORDER_NO=AIA.INVOICE_NUM
         --AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
         --AND MOH.TRANSPORTER_VENDOR_ID=APS.VENDOR_ID
         AND AIA.VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
         AND APS.VENDOR_ID = APSA.VENDOR_ID
         --AND MTO.TRANSPORTER_VENDOR_ID=APS.VENDOR_ID
         --AND MTO.TRANSPORTER_VENDOR_SITE_ID=APSA.VENDOR_SITE_ID
         AND AIA.PAYMENT_STATUS_FLAG = 'N'
         --AND AIA.INVOICE_NUM=:P_INVOICE_NUM
         --AND APS.SEGMENT1=:P_SEGMENT1
         AND AIA.CREATION_DATE BETWEEN '01-JAN-2011' AND '08-JAN-2018'
--AND DOH.CUSTOMER_NUMBER IN ('20107','20770','184363')
--AND AIA.SOURCE='Manual Invoice Entry'
--and fndu.user_id=aia.LAST_UPDATED_BY
--AND fndu.user_name IN ('2087','21213')
--AND AIA.INVOICE_AMOUNT!='0'
GROUP BY --MOH.TRANSPORTER_NAME,
         APS.SEGMENT1,
         APSA.ADDRESS_LINE1,
         --DOH.CUSTOMER_NUMBER,
         --DOH.CUSTOMER_NAME,
         AIA.INVOICE_NUM,
         --MOH.TRANSPORT_MODE,
         AIA.INVOICE_AMOUNT,
         AIA.CREATION_DATE
--,MOH.WAREHOUSE_ORG_CODE
--,MTO.MOV_ORDER_NO,
--MTO.QUANTITY

--------------------------------------------------------------------------------
/* Formatted on 11/17/2019 5:56:50 PM (QP5 v5.287) */
  SELECT 'MOVE' TRIP_TYPE,
         NVL(DBM.REGION_NAME,'Unspecified') REGION_NAME,
         AIA.INVOICE_TYPE_LOOKUP_CODE INVOICE_TYPE,
         APS.SEGMENT1 SUPPLIER_NUMBER,
         APS.VENDOR_NAME SUPPLIER_NAME,
         APSA.VENDOR_SITE_CODE SUPPLIER_SITE,
         TO_NUMBER (DOH.CUSTOMER_NUMBER) CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         MOH.TRANSPORT_MODE,
         AIA.INVOICE_NUM,
         DOH.DO_NUMBER "D/TO_NUMBER",
         SUM (OOL.SHIPPED_QUANTITY) QUANTITY,
         MOH.HIRE_RATE_AP UPDATE_HIRE_RATE,
         HR.PAYABLE_RATE CHART_RATE,
         AIA.INVOICE_AMOUNT,
         TO_CHAR (AIA.INVOICE_DATE) INVOICE_DATE,
         HR.M_FROM_LOCATION WAREHOUSE,
         MOH.FINAL_DESTINATION
    FROM APPS.XXAKG_TRANSPORT_HIRERATE HR,
         APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
         APPS.XXAKG_DEL_ORD_HDR DOH,
         APPS.OE_ORDER_LINES_ALL OOL,
         APPS.XXAKG_MOV_ORD_DTL MODT,
         APPS.XXAKG_MOV_ORD_HDR MOH,
         APPS.AP_INVOICES_ALL AIA,
         APPS.AP_SUPPLIERS APS,
         APPS.AP_SUPPLIER_SITES_ALL APSA
   WHERE     1 = 1
         AND HR.FROM_LOCATION = OOL.SHIP_FROM_ORG_ID
         AND HR.TO_LOCATION = MOH.FINAL_DESTINATION
         AND HR.TRANSPORT_MODE = MOH.TRANSPORT_MODE
         AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
         AND DOH.DO_NUMBER = MODT.DO_NUMBER
         AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
         AND MOH.MOV_ORDER_NO = AIA.INVOICE_NUM
         AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
         AND MOH.TRANSPORTER_VENDOR_ID = APS.VENDOR_ID
         AND AIA.VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
         AND APS.VENDOR_ID = APSA.VENDOR_ID
         AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER(+)
         AND AIA.PAYMENT_STATUS_FLAG = 'N'
         AND HR.END_DATE_ACTIVE IS NULL
         AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
         AND DOH.ORG_ID = 85
         --AND AIA.INVOICE_NUM=:P_INVOICE_NUM
         --AND APS.SEGMENT1=:P_SEGMENT1
         --AND AIA.INVOICE_DATE BETWEEN '15-OCT-2017' and '16-OCT-2017'
         --AND TO_CHAR (AIA.INVOICE_DATE, 'RRRR') = '2011'
         AND     (:P_Period_of_Month IS NULL OR (to_char(AIA.INVOICE_DATE,'MON-RR')=:P_Period_of_Month))
GROUP BY DBM.REGION_NAME,
         APS.VENDOR_NAME,
         APS.SEGMENT1,
         APSA.VENDOR_SITE_CODE,
         DOH.CUSTOMER_NUMBER,
         DOH.CUSTOMER_NAME,
         AIA.INVOICE_NUM,
         MOH.TRANSPORT_MODE,
         MOH.HIRE_RATE_AP,
         HR.PAYABLE_RATE,
         AIA.INVOICE_AMOUNT,
         AIA.INVOICE_DATE,
         HR.M_FROM_LOCATION,
         MOH.FINAL_DESTINATION
         ,AIA.INVOICE_TYPE_LOOKUP_CODE
         ,DOH.DO_NUMBER
--ORDER BY AIA.INVOICE_DATE DESC
UNION ALL
SELECT 'MTO' TRIP_TYPE,
       'Undefined' REGION_NAME,
       AIA.INVOICE_TYPE_LOOKUP_CODE INVOICE_TYPE,
       APS.SEGMENT1 SUPPLIER_NUMBER,
       APS.VENDOR_NAME SUPPLIER_NAME,
       APSA.VENDOR_SITE_CODE SUPPLIER_SITE,
       MTO.CUSTOMER_ID CUSTOMER_NUMBER,
       MTO.CUSTOMER_NAME,
       MTO.MODE_OF_TRANSPORT TRANSPORT_MODE,
       AIA.INVOICE_NUM,
       MTO.TRANSFER_ORDER_NO "D/TO_NUMBER",
       MTO.QUANTITY QUANTITY,
       MTO.HIRE_RATE_AP UPDATE_HIRE_RATE,
       HR.PAYABLE_RATE CHART_RATE,
       AIA.INVOICE_AMOUNT,
       TO_CHAR (AIA.INVOICE_DATE) INVOICE_DATE,
       HR.M_FROM_LOCATION WAREHOUSE,
       MTO.FINAL_DESTINATION
  FROM APPS.XXAKG_TRANSPORT_HIRERATE HR,
       --APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
       APPS.AP_INVOICES_ALL AIA,
       APPS.AP_SUPPLIERS APS,
       APPS.AP_SUPPLIER_SITES_ALL APSA,
       APPS.XXAKG_TO_MO_DETAIL_CEMENT MTO
 WHERE     1 = 1
       AND HR.FROM_LOCATION = MTO.FROM_ORGANIZATION_ID
       AND HR.TO_LOCATION = MTO.FINAL_DESTINATION
       AND HR.TRANSPORT_MODE = MTO.TRANSPORT_MODE
       AND APS.VENDOR_ID = AIA.VENDOR_ID
       AND AIA.VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
       AND APS.VENDOR_ID = APSA.VENDOR_ID
       AND MTO.MOV_ORDER_NO = AIA.INVOICE_NUM
       AND MTO.TRANSPORTER_VENDOR_ID = APS.VENDOR_ID
       AND MTO.TRANSPORTER_VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
       --AND MTO.CUSTOMER_ID=DBM.CUSTOMER_NUMBER
       AND AIA.PAYMENT_STATUS_FLAG = 'N'
       AND HR.END_DATE_ACTIVE IS NULL
       AND MTO.ORG_ID = 85
       --AND AIA.INVOICE_NUM=:P_INVOICE_NUM
       --AND APS.SEGMENT1=:P_SEGMENT1
       --AND AIA.INVOICE_DATE BETWEEN '15-OCT-2017' and '16-OCT-2017'
       AND     (:P_Period_of_Month IS NULL OR (to_char(AIA.INVOICE_DATE,'MON-RR')=:P_Period_of_Month))
--AND TO_CHAR (AIA.INVOICE_DATE, 'RRRR') = '2011'
--ORDER BY AIA.INVOICE_DATE DESC