SELECT
--OU.*
INC.*
FROM
APPS.XXAKG_SCIL_INCENTIVE_INV_STG INC
,APPS.HR_OPERATING_UNITS OU
WHERE 1=1
AND INC.OPERATING_UNIT_NAME=OU.NAME
AND OU.ORGANIZATION_ID='83'
--AND STATUS!='PROCESSED'
--AND TO_CHAR(INC.TRANSACTION_DATE,'DD-MON-RR')='31-MAY-19'
--AND TO_CHAR(INC.GL_DATE,'MON-RR')='JAN-19'
--AND TO_CHAR(INC.GL_DATE,'RRRR')='2019'
--AND ROWNUM<=3
ORDER BY INC.TRANSACTION_DATE DESC