SELECT 
NVL(DBM.REGION_NAME,'Unspecified') REGION_NAME,
DBM.CUSTOMER_NUMBER,
DBM.CUSTOMER_NAME,
SUM(DODL.LINE_QUANTITY) QUANTITY,
MOH.HIRE_RATE_AP "Sum of CPB",
(MOH.HIRE_RATE_AP*SUM(DODL.LINE_QUANTITY)) "Sum of Amount"
FROM 
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.DO_NUMBER=DODL.DO_NUMBER
AND DBM.REGION_NAME!='Scrap'
AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
AND DOH.ORG_ID=85
AND MOH.TRANSPORT_MODE='Rental Truck'
AND DODL.WAREHOUSE_ORG_CODE='SCI'
AND DOH.ORG_ID=MOH.ORG_ID
AND TO_CHAR(MOH.CONFIRMED_DATE,'DD-MON-RR')='13-MAR-18'
--AND DBM.REGION_NAME='Bogra'
--AND EXISTS (SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OOL WHERE OOL.LINE_ID=DODL.ORDER_LINE_ID AND OOL.FLOW_STATUS_CODE='CLOSED' 
--                    AND TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE,'DD-MON-RR')='13-MAR-18')
--AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2018'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'JAN-18'
GROUP BY 
DBM.REGION_NAME,
DBM.CUSTOMER_NUMBER,
DBM.CUSTOMER_NAME,
MOH.HIRE_RATE_AP