SELECT 
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
SOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--OOD.ORGANIZATION_NAME,
DODL.WAREHOUSE_ORG_CODE,
--MOH.MOV_ORDER_NO,
DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
SUM(NVL (LINE_QUANTITY, 0)) DO_QUANTITY,
--WPB.NAME BATCH_NO,
TO_CHAR(SOL.ACTUAL_SHIPMENT_DATE) ACTUAL_SHIPMENT_DATE
--DOH.MODE_OF_TRANSPORT,
--DOH.TRANSPORTER_NAME,
--WSHD.RELEASED_STATUS_NAME,
--MOH.READY_FOR_INVOICE
FROM APPS.XXAKG_DEL_ORD_HDR DOH,
          APPS.XXAKG_DEL_ORD_DO_LINES DODL,
          APPS.XXAKG_MOV_ORD_DTL MODT,
          APPS.XXAKG_MOV_ORD_HDR MOH,
          APPS.OE_ORDER_LINES_ALL SOL,
          --WSH_DELIVERY_DETAILS WSHD
          APPS.WSH_DELIVERABLES_V WSHD,
          APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
          APPS.WSH_PICKING_BATCHES WPB,
APPS.ORG_ORGANIZATION_DEFINITIONS OOD
    WHERE     DOH.DO_HDR_ID = DODL.DO_HDR_ID
          AND DOH.ORG_ID = DODL.ORG_ID
          AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
          AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
          AND MOH.ORG_ID = DOH.ORG_ID
          AND DOH.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
          AND MOH.ORG_ID = SOL.ORG_ID
          AND DODL.ORDER_HEADER_ID = SOL.HEADER_ID
          AND DODL.ORDER_LINE_ID = SOL.LINE_ID
          AND SOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
          AND SOL.LINE_ID = WSHD.SOURCE_LINE_ID
          AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
          AND WSHD.BATCH_ID=WPB.BATCH_ID
          AND DODL.WAREHOUSE_ORG_ID=OOD.ORGANIZATION_ID
          AND DBM.REGION_NAME='Comilla'
          AND SOL.ORG_ID=85
          and to_char(Sol.actual_shipment_date,'MON-RR')='NOV-17' 
--          AND DOH.DO_NUMBER=:P_DO_NUMBER
--          AND DODL.WAREHOUSE_ORG_ID IN (1345,1346)
GROUP BY
  DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
SOL.SHIPMENT_PRIORITY_CODE,
--OOD.ORGANIZATION_NAME,
DODL.WAREHOUSE_ORG_CODE,
--MOH.MOV_ORDER_NO,
DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
--SUM(NVL (LINE_QUANTITY, 0)) DO_QUANTITY,
--WPB.NAME BATCH_NO,
SOL.ACTUAL_SHIPMENT_DATE
--DOH.MODE_OF_TRANSPORT,
--DOH.TRANSPORTER_NAME,
--WSHD.RELEASED_STATUS_NAME,
--MOH.READY_FOR_INVOICE
   UNION ALL
   SELECT 
   DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
SOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--OOD.ORGANIZATION_NAME,
DODL.WAREHOUSE_ORG_CODE,
--MOH.MOV_ORDER_NO,
DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
SUM(NVL (LINE_QUANTITY, 0)) DO_QUANTITY,
--WPB.NAME BATCH_NO,
TO_CHAR(SOL.ACTUAL_SHIPMENT_DATE) ACTUAL_SHIPMENT_DATE
--DOH.MODE_OF_TRANSPORT,
--DOH.TRANSPORTER_NAME,
--WSHD.RELEASED_STATUS_NAME,
--MOH.READY_FOR_INVOICE
     FROM APPS.XXAKG_DEL_ORD_HDR DOH,
          APPS.XXAKG_DEL_ORD_DO_LINES DODL,
          APPS.XXAKG_MOV_ORD_DTL MODT,
          APPS.XXAKG_MOV_ORD_HDR MOH,
          APPS.OE_ORDER_LINES_ALL SOL,
          --WSH_DELIVERY_DETAILS WSHD
          APPS.WSH_DELIVERABLES_V WSHD,
          APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
          APPS.WSH_PICKING_BATCHES WPB,
APPS.ORG_ORGANIZATION_DEFINITIONS OOD
    WHERE     DOH.DO_HDR_ID = DODL.DO_HDR_ID
          AND DOH.ORG_ID = DODL.ORG_ID
          AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
          AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
          AND MOH.ORG_ID = DOH.ORG_ID
          AND DOH.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
          AND MOH.ORG_ID = SOL.ORG_ID
          AND DODL.ORDER_HEADER_ID = SOL.HEADER_ID
          AND SOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
          AND SOL.LINE_ID = WSHD.SOURCE_LINE_ID
          AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
          AND WSHD.BATCH_ID=WPB.BATCH_ID
          AND DODL.WAREHOUSE_ORG_ID=OOD.ORGANIZATION_ID
          AND DBM.REGION_NAME='Comilla'
          AND SOL.ORG_ID=85
          and to_char(Sol.actual_shipment_date,'MON-RR')='NOV-17' 
--          AND DOH.DO_NUMBER=:P_DO_NUMBER
--          AND DODL.WAREHOUSE_ORG_ID IN (1345,1346)
          AND NOT EXISTS
                (SELECT 1
                   FROM XXAKG_DEL_ORD_DO_LINES DOL1
                  WHERE DOL1.ORDER_LINE_ID = SOL.LINE_ID
                        AND DOL1.ORG_ID = SOL.ORG_ID)
           GROUP BY
             DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER,
SOL.SHIPMENT_PRIORITY_CODE,
--OOD.ORGANIZATION_NAME,
DODL.WAREHOUSE_ORG_CODE,
--MOH.MOV_ORDER_NO,
DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
--SUM(NVL (LINE_QUANTITY, 0)) DO_QUANTITY,
--WPB.NAME BATCH_NO,
SOL.ACTUAL_SHIPMENT_DATE
--DOH.MODE_OF_TRANSPORT,
--DOH.TRANSPORTER_NAME,
--WSHD.RELEASED_STATUS_NAME,
--MOH.READY_FOR_INVOICE
