SELECT
--OOH.*
--OOL.*
DOH.CUSTOMER_NUMBER
,DOH.DO_NUMBER
,TO_CHAR(DOH.DO_DATE) DO_DATE
,SUM(OOL.ORDERED_QUANTITY) QUANTITY
--DODL.*
,MOH.GATE_PASS_NO CHALLAN_NO
--MODT.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND OOL.HEADER_ID=OOH.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=MODT.CUSTOMER_NUMBER
AND DOH.DO_DATE BETWEEN '01-JAN-2017' and '17-SEP-2018'
AND DOH.CUSTOMER_NUMBER='21309'
--AND MODT.VAT_CHALLAN_NO=:P_VAT_CHALLAN_NO
--AND OOH.ORDER_NUMBER='1609136'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND DOH.DO_NUMBER='DO/SCOU/1014258'
--AND DOH.DO_STATUS='GENERATED'
AND DOH.DO_STATUS='CONFIRMED'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.MOV_ORDER_NO='MO/SCOU/036734'
--AND MOV_ORDER_STATUS='GENERATED'
--AND MOV_ORDER_STATUS='CONFIRMED'
--AND DODL.ITEM_NUMBER LIKE '%SCRP.%'
--AND DODL.WAREHOUSE_ORG_ID=1346
--AND OOH.ORDER_TYPE_ID=1101
--AND OOH.SHIP_FROM_ORG_ID=805
GROUP BY
DOH.CUSTOMER_NUMBER
,DOH.DO_NUMBER
,MOH.GATE_PASS_NO
,DOH.DO_DATE
ORDER BY DOH.DO_DATE