SELECT
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER
DODL.DO_NUMBER,
MOH.MOV_ORDER_NO,
OOD.ORGANIZATION_NAME,
DODL.WAREHOUSE_ORG_CODE,
DODL.ITEM_DESCRIPTION,
SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
DOH.MODE_OF_TRANSPORT
FROM
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND DODL.ORDER_HEADER_ID=OOH.HEADER_ID
AND DODL.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND DODL.WAREHOUSE_ORG_ID=OOD.ORGANIZATION_ID
AND DOH.DO_NUMBER=:P_DO_NUMBER
GROUP BY
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--DODL.ORDER_NUMBER
DODL.DO_NUMBER,
MOH.MOV_ORDER_NO,
DODL.WAREHOUSE_ORG_CODE,
OOD.ORGANIZATION_NAME,
DODL.ITEM_DESCRIPTION,
--SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
DOH.MODE_OF_TRANSPORT