SELECT
--*
--MMT.*
MTT.*
--
,MTT.TRANSACTION_TYPE_NAME
FROM
APPS.MTL_MATERIAL_TRANSACTIONS MMT
,INV.MTL_TRANSACTION_TYPES MTT
,APPS.MTL_SYSTEM_ITEMS_B MSI
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 1=1
AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
AND MMT.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
AND MSI.ORGANIZATION_ID=MMT.ORGANIZATION_ID
AND MTT.TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID
AND MTT.TRANSACTION_SOURCE_TYPE_ID = MMT.TRANSACTION_SOURCE_TYPE_ID
AND MTT.TRANSACTION_TYPE_ID=3
--AND MMT.TRANSACTION_ID = '5497'
--AND INVENTORY_ITEM_ID = '511077'
--AND MMT.TRANSACTION_SOURCE_ID='9484741'--- INV_MOVE_ORDER
AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.OBAG.0001','CMNT.SBAG.0001')
AND OOD.ORGANIZATION_CODE='G10'
--AND MMT.ORGANIZATION_ID = '112'
--AND MMT.SUBINVENTORY_CODE = 'AKC-GEN ST'
--AND TO_CHAR (MMT.TRANSACTION_DATE, 'MON-RR') = 'APR-18'
--AND TO_CHAR (MMT.TRANSACTION_DATE, 'RRRR') = '2018'
AND TO_CHAR (MMT.TRANSACTION_DATE, 'DD-MON-RR') = '31-JUL-18'
ORDER BY MMT.TRANSACTION_DATE DESC
