SELECT
*
FROM
APPS.RCV_SHIPMENT_HEADERS
--JOINED BY SHIPMENT_HEADER_ID, VENDOR_ID, VENDOR_SITE_ID, ORGANIZATION_ID, SHIPMENT_NUMBER,
--



SELECT
*
FROM
APPS.RCV_SHIPMENT_LINES      
--JOINED BY  SHIPMENT_LINE_ID, SHIPMENT_HEADER_ID, LINE_NUM, CATAGORY_ID, 
--FIND OUT QUANTITY_SHIPPED, QUANTITY_RECEIVED, UNIT_OF_MEASURE, ITEM_DESCRIPTION, ITEM_ID, 
--CONDITIONED BY PO_HEADER_ID, PO_LINE_ID
            

SELECT
*
FROM
APPS.RCV_TRANSACTIONS
WHERE 1=1
--AND TRANSACTION_TYPE NOT IN ('TRANSFER','ACCEPT','DELIVER','RECEIVE','REJECT','RETURN TO VENDOR','CORRECT','RETURN TO RECEIVING','UNORDERED','RETURN TO CUSTOMER')
--JOINED BY TRANSACTION_ID, QUANTITY, SHPMENT_HEADER_ID, SHIPMENT_LINE_ID, EMPLOYEE_ID, VENDOR_ID, VENDOR_SITE_ID,
--SEARCH BY TRANSACTION_TYPE, 
--FIND OUT UINIT_OF_MEASURE, SUBINVENTORY,