/* Formatted on 7/14/2019 12:28:33 PM (QP5 v5.287) */
SELECT *
  FROM INV.MTL_TRANSACTION_REASONS MTR,
       INV.MTL_MATERIAL_TRANSACTIONS MMT,
       INV.MTL_TRANSACTION_TYPES MTT
 WHERE     1 = 1
       AND MMT.TRANSACTION_TYPE_ID = MTT.TRANSACTION_TYPE_ID
       AND MMT.REASON_ID = MTR.REASON_ID
       AND MMT.TRANSACTION_ID = '237943'