SELECT 
    oap.ORGANIZATION_ID, 
    ood.OPERATING_UNIT, 
    oap.STATUS, 
    oap.PERIOD_NAME, 
    oap.PERIOD_NUMBER, 
    ood.ORGANIZATION_CODE, 
    ood.ORGANIZATION_NAME
FROM 
    APPS.ORG_ACCT_PERIODS_V oap, 
    APPS.ORG_ORGANIZATION_DEFINITIONS ood
WHERE 
    oap.organization_id=ood.organization_id
AND PERIOD_YEAR = 2016
ORDER BY 1,4

SELECT *
FROM APPS.ORG_ORGANIZATION_DEFINITIONS

