SELECT 
MOH.MOV_ORDER_NO,
TRUNC(CONFIRMED_DATE-INITIAL_GATE_IN_DATE) ||'-'||MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 24 ), 24)||'-'||MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 1440 ), 60 )||'-'||MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 86400 ), 60 ) "Days-Hours-Min-Sec"
--TRUNC(CONFIRMED_DATE-INITIAL_GATE_IN_DATE) DAYS,
--MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 24 ), 24) HOURS,
--MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 1440 ), 60 ) MINUTES,
--MOD( TRUNC( ( CONFIRMED_DATE-INITIAL_GATE_IN_DATE ) * 86400 ), 60 ) SECONDS
--(CONFIRMED_DATE - INITIAL_GATE_IN_DATE) * 1440
--,MOH.*
FROM XXAKG.XXAKG_MOV_ORD_HDR MOH
WHERE 1=1
AND MOH.ORG_ID=83
--AND MOH.MOV_ORDER_NO IN ('MO/COU/036400')
AND MOH.INITIAL_GATE_IN='Y'
AND TO_CHAR(MOH.GATE_OUT_DATE,'YYYY/MON/DD HH24:MI:SS') BETWEEN '2019/FEB/26 00:00:00' AND '2019/FEB/26 23:59:59'--HH:MI:SS--12:00:00
ORDER BY MOH.MOV_ORDER_DATE DESC