SELECT 
OOL.ORG_ID,
DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
OOH.ORDER_NUMBER,
WDD.SHIPMENT_PRIORITY_CODE DO_NUMBER,
WDD.ITEM_DESCRIPTION,
CAT.CATEGORY_CODE ITEM_CATEGORY,
ORG.ORGANIZATION_NAME,
ORG.ORGANIZATION_CODE,
OOL.ORDERED_QUANTITY QUANTITY,
OOL.ORDER_QUANTITY_UOM UNIT_OF_MEASURE,
TO_CHAR(DOH.DO_DATE) DO_DATE
FROM 
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
WSH.WSH_DELIVERY_DETAILS WDD,
APPS.ORG_ORGANIZATION_DEFINITIONS ORG,
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
,APPS.XXAKG_BIEE_ORGITEMMASTER CAT
WHERE 1=1
AND OOH.ORG_ID=OOL.ORG_ID
AND DBM.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND OOH.HEADER_ID=WDD.SOURCE_HEADER_ID
AND OOL.LINE_ID=WDD.SOURCE_LINE_ID
AND ORG.ORGANIZATION_ID= OOL.SHIP_FROM_ORG_ID
AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
AND ORG.ORGANIZATION_ID=CAT.ORGANIZATION_ID
AND OOL.ORDERED_ITEM=CAT.ITEM_CODE
AND WDD.RELEASED_STATUS='B'
AND OOL.ORG_ID=83
AND ORG.ORGANIZATION_CODE='CER'
AND OOL.ORDER_QUANTITY_UOM IN ('PCS')
--AND DOH.DO_DATE BETWEEN '01-JAN-2011' and '31-OCT-2017'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'OCT-17'
ORDER BY DOH.DO_DATE DESC

