SELECT
MC.SEGMENT4 "Product/Item Type",
MC.SEGMENT6 "Item Name/Product Brand",
MC.SEGMENT14 "Grade",
MC.SEGMENT15 "Color Type/Shade",
MC.SEGMENT11 "Color",
MSI.DESCRIPTION "Item_Description",
QLL.OPERAND "Unit Price",
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 "Item_Code",
CAT.CATEGORY_CODE "Item Category",
MSI.PRIMARY_UOM_CODE "Unit of Measure"
--,MC.*
--MSI.*
--MIC.*
FROM
INV.MTL_SYSTEM_ITEMS_B MSI
,INV.MTL_ITEM_CATEGORIES MIC
,INV.MTL_CATEGORIES_B MC
,APPS.MTL_CATEGORY_SETS MCS
,APPS.XXAKG_BIEE_ORGITEMMASTER CAT
,APPS.QP_LIST_HEADERS_V QLH
,APPS.QP_LIST_LINES_V QLL
WHERE 1=1
AND QLL.PRODUCT_ATTR_VAL_DISP=CAT.CATEGORY_CODE
AND QLH.LIST_HEADER_ID=QLL.LIST_HEADER_ID
AND MSI.ORGANIZATION_ID=CAT.ORGANIZATION_ID
AND MSI.INVENTORY_ITEM_ID=CAT.INVENTORY_ITEM_ID
AND MIC.CATEGORY_SET_ID=MCS.CATEGORY_SET_ID
AND MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MSI.INVENTORY_ITEM_ID=MIC.INVENTORY_ITEM_ID
AND MSI.ORGANIZATION_ID=MIC.ORGANIZATION_ID
AND MSI.ORGANIZATION_ID=99
AND MCS.CATEGORY_SET_NAME='Product Categories'
AND MC.SEGMENT1='CERAMIC'
--AND MC.SEGMENT4='WASH BASIN'
--AND MC.SEGMENT6='SOFIA'
--AND MC.SEGMENT15='NORMAL'
AND QLL.PRODUCT_ATTR_VAL_DISP='FINISH GOODS|WASH BASIN SOFIA-A'
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('BSNA.SFII.0001')
AND QLH.NAME='AKG Ceramic Price List'
AND QLL.END_DATE_ACTIVE IS NULL
AND QLH.ORIG_ORG_ID=83