/* Formatted on 10/19/2019 11:21:16 AM (QP5 v5.287) */
SELECT QLL.PRODUCT_ATTR_VAL_DISP ITEM_CATEGORY,
       --MC.SEGMENT2 PRODUCT_DESCRIPTION,
       --    MC.SEGMENT1||'|'||MC.SEGMENT2 CATEGORY_CODE,
       MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 ITEM_CODE,
       MSI.DESCRIPTION,
       --    MSI.INVENTORY_ITEM_ID,
       QLL.OPERAND PRICE,
       QLL.PRODUCT_UOM_CODE UOM,
       QLL.START_DATE_ACTIVE START_DATE,
       QLL.END_DATE_ACTIVE END_DATE,
       QLL.ARITHMETIC_OPERATOR APPLICATION_METHOD
  --    ,MC.*
  FROM APPS.QP_LIST_HEADERS_V QLH,
       APPS.QP_LIST_LINES_V QLL,
       APPS.MTL_CATEGORIES MC,
       APPS.MTL_ITEM_CATEGORIES MIC,
       APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE     1 = 1
       AND QLH.NAME = 'AKG Ceramic Price List'
       AND QLH.LIST_HEADER_ID = QLL.LIST_HEADER_ID
       AND QLL.PRODUCT_ATTR_VALUE = MC.CATEGORY_ID
       AND MIC.CATEGORY_ID = MC.CATEGORY_ID
       AND MIC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
       AND QLL.END_DATE_ACTIVE IS NULL
       AND QLH.ORIG_ORG_ID = 83
       AND MIC.ORGANIZATION_ID = 99
       AND MC.SEGMENT1 IN ('INGREDIENT', 'FINISH GOODS', 'INDIRECT MATERIAL') --'FINISH GOODS'--'INDIRECT MATERIAL'--'INGREDIENT'
       AND (   :ITEM_CODE IS NULL
            OR (MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 =
                   :ITEM_CODE))
--    AND QLL.ARITHMETIC_OPERATOR='UNIT_PRICE'
--    AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('BSNA.ELAB.0020')
--    AND MSI.DESCRIPTION LIKE ('Water Closet Marcella-P Trap-Rose Pink-B')
--    AND MC.SEGMENT2 in ('COMODE(WC)-IMOLA P-B(WOP)')
UNION ALL
SELECT ' ' ITEM_CATEGORY,
       OPLL.CONCATENATED_SEGMENTS ITEM_CODE,
       OPLL.ITEM_DESCRIPTION,
       OPLL.LIST_PRICE PRICE,
       OPLL.UNIT_CODE "UOM",
       OPLL.START_DATE_ACTIVE START_DATE,
       OPLL.END_DATE_ACTIVE END_DATE,
       OPLL.METHOD_CODE APPLICATION_METHOD
  --,OPLL.*
  FROM APPS.OE_PRICE_LISTS OPL,
       APPS.OE_PRICE_LIST_LINES OPLL,
       APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE     1 = 1
       AND OPL.PRICE_LIST_ID = OPLL.PRICE_LIST_ID
       AND OPLL.END_DATE_ACTIVE IS NULL
       AND OPL.ATTRIBUTE1 IS NULL
       AND OPLL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND ( :ITEM_CODE IS NULL OR (OPLL.CONCATENATED_SEGMENTS = :ITEM_CODE))
       --AND OPLL.CONCATENATED_SEGMENTS=:P_CONCATENATED_SEGMENTS
       --AND OPLL.CONCATENATED_SEGMENTS IN ('INJT.TUBE.0001')
       AND OPL.NAME = 'AKG Ceramic Price List'
       AND MSI.ORGANIZATION_ID = 99
--AND OPLL.METHOD_CODE='UNIT_PRICE'
;
---------------------------------------**************--------------------------------------------------------

SELECT QLL.PRODUCT_ATTR_VAL_DISP PRODUCT_VALUE,
       MC.SEGMENT2 PRODUCT_DESCRIPTION,
       --    MC.SEGMENT1||'|'||MC.SEGMENT2 CATEGORY_CODE,
       --    MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
       --    MSI.DESCRIPTION,
       --    MSI.INVENTORY_ITEM_ID,
       QLL.OPERAND PRICE,
       QLL.PRODUCT_UOM_CODE UOM,
       QLL.START_DATE_ACTIVE START_DATE,
       QLL.END_DATE_ACTIVE END_DATE,
       QLL.ARITHMETIC_OPERATOR APPLICATION_METHOD
  --    ,MC.*
  FROM APPS.QP_LIST_HEADERS_V QLH,
       APPS.QP_LIST_LINES_V QLL,
       APPS.MTL_CATEGORIES MC
 --    ,APPS.MTL_ITEM_CATEGORIES MIC
 --    ,APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE     1 = 1
       AND QLH.NAME = 'AKG Ceramic Price List'
       AND QLH.LIST_HEADER_ID = QLL.LIST_HEADER_ID
       AND QLL.PRODUCT_ATTR_VALUE = MC.CATEGORY_ID
       --    AND MIC.CATEGORY_ID=MC.CATEGORY_ID
       --    AND MIC.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
       --    AND MSI.ORGANIZATION_ID=MIC.ORGANIZATION_ID
       AND QLL.END_DATE_ACTIVE IS NULL
       AND QLH.ORIG_ORG_ID = 83
       --    AND MIC.ORGANIZATION_ID=99
       AND MC.SEGMENT1 IN ('INGREDIENT', 'FINISH GOODS', 'INDIRECT MATERIAL') --='FINISH GOODS'--'INGREDIENT'--'FINISH GOODS'--'INDIRECT MATERIAL'
       --    AND QLL.ARITHMETIC_OPERATOR='UNIT_PRICE'
       --    AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('BSNA.ELAB.0020')
       --    AND MSI.DESCRIPTION IN ('Water Closet Marcella-P Trap-Rose Pink-B')
       --    AND MC.SEGMENT2 in ('COMODE(WC)-IMOLA P-B(WOP)')
       --AND QLL.PRODUCT_ATTR_VAL_DISP IN ('FINISH GOODS|SEAT COVER- VERSO SOFT')
       AND (   :ITEM_CATEGORY IS NULL
            OR (QLL.PRODUCT_ATTR_VAL_DISP = :ITEM_CATEGORY));

-----------------------------------*********************-------------------------

SELECT OPLL.CONCATENATED_SEGMENTS ITEM_CODE,
       OPLL.ITEM_DESCRIPTION,
       OPLL.LIST_PRICE PRICE,
       OPLL.UNIT_CODE "UOM",
       OPLL.START_DATE_ACTIVE START_DATE,
       OPLL.END_DATE_ACTIVE END_DATE,
       OPLL.METHOD_CODE APPLICATION_METHOD
  --,OPLL.*
  FROM APPS.OE_PRICE_LISTS OPL,
       APPS.OE_PRICE_LIST_LINES OPLL,
       APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE     1 = 1
       AND OPL.PRICE_LIST_ID = OPLL.PRICE_LIST_ID
       AND OPLL.END_DATE_ACTIVE IS NULL
       AND OPL.ATTRIBUTE1 IS NULL
       AND OPLL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       --AND OPLL.CONCATENATED_SEGMENTS=:P_CONCATENATED_SEGMENTS
       --AND OPLL.CONCATENATED_SEGMENTS IN ('INJT.TUBE.0001')
       --AND MSI.SEGMENT1='COVR'
       AND OPL.NAME = 'AKG Ceramic Price List'
       AND MSI.ORGANIZATION_ID = 99
       AND ( :ITEM_CODE IS NULL OR (OPLL.CONCATENATED_SEGMENTS = :ITEM_CODE))
--AND OPLL.METHOD_CODE='UNIT_PRICE'
;

---------------------------------**************-----------------------

SELECT MSI.ORGANIZATION_ID,
       (SELECT ORGANIZATION_CODE
          FROM APPS.MTL_PARAMETERS
         WHERE ORGANIZATION_ID = MSI.ORGANIZATION_ID)
          ORG_CODE,
       MSI.INVENTORY_ITEM_ID,
       MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 ITEM_CODE,
       MSI.DESCRIPTION,
       MSI.PRIMARY_UOM_CODE,
       MTC.SEGMENT1 || '|' || MTC.SEGMENT2 ITEM_CATEGORIES
  FROM APPS.MTL_SYSTEM_ITEMS_B MSI,
       APPS.MTL_ITEM_CATEGORIES MTIC,
       APPS.MTL_CATEGORIES MTC
       ,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
 WHERE     1 = 1
       AND MTIC.CATEGORY_ID = MTC.CATEGORY_ID
       AND MTIC.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTIC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTC.STRUCTURE_ID = 101
       AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       --AND MSI.ORGANIZATION_ID=99
       --AND MSI.PRIMARY_UOM_CODE='PCS'
       --AND MTC.SEGMENT1 IN  ('INGREDIENT','FINISH GOODS','INDIRECT MATERIAL')
       AND (   :P_ORGANIZATION_CODE IS NULL
              OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
       AND (   :ITEM_CODE IS NULL
            OR (MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 =
                   :ITEM_CODE))
       AND (   :ITEM_CATEGORY IS NULL
            OR (MTC.SEGMENT1 || '|' || MTC.SEGMENT2 = :ITEM_CATEGORY))
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('BSNA.ELAB.0020')
--AND MTC.SEGMENT1||'|'||MTC.SEGMENT2 IN ('FINISH GOODS|SEAT COVER- VERSO SOFT')