SELECT
    DBM.REGION_NAME,
    MODT.CUSTOMER_NUMBER,
    DBM.CUSTOMER_NAME,
--    ORD.DO_NUMBER,
    MOH.MOV_ORDER_NO,
    SUM(ORD.ORDERED_QUANTITY) QUANTITY
,SUM(ORD.ORDERED_AMT) AMOUNT
--,MOH.TRANSPORTER_NAME
,APS.SEGMENT1 TRANSPORTER_NO
,APS.VENDOR_NAME TRANSPORTER
--,MOH.TRANSPORTER_VENDOR_SITE_ID
,APSA.VENDOR_SITE_CODE TRANSPORTER_SITE
,MOH.VEHICLE_NO
,MOH.VEHICLE_TYPE
,MOH.TRANSPORT_MODE
,MOH.HIRE_RATE_AP PAYMENT
,MOH.DEMURRAGE
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
APPS.XXAKG_MOV_ORD_DTL MODT,
      APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.XXAKG_HEADER_DETAIL_V ORD
,APPS.AP_SUPPLIERS APS
,APPS.AP_SUPPLIER_SITES_ALL APSA
WHERE 1=1
AND APS.VENDOR_ID=APSA.VENDOR_ID
AND MOH.TRANSPORTER_VENDOR_ID=APS.VENDOR_ID
AND MOH.TRANSPORTER_VENDOR_SITE_ID=APSA.VENDOR_SITE_ID
      AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
      AND MODT.DO_NUMBER = ORD.DO_NUMBER
      AND MOH.ORG_ID = ORD.ORG_ID
      AND DBM.ORG_ID = ORD.ORG_ID
      AND APSA.ORG_ID = ORD.ORG_ID
      AND MODT.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
--      AND MOH.TRANSPORT_MODE='Rental Truck'
      AND MOH.MOV_ORDER_STATUS='CONFIRMED'
--      AND MOH.TRANSPORTER_VENDOR_ID='137429'
--      AND MOH.TRANSPORTER_NAME='M/S Borsha Paribahan Songstha ~ GAZIPUR-CER'
--      AND APS.VENDOR_NAME='M/S Borsha Paribahan Songstha'
--      AND APS.SEGMENT1='13966'
--      AND TO_CHAR(APS.SEGMENT1)=TO_CHAR(:P_TRANSPORTER_NUMBER)
--      AND DBM.CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
--      AND ORD.DO_NUMBER=:P_DO_NUMBER
      AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
AND ORD.ORG_ID=83
AND APS.VENDOR_TYPE_LOOKUP_CODE='TRANSPORTER'
--AND ORD.PERIOD='JAN-18'
AND TO_CHAR (MOH.CONFIRMED_DATE, 'MON-RR') = 'JAN-18'
AND ORD.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND ROWNUM<=2
GROUP BY
DBM.REGION_NAME,
    MODT.CUSTOMER_NUMBER,
    DBM.CUSTOMER_NAME,
--    ORD.DO_NUMBER,
    MOH.MOV_ORDER_NO
--    ,MOH.TRANSPORTER_NAME
,MOH.VEHICLE_TYPE
,MOH.TRANSPORT_MODE
,MOH.HIRE_RATE_AP
,MOH.DEMURRAGE
,APS.SEGMENT1
,APS.VENDOR_NAME
--,MOH.TRANSPORTER_VENDOR_SITE_ID
,APSA.VENDOR_SITE_CODE
,MOH.VEHICLE_NO


SELECT DISTINCT
MOH.TRANSPORTER_VENDOR_ID
--,MOH.TRANSPORTER_VENDOR_SITE_ID
,APS.SEGMENT1 TRANSPORTER_NO
,APS.VENDOR_NAME TRANSPORTER
,APSA.VENDOR_SITE_CODE TRANSPORTER_SITE
FROM
APPS.AP_SUPPLIERS APS,
APPS.AP_SUPPLIER_SITES_ALL APSA
,APPS.XXAKG_MOV_ORD_HDR MOH
WHERE 1=1
AND APS.VENDOR_ID=APSA.VENDOR_ID
AND MOH.TRANSPORTER_VENDOR_ID=APS.VENDOR_ID
AND MOH.TRANSPORTER_VENDOR_SITE_ID=APSA.VENDOR_SITE_ID
AND TO_CHAR(APS.SEGMENT1)=TO_CHAR(:P_TRANSPORTER_NUMBER)
