SELECT
--ORGANIZATION_NAME,
--ORGANIZATION_CODE,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
--DO_NUMBER,
--(SELECT MSI.DESCRIPTION FROM APPS.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=ORD.ORDERED_ITEM_ID AND MSI.ORGANIZATION_ID=ORD.SHIP_FROM_ORG_ID) ITEM_NAME,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
SUM(SHIPPING_QUANTITY) SHIPPING_QUANTITY,
SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
--SUM(DECODE (ORDER_QUANTITY_UOM, 'MTN', SHIPPING_QUANTITY*20,
--                                        'BAG', SHIPPING_QUANTITY)) SHIPPING_QUANTITY,
--SUM(DECODE (ORDER_QUANTITY_UOM, 'MTN', INVOICED_QUANTITY*20,
--                                        'BAG', INVOICED_QUANTITY)) INVOICED_QUANTITY
--SUM(SHIPPING_QUANTITY) SHIPPING_QUANTITY,
--SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
--SUM(ORDERED_AMT) AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--PERIOD
--ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
WHERE 1=1
AND ORG_ID=83
--AND ORGANIZATION_CODE='G10'
--AND PERIOD='DEC-18'
AND TO_CHAR (DELIVERY_DATE, 'RRRR') = '2018'
--AND ORDER_QUANTITY_UOM='MTN'
--AND DELIVERY_DATE BETWEEN '01-SEP-18' AND '30-SEP-18'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_HDR DOH WHERE DOH.DO_NUMBER=ORD.DO_NUMBER AND DOH.MODE_OF_TRANSPORT='Company Truck')
--GROUP BY
--ORGANIZATION_NAME
--,ORGANIZATION_CODE
--,DO_NUMBER
--,ORD.ORDERED_ITEM_ID
--,ORD.SHIP_FROM_ORG_ID


------------------------------------------------------------------------------------------------

SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOH.ORDERED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOH.ORDER_TYPE_ID=1173--1099
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JAN-18'
--AND TO_CHAR (DOH.OR, 'RRRR') = '2017'
AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
AND OOH.ORG_ID=83
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER


SELECT 
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOH.ORDERED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
OOL.FLOW_STATUS_CODE,
OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
--,OOL.*
--,OOH.*
--,OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
WHERE 1=1 
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.ORDER_QUANTITY_UOM='PCS'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_SHIPMENT_PRIORITY_CODE
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'DEC-17'
AND ORDER_TYPE_ID=1173
--AND OOH.SHIP_FROM_ORG_ID=1346
ORDER BY OOH.ORDERED_DATE DESC

------------------------------------------------------------------------------------------------


SELECT
--ORGANIZATION_NAME,
--ORGANIZATION_CODE,
--ACSV.CUSTOMER_NUMBER,
--ACSV.CUSTOMER_NAME,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
--ORDERED_QUANTITY,
SUM(ORDERED_QUANTITY) ORD_QUANTITY
--SUM(INVOICED_QUANTITY) QUANTITY,
--SUM(ORDERED_AMT) AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--DO_NUMBER,
--PERIOD
--,ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND ORD.ORG_ID=85
AND ACSV.CUSTOMER_ID=ORD.SOLD_TO_ORG_ID
AND ACSV.SHIP_TO_ORG_ID=ORD.SHIP_TO_ORG_ID
AND PERIOD='FEB-18'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
AND ORGANIZATION_CODE='G32'
AND ACSV.STATUS='A'
--AND ACSV.SITE_USE_CODE='BILL_TO'
--AND ACSV.SITE_USE_CODE='SHIP_TO'
--AND ACSV.PRIMARY_FLAG='Y'
AND ACSV.SITE_USE_STATUS='A'
AND ACSV.ACCT_USE_STATUS='A'
--AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE 1=1 AND  ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER )
--AND CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
--AND ORD.ORDER_NUMBER IN ('1659352')
--AND ORD.DO_NUMBER=:P_DO_NUMBER