SELECT
HCA.ACCOUNT_NUMBER CUTOMER_NUMBER,
HP.PARTY_NAME CUSTOMER_NAME,
TO_CHAR(MAX(OOH.ORDERED_DATE)) LAST_ORDERED_DATE,
TO_CHAR(MAX(OOL.ACTUAL_SHIPMENT_DATE)) LAST_SHIPMENT_DATE,
TO_CHAR(MAX(ACR.RECEIPT_DATE)) LAST_RECEIPT_DATE
FROM
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.HZ_CUST_ACCOUNTS_ALL HCA,
APPS.HZ_PARTIES HP,
APPS.AR_CASH_RECEIPTS_ALL ACR
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SOLD_TO_ORG_ID=HCA.CUST_ACCOUNT_ID
AND HCA.PARTY_ID=HP.PARTY_ID
 AND ACR.PAY_FROM_CUSTOMER=HCA.CUST_ACCOUNT_ID
 -- AND NVL(HCA.STATUS, 'A') = 'A'
 --AND HCA.ACCOUNT_NUMBER=:P_CUSTOMER_NUMBER
AND OOH.ORG_ID=83
GROUP BY
 HCA.ACCOUNT_NUMBER
 ,HP.PARTY_NAME
 

-------------------------------------********************----------------------------------
SELECT
DOH.CUSTOMER_NUMBER "Customer ID",
DOH.CUSTOMER_NAME,
TO_CHAR(MAX(OOH.ORDERED_DATE)) LAST_ORDERED_DATE,
TO_CHAR(MAX(OOL.ACTUAL_SHIPMENT_DATE)) LAST_SHIPMENT_DATE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND OOL.LINE_ID=DODL.ORDER_LINE_ID
AND DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE
AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND OOL.SOLD_TO_ORG_ID=ACSV.CUSTOMER_ID
AND OOL.SHIP_TO_ORG_ID=ACSV.SHIP_TO_ORG_ID
--AND OOL.ACTUAL_SHIPMENT_DATE>='01-NOV-2017'
--and TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE,'MON-RR')='NOV-17' 
--AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND DOH.CUSTOMER_NUMBER IN ('186111','186865','187387','187661','187591','187532','186699','186216','185815')
--AND DOH.CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
AND DOH.ORG_ID=83
GROUP BY
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME



--------------------------------********************-------------------------------------------------

SELECT
HCA.ACCOUNT_NUMBER CUTOMER_NUMBER,
HP.PARTY_NAME CUSTOMER_NAME,
TO_CHAR(MAX(OOH.ORDERED_DATE)) LAST_ORDERED_DATE,
TO_CHAR(MAX(OOL.ACTUAL_SHIPMENT_DATE)) LAST_SHIPMENT_DATE
FROM
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.HZ_CUST_ACCOUNTS_ALL HCA,
APPS.HZ_PARTIES HP
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SOLD_TO_ORG_ID=HCA.CUST_ACCOUNT_ID
AND HCA.PARTY_ID=HP.PARTY_ID
--AND OOL.ACTUAL_SHIPMENT_DATE>='01-NOV-2017'
--and TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE,'MON-RR')='NOV-17' 
--AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND HCA.ACCOUNT_NUMBER IN ('186111','186865','187387','187661','187591','187532','186699','186216','185815')
--AND HCA.ACCOUNT_NUMBER=:P_CUSTOMER_NUMBER
AND OOH.ORG_ID=83
GROUP BY
 HCA.ACCOUNT_NUMBER
 ,HP.PARTY_NAME


--------------------------------********************-------------------------------------------------


 SELECT 
 HCA.ACCOUNT_NUMBER CUTOMER_NUMBER
 ,HP.PARTY_NAME CUSTOMER_NAME
,TO_CHAR(MAX(ACR.RECEIPT_DATE)) LAST_RECEIPT_DATE
 FROM
 APPS.AR_CASH_RECEIPTS_ALL ACR
 ,APPS.HZ_CUST_ACCOUNTS_ALL HCA
 ,APPS.HZ_PARTIES HP
-- ,APPS.HZ_PARTY_SITES HPS
 WHERE 1=1
 AND ACR.PAY_FROM_CUSTOMER=HCA.CUST_ACCOUNT_ID
 AND HCA.PARTY_ID=HP.PARTY_ID
 AND ACR.ORG_ID=83
-- AND NVL(HCA.STATUS, 'A') = 'A'
GROUP BY
HCA.ACCOUNT_NUMBER
,HP.PARTY_NAME 