SELECT
APSA.ORG_ID
,APS.SEGMENT1 SUPPLIER_NUMBER
,APS.VENDOR_NAME SUPPLIER_NAME
,TO_CHAR(APS.START_DATE_ACTIVE,'DD-MON-YYYY HH24:MI:SS') CREATION_DATE
,APS.ENABLED_FLAG
,APSA.VENDOR_SITE_CODE SUPPLIER_SITE
,TO_CHAR(APS.START_DATE_ACTIVE,'DD-MON-YYYY HH24:MI:SS') SITE_CREATION_DATE
,APSA.ADDRESS_LINE1||','||APSA.ADDRESS_LINE2||','||APSA.ADDRESS_LINE3 ADDRESS
--,APS.*
--,APSA.*
FROM
APPS.AP_SUPPLIERS APS,
APPS.AP_SUPPLIER_SITES_ALL APSA
WHERE 1=1
AND UPPER(APS.VENDOR_NAME) LIKE UPPER('%'||:P_SUPPLIER_NAME||'%')
AND APS.VENDOR_ID=APSA.VENDOR_ID
AND ((:SUPPLIER_ID IS NULL)  OR (APS.SEGMENT1=:SUPPLIER_ID))
AND ((:P_ORG_ID IS NULL AND APSA.ORG_ID IN (83,84,85,605))  OR (APSA.ORG_ID=:P_ORG_ID))