WITH XX_CUSTOMER_SUMMARY_TAB
     AS (  SELECT XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CB.CUSTOMER_ID) REGION,
                  CUSTOMER_ID,
                  XXAKG_AR_PKG.GET_CUSTOMER_NAME_WITH_NUMBER (CB.CUSTOMER_ID) CUSTOMER,
                  XXAKG_AR_PKG.GET_CUSTOMER_ADDRESS (CB.CUSTOMER_ID) ADDRESS,
                  NVL (SUM (NVL (DR_AMOUNT, 0) - NVL (CR_AMOUNT, 0)), 0) OPEN_BALANCE,
                  0 DR_AMOUNT,
                  0 CR_AMOUNT
             FROM XXAKG_AR_CUSTOMER_LEDGER_V CB
            WHERE     (:P_ORG_ID IS NULL OR ORG_ID = :P_ORG_ID)
                  AND (:P_CUSTOMER_ID_FROM IS NULL OR CUSTOMER_ID >= :P_CUSTOMER_ID_FROM)
                  AND (:P_CUSTOMER_ID_TO IS NULL OR CUSTOMER_ID <= :P_CUSTOMER_ID_TO)
                  AND GL_DATE < :P_DATE_FROM
                  AND (:P_REGION IS NULL OR XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CB.CUSTOMER_ID) = :P_REGION)
         GROUP BY CUSTOMER_ID
         UNION ALL
           SELECT XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (PS.CUSTOMER_ID) REGION,
                  CUSTOMER_ID,
                  XXAKG_AR_PKG.GET_CUSTOMER_NAME_WITH_NUMBER (PS.CUSTOMER_ID) CUSTOMER,
                  XXAKG_AR_PKG.GET_CUSTOMER_ADDRESS (PS.CUSTOMER_ID) ADDRESS,
                  0 OPEN_BALANCE,
                  SUM (GREATEST (PS.AMOUNT_DUE_ORIGINAL, 0)) DR_AMOUNT,
                  (0 - SUM (LEAST (PS.AMOUNT_DUE_ORIGINAL, 0))) CR_AMOUNT
             FROM XXAKG_AR_PAYMENT_SCHEDULES_V PS
            WHERE     NOT EXISTS
                             (SELECT 1
                                FROM AR_CASH_RECEIPTS_ALL CR
                               WHERE     PS.CASH_RECEIPT_ID = CR.CASH_RECEIPT_ID
                                     AND PS.ORG_ID = CR.ORG_ID
                                     AND NVL (CR.STATUS, 'AKG') IN ('CCRR', 'CC_CHARGEBACK_REV', 'NSF', 'REV', 'STOP'))
                  AND PS.ORG_ID = :P_ORG_ID
                  AND (:P_CUSTOMER_ID_FROM IS NULL OR PS.CUSTOMER_ID BETWEEN :P_CUSTOMER_ID_FROM AND :P_CUSTOMER_ID_TO)
                  AND PS.GL_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
                  AND (:P_REGION IS NULL OR XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (PS.CUSTOMER_ID) = :P_REGION)
         GROUP BY PS.ORG_ID, PS.CUSTOMER_ID)
  SELECT REGION,
         CUSTOMER_ID,
         CUSTOMER,
         ADDRESS,
         SUM (OPEN_BALANCE) OPEN_BALANCE,
         SUM (DR_AMOUNT) DR_AMOUNT,
         SUM (CR_AMOUNT) CR_AMOUNT
    FROM XX_CUSTOMER_SUMMARY_TAB
GROUP BY REGION,
         CUSTOMER_ID,
         CUSTOMER,
         ADDRESS
ORDER BY 1