SELECT REGION_NAME, DO_NUMBER, DO_DATE, MOV_ORDER_NO, MOV_ORDER_DATE, GROUP_PARTY_NUMBER, GROUP_PARTY_NAME, PARTY_NUMBER, PARTY_NAME,VEHICLE_NO,
MOV_ORDER_STATUS, WAREHOUSE, SUM(DO_QUANTITY) DO_QUANTITY, SUM(ORIGINAL_QUANTITY) ORIGINAL_QUANTITY, BILL_STATUS, PAY_DATE, TRANSPORT_MODE,  
FINAL_DESTINATION, NULL DELIVERY_LOCATION, HIRE_RATE
FROM 
(
SELECT R.REGION_NAME, DOH.DO_NUMBER, TRUNC(DOH.DO_DATE) DO_DATE, MVH.MOV_ORDER_NO, TRUNC(MVH.MOV_ORDER_DATE) MOV_ORDER_DATE,MVH.VEHICLE_NO,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NUMBER,  APS.SEGMENT1) GROUP_PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NAME,  APS.VENDOR_NAME) GROUP_PARTY_NAME,  
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.SEGMENT1, CUST.CUSTOMER_NUMBER) PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.VENDOR_NAME, CUST.CUSTOMER_NAME) PARTY_NAME,  
DECODE(APPS.XXAKG_AP_PKG.get_invoice_status(API.INVOICE_ID), 'Never Validated', 'Invoiced', APPS.XXAKG_AP_PKG.get_invoice_status(API.INVOICE_ID))  MOV_ORDER_STATUS,  
DECODE (MVH.WAREHOUSE_ORG_ID, 101, MVH.WAREHOUSE_ORG_CODE, APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (MVH.WAREHOUSE_ORG_ID)) WAREHOUSE,  
DECODE(DOL.ORDERED_ITEM_ID, 24408, (DOL.LINE_QUANTITY*APPS.XXAKG_ONT_PKG.GET_BULK_CONVERSION), DOL.LINE_QUANTITY) DO_QUANTITY, DOL.LINE_QUANTITY ORIGINAL_QUANTITY,
(CASE
 WHEN NVL(INVOICE_AMOUNT,0) = 0 THEN NULL
 WHEN (NVL(INVOICE_AMOUNT,0) - (NVL(AMOUNT_PAID,0)+NVL(DISCOUNT_AMOUNT_TAKEN,0))) = 0 THEN 'Fully Paid'
 WHEN NVL(AMOUNT_PAID,0) = 0 THEN 'Unpaid'
 WHEN (NVL(INVOICE_AMOUNT,0) - (NVL(AMOUNT_PAID,0)+NVL(DISCOUNT_AMOUNT_TAKEN,0))) > 0 THEN 'Partially Paid'                 
 ELSE NULL 
 END) BILL_STATUS, APPS.xxakg_ap_pkg.get_max_chk_date_from_invoice(API.INVOICE_ID) PAY_DATE, MVH.TRANSPORT_MODE,  MVH.FINAL_DESTINATION,
 NVL (DOL.ACTUAL_RETAILER_SHIP_TO, APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DOL.SHIP_TO_ORG_ID)) DELIVERY_LOCATION, 
 MVH.HIRE_RATE_AP HIRE_RATE
FROM APPS.XXAKG_DEL_ORD_HDR DOH,
         APPS.XXAKG_DEL_ORD_DO_LINES DOL,
         APPS.XXAKG_MOV_ORD_HDR MVH,
         APPS.XXAKG_MOV_ORD_DTL MVD,
         APPS.AP_INVOICES_ALL API,
         APPS.XXAKG_AR_CUSTOMER_SITE_V CUST,
         APPS.AP_SUPPLIERS APS,
         APPS.XXAKG_DISTRIBUTOR_BLOCK_M R                  
WHERE DOH.DO_HDR_ID = DOL.DO_HDR_ID 
AND      DOH.ORG_ID = DOL.ORG_ID
AND      DOL.ORDERED_ITEM_ID NOT IN (24397, 24398)   -->> EBAG.PBAG.0001 (24397), EBAG.SBAG.0001 (24398)
AND      DOH.DO_HDR_ID = MVD.DO_HDR_ID  
AND      MVH.MOV_ORD_HDR_ID = MVD.MOV_ORD_HDR_ID
AND      MVH.MOV_ORDER_NO = API.INVOICE_NUM
AND      MVH.ORG_ID = API.ORG_ID
--AND     MVH.TRANSPORT_MODE NOT IN ('Ex factory truck', 'Barge Ex factory')
AND     DOH.CUSTOMER_NUMBER = CUST.CUSTOMER_NUMBER
AND     CUST.SITE_USE_CODE = 'BILL_TO'
AND     CUST.PRIMARY_FLAG = 'Y'
AND     MVH.AP_FLAG = 'Y'
AND     API.VENDOR_ID = APS.VENDOR_ID (+)
AND     DOH.CUSTOMER_NUMBER = R.CUSTOMER_NUMBER(+)
AND     (:P_PARTY_ID IS NULL OR (DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_ID, APS.VENDOR_ID) = :P_PARTY_ID))
AND     TRUNC(API.GL_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO
AND     API.ORG_ID = :P_ORG_ID
AND     CUST.ORG_ID = :P_ORG_ID
AND     R.ORG_ID = :P_ORG_ID
AND     (:P_WAREHOUSE IS NULL OR (MVH.WAREHOUSE_ORG_ID = :P_WAREHOUSE))
AND     (:P_TRANSPORT_MODE IS NULL OR (MVH.TRANSPORT_MODE = :P_TRANSPORT_MODE)) 
AND     (:P_REGION_NAME IS NULL OR (R.REGION_NAME = :P_REGION_NAME))
AND     (:P_REGION_NAME_EXCLUDE IS NULL OR (R.REGION_NAME <> :P_REGION_NAME_EXCLUDE))
AND     (:P_BILL_STATUS IS NULL OR (DECODE(APPS.XXAKG_AP_PKG.get_invoice_status(API.INVOICE_ID), 'Never Validated', 'Invoiced', APPS.XXAKG_AP_PKG.get_invoice_status(API.INVOICE_ID)) = :P_BILL_STATUS))
AND     (:P_PAID_STATUS IS NULL OR APPS.XXAKG_AP_PKG.GET_INVOICE_PAID_STATUS(API.INVOICE_ID) = :P_PAID_STATUS)
UNION ALL  -- Below Union is used when AP and AR invoices are not created
SELECT R.REGION_NAME, DOH.DO_NUMBER, TRUNC(DOH.DO_DATE) DO_DATE, MVH.MOV_ORDER_NO, TRUNC(MVH.MOV_ORDER_DATE) MOV_ORDER_DATE, MVH.VEHICLE_NO,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NUMBER,  DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  '6431', 84, '4731', APS.SEGMENT1), APS.SEGMENT1)) GROUP_PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NAME,  DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  'Abul Khair Carrier Limited', 84, 'Shah Cement Industries Ltd.', APS.VENDOR_NAME), APS.VENDOR_NAME)) GROUP_PARTY_NAME,
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.SEGMENT1, CUST.CUSTOMER_NUMBER) PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.VENDOR_NAME, CUST.CUSTOMER_NAME) PARTY_NAME,  INITCAP(MVH.MOV_ORDER_STATUS) MOV_ORDER_STATUS,  
DECODE (MVH.WAREHOUSE_ORG_ID, 101, MVH.WAREHOUSE_ORG_CODE, APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (MVH.WAREHOUSE_ORG_ID)) WAREHOUSE,  
DECODE(SOL.INVENTORY_ITEM_ID, 24408, (SOL.SHIPPED_QUANTITY*APPS.XXAKG_ONT_PKG.GET_BULK_CONVERSION), SOL.SHIPPED_QUANTITY) DO_QUANTITY, SOL.SHIPPED_QUANTITY ORIGINAL_QUANTITY,
'Uninvoiced'  BILL_STATUS, NULL PAY_DATE, MVH.TRANSPORT_MODE, MVH.FINAL_DESTINATION,
NVL (DOL.ACTUAL_RETAILER_SHIP_TO, CUST.LOCATION||DECODE(CUST.LOCATION_ADDRESS, NULL, NULL,', '||CUST.LOCATION_ADDRESS)) DELIVERY_LOCATION,
MVH.HIRE_RATE_AP HIRE_RATE
FROM APPS.XXAKG_DEL_ORD_HDR DOH,
        APPS.XXAKG_DEL_ORD_DO_LINES DOL,
        APPS.XXAKG_MOV_ORD_DTL MVD,
        APPS.XXAKG_MOV_ORD_HDR MVH,
        APPS.OE_ORDER_LINES_ALL SOL,
        APPS.XXAKG_AR_CUSTOMER_SITE_V CUST, 
        APPS.AP_SUPPLIERS APS,
        APPS.XXAKG_DISTRIBUTOR_BLOCK_M R        
WHERE  DOH.DO_HDR_ID = DOL.DO_HDR_ID
AND      DOH.ORG_ID = DOL.ORG_ID
AND      DOH.DO_HDR_ID = MVD.DO_HDR_ID
AND      MVH.MOV_ORD_HDR_ID = MVD.MOV_ORD_HDR_ID
AND      MVH.ORG_ID = DOH.ORG_ID
AND      MVD.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
AND      MVH.ORG_ID = SOL.ORG_ID
AND      DOL.ORDER_HEADER_ID = SOL.HEADER_ID
AND     DOL.ORDER_LINE_ID = SOL.LINE_ID
AND     MVH.MOV_ORDER_STATUS = 'CONFIRMED'
AND     NVL(MVH.AP_FLAG, 'N') = 'N'
AND     MVH.ORG_ID = :P_ORG_ID
AND     MVH.MOV_ORDER_TYPE = 'RELATED'
--AND     MVH.TRANSPORT_MODE NOT IN ('Ex factory truck', 'Barge Ex factory')
AND     SOL.INVENTORY_ITEM_ID NOT IN (24397, 24398)   -->> EBAG.PBAG.0001 (24397), EBAG.SBAG.0001 (24398) 
AND     DOH.CUSTOMER_NUMBER = CUST.CUSTOMER_NUMBER
AND     CUST.SITE_USE_CODE = 'BILL_TO'
AND     CUST.PRIMARY_FLAG = 'Y'
AND     DOH.CUSTOMER_NUMBER = R.CUSTOMER_NUMBER(+)
AND     R.ORG_ID = CUST.ORG_ID
AND     DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  10008, 84, 5865, MVH.TRANSPORTER_VENDOR_ID), MVH.TRANSPORTER_VENDOR_ID) = APS.VENDOR_ID (+)
AND     (:P_PARTY_ID IS NULL OR (DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_ID, APS.VENDOR_ID) = :P_PARTY_ID))
AND     TRUNC (SOL.ACTUAL_SHIPMENT_DATE) IS NOT NULL
AND     TRUNC (SOL.ACTUAL_SHIPMENT_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO
AND     (:P_WAREHOUSE IS NULL OR (MVH.WAREHOUSE_ORG_ID = :P_WAREHOUSE))
AND     (:P_TRANSPORT_MODE IS NULL OR (MVH.TRANSPORT_MODE = :P_TRANSPORT_MODE))
AND     (:P_BILL_STATUS IS NULL OR (INITCAP(MVH.MOV_ORDER_STATUS) = :P_BILL_STATUS))
AND     (:P_REGION_NAME IS NULL OR (R.REGION_NAME = :P_REGION_NAME))
AND     (:P_REGION_NAME_EXCLUDE IS NULL OR (R.REGION_NAME <> :P_REGION_NAME_EXCLUDE))
AND      'Uninvoiced'=nvl(:P_PAID_STATUS,'Uninvoiced')
AND NOT EXISTS
         (SELECT 1
            FROM APPS.AP_INVOICES_ALL API
           WHERE MVH.MOV_ORDER_NO = API.INVOICE_NUM
                 AND MVH.ORG_ID = API.ORG_ID)                 
UNION ALL                                  
-- Those Line ID is available in Sales Order Line but not in DO line table
SELECT R.REGION_NAME, DOH.DO_NUMBER, TRUNC(DOH.DO_DATE) DO_DATE, MVH.MOV_ORDER_NO, TRUNC(MVH.MOV_ORDER_DATE) MOV_ORDER_DATE, MVH.VEHICLE_NO,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NUMBER,  DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  '6431', 84, '4731', APS.SEGMENT1), APS.SEGMENT1)) GROUP_PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_NAME,  DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  'Abul Khair Carrier Limited', 84, 'Shah Cement Industries Ltd.', APS.VENDOR_NAME), APS.VENDOR_NAME)) GROUP_PARTY_NAME,
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.SEGMENT1, CUST.CUSTOMER_NUMBER) PARTY_NUMBER,
DECODE(:P_GROUP_BY, 'CUSTOMER', APS.VENDOR_NAME, CUST.CUSTOMER_NAME) PARTY_NAME,  INITCAP(MVH.MOV_ORDER_STATUS) MOV_ORDER_STATUS,  
DECODE (MVH.WAREHOUSE_ORG_ID, 101, MVH.WAREHOUSE_ORG_CODE, APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (MVH.WAREHOUSE_ORG_ID)) WAREHOUSE,  
DECODE(SOL.INVENTORY_ITEM_ID, 24408, (SOL.SHIPPED_QUANTITY*APPS.XXAKG_ONT_PKG.GET_BULK_CONVERSION), SOL.SHIPPED_QUANTITY) DO_QUANTITY, SOL.SHIPPED_QUANTITY ORIGINAL_QUANTITY,
'Uninvoiced'  BILL_STATUS, NULL PAY_DATE, MVH.TRANSPORT_MODE, MVH.FINAL_DESTINATION,
NVL (DOL.ACTUAL_RETAILER_SHIP_TO, CUST.LOCATION||DECODE(CUST.LOCATION_ADDRESS, NULL, NULL,', '||CUST.LOCATION_ADDRESS)) DELIVERY_LOCATION,
MVH.HIRE_RATE_AP HIRE_RATE
 FROM APPS.XXAKG_DEL_ORD_HDR DOH,
      APPS.XXAKG_DEL_ORD_DO_LINES DOL,
      APPS.XXAKG_MOV_ORD_DTL MVD,
      APPS.XXAKG_MOV_ORD_HDR MVH,
      APPS.OE_ORDER_LINES_ALL SOL,
      APPS.XXAKG_AR_CUSTOMER_SITE_V CUST, 
      APPS.AP_SUPPLIERS APS,
      APPS.XXAKG_DISTRIBUTOR_BLOCK_M R              
WHERE     DOH.DO_HDR_ID = DOL.DO_HDR_ID
      AND DOH.ORG_ID = DOL.ORG_ID
      AND DOH.DO_HDR_ID = MVD.DO_HDR_ID
      AND MVH.MOV_ORD_HDR_ID = MVD.MOV_ORD_HDR_ID
      AND MVH.ORG_ID = DOH.ORG_ID
      AND MVD.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
      AND MVH.ORG_ID = SOL.ORG_ID
      AND DOL.ORDER_HEADER_ID = SOL.HEADER_ID
      --AND DOL.ORDER_LINE_ID = SOL.LINE_ID
      AND MVH.MOV_ORDER_STATUS = 'CONFIRMED'
      AND NVL(MVH.AP_FLAG, 'N') = 'N'
      AND MVH.ORG_ID = :P_ORG_ID
      AND MVH.MOV_ORDER_TYPE = 'RELATED'
--      AND MVH.TRANSPORT_MODE NOT IN ('Ex factory truck', 'Barge Ex factory')
      AND SOL.INVENTORY_ITEM_ID NOT IN (24397, 24398)   -->> EBAG.PBAG.0001 (24397), EBAG.SBAG.0001 (24398)
    AND     DOH.CUSTOMER_NUMBER = CUST.CUSTOMER_NUMBER
    AND     CUST.SITE_USE_CODE = 'BILL_TO'
    AND     CUST.PRIMARY_FLAG = 'Y'
    AND     DOH.CUSTOMER_NUMBER = R.CUSTOMER_NUMBER(+)
    AND     R.ORG_ID = CUST.ORG_ID
    AND     DECODE(UPPER(transport_mode), 'COMPANY TRUCK', DECODE(MVH.ORG_ID, 85,  10008, 84, 5865, MVH.TRANSPORTER_VENDOR_ID), MVH.TRANSPORTER_VENDOR_ID) = APS.VENDOR_ID (+)
    AND     (:P_PARTY_ID IS NULL OR (DECODE(:P_GROUP_BY, 'CUSTOMER', CUST.CUSTOMER_ID, APS.VENDOR_ID) = :P_PARTY_ID))
    AND     TRUNC (SOL.ACTUAL_SHIPMENT_DATE) IS NOT NULL
    AND     TRUNC (SOL.ACTUAL_SHIPMENT_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO
    AND     (:P_WAREHOUSE IS NULL OR (MVH.WAREHOUSE_ORG_ID = :P_WAREHOUSE))
    AND     (:P_TRANSPORT_MODE IS NULL OR (MVH.TRANSPORT_MODE = :P_TRANSPORT_MODE))
    AND     (:P_BILL_STATUS IS NULL OR (INITCAP(MVH.MOV_ORDER_STATUS) = :P_BILL_STATUS))
    AND     (:P_REGION_NAME IS NULL OR (R.REGION_NAME = :P_REGION_NAME))     
   AND     (:P_REGION_NAME_EXCLUDE IS NULL OR (R.REGION_NAME <> :P_REGION_NAME_EXCLUDE)) 
   AND      'Uninvoiced'=nvl(:P_PAID_STATUS,'Uninvoiced')
      AND NOT EXISTS
                 (SELECT 1
                    FROM APPS.AP_INVOICES_ALL API
                   WHERE MVH.MOV_ORDER_NO = API.INVOICE_NUM
                         AND MVH.ORG_ID = API.ORG_ID)
      AND NOT EXISTS
                 (SELECT 1
                    FROM APPS.XXAKG_DEL_ORD_DO_LINES DOL1
                   WHERE DOL1.ORDER_LINE_ID = SOL.LINE_ID
                         AND DOL1.ORG_ID = SOL.ORG_ID)     
)
GROUP BY REGION_NAME, DO_NUMBER, DO_DATE, MOV_ORDER_NO, MOV_ORDER_DATE, GROUP_PARTY_NUMBER, GROUP_PARTY_NAME, PARTY_NUMBER, PARTY_NAME,
MOV_ORDER_STATUS, WAREHOUSE, BILL_STATUS, PAY_DATE, TRANSPORT_MODE,  FINAL_DESTINATION, HIRE_RATE,VEHICLE_NO
ORDER BY REGION_NAME, MOV_ORDER_NO, DO_NUMBER
