----------------------------------CERAMIC RECEIPE DETAILS----------------------------------------------

SELECT GRB.RECIPE_NO,
       GRB.RECIPE_VERSION,
       GOR.RESOURCES,
       MP.ORGANIZATION_CODE,
       GRB.RECIPE_ID,
       GRB.ROUTING_ID,
       GRB.FORMULA_ID,
       GRVR.RECIPE_VALIDITY_RULE_ID
FROM APPS.GMD_OPERATION_RESOURCES GOR,
APPS.GMD_OPERATION_ACTIVITIES GOA,
APPS.GMD_OPERATIONS_B GOB,
APPS.GMD_RECIPES_B GRB,
APPS.FM_ROUT_DTL FRD,
APPS.GMD_RECIPE_VALIDITY_RULES GRVR,
APPS.MTL_PARAMETERS MP,
APPS.GMD_RECIPE_ORGN_RESOURCES GROR
WHERE GOR.OPRN_LINE_ID = GOA.OPRN_LINE_ID
AND GOA.OPRN_ID = GOB.OPRN_ID
AND GOB.OPRN_ID = FRD.OPRN_ID
AND FRD.ROUTING_ID = GRB.ROUTING_ID
AND GRB.RECIPE_ID = GRVR.RECIPE_ID
--AND GRB.DELETE_MARK = 0
--AND GRVR.DELETE_MARK = 0
--AND GRVR.RECIPE_USE IN('0', '1')
--AND GRVR.VALIDITY_RULE_STATUS IN('100','700', '900')
--AND NVL(GRVR.END_DATE, (SYSDATE + 1)) > SYSDATE
AND GRVR.ORGANIZATION_ID = MP.ORGANIZATION_ID (+)
AND GOR.RESOURCES = GROR.RESOURCES
--AND MP.ORGANIZATION_CODE='SCI'
AND GRB.RECIPE_NO='BSNA.OVCY.0001_PACK'
AND RESOURCES='PACK_PACKER'