/* Formatted on 7/18/2019 10:56:44 AM (QP5 v5.287) */
SELECT *
  FROM APPS.MRP_FORECAST_DATES MFD;


----------------------------FORECAST_DESIGNATORS--------------------------------

  SELECT FC.FORECAST_SET, FC.FORECAST_DESIGNATOR
    FROM MRP.MRP_FORECAST_DESIGNATORS FC
   WHERE     FC.FORECAST_SET IS NOT NULL
         AND (FC.DISABLE_DATE IS NULL OR FC.DISABLE_DATE > SYSDATE)
ORDER BY FC.FORECAST_SET, FC.FORECAST_DESIGNATOR;

-------------------------------VIEW---------------------------------------------

SELECT * FROM APPS.MTL_FORECAST_DATES_COST_V;

SELECT * FROM APPS.MRP_FORECAST_DESIGNATORS_V;

