/* Formatted on 9/16/2019 2:23:11 PM (QP5 v5.287) */
  SELECT GMD.RECIPE_NO RECEIPE_CODE,
         RECIPE_DESCRIPTION RECEIPE_NAME,
         GMD.RECIPE_VERSION,
         (SELECT DISTINCT DESCRIPTION
            FROM APPS.MTL_SYSTEM_ITEMS MTL1, APPS.FM_MATL_DTL FD1
           WHERE     FD1.LINE_TYPE = 1
                 AND FD1.FORMULA_ID = FD.FORMULA_ID
                 AND FD1.INVENTORY_ITEM_ID = MTL1.INVENTORY_ITEM_ID
                 AND FD1.ORGANIZATION_ID = MTL1.ORGANIZATION_ID)
            PRODUCT,
         FM.FORMULA_NO,
         FM.FORMULA_DESC1,
         FM.FORMULA_VERS,
         DECODE (GMD.RECIPE_STATUS,
                 '900', 'Frozen',
                 '700', 'Approved for General Use')
            REC_STATUS,
            B.SEGMENT1 || '.' || B.SEGMENT2 || '.' || B.SEGMENT3 INV_ITEM_CODE,
         B.SEGMENT1 || '-' || B.SEGMENT2 ITEM_CODE,
         B.DESCRIPTION ITEM_DESC,
         FD.LINE_NO,
         FD.QTY
         ,DECODE (FD.LINE_TYPE, -1, 'INGREDIENT', 'PRODUCT') PRODUCT_TYPE
         --,FM.*
         --,FD.*
    FROM APPS.FM_FORM_MST FM,
         APPS.FM_MATL_DTL FD,
         APPS.MTL_SYSTEM_ITEMS B,
         APPS.GMD_RECIPE_VALIDITY_RULES GV,
         APPS.GMD_RECIPES GMD
   WHERE     FD.FORMULA_ID = FM.FORMULA_ID
         AND FD.ORGANIZATION_ID = FM.OWNER_ORGANIZATION_ID
         AND FM.FORMULA_ID = GMD.FORMULA_ID
         AND FM.OWNER_ORGANIZATION_ID = GMD.OWNER_ORGANIZATION_ID
         AND GV.RECIPE_ID = GMD.RECIPE_ID
         AND B.INVENTORY_ITEM_ID = FD.INVENTORY_ITEM_ID
         AND B.ORGANIZATION_ID = FM.OWNER_ORGANIZATION_ID
         AND FM.OWNER_ORGANIZATION_ID IN ('101')
         AND FM.FORMULA_NO='CMNT.OBAG.0001'
         AND RECIPE_DESCRIPTION='Ordinary Portland Cement (Bag) - Packer 1'
         --AND fd.line_type IN (-1, 2)
         --and fm.FORMULA_STATUS=700
         --AND gmd.RECIPE_STATUS IN (700)
--and gmd.RECIPE_NO=''XXXX
ORDER BY 1;

