/* Formatted on 9/16/2019 3:15:26 PM (QP5 v5.287) */
  SELECT B.RECIPE_DESCRIPTION,
         A.RECIPE_VALIDITY_RULE_ID,
         C.INVENTORY_ITEM_ID,
         D.DESCRIPTION,
         DECODE (C.LINE_TYPE, -1, 'INGREDIENT', 'PRODUCT') TYPE,
         SUM (E.TRANSACTION_QUANTITY) QUANTITY
    FROM APPS.GME_BATCH_HEADER A,
         APPS.GMD_RECIPES B,
         APPS.GMD_RECIPE_VALIDITY_RULES GRR,
         APPS.GME_MATERIAL_DETAILS C,
         APPS.MTL_SYSTEM_ITEMS D,
         APPS.MTL_MATERIAL_TRANSACTIONS E
   WHERE     A.FORMULA_ID = B.FORMULA_ID
         AND A.ROUTING_ID = B.ROUTING_ID
         AND A.RECIPE_VALIDITY_RULE_ID = GRR.RECIPE_VALIDITY_RULE_ID
         AND GRR.RECIPE_ID = B.RECIPE_ID
         AND A.BATCH_ID = C.BATCH_ID
         AND A.ORGANIZATION_ID = C.ORGANIZATION_ID
         AND C.INVENTORY_ITEM_ID = D.INVENTORY_ITEM_ID
         AND C.ORGANIZATION_ID = D.ORGANIZATION_ID
         AND A.BATCH_ID = E.TRANSACTION_SOURCE_ID
         AND A.ORGANIZATION_ID = E.ORGANIZATION_ID
         AND C.INVENTORY_ITEM_ID = E.INVENTORY_ITEM_ID
         AND A.BATCH_NO IN
                (SELECT BATCH_NO
                   FROM APPS.GME_BATCH_HEADER
                  WHERE TRUNC (PLAN_START_DATE) BETWEEN :FROM_DATE AND :TO_DATE)
         AND A.ORGANIZATION_ID = :YOUR_ORG_ID
         AND TRUNC (E.TRANSACTION_DATE) BETWEEN :FROM_DATE AND :TO_DATE
GROUP BY B.RECIPE_DESCRIPTION,
         A.RECIPE_VALIDITY_RULE_ID,
         C.INVENTORY_ITEM_ID,
         D.DESCRIPTION,
         C.LINE_TYPE
ORDER BY RECIPE_DESCRIPTION