/* Formatted on 7/13/2019 6:33:24 PM (QP5 v5.287) */
SELECT MSI.SEGMENT1, MIT.TEMPLATE_NAME, MITA.ATTRIBUTE_NAME
  FROM APPS.MTL_ITEM_TEMPL_ATTRIBUTES MITA,
       APPS.MTL_SYSTEM_ITEMS_B MSI,
       APPS.MTL_ITEM_TEMPLATES MIT
 WHERE     MITA.ATTRIBUTE_VALUE IS NOT NULL
       --AND mita.attribute_name = 'MTL_SYSTEM_ITEMS.ITEM_TYPE'
       AND MIT.TEMPLATE_ID = MITA.TEMPLATE_ID
       AND MITA.ATTRIBUTE_VALUE = MSI.ITEM_TYPE
       AND MSI.ORGANIZATION_ID = 1265
       AND MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 IN
              ('DRCT.R340.0925')