select
*
from
apps.MTL_CATEGORIES
WHERE 1=1
--AND SEGMENT1='FINISH GOODS'
--AND SEGMENT2='PEDESTAL-SILVANA-A'
--JOINED BY CATEGORY_ID, STUCTURE_ID, 
--FIND OUT SEGMENT1 (ITEM_CATEGORY), SEGMENT2(ITEM_TYPE)



SELECT
MIC.CATEGORY_ID,
MIC.ORGANIZATION_ID,
MIC.INVENTORY_ITEM_ID,
MC.SEGMENT1,
MC.SEGMENT2
FROM
APPS.MTL_ITEM_CATEGORIES MIC,
APPS.MTL_CATEGORIES MC
WHERE 1=1
AND MIC.CATEGORY_ID=MC.CATEGORY_ID
--AND INVENTORY_ITEM_ID=INVENTORY_ITEM_ID
--AND MC.SEGMENT1='FINISH GOODS'
--AND MC.SEGMENT2='PEDESTAL-SILVANA-A'_ID
--AND MIC.INVENTORY_ITEM_ID=856986


SELECT
*
FROM
INV.MTL_CATEGORIES_B
WHERE 1=1
--AND CATEGORY_ID=8129
--UNIQUE COLUMN CATEGORY_ID, STRUCTURE_ID, 
--FIND OUT SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, SEGMENT6

SELECT
*
FROM
INV.MTL_ITEM_CATEGORIES MIC
WHERE 1=1 
--JOINED BY INVENTORY_ITEM_ID, ORGANZATION_ID, 
--CONDITIONED BY CATEGORY_ID, CATEGORY_SET_ID,

SELECT
*
FROM
APPS.MTL_CATEGORIES_B_KFV
--joined by category_id, structure_id,
--find out concatenated_segments, padded_concatenated_segments, segment1, segment2, segment3, segment4, segment5, segment6


SELECT
*
FROM
APPS.MTL_CATEGORIES_B
--JOINED BY CATEGORY_ID, STRUCTURE_ID
--FIND OUT CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, SEGMENT6

SELECT
*
FROM
APPS.MTL_CATEGORY_SETS_VL
WHERE 1=1
--JOINED BY CATEGORY_SET_ID, STRUCTURE_ID, 
--FIND OUT CATEGORY_SET_NAME, DESCRIPTION, 

SELECT
*
FROM
APPS.MTL_ITEM_CATEGORIES
WHERE 1=1
--JOINED BY INVENTORY_ITEM_ID, ORGANIZATION_ID, CATEGORY_SET_ID, CATEGORY_ID, 
--CONDITIONED BY PROGRAM_ID, 

SELECT
*
FROM
APPS.FA_CATEGORIES_B_KFV
--JOINED BY CATEGORY_ID, 
--FIND OUT CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, SEGMENT1, SEGMENT2
--CONDITIONED BY CATEGORY_TYPE, 


SELECT
*
FROM
APPS.MTL_CATEGORY_SET_VALID_CATS_V
--JOINED BY  CATEGORY_SET_ID, CATEGORY_ID
--FIND OUT CATEGORY_SET_NAME, CATEGORY_COCAT_SEGMENTS


SELECT
*
FROM
APPS.MTL_CATEGORY_SETS
--JOINED BY CATEGORY_SET_ID, STRUCTURE_ID,
--CONDITIONED BY DEFAULT_CATEGORY_ID, 
--FIND OUT CATEGORY_SET_NAME, DESCRIPTION

SELECT
*
FROM
APPS.MTL_CATEGORIES
--CONDITIONED BY CATEGORY_SET_ID, STRUCTURE_ID,
--FIND OUT segment1, segment2, segment3, segment4, segment5, segment6, DESCRIPTION
--JOINED BY 
--SEARCH BY 
--CONDITIONED BY 
