
---------------------------------------------------------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.MTL_CATEGORIES_B_KFV
--joined by category_id, structure_id,
--find out concatenated_segments, padded_concatenated_segments, segment1, segment2, segment3, segment4, segment5, segment6


SELECT
*
FROM
APPS.MTL_CATEGORIES_B
--JOINED BY CATEGORY_ID, STRUCTURE_ID
--FIND OUT CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, SEGMENT6

SELECT
*
FROM
APPS.MTL_CATEGORY_SETS_VL
WHERE 1=1
--JOINED BY CATEGORY_SET_ID, STRUCTURE_ID, 
--FIND OUT CATEGORY_SET_NAME, DESCRIPTION, 

SELECT
*
FROM
APPS.MTL_ITEM_CATEGORIES
WHERE 1=1
--JOINED BY INVENTORY_ITEM_ID, ORGANIZATION_ID, CATEGORY_SET_ID, CATEGORY_ID, 
--CONDITIONED BY PROGRAM_ID, 

SELECT
*
FROM
APPS.FA_CATEGORIES_B_KFV
--JOINED BY CATEGORY_ID, 
--FIND OUT CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, SEGMENT1, SEGMENT2
--CONDITIONED BY CATEGORY_TYPE, 


SELECT
*
FROM
APPS.MTL_CATEGORY_SET_VALID_CATS_V
--JOINED BY  CATEGORY_SET_ID, CATEGORY_ID
--FIND OUT CATEGORY_SET_NAME, CATEGORY_COCAT_SEGMENTS


SELECT
*
FROM
APPS.MTL_CATEGORY_SETS
--JOINED BY CATEGORY_SET_ID, STRUCTURE_ID,
--CONDITIONED BY DEFAULT_CATEGORY_ID, 
--FIND OUT CATEGORY_SET_NAME, DESCRIPTION

SELECT
*
FROM
APPS.MTL_CATEGORIES
--CONDITIONED BY CATEGORY_SET_ID, STRUCTURE_ID,
--FIND OUT segment1, segment2, segment3, segment4, segment5, segment6, DESCRIPTION
--JOINED BY 
--SEARCH BY 
--CONDITIONED BY 


---------------------------------------------------------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.MTL_PARAMETERS
WHERE 1=1
--JOINED BY ORGANIZATION_ID, MASTER_ORGAIZATION_ID
--FIND OUT ORGANIZATION_CODE, ORGAIZATION_ID, 


-----------------------------------------------------------------------------------------------------------------------------------------------------
SELECT
*
FROM
APPS.MTL_SYSTEM_ITEMS_B
--JOINED BY INVENTORY_ITEM_ID, ORGANIZATION_ID
--FIND OUT PRIMARY_UOM_CODE, SEGMENT1, SEGMENT2, SEGMENT3, DESCRIPTION, LIST_PRICE_PER_UNIT
--SEARCH BY CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, 
--CONNECTED BY EXPENSE_ACCOUNT, INVENTORY_ITEM_STATUS_CODE

SELECT
*
FROM
APPS.MTL_SYSTEM_ITEMS_TL
WHERE 1=1
--JOINED BY INVENTORY_ITEM_ID, ORGANIZATION_ID
--FIND OUT DESCRIPTION, 


SELECT
*
FROM
APPS.MTL_SYSTEM_ITEMS_VL
WHERE 1=1
--JOINED BY INVENTORY_ITEM_ID, ORGANIZATION_ID
--FIND OUT PRIMARY_UNIT_OF_MEASURE, SEGMENT1, SEGMENT2, SEGMENT3, DESCRIPTION
--SEARCH BY CONCATED_SEGMENTS, PADDED_CONCATED_SEGMENTS, 



SELECT
*
FROM
APPS.MTL_ITEM_STATUS 
WHERE 1=1
--CONDITIONED BY INVETORY_ITEM_STATUS_CODE, INVENTORY_ITEM_STATUS_CODE_TL, 
--FIND OUT DESCRIPTION
--JOINED BY 
--SEARCH BY 
--CONDITIONED BY 


---------------------------------------------------------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.MTL_UNITS_OF_MEASURE
WHERE 1=1
--JOINED BY
--FIND OUT UNIT_OF_MEASURE, UOM_CODE, DESCRIPTION
--CONDITIONED BY UOM_CLASS, UNIT_OF_MEASURE_TL,

SELECT
*
FROM
APPS.MTL_UNITS_OF_MEASURE_TL

SELECT
*
FROM
APPS.MTL_ITEM_LOCATIONS
--JOINED BY INVENTORY_LOCATION_ID,
--FIND OUT SUBINVENTORY_CODE, 
--CONDITIONED BY SEGMENT1, SEGMENT2, SEGMENT3, 

SELECT
*
FROM
APPS.MTL_DEMAND
