/* Formatted on 7/2/2019 5:26:40 PM (QP5 v5.287) */
  SELECT OOH.ORG_ID,
         APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (OOH.ORG_ID) OPERATING_UNIT,
         APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID)
            CUSTOMER_NUMBER,
         APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOH.SOLD_TO_ORG_ID)
            CUSTOMER_NAME,
         (SELECT OT.NAME
            FROM APPS.OE_TRANSACTION_TYPES_TL OT
           WHERE OT.TRANSACTION_TYPE_ID = OOH.ORDER_TYPE_ID)
            ORDER_TYPE_NAME,
         (SELECT NAME
            FROM APPS.OE_PRICE_LISTS OPL
           WHERE PRICE_LIST_ID = OOL.PRICE_LIST_ID)
            PRICE_LIST,
         OOL.ORDERED_ITEM ITEM_CODE,
         TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-YY') ORDERED_DATE,
         OOL.ORDERED_QUANTITY,
         OOL.ORDER_QUANTITY_UOM UOM,
         OOL.UNIT_SELLING_PRICE,
         (SELECT OT.NAME
            FROM APPS.OE_TRANSACTION_TYPES_TL OT
           WHERE OT.TRANSACTION_TYPE_ID = OOL.LINE_TYPE_ID)
            LINE_TYPE,
         OOL.ATTRIBUTE4 PROJECT_TOTAL_BILL_AMNT,
         OOL.ATTRIBUTE5 Remarks,
         OOL.ATTRIBUTE6 Expense_Type_DFF,
         TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') Month_Year,
         ABS (CEIL ( (OOL.UNIT_SELLING_PRICE * OOL.ORDERED_QUANTITY))) TOTAL_TK,
         CEIL (OOL.UNIT_SELLING_PRICE * OOL.ORDERED_QUANTITY) MESSAGE
    FROM APPS.OE_ORDER_LINES_ALL OOL, APPS.OE_ORDER_HEADERS_ALL OOH
   WHERE 1 = 1 AND OOH.HEADER_ID = OOL.HEADER_ID --AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER
                                                 --AND OOH.ORDER_NUMBER IN ('1417741')
                                                 --AND OOL.ORDER_QUANTITY_UOM='MTN'
                                                 --AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
                                                 --AND OOL.INVENTORY_ITEM_ID='206571'
                                                 --AND OOH.FLOW_STATUS_CODE='CLOSED'--'BOOKED'
                                                 --AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
                                                 --AND OOL.SHIPMENT_PRIORITY_CODE IN ('DO/SCOU/1400335')
                                                 --AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
                                                 --AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
         AND TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR') = '30-MAY-19' --AND ORDER_TYPE_ID=1101
         AND OOH.ORG_ID = 665
--AND OOH.SHIP_FROM_ORG_ID=1346
--         AND APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID) =:CUSTOMER_NUMBER
ORDER BY OOH.ORDERED_DATE DESC;

--------------------------------------------------------------------------------CERAMIC


  SELECT OOH.ORG_ID,
         APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (OOH.ORG_ID) OPERATING_UNIT,
         APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID)
            CUSTOMER_NUMBER,
         APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOH.SOLD_TO_ORG_ID)
            CUSTOMER_NAME,
         (SELECT OT.NAME
            FROM APPS.OE_TRANSACTION_TYPES_TL OT
           WHERE OT.TRANSACTION_TYPE_ID = OOH.ORDER_TYPE_ID)
            ORDER_TYPE_NAME,
         (SELECT NAME
            FROM APPS.OE_PRICE_LISTS OPL
           WHERE PRICE_LIST_ID = OOL.PRICE_LIST_ID)
            PRICE_LIST,
         OOL.INVENTORY_ITEM_ID,
         OOL.ORDERED_ITEM ITEM_CODE,
         TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-YY') ORDERED_DATE,
         OOL.ORDERED_QUANTITY,
         OOL.ORDER_QUANTITY_UOM UOM,
         OOL.UNIT_SELLING_PRICE,
         OOL.LINE_TYPE_ID,
         (SELECT OT.NAME
            FROM APPS.OE_TRANSACTION_TYPES_TL OT
           WHERE OT.TRANSACTION_TYPE_ID = OOL.LINE_TYPE_ID)
            LINE_TYPE,
         OOL.ATTRIBUTE4 PROJECT_TOTAL_BILL_AMNT,
         OOL.ATTRIBUTE5 Remarks,
         OOL.ATTRIBUTE6 Expense_Type_DFF,
         TO_CHAR (OOH.ORDERED_DATE, 'MON-RRRR') Month_Year,
         ABS (CEIL ( (OOL.UNIT_SELLING_PRICE * OOL.ORDERED_QUANTITY))) TOTAL_TK,
         CEIL (OOL.UNIT_SELLING_PRICE * OOL.ORDERED_QUANTITY) MESSAGE
    FROM APPS.OE_ORDER_LINES_ALL OOL, APPS.OE_ORDER_HEADERS_ALL OOH
   WHERE 1 = 1 AND OOH.HEADER_ID = OOL.HEADER_ID --AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER
                                                 --AND OOH.ORDER_NUMBER IN ('1417741')
                                                 --AND OOL.ORDER_QUANTITY_UOM='MTN'
                                                 --AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
                                                 --AND OOL.INVENTORY_ITEM_ID='206571'
                                                 --AND OOH.FLOW_STATUS_CODE='CLOSED'--'BOOKED'
                                                 --AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
                                                 --AND OOL.SHIPMENT_PRIORITY_CODE IN ('DO/SCOU/1400335')
                                                 --AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
                                                 --AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
         AND TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR') = '30-MAY-19' --AND ORDER_TYPE_ID=1101
         AND OOH.ORG_ID = 83
--AND OOH.SHIP_FROM_ORG_ID=1346
--         AND APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID) =:CUSTOMER_NUMBER
ORDER BY OOH.ORDERED_DATE DESC;