/* Formatted on 7/8/2019 9:27:40 AM (QP5 v5.287) */
SELECT 
       FU.USER_ID,
       PPF.PERSON_ID,
       PPF.EMPLOYEE_NUMBER,
       PPF.FULL_NAME EMPLOYEE_NAME,
       PPF.START_DATE APPLICANT_START_DATE,
       PPOS.DATE_START EFFECTIVE_START_DATE,
       PPF.ORIGINAL_DATE_OF_HIRE,
       PPF.MARITAL_STATUS,
       PPF.NATIONAL_IDENTIFIER,
       DECODE (PPF.SEX,  'M', 'MALE',  'F', 'FEMALE',  'OTHERS') GENDER,
       PPF.DATE_OF_BIRTH,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_DIFF_ALL (CURRENT_DATE,
                                                PPF.DATE_OF_BIRTH)
          AGE,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_YEAR_CAL_YEAR (CURRENT_DATE,
                                                     PPF.DATE_OF_BIRTH)
          AGE_YEAR,
       PPF.ATTRIBUTE1 BLOOD_GROUP,
       PPF.ATTRIBUTE2 RELIGN,
       PPF.ATTRIBUTE7 HIGHT,
       APPS.XXAKG_ORACLE_PKG.GET_HIGHEST_QUALIFICATION (PPF.PERSON_ID)
          HIGHEST_QUALIFICATION,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_YEAR_CAL_YEAR (
          CURRENT_DATE,
          PPOS.DATE_START)
          TENURE_YEAR,
       APPS.XXAKG_ORACLE_PKG.GET_DATE_DIFF_ALL (CURRENT_DATE,
                                                PPOS.DATE_START)
          TENURE,
       APPS.XXAKG_ORACLE_PKG.GET_TOTAL_EXPERIENCE (PPF.PERSON_ID)
          TOTAL_EXPERIENCE,
       APPS.XXAKG_ORACLE_PKG.GET_PREVIOUS_JOB_DETAILS (PPF.PERSON_ID)
          PREVIOUS_JOB_DETAILS,
       APPS.XXAKG_ORACLE_PKG.GET_PERSON_TYPE (PPF.PERSON_ID) PERSON_TYPE,
       APPS.XXAKG_ORACLE_PKG.GET_PERSON_NAME (PPF.PERSON_ID) PERSON_NAME,
       APPS.XXAKG_ORACLE_PKG.GET_ENAME_FRM_ENUM (PPF.EMPLOYEE_NUMBER)
          GET_ENAME_FRM_ENUM,
       PAAF.SUPERVISOR_ID,
       PPX.EMPLOYEE_NUMBER SUPERVISOR_EMP_NUM,
       NVL (PPX.FULL_NAME, 'NONE') SUPERVISOR_EMP_NAME,
       (SELECT PPDS.SEGMENT2
          FROM APPS.PER_POSITION_DEFINITIONS PPDS,
               APPS.HR_ALL_POSITIONS_F HAPFS,
               APPS.PER_ALL_ASSIGNMENTS_F PAAFS
         WHERE     SYSDATE BETWEEN PAAFS.EFFECTIVE_START_DATE
                               AND PAAFS.EFFECTIVE_END_DATE
               AND NVL (PAAFS.POSITION_ID, 1) = HAPFS.POSITION_ID(+)
               AND HAPFS.POSITION_DEFINITION_ID =
                      PPDS.POSITION_DEFINITION_ID(+)
               --AND PAAFS.ASSIGNMENT_NUMBER = PPX.EMPLOYEE_NUMBER
               AND PAAFS.PERSON_ID=PPF.PERSON_ID)
          SUPERVISOR_DESIGNATION,
       APPS.XXAKG_ORACLE_PKG.GET_SUPERVISOR_NAME (PPF.PERSON_ID)
          SUPERVISOR_NAME,
       PJD.SEGMENT1 Department,
       PJD.SEGMENT2 SUB_DEPARTMENT,
       PPSF.PAYROLL_NAME,
       HRL.LOCATION_CODE,
       POU.NAME ORGANIZATION_NAME,
       PPD.SEGMENT2 EMP_DESIGNATION,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'M')
          PERSONAL_NUMBER,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'C1')
          OFFICE_NUMBER,
       APPS.XXAKG_ORACLE_PKG.GET_CONTACT_NUMBER (PPF.PERSON_ID, 'H1')
          HOME_NUMBER--,PPF.*
                     --,PJD.*
                     --,PPSF.*
                     --,HRL.*
                     --,POU.*
                     --,PPD.*
                     --,HAPF.*
                     --,PPOS.*
       ,APPS.XXAKG_ORACLE_PKG.EMPLOYEE_CREATED_BY (PPF.PERSON_ID) CREATED_USER_ID
  FROM APPS.PER_PEOPLE_F PPF,
       APPS.FND_USER FU,
       APPS.PER_ALL_ASSIGNMENTS_F PAAF,
       APPS.PER_PEOPLE_X PPX,
       APPS.PER_JOBS PJ,
       APPS.PER_JOB_DEFINITIONS PJD,
       APPS.PAY_PAYROLLS_F PPSF,
       APPS.HR_LOCATIONS HRL,
       APPS.PER_ORGANIZATION_UNITS POU,
       APPS.PER_POSITION_DEFINITIONS PPD,
       APPS.HR_ALL_POSITIONS_F HAPF,
       APPS.PER_PERIODS_OF_SERVICE PPOS
 WHERE     1 = 1
       AND PPF.PERSON_ID = PPOS.PERSON_ID
       AND PPF.PERSON_ID=FU.EMPLOYEE_ID
       AND HAPF.LOCATION_ID(+) = HRL.LOCATION_ID
       AND NVL (PAAF.POSITION_ID, 1) = HAPF.POSITION_ID(+)
       AND HAPF.POSITION_DEFINITION_ID = PPD.POSITION_DEFINITION_ID(+)
       AND PAAF.ORGANIZATION_ID = POU.ORGANIZATION_ID
       AND NVL (PAAF.LOCATION_ID, 1) = HRL.LOCATION_ID(+)
       AND NVL (PAAF.PAYROLL_ID, 1) = PPSF.PAYROLL_ID(+)
       AND PJD.JOB_DEFINITION_ID = PJ.JOB_DEFINITION_ID
       AND NVL (PAAF.JOB_ID, 1) = PJ.JOB_ID
       AND PPF.PERSON_ID = PAAF.PERSON_ID
       AND PAAF.SUPERVISOR_ID = PPX.PERSON_ID(+)
       --AND FU.USER_ID=:P_USER_ID
       --AND PPF.EMPLOYEE_NUMBER = :P_EMPLOYEE_NUMBER
       AND UPPER (PPF.FULL_NAME) LIKE UPPER ('%' || :P_EMPLOYEE_NAME || '%')
       --AND UPPER (POU.NAME) LIKE UPPER ('%' || :P_ORGANIZATION_NAME || '%')
       --AND UPPER (PJD.SEGMENT1) LIKE UPPER ('%' || :P_DEPARTMENT_NAME || '%')
       --AND UPPER (PJD.SEGMENT2) LIKE UPPER ('%' || :P_SUB_DEPARTMENT || '%')
       --AND UPPER (PJD.SEGMENT2) LIKE UPPER ('%' || :P_SUB_DEPARTMENT || '%')
       --AND UPPER (HRL.LOCATION_CODE) LIKE UPPER ('%' || :P_LOCATION || '%')
       AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE
                       AND PPF.EFFECTIVE_END_DATE
       AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE
                       AND PAAF.EFFECTIVE_END_DATE
--AND SYSDATE BETWEEN PPD.START_DATE_ACTIVE AND PPD.END_DATE_ACTIVE