/* Formatted on 5/16/2019 10:23:09 AM (QP5 v5.287) */
SELECT *
  FROM APPS.PER_QUALIFICATIONS PQ
 WHERE 1 = 1
--JOINED BY QUALIFICATION_ID

APPS.PER_QUALIFICATIONS QUA,
APPS.PER_QUALIFICATIONS_TL QT,
APPS.PER_QUALIFICATION_TYPES_TL QTT,
APPS.PER_ESTABLISHMENT_ATTENDANCES ESA,
APPS.PER_ESTABLISHMENTS EST,
APPS.PER_QUALIFICATION_TYPES QUT,
APPS.PER_ALL_PEOPLE_F PPF,
APPS.PER_ALL_ASSIGNMENTS_F PAF,
APPS.PER_JOB_DEFINITIONS PJD,
APPS.PER_JOBS PJ,
APPS.PAY_PEOPLE_GROUPS PPG,
APPS.PER_ORGANIZATION_UNITS POU,
APPS.PER_ASSIGNMENT_STATUS_TYPES_TL PAST,
APPS.PAY_COST_ALLOCATIONS_F PCAF,
APPS.PAY_COST_ALLOCATION_KEYFLEX PCAK,
APPS.AKG_MAX_PPOS_VIEW AMPV,
APPS.PER_PERSON_TYPE_USAGES_F PPTU,
APPS.PER_PERSON_TYPES PPT,
APPS.HR_LOCATIONS_ALL HRL,
APPS.PAY_PAYROLLS_F PAPF,