SELECT
AED.EMPLOYEE_NUMBER,
AED.FULL_NAME,
AED.DESIGNATION,
PP.PHONE_NUMBER
FROM
APPS.PER_PHONES PP,
APPS.AKG_EMPLOYEE_DETAILS AED
WHERE 1=1
AND AED.PERSON_ID=PP.PARENT_ID
--AND AED.DEPARTMENT='MARKETING'
AND AED.PERSON_TYPE!='Ex-employee'
AND PERSON_STATUS='Active Assignment'
AND PAPF.EMPLOYEE_NUMBER='32053'
--AND PP.PHONE_NUMBER='01985559051'

SELECT
PP.*
FROM
APPS.PER_PEOPLE_F PPF,
APPS.PER_PHONES PP
WHERE 1=1
AND PPF.PERSON_ID=PP.PARENT_ID
and EMPLOYEE_NUMBER='32053'
--AND PP.PHONE_NUMBER='01985559051'
AND PHONE_TYPE='C1'

SELECT
*
FROM
APPS.PER_PHONES PP
WHERE 1=1
AND PHONE_NUMBER='01985559051'