SELECT
--VH.*
--TD.*
DD.*
FROM
APPS.XXAKG_TYRE_DETAILS TD
,APPS.XXAKG_VEHICLE_HEADERS VH
,APPS.XXAKG_DRIVER_DETAILS DD
WHERE 1=1
AND DD.VEHICLE_ID=VH.VEHICLE_ID
AND TD.VEHICLE_ID=VH.VEHICLE_ID
AND VH.REG_NUMBER='DM-SHA-11-0968'
--AND TD.TYRE_NUMBER='119141'
AND DD.END_DATE IS NULL

------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.XXAKG_TYRE_DETAILS


SELECT
*
FROM
APPS.XXAKG_VEHICLE_HEADERS
WHERE 1=1
AND REG_NUMBER='DM-SHA-11-0968'


SELECT
*
FROM
APPS.XXAKG_DRIVER_DETAILS DD
WHERE 1=1
AND DRIVER_EMP_NUM='18627'
AND END_DATE IS NULL


