SELECT
LOOKUP_TYPE,
LOOKUP_CODE,
MEANING,
DESCRIPTION
--,FLV.*
FROM
APPS.FND_LOOKUP_VALUES FLV
WHERE 1=1
--AND DESCRIPTION=:P_DESCRIPTION
AND LOOKUP_TYPE='XXAKG_SCIL_SCM_TRIP_VEHICLE'
--AND LOOKUP_CODE like '%SCIL-SCM-0001%'
--AND MEANING LIKE '%Company Truck%'