SELECT     
Registration_Number VEHICLE_NO
,INSURANCE_EXPIRY_DATE "Insurance Expiration Date"
,VRE_ATTRIBUTE16 "Vehicle Group"
,NVL(LOCATION_NAME,'SCIL Factory') "Operating Location"
,VRE_ATTRIBUTE12 "Tax Token Expire Date"
,VRE_ATTRIBUTE14 "Route Permit Expire Date"
,VRE_ATTRIBUTE13 "Fitness Expire Date"
,DRIVER_NUMBER DRIVER_ID
,DRIVER_FULL_NAME DRIVER_NAME
,VR.*
FROM
APPS.XXAKG_VEHICLE_REPOSITORY_F VR
WHERE 1=1
AND VR.VRE_ATTRIBUTE2 = 82
AND VR.VEHICLE_STATUS='A'
AND UPPER (REGISTRATION_NUMBER) LIKE UPPER ('%' || :P_VEHICLE_NUMBER || '%')
--AND VR.VRE_ATTRIBUTE3='Road Transport'
AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
--AND TRUNC(VR.CREATION_DATE) BETWEEN '28-NOV-2018' and '29-NOV-2018'

------------------------**********VEHICLE_REPOSITORY**********---------------------
SELECT 
REGISTRATION_NUMBER VEHICLE_NO,
VRE_ATTRIBUTE16 VEHICLE_GROUP,
(SELECT PAPF.EMPLOYEE_NUMBER||'-'||PAPF.FULL_NAME FROM APPS.PER_ALL_PEOPLE_F PAPF WHERE PAPF.PERSON_ID=VR.VRE_ATTRIBUTE19 AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE) DRIVER,
VR.VEHICLE_STATUS STATUS
--,VR.*
FROM 
APPS.PQP_VEHICLE_REPOSITORY_F VR
WHERE   1=1
AND SYSDATE BETWEEN VR.EFFECTIVE_START_DATE AND VR.EFFECTIVE_END_DATE
AND  REGISTRATION_NUMBER = 'D.M.AU-11-4261'
AND VRE_ATTRIBUTE2 = 82
--AND VRE_ATTRIBUTE3 = 'Road Transport'
AND VEHICLE_STATUS = 'A'

----------------------------*********VMS******---------------------------------------

SELECT
*
FROM
APPS.XXAKG_VMS_F
WHERE 1=1
AND ORG_ID= 85
and GATE_OUT_DATE is not null 
and GATE_OUT='Y'
and GATE_IN_DATE is null 
and DO_WAREHOUSE_ORG_CODE='SCI' 
AND DO_MODE_OF_TRANSPORT IN ('Company Bulk Carrier','Company Truck')
--and VEHICLE_GROUP='Group-C'-- IN ('Group-A', 'Group-D', 'Group-C', 'Group-Bulk', 'Group-G2', 'Group-G1', 'Group-E', 'Group-F1','Ghat','Group-B','Group-F2')
AND VEHICLE_NO='D.M.AU-11-4261'
AND GATE_IN IS NULL


-------------------------------------------------------********-------------------------------------------------
SELECT
*
FROM
APPS.XXAKG_MOV_ORD_HDR MOH
WHERE 1=1
AND VEHICLE_NO=:P_VEHICLE_NO--'D.M.U-11-0949'--'D.M.U-11-1118'--
--AND READY_FOR_INVOICE='N'
--AND MOH.INITIAL_GATE_IN='Y'
--AND MOH.MOV_ORDER_DATE BETWEEN '01-OCT-2017' AND '28-OCT-2017'
--AND MOH.GATE_OUT IS NULL
AND MOH.GATE_IN IS NULL
AND MOH.ORG_ID=85
--AND MOV_ORDER_STATUS='CONFIRMED'
AND TRANSPORT_MODE='Company Truck'
--AND EMPTY_TRUCK_WT IS NULL
--AND FINAL_DESTINATION IN ('For Loading','AKCL Workshop')
ORDER BY MOV_ORDER_DATE DESC

SELECT
*
FROM
XXAKG.XXAKG_TO_MO_HDR 
WHERE 1=1
--AND MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND GATE_OUT IS NULL
AND GATE_IN IS NULL
AND INITIAL_GATE_IN='Y'
--AND AP_FLAG IS NULL
AND ORG_ID=85
AND VEHICLE_NO=:P_VEHICLE_NO--'D.M.U-11-0949'





