SELECT
* FROM(
SELECT  DO_NUMBER,CUSTOMER_NAME,CUSTOMER_NUMBER,PHONE_NUMBER,TERRITORY,DO_STATUS,CONFIRMED_DATE,DO_WAREHOUSE_ORG_CODE,VEHICLE_NO,  DRIVER_NAME,DRIVER_MOBILE,
RTRIM(LISTAGG(ITEM ||' '|| QTY ||' '||UOM_CODE || ', ') WITHIN GROUP(ORDER BY DO_NUMBER),', ') Item
FROM (
SELECT DO_NUMBER,CUSTOMER_NAME,CUSTOMER_NUMBER,ITEM_SHORT_NAME ITEM,PHONE_NUMBER,TERRITORY,DO_STATUS,CONFIRMED_DATE,DO_WAREHOUSE_ORG_CODE,VEHICLE_NO,  DRIVER_NAME,DRIVER_MOBILE,SUM(LINE_QUANTITY) QTY ,UOM_CODE
    FROM apps.cgd_delivery_sms
    where DO_STATUS='CONFIRMED' --and DO_NUMBER IN  ('DO/CGOU/209208' ,'DO/CGOU/209191' )
    GROUP BY DO_NUMBER,CUSTOMER_NAME,CUSTOMER_NUMBER, ITEM_SHORT_NAME,PHONE_NUMBER,TERRITORY,DO_STATUS,CONFIRMED_DATE,DO_WAREHOUSE_ORG_CODE,VEHICLE_NO,  DRIVER_NAME,DRIVER_MOBILE,UOM_CODE)
    GROUP BY DO_NUMBER,CUSTOMER_NAME,CUSTOMER_NUMBER,PHONE_NUMBER,TERRITORY,DO_STATUS,CONFIRMED_DATE,DO_WAREHOUSE_ORG_CODE, VEHICLE_NO, DRIVER_NAME,DRIVER_MOBILE) AA,          
(SELECT DO_NUMBER, 
RTRIM(LISTAGG(ORDER_NUMBER || ', ') WITHIN GROUP(ORDER BY 1),', ') ORDER_NUMBER
FROM (
SELECT DISTINCT ORDER_NUMBER,DO_NUMBER
    FROM 
        apps.CGD_DELIVERY_SMS
        WHERE DO_STATUS='CONFIRMED' --DO_NUMBER IN  ('DO/CGOU/209208' ,'DO/CGOU/209191' )
        --and DO_NUMBER ='DO/CGOU/209209'
        )         
        GROUP BY DO_NUMBER) BB
        WHERE AA.DO_NUMBER=BB.DO_NUMBER
        AND CONFIRMED_DATE>'1-JAN-2016'