SELECT ORDER_NUMBER,CUSTOMER_NUMBER,CUSTOMER_NAME ,PHONE_NUMBER,TERRITORY,ORDER_FLOW_STATUS_CODE Status,BOOKED_DATE, 
RTRIM(LISTAGG(ITEM_SHORT_NAME ||' '|| ORDERED_QUANTITY ||' '||ORDER_QUANTITY_UOM || ', ') WITHIN GROUP(ORDER BY 1),', ') Item FROM CGD_ORDER_SMS 
where ORDER_NUMBER='610054113' GROUP BY ORDER_NUMBER,CUSTOMER_NUMBER, CUSTOMER_NAME, PHONE_NUMBER,TERRITORY,ORDER_FLOW_STATUS_CODE,BOOKED_DATE 
