select
*
from
apps.RA_CUSTOMER_MERGES RCM
where 1=1
AND PROCESS_FLAG='SAVED'
order by  LAST_UPDATE_DATE desc 
--CUSTOMER_MARGE_ID, CREATED_BY, CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_REF, CUSTOMER_SITE_ID, CUSTOMER_SITE_CODE, CUSTOMER_LOCATION, CUSTOMER_SITE_NUMBER, ORG_ID, 

SELECT
*
FROM
APPS.HZ_CUST_ACCOUNTS
WHERE 1=1
--CUST_ACCOUNT_ID, PARTY_ID, ACCOUNT_NUMBER, ORIG_SYSTEM_REFERENCE, STATUS, ACCOUNT_NAME, 
--AND ACCOUNT_NUMBER='15707'

SELECT
HCA.*
FROM
APPS.RA_CUSTOMER_MERGES RCM,
APPS.HZ_CUST_ACCOUNTS HCA
WHERE 1=1
AND RCM.CUSTOMER_NUMBER=HCA.ACCOUNT_NUMBER
AND CUSTOMER_ID='6071'
AND CUSTOMER_NUMBER='35082'