---------------------------------------Officer Phone Number--------------------------------------------------------------

SELECT DISTINCT
RBC.REGION_NAME,
--RBC.BLOCK_NAME,
--RBC.CELL_NAME,
CA.ACCOUNT_NUMBER CUSTOMER_NUMBER,
HP.PARTY_NAME CUSTOMER_NAME,
CA.ATTRIBUTE9 "Officer Phone Number",
AED.EMPLOYEE_NUMBER,
AED.FULL_NAME,
AED.DESIGNATION
--CA.ACCOUNT_NAME,
--CA.STATUS ACCOUNT_STATUS,
--CSUA.STATUS CUSTOMER_SITE_STATUS,
--CA.CREATION_DATE "ACCOUNT CREATION DATE",
--CASA.CREATION_DATE "ACCOUNT SITE CREATION DATE",
--CSUA.SITE_USE_CODE,
--CSUA.LOCATION
--,RBC.*
FROM
APPS.HZ_CUST_ACCOUNTS CA,
APPS.HZ_PARTIES HP,
APPS.HZ_CUST_SITE_USES_ALL CSUA,
APPS.HZ_CUST_ACCT_SITES_ALL CASA
,APPS.XXAKG_REGION_BLOCK_CELL_V RBC
,APPS.PER_PHONES PP
,APPS.AKG_EMPLOYEE_DETAILS AED
WHERE 1=1
AND CA.CUST_ACCOUNT_ID=RBC.CUSTOMER_ID
AND CA.PARTY_ID=HP.PARTY_ID
AND CSUA.CUST_ACCT_SITE_ID=CASA.CUST_ACCT_SITE_ID
AND CA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID
--AND CA.STATUS='A'
--AND CSUA.STATUS='A'
AND PERSON_STATUS='Active Assignment'
AND PP.PHONE_NUMBER=CA.ATTRIBUTE9
AND AED.PERSON_ID=PP.PARENT_ID 
AND CA.ATTRIBUTE9 IS NOT NULL
--AND CA.ATTRIBUTE9='01713441645'
AND CSUA.SITE_USE_CODE='BILL_TO'
--AND RBC.CUSTOMER_NUMBER='34262'
AND RBC.ORG_ID=85
--and RBC.REGION_NAME NOT IN ('Corporate North','Corporate South','Institutional','MES')
--and RBC.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')

SELECT
*
FROM
APPS.XXAKG_REGION_BLOCK_CELL_V

SELECT
*
FROM
APPS.AKG_EMPLOYEE_DETAILS
WHERE 1=1
AND EMPLOYEE_NUMBER='32053'



SELECT DISTINCT
TO_CHAR(DOH.DO_DATE) DO_DATE,
DOH.DO_NUMBER,
RBC.REAILER SITE_NAME,
RBC.REAILER_ADDRESS LOCATION,
RBC.REGION_NAME,
CA.ACCOUNT_NUMBER CUSTOMER_NUMBER,
HP.PARTY_NAME CUSTOMER_NAME,
CA.ATTRIBUTE9 "Officer Phone Number",
AED.EMPLOYEE_NUMBER,
AED.FULL_NAME,
AED.DESIGNATION
FROM
APPS.HZ_CUST_ACCOUNTS CA,
APPS.HZ_PARTIES HP,
APPS.HZ_CUST_SITE_USES_ALL CSUA,
APPS.HZ_CUST_ACCT_SITES_ALL CASA
,APPS.XXAKG_REGION_BLOCK_CELL_V RBC
,APPS.PER_PHONES PP
,APPS.AKG_EMPLOYEE_DETAILS AED
,APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND RBC.SHIP_SITE_LOCATION_ID=DODL.SHIP_TO_ORG_ID
AND RBC.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
AND CA.CUST_ACCOUNT_ID=RBC.CUSTOMER_ID
AND CA.PARTY_ID=HP.PARTY_ID
AND CSUA.CUST_ACCT_SITE_ID=CASA.CUST_ACCT_SITE_ID
AND CA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID
--AND CA.STATUS='A'
--AND CSUA.STATUS='A'
AND PP.PHONE_NUMBER=CA.ATTRIBUTE9
AND AED.PERSON_ID=PP.PARENT_ID 
AND AED.PERSON_STATUS='Active Assignment'
AND CA.ATTRIBUTE9 IS NOT NULL
--AND CA.ATTRIBUTE9 IN ('01975441919','01817292822')
AND CSUA.SITE_USE_CODE='BILL_TO'
--AND RBC.CUSTOMER_NUMBER='20559'
AND RBC.ORG_ID=85
AND TO_CHAR (DOH.DO_DATE, 'DD-MON-RR') = '29-MAY-18'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'MAY-18'
--AND RBC.REGION_NAME='Dhaka North'