SELECT DISTINCT doh.DO_NUMBER DO_NUMBER,
                ORDER_NUMBER,
                TRUNC (doh.DO_DATE) DO_DATE,
                TRUNC (line.actual_shipment_date) delivery_date,
                doh.CUSTOMER_NUMBER,
                doh.CUSTOMER_NAME CUSTOMER_NAME,
                b.bill_to_location,
                b.site_address
  FROM XXAKG_DEL_ORD_HDR doh,
       XXAKG_DEL_ORD_DO_LINES dol,
       APPS.oe_order_lines_all line,
       (SELECT CUSTOMER_NUMBER,
               org_id,
               SHIP_TO_ORG_ID bill_to_location,
               ADDRESS1 || ADDRESS2 site_address
          FROM APPS.xxakg_AR_CUSTOMER_SITE_V
         WHERE SITE_USE_CODE = 'BILL_TO' AND PRIMARY_FLAG = 'Y') b
 WHERE     DO_STATUS = 'CONFIRMED'
       AND doh.DO_HDR_ID = dol.DO_HDR_ID
       AND doh.CUSTOMER_NUMBER = b.CUSTOMER_NUMBER
       AND doh.org_id = b.org_id
       AND line.header_id = dol.ORDER_HEADER_ID
       AND line.line_id = dol.ORDER_LINE_ID
       AND line.SHIPMENT_PRIORITY_CODE = dol.DO_NUMBER
       AND UPPER (line.flow_status_code) = UPPER ('CLOSED')
       AND dol.DO_NUMBER||'-'|| dol.order_number||'-'|| dol.item_number in ( select distinct dl.DO_NUMBER||'-'||dl.order_number||'-'|| dl.item_number from APPS.XXAKG_DEL_ORD_DO_LINES dl,
        APPS.XXAKG_DEL_ORD_HDR dh
        where dh.DO_HDR_ID=dl.DO_HDR_ID
        and dh.DO_STATUS = 'CONFIRMED'
        and TRUNC(dh.DO_DATE) = NVL(:do_date,TRUNC(dh.DO_DATE))
                 AND dh.ORG_ID =:org_id
                 minus
                select dO_NUMBER||'-'|| order_number||'-'|| item_number from  APPS.XXAKG_CUST_COMPLAINTS 
                where org_id=:org_id)
        ORDER BY 1 
        
        
        
------------------------------------------------------------------------------------------------


SELECT
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER
,OOH.ORDER_NUMBER
,(SELECT TO_CHAR(DOH.DO_DATE,'DD-MON-YYYY HH24:MI:SS') FROM APPS.XXAKG_DEL_ORD_HDR DOH WHERE DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE) DO_DATE
,TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE) DELIVERY_DATE
,ACSV.CUSTOMER_NUMBER
,ACSV.CUSTOMER_NAME
,ACSV.SHIP_TO_ORG_ID BILL_TO_LOCATION
,ACSV.ADDRESS1 || ACSV.ADDRESS2 SITE_ADDRESS
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND ACSV.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND OOL.FLOW_STATUS_CODE='CLOSED'
AND OOH.ORG_ID=:P_ORG_ID
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
AND EXISTS (SELECT 1 FROM APPS.XXAKG_DEL_ORD_HDR DOH WHERE TO_CHAR (DOH.DO_DATE, 'DD-MON-RR')=TO_CHAR(:P_DO_DATE) AND DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE AND DOH.DO_STATUS='CONFIRMED')
AND ACSV.SITE_USE_CODE='BILL_TO'
AND ACSV.PRIMARY_FLAG='Y'
AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_CUST_COMPLAINTS CC WHERE 1=1
AND ACSV.CUSTOMER_NUMBER=CC.CUSTOMER_NUMBER AND OOL.SHIPMENT_PRIORITY_CODE=CC.DO_NUMBER AND OOL.ORDERED_ITEM=CC.ITEM_NUMBER AND CC.ORDER_NUMBER=OOH.ORDER_NUMBER)



-----------------------------REVISED---------------------------------------------------------


SELECT
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER
,OOH.ORDER_NUMBER
,TO_CHAR(DOH.DO_DATE,'DD-MON-YYYY HH24:MI:SS') DO_DATE
,TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE) DELIVERY_DATE
,ACSV.CUSTOMER_NUMBER
,ACSV.CUSTOMER_NAME
,ACSV.SHIP_TO_ORG_ID BILL_TO_LOCATION
,ACSV.ADDRESS1 || ACSV.ADDRESS2 SITE_ADDRESS
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
,APPS.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND ACSV.CUSTOMER_ID=OOL.SOLD_TO_ORG_ID
AND OOL.FLOW_STATUS_CODE='CLOSED'
AND DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE 
AND DOH.DO_STATUS='CONFIRMED'
AND TO_CHAR (DOH.DO_DATE, 'DD-MON-RR')=TO_CHAR(:DO_DATE)
AND OOH.ORG_ID=:ORG_ID
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
AND ACSV.SITE_USE_CODE='BILL_TO'
AND ACSV.PRIMARY_FLAG='Y'
AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_CUST_COMPLAINTS CC WHERE 1=1
AND ACSV.CUSTOMER_NUMBER=CC.CUSTOMER_NUMBER AND OOL.SHIPMENT_PRIORITY_CODE=CC.DO_NUMBER AND OOL.ORDERED_ITEM=CC.ITEM_NUMBER AND CC.ORDER_NUMBER=OOH.ORDER_NUMBER)

