SELECT
*
FROM
APPS.PO_HEADERS_ALL PHA
WHERE 1=1
--JOINED BY PO_HEADER-ID, AGENT_ID, SEGMENT1,
--CONDITIONED BY TYPE_LOOKUP_CODE, ENABLED_FLAG, APPROVED_FLAG, APPROVED_DATE, AUTHORIZATION_STATUS, 
--FIND OUT VENDOR_ID, VENDOR_SITE_ID, SHIP_TO_LOCATION, BILL_TO_LOCATION, CURRENCY_CODE, 



SELECT
*
FROM
APPS.PO_LINES_ALL
WHERE 1=1
--JOINED BY PO_LINE_ID , PO_HEADER_ID, ITEM_ID, ORG_ID, 
--FIND OUT ITEM_DESCRIPTION, UNIT_MEAS_LOOKUP_CODE, UNIT_PRICE, QUANTITY, MRKET_PRICE, 
--CONDITIONED BY LINE_TYPE_ID, LINE_NUM, ATTRIBUTE_CATEGORY (RFQ), ATTRIBUTE10(STATUS), 
--CONNECTED BY FROM_HEADER_ID, FROM_LINE_ID, 


SELECT
*
FROM
APPS.PO_HEADERS_ALL PHA,
APPS.PO_LINES_ALL PLA,
APPS.PO_LINE_LOCATIONS_ALL PLLA
WHERE 1=1
AND PHA.PO_HEADER_ID=PLA.PO_HEADER_ID
AND PHA.PO_HEADER_ID=PLLA.PO_HEADER_ID
AND PLA.PO_LINE_ID=PLLA.PO_LINE_ID
AND PHA.TYPE_LOOKUP_CODE='STANDARD'


SELECT
*
FROM
APPS.PO_LINE_LOCATIONS_ALL
--LINE_LOCATION_ID, PO_HEADER_ID, PO_LINE_ID , ORG_ID,  
--FIND OUT QUANTITY, UNIT_MEAS_LOOKUP_CODE, 
--CONNECTED BY SHIP_TO_LOCATION_ID, SHIP_TO_ORGANIZATION_ID,  FROM_HEADER_ID, FROM_LINE_ID, FROM_LINE_LOCATION_ID,  
--CONDITIONED BY NEED_BY_DATE, SHIPMENT_TYPE, CLOSED_CODE,



SELECT
*
FROM
APPS.PO_ACTION_HISTORY
--OBJECT_ID, SEQUENCE_NUM,
--CONDITION BY ACTION_CODE, ACTION_DATE, OBJECT_TYPE_CODE, OBJECT_SUB_TYPE_CODE, 
--SUBMITTED BY EMPLOYEE_ID, APPROVAL_PATH_ID, 
--SEARCH BY CREATED_BY, 

SELECT
*
FROM
APPS.PO_VENDORS PV
--JOINED BY VENDOR_ID, EMPLYEE_ID, 
--FIND OUT VENDOR_NAME, SEGMENT1,


SELECT
*
FROM
APPS.AP_INVOICES_ALL
--JOINED BY INVOICE_ID, VENDOR_ID, VENDOR_SITE_ID, 
--SEARCH BY INVOICE_NUM, SET_OF_BOOKS,
--FIND OUT PAYMENT_CURRENCY_CODE, INVOICE_AMOUNT, AMOUNT_PAID, 
--CONDITIONED BY INVOICE_TYPE_LOOKUP_CODE, DESCRIPTION


---------------------------------------------------------------------------------------------------------



SELECT
*
FROM
APPS.RCV_SHIPMENT_HEADERS
WHERE 1=1
--JOINED BY SHIPMENT_HEADER_ID, EMPLOYEE_ID, SHIP_TO_ORG_ID
--CONNECTED BY VENDOR_ID, VENDOR_SITE_ID, ORGANIZATION_ID, 
--FIND OUT SHIPMENT_NUM, RECEIPT_NUM, SHIPPED_DATE, 


SELECT
*
FROM
APPS.RCV_SHIPMENT_LINES
WHERE 1=1
--JOINED BY  SHIPMENT_LINE_ID, SHIPMENT_HEADER_ID, LINE_NUM, CATAGORY_ID, 
--FIND OUT QUANTITY_SHIPPED, QUANTITY_RECEIVED, UNIT_OF_MEASURE, ITEM_DESCRIPTION, ITEM_ID, 
--CONDITIONED BY PO_HEADER_ID, PO_LINE_ID


SELECT
*
FROM
APPS.RCV_TRANSACTIONS
WHERE 1=1
--JOINED BY TRANSACTION_ID, QUANTITY, SHPMENT_HEADER_ID, SHIPMENT_LINE_ID, EMPLOYEE_ID, VENDOR_ID, VENDOR_SITE_ID,
--SEARCH BY TRANSACTION_TYPE, 
--FIND OUT UINIT_OF_MEASURE, SUBINVENTORY,

---------------------------------------------------------------------------------------------------------



SELECT
OOH.ORG_ID,
RT.ORGANIZATION_ID,
--OOH.ORDER_TYPE_ID,
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.INVENTORY_ITEM_ID,
OOL.UNIT_SELLING_PRICE,
OOL.UNIT_COST,
OOL.ACTUAL_SHIPMENT_DATE,
OOL.FLOW_STATUS_CODE,
OOL.INVOICED_QUANTITY,
RSL.QUANTITY_SHIPPED,
RSL.QUANTITY_RECEIVED,
--RSL.UNIT_OF_MEASURE,
RSL.ITEM_DESCRIPTION,
RT.TRANSACTION_TYPE,
RT.QUANTITY,
RT.UNIT_OF_MEASURE,
RT.SUBINVENTORY,
--,RT.DESTINATION_CONTEXT
--RT.CUSTOMER_ID
--RT.CUSTOMER_SITE_ID
--,RSH.EMPLOYEE_ID
--,RSH.CUSTOMER_ID
RSH.RECEIPT_NUM
,RT.INTERFACE_TRANSACTION_ID
--,RT.TRANSACTION_ID
,RT.*
FROM
APPS.RCV_TRANSACTIONS RT,
APPS.RCV_SHIPMENT_HEADERS RSH,
APPS.RCV_SHIPMENT_LINES RSL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL
--,APPS.MTL_TRANSACTIONS_INTERFACE MTI
WHERE 1=1
AND RT.SHIPMENT_HEADER_ID=RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID=RSL.SHIPMENT_HEADER_ID
AND RT.OE_ORDER_HEADER_ID=OOH.HEADER_ID
AND RT.OE_ORDER_LINE_ID=OOL.LINE_ID
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=RSL.ITEM_ID
--AND MTI.TRANSACTION_INTERFACE_ID=RT.INTERFACE_TRANSACTION_ID
--AND OOL.INVENTORY_ITEM_ID=MTI.INVENTORY_ITEM_ID
--AND OOH.ORDER_TYPE_ID='1014'
AND RSH.ORGANIZATION_ID=99
--AND RSH.RECEIPT_NUM=16231
AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER



---------------------------------------------------------------------------------------------------------

SELECT  
PO.SEGMENT1 VENDOR_NUMBER,
PO.VENDOR_NAME,
PO.VENDOR_NAME_ALT,
PO.VENDOR_TYPE_LOOKUP_CODE,
POS.VENDOR_SITE_CODE
,VENDOR_SITE_CODE_ALT
,POS.ADDRESS_LINE1
,POS.ADDRESS_LINE2
,POS.ADDRESS_LINE3
,POS.ADDRESS_LINE4
,POS.CITY
,POS.COUNTRY
,POS.ZIP
,POS.COUNTY
,POS.STATE
,POS.INVOICE_CURRENCY_CODE
,POS.PAYMENT_CURRENCY_CODE
,POS.PAYMENT_METHOD_LOOKUP_CODE
,POS.PAY_GROUP_LOOKUP_CODE
,HR.NAME
,INACTIVE_DATE
,GLCC.CONCATENATED_SEGMENTS LIABILITY_ACCOUNT
,GLCCP.CONCATENATED_SEGMENTS PREPAY_ACCOUNT
,POS.EMAIL_ADDRESS
FROM APPS.AP_SUPPLIERS PO,APPS.AP_SUPPLIER_SITES_ALL POS
,APPS.GL_CODE_COMBINATIONS_KFV GLCC,APPS.GL_CODE_COMBINATIONS_KFV GLCCP
, APPS.HR_OPERATING_UNITS HR
WHERE PO.VENDOR_ID=POS.VENDOR_ID
AND GLCC.CODE_COMBINATION_ID=POS.ACCTS_PAY_CODE_COMBINATION_ID
AND GLCCP.CODE_COMBINATION_ID=POS.PREPAY_CODE_COMBINATION_ID
AND HR.ORGANIZATION_ID=POS.ORG_ID
--AND PO.SEGMENT1 BETWEEN NVL(:P_SUPPLIER_NUMBER_FROM,PO.SEGMENT1) AND NVL(:P_SUPPLIER_NUMBER_TO,PO.SEGMENT1)
--AND PO.VENDOR_NAME=NVL(:P_VENDOR_NAME,PO.VENDOR_NAME)
ORDER BY 1;
