select 
TO_CHAR(TRX_DATE,'DD-MON-RR')TRX_DATE,
NVL(SPECIAL_CLN,0)SPECIAL_CLN,
NVL(SPECIAL_GYP,0)SPECIAL_GYP,
NVL(SPECIAL_LIME,0)SPECIAL_LIME,
NVL(SPECIAL_FLY,0)SPECIAL_FLY,
NVL(SPECIAL_SLAG,0)SPECIAL_SLAG,
(NVL(SPECIAL_CLN,0)+NVL(SPECIAL_GYP,0)+NVL(SPECIAL_LIME,0)+NVL(SPECIAL_FLY,0)+NVL(SPECIAL_SLAG,0)) SPECIAL_INGR_TOT,
NVL(SPECIAL_P_QTY,0)SPECIAL_P_QTY,
NVL(POPULAR_CLN,0)POPULAR_CLN,
NVL(POPULAR_GYP,0)POPULAR_GYP,
NVL(POPULAR_LIME,0)POPULAR_LIME,
NVL(POPULAR_FLY,0)POPULAR_FLY,
NVL(POPULAR_SLAG,0)POPULAR_SLAG,
(NVL(POPULAR_CLN,0)+NVL(POPULAR_GYP,0)+NVL(POPULAR_LIME,0)+NVL(POPULAR_FLY,0)+NVL(POPULAR_SLAG,0)) POPULAR_INGR_TOT,
NVL(POPULAR_P_QTY,0)POPULAR_P_QTY,
NVL(OPC_CLN,0)OPC_CLN,
NVL(OPC_GYP,0)OPC_GYP,
NVL(OPC_LIME,0)OPC_LIME,
NVL(OPC_FLY,0)OPC_FLY,
NVL(OPC_SLAG,0)OPC_SLAG,
(NVL(OPC_CLN,0)+NVL(OPC_GYP,0)+NVL(OPC_LIME,0)+NVL(OPC_FLY,0)+NVL(OPC_SLAG,0)) OPC_INGR_TOT,
NVL(OPC_P_QTY,0)OPC_P_QTY,
NVL(OPC_CLN,0)CEM3_CLN,
NVL(OPC_GYP,0)CEM3_GYP,
NVL(OPC_LIME,0)CEM3_LIME,
NVL(OPC_FLY,0)CEM3_FLY,
NVL(OPC_SLAG,0)CEM3_SLAG,
(NVL(CEM3_CLN,0)+NVL(CEM3_GYP,0)+NVL(CEM3_LIME,0)+NVL(CEM3_FLY,0)+NVL(CEM3_SLAG,0)) CEM3_INGR_TOT,
NVL(OPC_P_QTY,0)CEM3_P_QTY,
(NVL(SPECIAL_CLN,0)+NVL(POPULAR_CLN,0)+NVL(OPC_CLN,0)+NVL(CEM3_CLN,0)) TOT_CLNK,
(NVL(SPECIAL_GYP,0)+NVL(POPULAR_GYP,0)+NVL(OPC_GYP,0)+NVL(CEM3_GYP,0)) TOT_GYP,
(NVL(SPECIAL_LIME,0)+NVL(POPULAR_LIME,0)+NVL(OPC_LIME,0)+NVL(CEM3_LIME,0)) TOT_LIME,
(NVL(SPECIAL_FLY,0)+NVL(POPULAR_FLY,0)+NVL(OPC_FLY,0)+NVL(CEM3_FLY,0)) TOT_FLY,
(NVL(SPECIAL_SLAG,0)+NVL(POPULAR_SLAG,0)+NVL(OPC_SLAG,0)+NVL(CEM3_SLAG,0)) TOT_SLAG,
(NVL(SPECIAL_P_QTY,0)+NVL(POPULAR_P_QTY,0)+NVL(OPC_P_QTY,0)+NVL(CEM3_P_QTY,0)) TOT_PRODUCT
 from
(SELECT trx_date,
DECODE(GMD.INVENTORY_ITEM_ID,24408,'Special',24402,'Popular',206570,'OPC',992039,'CEM3') prd,
GMD.ACTUAL_QTY,
CLINKER,
GYPSUM,
LIME,
FLYASH,
SLAG 
FROM apps.GME_MATERIAL_DETAILS GMD,
(select 
trx_date,
BATCH_NO,
BATCH_ID,
SUM(NVL(CLINKER_QTY,0))CLINKER,
SUM(NVL(GYPSUM_QTY,0))GYPSUM,
SUM(NVL(LIME_QTY,0))LIME,
SUM(NVL(FLYASH_QTY,0))FLYASH,
SUM(NVL(SLAG_QTY,0))SLAG from
(SELECT 
TRUNC(TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) trx_date,
GBH.BATCH_NO,
GMD.BATCH_ID,
GMD.INVENTORY_ITEM_ID,
(MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3)ITEM_CODE,
MSI.DESCRIPTION,
GMD.ACTUAL_QTY qty 
FROM apps.GME_BATCH_HEADER GBH,apps.GME_MATERIAL_DETAILS GMD,apps.MTL_SYSTEM_ITEMS_B MSI
WHERE GBH.ORGANIZATION_ID=GMD.ORGANIZATION_ID
AND GMD.ORGANIZATION_ID=MSI.ORGANIZATION_ID
AND GMD.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
AND GBH.BATCH_ID=GMD.BATCH_ID
AND GMD.ORGANIZATION_ID=101
AND GMD.LINE_TYPE IN ('-1','1')
and gbh.batch_status in ('2','3','4')
AND upper(MSI.DESCRIPTION) IN ('CLINKER','GYPSUM','SLAG (GBFS)','LIME STONE','FLYASH')
AND TRUNC(TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) BETWEEN TRUNC(:PL_DATE) AND TRUNC(:PH_DATE))
--AND (TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) BETWEEN (:PL_DATE) AND (:PH_DATE))
pivot(sum(qty)as qty for description in ('Clinker'as Clinker,'Gypsum'as Gypsum,'Lime Stone'as Lime,'Flyash'as Flyash,'Slag (GBFS)'as Slag))
GROUP BY trx_date,BATCH_NO,BATCH_ID
order by to_number(batch_no))X
WHERE GMD.BATCH_ID=X.BATCH_ID
AND GMD.LINE_TYPE='1')
pivot(sum(actual_qty)as p_qty,sum(clinker)as cln,sum(gypsum)as gyp,sum(lime)as lime,sum(flyash)as fly,sum(slag)as slag for prd in('Special'as Special,'Popular'as Popular, 'OPC' as OPC,'CEM3' as CEM3))
order by To_date(trx_date)



------------------------------------------------------------------------------------------------

select 
TO_CHAR(TRX_DATE,'DD-MON-RR')TRX_DATE,
NVL(SPECIAL_CLN,0)SPECIAL_CLN,
NVL(SPECIAL_GYP,0)SPECIAL_GYP,
NVL(SPECIAL_LIME,0)SPECIAL_LIME,
NVL(SPECIAL_FLY,0)SPECIAL_FLY,
NVL(SPECIAL_SLAG,0)SPECIAL_SLAG,
(NVL(SPECIAL_CLN,0)+NVL(SPECIAL_GYP,0)+NVL(SPECIAL_LIME,0)+NVL(SPECIAL_FLY,0)+NVL(SPECIAL_SLAG,0)) SPECIAL_INGR_TOT,
NVL(SPECIAL_P_QTY,0)SPECIAL_P_QTY,
NVL(POPULAR_CLN,0)POPULAR_CLN,
NVL(POPULAR_GYP,0)POPULAR_GYP,
NVL(POPULAR_LIME,0)POPULAR_LIME,
NVL(POPULAR_FLY,0)POPULAR_FLY,
NVL(POPULAR_SLAG,0)POPULAR_SLAG,
(NVL(POPULAR_CLN,0)+NVL(POPULAR_GYP,0)+NVL(POPULAR_LIME,0)+NVL(POPULAR_FLY,0)+NVL(POPULAR_SLAG,0)) POPULAR_INGR_TOT,
NVL(POPULAR_P_QTY,0)POPULAR_P_QTY,
NVL(OPC_CLN,0)OPC_CLN,
NVL(OPC_GYP,0)OPC_GYP,
NVL(OPC_LIME,0)OPC_LIME,
NVL(OPC_FLY,0)OPC_FLY,
NVL(OPC_SLAG,0)OPC_SLAG,
(NVL(OPC_CLN,0)+NVL(OPC_GYP,0)+NVL(OPC_LIME,0)+NVL(OPC_FLY,0)+NVL(OPC_SLAG,0)) OPC_INGR_TOT,
NVL(OPC_P_QTY,0)OPC_P_QTY,
(NVL(SPECIAL_CLN,0)+NVL(POPULAR_CLN,0)+NVL(OPC_CLN,0)) TOT_CLNK,
(NVL(SPECIAL_GYP,0)+NVL(POPULAR_GYP,0)+NVL(OPC_GYP,0)) TOT_GYP,
(NVL(SPECIAL_LIME,0)+NVL(POPULAR_LIME,0)+NVL(OPC_LIME,0)) TOT_LIME,
(NVL(SPECIAL_FLY,0)+NVL(POPULAR_FLY,0)+NVL(OPC_FLY,0)) TOT_FLY,
(NVL(SPECIAL_SLAG,0)+NVL(POPULAR_SLAG,0)+NVL(OPC_SLAG,0)) TOT_SLAG,
(NVL(SPECIAL_P_QTY,0)+NVL(POPULAR_P_QTY,0)+NVL(OPC_P_QTY,0)) TOT_PRODUCT
 from
(SELECT trx_date,
DECODE(GMD.INVENTORY_ITEM_ID,24408,'Special',24402,'Popular',206570,'OPC') prd,
GMD.ACTUAL_QTY,
CLINKER,
GYPSUM,
LIME,
FLYASH,
SLAG 
FROM apps.GME_MATERIAL_DETAILS GMD,
(select 
trx_date,
BATCH_NO,
BATCH_ID,
SUM(NVL(CLINKER_QTY,0))CLINKER,
SUM(NVL(GYPSUM_QTY,0))GYPSUM,
SUM(NVL(LIME_QTY,0))LIME,
SUM(NVL(FLYASH_QTY,0))FLYASH,
SUM(NVL(SLAG_QTY,0))SLAG from
(SELECT 
TRUNC(TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) trx_date,
GBH.BATCH_NO,
GMD.BATCH_ID,
GMD.INVENTORY_ITEM_ID,
(MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3)ITEM_CODE,
MSI.DESCRIPTION,
GMD.ACTUAL_QTY qty 
FROM apps.GME_BATCH_HEADER GBH,apps.GME_MATERIAL_DETAILS GMD,apps.MTL_SYSTEM_ITEMS_B MSI
WHERE GBH.ORGANIZATION_ID=GMD.ORGANIZATION_ID
AND GMD.ORGANIZATION_ID=MSI.ORGANIZATION_ID
AND GMD.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
AND GBH.BATCH_ID=GMD.BATCH_ID
AND GMD.ORGANIZATION_ID=101
AND GMD.LINE_TYPE IN ('-1','1')
and gbh.batch_status in ('2','3','4')
AND upper(MSI.DESCRIPTION) IN ('CLINKER','GYPSUM','SLAG (GBFS)','LIME STONE','FLYASH')
AND TRUNC(TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) BETWEEN TRUNC(:PL_DATE) AND TRUNC(:PH_DATE))
--AND (TO_DATE(GBH.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS')) BETWEEN (:PL_DATE) AND (:PH_DATE))
pivot(sum(qty)as qty for description in ('Clinker'as Clinker,'Gypsum'as Gypsum,'Lime Stone'as Lime,'Flyash'as Flyash,'Slag (GBFS)'as Slag))
GROUP BY trx_date,BATCH_NO,BATCH_ID
order by to_number(batch_no))X
WHERE GMD.BATCH_ID=X.BATCH_ID
AND GMD.LINE_TYPE='1')
pivot(sum(actual_qty)as p_qty,sum(clinker)as cln,sum(gypsum)as gyp,sum(lime)as lime,sum(flyash)as fly,sum(slag)as slag for prd in('Special'as Special,'Popular'as Popular, 'OPC' as OPC))
order by To_date(trx_date)