select * from
APPS.XXAKG_AR_CUSTOMER_SITE_V
WHERE ORG_ID = 85 
--AND SITE_USE_CODE = 'BILL_TO'
--AND PRIMARY_FLAG='Y'
--AND STATUS = 'A'
AND SHIP_TO_ORG_ID IN ('336139','306144')
AND CUSTOMER_ID IN ('704375')
--and customer_number in('25954','21615')
order by CUSTOMER_NUMBER


SELECT DISTINCT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.SHIP_FROM_ORG_ID,
OOL.SOLD_TO_ORG_ID,
OOL.PRICE_LIST_ID,
OOL.SHIP_TO_ORG_ID,
OOH.ORDERED_DATE,
OOL.UNIT_SELLING_PRICE,
OOL.UNIT_LIST_PRICE,
OOL.ATTRIBUTE10,
OOL.ATTRIBUTE11,
OOH.TP_ATTRIBUTE15
,OOH.*
--,OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
WHERE 1=1 
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOH.ORDER_NUMBER IN ('1663921','1662874','1660407','1660409','1654777')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOL.FLOW_STATUS_CODE='BOOKED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_SHIPMENT_PRIORITY_CODE
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'NOV-17'
--AND OOL.SHIPMENT_PRIORITY_CODE IN ('DO/MOU/13984')
--AND ORDER_TYPE_ID=1101
--AND OOH.SHIP_FROM_ORG_ID=1346
ORDER BY OOH.ORDERED_DATE DESC