/* Formatted on 5/26/2019 12:10:01 PM (QP5 v5.287) */
SELECT *
  FROM APPS.XXAKG_AR_DTL_CUSTOMER_LEDGER_V
 WHERE     1 = 1
       AND ( :P_ORG_ID IS NULL OR (ORG_ID = :P_ORG_ID))
       AND (   :P_CUSTOMER_NUMBER IS NULL
            OR (CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER))
       AND ( :P_DO_NUMBER IS NULL OR (DO_NUMBER = :P_DO_NUMBER))
       AND ( :P_VOUCHER IS NULL OR (VOUCHER = :P_VOUCHER))
--AND TO_CHAR (GL_DATE, 'MON-RR') ='AUG-18'
--AND TO_CHAR(GL_DATE,'DD-MON-RR')='31-DEC-18'
--AND TO_CHAR(GL_DATE,'RRRR')='2018'