SELECT 'Customer wise Rate' Rate_Type,
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
MSI.DESCRIPTION,
QPA.PRODUCT_UOM_CODE UOM,
--QR.NAME MODIFIER_NAME,
QPA.LIST_LINE_ID MODIFIER_LINE_NO,
QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
QQ.START_DATE_ACTIVE START_DATE,
QQ.END_DATE_ACTIVE END_DATE
FROM
APPS.QP_QUALIFIERS QQ
,APPS.QP_PRICING_ATTRIBUTES QPA
,APPS.XXAKG_AR_CUSTOMER_SITE_V A
,APPS.MTL_SYSTEM_ITEMS_B MSI
WHERE 1=1
AND MSI.ORGANIZATION_ID='91'
AND A.ORG_ID=85
AND QPA.PRODUCT_ATTR_VALUE=MSI.INVENTORY_ITEM_ID
AND A.CUSTOMER_ID=QQ.QUAL_ATTR_VALUE_FROM_NUMBER
AND QQ.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QQ.LIST_LINE_ID=QPA.LIST_LINE_ID
AND A.CUSTOMER_NUMBER=:CUSTOMER_NUMBER--  IN ('20482')
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBLK.0001')
AND QQ.END_DATE_ACTIVE IS NULL
AND A.SITE_USE_CODE = 'BILL_TO'
UNION ALL
SELECT 'Site wise Rate' Rate_Type,
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
MSI.DESCRIPTION,
QPA.PRODUCT_UOM_CODE UOM,
--QR.NAME MODIFIER_NAME,
QPA.LIST_LINE_ID MODIFIER_LINE_NO,
QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
QQ.START_DATE_ACTIVE START_DATE,
QQ.END_DATE_ACTIVE END_DATE
FROM
APPS.QP_QUALIFIERS QQ
,APPS.QP_PRICING_ATTRIBUTES QPA
,APPS.XXAKG_AR_CUSTOMER_SITE_V A
,APPS.MTL_SYSTEM_ITEMS_B MSI
WHERE 1=1
AND MSI.ORGANIZATION_ID='91'
AND A.ORG_ID=85
AND QPA.PRODUCT_ATTR_VALUE=MSI.INVENTORY_ITEM_ID
AND A.SHIP_TO_ORG_ID=QQ.QUAL_ATTR_VALUE_FROM_NUMBER
AND QQ.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QQ.LIST_LINE_ID=QPA.LIST_LINE_ID
AND A.CUSTOMER_NUMBER=:CUSTOMER_NUMBER--  IN ('20482')
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBAG.0003')
AND QQ.END_DATE_ACTIVE IS NULL
AND A.SITE_USE_CODE = 'SHIP_TO' 




------------------------------------------------------------------------------------------------

SELECT
*
FROM
APPS.XXAKG_QP_MODIFIER_DISCOUNT_V
WHERE 1=1
--AND MODIFIER_NAME IN ('SCIL Corporate Fixed Rate For OPC Cement',
--                                    'SCIL Corporate Fixed Rate For Special Cement', 
--                                    'SCIL Corporate Fixed Rate For Special Bulk Cement',
--                                    'SCIL Corporate Fixed Rate For Popular Cement',
--                                    'SCIL Corporate Fixed Rate For OPC Bulk Cement'
----                                    'SCIL Fixed Rate for General Customer'
----                                    'SCIL General Commission'
--                                       )
--AND PRODUCT_ATTRIBUTE_TYPE='Item Number'
AND DESC_ATTRIB_VALUE_FROM LIKE '%20482%'
AND QUALIFIER_ATTR_TYPE='Customer Name'
--AND MOD_LINE_NO='1282482'
--AND END_DATE IS NULL
--AND ADJUST_RATE IS NOT NULL
--AND PRODUCT_ATTR_VALUE='CMNT.PBAG.0001 | Popular Cement'
ORDER BY START_DATE DESC

------------------------------------------------------------------------------------------------
SELECT --'Customer wise Rate' Rate_Type,
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (A.CUSTOMER_ID) REGION,
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
MSI.DESCRIPTION,
--MSI.PRIMARY_UOM_CODE UOM_CODE,
QPA.PRODUCT_UOM_CODE UOM,
QLH.NAME MODIFIER_NAME,
QLL.LIST_LINE_NO MODIFIER_LINE,
--QPA.LIST_LINE_ID MODIFIER_LINE_NO,
QLL.START_DATE_ACTIVE MODIFIER_LINE_START,
QLL.END_DATE_ACTIVE MODIFIER_LINE_END,
QLL.OPERAND VALUE,
QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
QQ.START_DATE_ACTIVE START_DATE,
QQ.END_DATE_ACTIVE END_DATE
--,QLH.*
FROM
APPS.QP_QUALIFIERS QQ
,APPS.QP_PRICING_ATTRIBUTES QPA
,APPS.QP_LIST_LINES QLL
,APPS.QP_LIST_HEADERS_VL QLH
,APPS.XXAKG_AR_CUSTOMER_SITE_V A
,APPS.MTL_SYSTEM_ITEMS_B MSI
WHERE 1=1
AND QLL.LIST_HEADER_ID=QLH.LIST_HEADER_ID
AND QLL.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QLL.LIST_LINE_ID=QPA.LIST_LINE_ID
AND MSI.ORGANIZATION_ID='91'
AND A.ORG_ID=QLH.ORIG_ORG_ID
AND QLH.ORIG_ORG_ID=85
AND QPA.PRODUCT_ATTR_VALUE=MSI.INVENTORY_ITEM_ID
AND A.CUSTOMER_ID=QQ.QUAL_ATTR_VALUE_FROM_NUMBER
AND QQ.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QQ.LIST_LINE_ID=QPA.LIST_LINE_ID
--AND A.CUSTOMER_NUMBER IN ('33867')
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBLK.0001')
AND QQ.END_DATE_ACTIVE IS NULL
AND A.SITE_USE_CODE = 'BILL_TO'
--AND A.STATUS='I'
AND QLL.END_DATE_ACTIVE IS NULL
AND QLL.ARITHMETIC_OPERATOR='AMT'

------------------------------------------------------------------------------------------------

SELECT
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
MSI.DESCRIPTION,
QPA.PRODUCT_UOM_CODE UOM,
--QR.NAME MODIFIER_NAME,
QPA.LIST_LINE_ID MODIFIER_LINE_NO,
QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
QQ.START_DATE_ACTIVE START_DATE,
QQ.END_DATE_ACTIVE END_DATE
--,QPA.*
--,QQ.*
--A.*
--MSI.*
FROM
APPS.QP_QUALIFIERS QQ
,APPS.QP_PRICING_ATTRIBUTES QPA
,APPS.XXAKG_AR_CUSTOMER_SITE_V A
,APPS.MTL_SYSTEM_ITEMS_B MSI
WHERE 1=1
AND MSI.ORGANIZATION_ID='91'
AND A.ORG_ID=85
--AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
AND QPA.PRODUCT_ATTR_VALUE=MSI.INVENTORY_ITEM_ID
AND A.SHIP_TO_ORG_ID=QQ.QUAL_ATTR_VALUE_FROM_NUMBER
AND QQ.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QQ.LIST_LINE_ID=QPA.LIST_LINE_ID
--AND QQ.QUALIFIER_ATTR_VALUE='3626'--CUSTOME_ID
--AND A.CUSTOMER_NUMBER IN ('20482')
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBAG.0003')
--AND QPA.PRODUCT_ATTR_VALUE='24408'--ITEM_ID
AND QQ.END_DATE_ACTIVE IS NULL
--AND QQ.QUALIFIER_CONTEXT IN ('CUSTOMER')
--AND A.SITE_USE_CODE = 'BILL_TO'
AND A.SITE_USE_CODE = 'SHIP_TO' --
--AND A.SITE_USE_CODE IN ('BILL_TO','SHIP_TO')

------------------------------------****SITE WISE RATE***-----------------------------
SELECT 'Site wise Rate' Rate_Type,
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 ITEM_CODE,
MSI.DESCRIPTION,
--QPA.PRODUCT_UOM_CODE UOM,
QLL.OPERAND VALUE,
--QR.NAME MODIFIER_NAME,
--QPA.LIST_LINE_ID MODIFIER_LINE_NO,
QLL.LIST_LINE_NO MODIFIER_LINE_NO,
QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
QQ.START_DATE_ACTIVE START_DATE,
QQ.END_DATE_ACTIVE END_DATE
,A.REAILER||','||A.REAILER_ADDRESS ADDRESS
--,QPA.PRODUCT_ATTR_VALUE ITEM_ID
--,A.REAILER
--,A.ADDRESS1 ADDRESS
--,QLL.*
FROM
APPS.QP_QUALIFIERS QQ
,APPS.QP_PRICING_ATTRIBUTES QPA
,APPS.XXAKG_AR_CUSTOMER_SITE_V A
,APPS.MTL_SYSTEM_ITEMS_B MSI
,APPS.QP_LIST_LINES QLL
,APPS.QP_LIST_HEADERS_VL QLH
WHERE 1=1
AND QLL.LIST_HEADER_ID=QLH.LIST_HEADER_ID
AND QLL.LIST_LINE_ID=QQ.LIST_LINE_ID
AND QLL.LIST_HEADER_ID=QQ.LIST_HEADER_ID
AND MSI.ORGANIZATION_ID='91'
AND A.ORG_ID=85
AND TO_CHAR(QPA.PRODUCT_ATTR_VALUE)=TO_CHAR(MSI.INVENTORY_ITEM_ID)
AND A.SHIP_TO_ORG_ID=QQ.QUAL_ATTR_VALUE_FROM_NUMBER
AND QQ.LIST_HEADER_ID=QPA.LIST_HEADER_ID
AND QQ.LIST_LINE_ID=QPA.LIST_LINE_ID
--AND A.CUSTOMER_NUMBER IN ('20482')
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBAG.0003')
AND QQ.END_DATE_ACTIVE IS NULL
AND A.SITE_USE_CODE = 'SHIP_TO' 





