SELECT
ACSV.CUSTOMER_NUMBER,
ACSV.CUSTOMER_NAME,
PRICE_LOCATION_CODE PRICE_LOCATION,
--PRICE_LOCATION_NAME,
TO_CHAR(PL.START_DATE_ACTIVE,'DD-MON-RR') START_DATE,
PL.END_DATE_ACTIVE END_DATE
--,PL.*
--,ACSV.*
FROM
APPS.XXAKG_DIST_PRICE_LOCATIONS_ALL PL
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV
WHERE 1=1
AND PL.CUSTOMER_ID=ACSV.CUSTOMER_ID
AND PL.END_DATE_ACTIVE IS NULL
AND ACSV.SITE_USE_CODE='BILL_TO'
AND ACSV.STATUS='A'
AND ACSV.PRIMARY_FLAG='Y'
--AND ACSV.ORG_ID=83
--AND ACSV.CUSTOMER_NUMBER=:P_CUSTOMER_NUMBER--'21615'