SELECT
QPM_DISC.LIST_LINE_NO,
QPM_DISC.ADJUSTED_AMOUNT,
QPM_DISC.OPERAND_PER_PQTY,
QPM_DISC.ADJUSTED_AMOUNT_PER_PQTY, 
QPM_DISC.RANGE_BREAK_QUANTITY,
QPM_DISC.ARITHMETIC_OPERATOR,
QPM_DISC.LIST_LINE_TYPE_CODE,
QPM_DISC.PRICE_BREAK_TYPE_CODE,
QPM_DISC.MODIFIER_LEVEL_CODE,
QPM_DISC.ACCRUAL_FLAG
FROM
APPS.OE_PRICE_ADJUSTMENTS QPM_DISC
WHERE 1=1
--JOINED BY  HEADER_ID, LINE_ID, LIST_HEADER_ID, LIST_LINE_ID, LIST_LINE_NO, 
--CONDITIONED BY LIST_LINE_TYPE_CODE, PRICE_BREAK_TYPE_CODE, ARITHMETIC_OPERATOR, MODIFIER_LEVEL_CODE, 
--FIND OUT OPERAND, ADJUSTED_AMOUNT, OPERAND_PER_PQTY, ADJUSTED_AMOUNT_PER_PQTY, RANGE_BREAK_QUANTITY,
--FLAG_OPEN ACCRUAL_FLAG, 
--AND QPM_DISC.LIST_LINE_TYPE_CODE IN ('DIS','PRG')
AND QPM_DISC.LIST_LINE_NO='837678'


SELECT
DECODE(HCA.SALES_CHANNEL_CODE, '-1', 'Unsigned'
                                                      , HCA.SALES_CHANNEL_CODE  ) "sales_channel_code_decode"
FROM
APPS.HZ_CUST_ACCOUNTS HCA
WHERE 1=1
AND HCA.SALES_CHANNEL_CODE='-1'-- IS NOT NULL--='Unassigned'ct

select
LOOKUP_CODE, meaning
from
apps.fnd_lookup_values
where 1=1
and lookup_type='PRICE_BREAK_TYPE_CODE'


select
*
from
apps.qp_list_headers_tl qpl
where 1=1
AND qpl.name in ('CER General Commission','CER Year End Commission','CER Broken Commission','CER Viola Commission','CER WC & WT Commission for B Grade')



SELECT
QPM_DISC.LIST_LINE_NO,
QPM_DISC.ADJUSTED_AMOUNT,
QPM_DISC.OPERAND_PER_PQTY,
QPM_DISC.ADJUSTED_AMOUNT_PER_PQTY, 
QPM_DISC.RANGE_BREAK_QUANTITY,
QPM_DISC.ARITHMETIC_OPERATOR,
QPM_DISC.LIST_LINE_TYPE_CODE,
QPM_DISC.PRICE_BREAK_TYPE_CODE,
QPM_DISC.MODIFIER_LEVEL_CODE,
QPM_DISC.ACCRUAL_FLAG
FROM
APPS.OE_PRICE_ADJUSTMENTS QPM_DISC
,APPS.QP_LIST_HEADERS_TL QPL
WHERE 1=1
AND QPL.LIST_HEADER_ID=QPM_DISC.LIST_HEADER_ID
--AND QPL.NAME='CER WC & WT Commission for B Grade'
--AND QPM_DISC.ARITHMETIC_OPERATOR='%'
AND QPM_DISC.LIST_LINE_NO='837678'