SELECT
*
FROM
APPS.XXAKG_DIST_PRICE_LOCATIONS_ALL


--------------------------
SELECT
FFV.FLEX_VALUE
--,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_Cement_Item_Price_Location'
--AND FFV.FLEX_VALUE='Dhaka'


-----------------------------------------------------------------------------

SELECT
*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
WHERE 1=1
AND FLEX_VALUE_SET_NAME='AKG_Cement_Item_Price_Location'


SELECT
*
FROM
APPS.FND_FLEX_VALUES
WHERE 1=1
AND FLEX_VALUE_SET_ID='1015022'
