SELECT 
--MOH.*
--APS.*
--APA.*
MOH.MOV_ORDER_NO,
MOH.WAREHOUSE_ORG_CODE,
MOH.FINAL_DESTINATION,
APS.VENDOR_NAME,
MOH.HIRE_RATE_AP,
APA.INVOICE_AMOUNT,
--APA.DOC_SEQUENCE_VALUE,
TO_CHAR (APA.CREATION_DATE, 'DD-MON-YYYY') INVOICE_DATE,
TO_CHAR (APA.GL_DATE, 'DD-MON-YYYY') GL_DATE,
APA.PAYMENT_METHOD_CODE
FROM
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.AP_INVOICES_ALL APA,
APPS.AP_SUPPLIERS APS
WHERE 1=1
AND MOH.MOV_ORDER_NO=APA.INVOICE_NUM
AND APA.VENDOR_ID=APS.VENDOR_ID
AND MOH.MOV_ORDER_NO='MO/SCOU/002346'
AND MOH.TRANSPORT_MODE='Rental Truck'
AND MOH.MOV_ORDER_TYPE='RELATED'
AND MOH.ORG_ID=85
