SELECT 
    BATCH_NO,
    GEH.ORGANIZATION_ID, 
    COUNT(*)
FROM 
    GME.GME_BATCH_HEADER BH, 
    GMF.GMF_XLA_EXTRACT_HEADERS GEH
WHERE 
    GEH.SOURCE_DOCUMENT_ID=BH.BATCH_ID 
    AND BH.ORGANIZATION_ID=GEH.ORGANIZATION_ID 
    AND GEH.LEDGER_ID=2025
    AND TRUNC(BH.PLAN_START_DATE) BETWEEN '01-JUL-2013' AND '31-JUL-2013' 
    AND BH.BATCH_CLOSE_DATE IS NULL  
    AND BH.BATCH_STATUS<>-1
GROUP BY 
    BH.BATCH_NO,GEH.ORGANIZATION_ID