SELECT MMT.SOURCE_LINE_ID
      ,MMT.TRANSACTION_DATE
      ,MMT.PARENT_TRANSACTION_ID
      ,MTT.TRANSACTION_TYPE_NAME
      ,CCE.EVENT_TYPE
      ,DECODE(CCE.COSTED,'N','Not Processed','Processed') EVENT_STATUS
      ,DECODE(CCE.COSTED,'N','Not Generated','Generated') ACCOUNT_GENERATION
      ,GCC.CONCATENATED_SEGMENTS ACCOUNT_INFO 
      ,MTA.BASE_TRANSACTION_VALUE
      ,OET.NAME
      ,OEH.ORDER_NUMBER
      --,CCE.*
FROM   INV.MTL_TRANSACTION_ACCOUNTS MTA
      ,INV.MTL_MATERIAL_TRANSACTIONS MMT
      ,INV.MTL_TRANSACTION_TYPES MTT
      ,APPS.GL_CODE_COMBINATIONS_KFV GCC
      ,APPS.CST_COGS_EVENTS CCE
      ,APPS.OE_ORDER_LINES_ALL OEL
      ,APPS.OE_ORDER_HEADERS_ALL OEH
      ,APPS.OE_TRANSACTION_TYPES_TL OET
WHERE CCE.COGS_OM_LINE_ID        =OEL.LINE_ID
--AND   CCE.EVENT_TYPE IN (1,2)
AND   OEL.HEADER_ID              =OEH.HEADER_ID
AND   OEH.ORDER_TYPE_ID          =OET.TRANSACTION_TYPE_ID
AND   MMT.TRANSACTION_ID         =CCE.MMT_TRANSACTION_ID
AND   MMT.TRANSACTION_TYPE_ID    = MTT.TRANSACTION_TYPE_ID
AND   MTA.TRANSACTION_ID(+)      = MMT.TRANSACTION_ID
AND   GCC.CODE_COMBINATION_ID(+) = MTA.REFERENCE_ACCOUNT
--AND   OEH.ORDER_NUMBER           = :P_ORDER_NUMBER
AND   OEL.SHIPMENT_PRIORITY_CODE = :DO_NUMBER
ORDER BY ORDER_NUMBER;

--------------------------------------------------------------------------------
SELECT
*
FROM
APPS.FND_LOOKUP_VALUES
WHERE 1=1
--AND LOOKUP_CODE='1'
AND LOOKUP_TYPE LIKE 'MTL_CCEOI_STATUS_FLAG' -- '%CST_PAC_PROCESS_STATUS%'
--AND UPPER(MEANING) LIKE UPPER('%Processed%')
--AND UPPER(DESCRIPTION) LIKE UPPER('%Processed%')