select 
--    *
    ORGANIZATION_ID,
    ORGANIZATION_CODE,
    ORGANIZATION_NAME,
    OPERATING_UNIT,
    SET_OF_BOOKS_ID,
    LEGAL_ENTITY
from APPS.ORG_ORGANIZATION_DEFINITIONS
where
--    SET_OF_BOOKS_ID=2025
--    AND 
--    ORGANIZATION_ID=425
--    AND 
    ORGANIZATION_CODE='MRB'
order by
        ORGANIZATION_ID
        