SELECT *
FROM APPS.MTL_TXN_REQUEST_LINES_V
--APPS.MTL_TXN_REQUEST_LINES_V
--APPS.MTL_TXN_REQUEST_HEADERS_V 
WHERE organization_id=101
AND trunc(CREATION_DATE) BETWEEN '31-JAN-2015' AND '10-MAR-2015'
--AND USE_OF_AREA = 'Packer Common'
AND TRANSACTION_TYPE_NAME = 'Material Issue to Production Batch'