    SELECT
    DOH.CUSTOMER_NUMBER,
    DOH.CUSTOMER_NAME,
    OOH.ORDER_NUMBER,
    TO_CHAR(OOH.ORDERED_DATE) ORDER_DATE,
    OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
    TO_CHAR(DOH.DO_DATE) DO_DATE,
    (SELECT MSI.DESCRIPTION FROM APPS.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID) ITEM_DESCRIPTION,
--    WSHD.ITEM_DESCRIPTION,
    TO_CHAR(OOL.SHIPPED_QUANTITY) SHIPPED_QUANTITY,
    OOL.UNIT_SELLING_PRICE,
    OOL.ORDER_QUANTITY_UOM UOM,
    TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE) ACTUAL_SHIPMENT_DATE
    FROM APPS.OE_ORDER_HEADERS_ALL OOH,
    APPS.OE_ORDER_LINES_ALL OOL, 
    APPS.XXAKG_DEL_ORD_HDR DOH
--      ,APPS.WSH_DELIVERABLES_V WSHD
      WHERE    1=1
      AND OOH.HEADER_ID=OOL.HEADER_ID
      AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
--      AND OOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
--      AND OOL.LINE_ID = WSHD.SOURCE_LINE_ID
      AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
      AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')
--      AND DOH.DO_NUMBER='DO/MOU/10732'
      AND     (:P_ORG_ID IS NULL OR (DOH.ORG_ID=:P_ORG_ID))
      AND TRUNC(OOL.ACTUAL_SHIPMENT_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(OOL.ACTUAL_SHIPMENT_DATE)) AND NVL(:P_DATE_TO,TRUNC(OOL.ACTUAL_SHIPMENT_DATE))