/* Formatted on 7/16/2019 12:42:52 PM (QP5 v5.287) */
SELECT MR.DEMAND_SOURCE_HEADER_ID ORDER_HEADER_ID,
       MR.DEMAND_SOURCE_LINE_ID ORDER_LINE_ID,
       MR.SUBINVENTORY_CODE,
       MR.INVENTORY_ITEM_ID,
       MR.LOT_NUMBER,
       MR.RESERVATION_QUANTITY,
       MR.PRIMARY_RESERVATION_QUANTITY,
       MR.RESERVATION_UOM_CODE,
       MR.SECONDARY_UOM_CODE
  FROM APPS.MTL_RESERVATIONS MR
 WHERE 1 = 1 AND MR.ORGANIZATION_ID = 606
--AND MR.INVENTORY_ITEM_ID=279176
--AND MR.DEMAND_SOURCE_HEADER_ID=:P_DEMAND_SOURCE_HEADER_ID
;

SELECT MOQ.SUBINVENTORY_CODE,
       MOQ.ORGANIZATION_ID,
       MOQ.INVENTORY_ITEM_ID,
       MOQ.PRIMARY_TRANSACTION_QUANTITY,
       MRS.PRIMARY_RESERVATION_QUANTITY RESERVE_QTY
  FROM APPS.MTL_ONHAND_QUANTITIES_DETAIL MOQ, APPS.MTL_RESERVATIONS MRS
 WHERE     MOQ.INVENTORY_ITEM_ID = MRS.INVENTORY_ITEM_ID(+)
       AND MOQ.ORGANIZATION_ID = MRS.ORGANIZATION_ID(+)
       AND MOQ.SUBINVENTORY_CODE = MRS.SUBINVENTORY_CODE(+)
       --AND moq.inventory_item_id = 279420
       AND MOQ.ORGANIZATION_ID = 606;