------------------------------------------------------------------------------------------------

SELECT
TDL.TO_NUMBER,
--TDH.TO_STATUS,
TMH.MOV_ORDER_NO,
--TMH.MOV_ORDER_STATUS,
TDL.ITEM_NUMBER,
--TDL.ITEM_DESCRIPTION,
--TDL.UOM_CODE,
TMH.FROM_INV,
TDL.TO_INV,
TMH.FINAL_DESTINATION,
TMH.TRANSPORT_MODE,
TMH.VEHICLE_NO
--TMH.INITIAL_GATE_IN,
--TMH.GATE_OUT,
--TMH.GATE_IN
,TO_CHAR(TDH.TO_DATE) To_DATE
,TO_CHAR(TMH.MOV_ORDER_DATE) MTO_DATE
,TDL.FROM_SUBINV
,TDL.TO_SUBINV
,TDL.QUANTITY
,TDH.TO_STATUS
,TMH.MOV_ORDER_STATUS
,LOT.LOT_NUMBER
,LOT.LOT_QUANTITY
--,TDL.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH,
APPS.XXAKG_TO_MO_DTL TMD,
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
,APPS.XXAKG_TO_DO_LOT LOT
WHERE 1=1
AND TMH.ORG_ID=605
AND TMD.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
--AND TDH.TO_STATUS='GENERATED'
--AND TMH.MOV_ORDER_STATUS='CONFIRMED'
--AND TMH.MOV_ORDER_NO='MTO/MOU/000004'
--AND TDL.TO_NUMBER='TO/MOU/000005'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND TMH.FROM_INV='SCI'
--AND TDL.TO_INV='G10'
AND LOT.TO_LINE_ID=TDL.TO_LINE_ID
AND LOT.INVENTORY_ITEM_ID=TDL.INVENTORY_ITEM_ID


-----------------------------TO_LOT---------------------------------------------------------

SELECT
*
FROM
APPS.XXAKG_TO_DO_LOT LOT


------------------------------------------------------------------------------------------------

SELECT
LOT.LOT_NUMBER,
LOT.LOT_QUANTITY
FROM
XXAKG.XXAKG_TO_DO_LINES TDL
,APPS.XXAKG_TO_DO_LOT LOT
WHERE 1=1
AND TDL.TO_NUMBER='TO/MOU/000003'
AND LOT.TO_LINE_ID=TDL.TO_LINE_ID
AND LOT.INVENTORY_ITEM_ID=TDL.INVENTORY_ITEM_ID

