SELECT
OOL.HEADER_ID ORDER_LINE_HEADER_ID,
OOH.HEADER_ID,
OOL.LINE_ID,
MR.DEMAND_SOURCE_HEADER_ID ORDER_HEADER_ID,
MR.DEMAND_SOURCE_LINE_ID ORDER_LINE_ID,
OOH.ORDER_NUMBER,
OOL.ORDERED_QUANTITY,
OOL.SHIPPED_QUANTITY,
OOL.INVOICED_QUANTITY,
OOL.CANCELLED_QUANTITY,
OOL.ORDERED_ITEM,
OOL.SHIPMENT_PRIORITY_CODE,
OOL.SHIP_FROM_ORG_ID,
MR.SUBINVENTORY_CODE,
MR.INVENTORY_ITEM_ID,
MR.LOT_NUMBER,
MR.RESERVATION_QUANTITY,
MR.PRIMARY_RESERVATION_QUANTITY,
MR.RESERVATION_UOM_CODE,
MR.SECONDARY_UOM_CODE
FROM
APPS.MTL_RESERVATIONS MR,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND MR.DEMAND_SOURCE_HEADER_ID=OOH.HEADER_ID
AND MR.DEMAND_SOURCE_LINE_ID=OOL.LINE_ID
AND MR.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID
--AND OOH.HEADER_ID=OOL.HEADER_ID
----AND MR.ORGANIZATION_ID=606
--AND MR.INVENTORY_ITEM_ID=279176
--AND MR.DEMAND_SOURCE_HEADER_ID=:P_DEMAND_SOURCE_HEADER_ID




             