select 
    OWNER_PHONE_NO,
    MANAGER_PHONE_NO,
    OFFICER_PHONE_NO,
    BOOKED_DATE, 
    ORDER_NUMBER, 
    CUSTOMER_NUMBER,CUSTOMER_NAME,
    'Dear Customer, Your requested Order is accepted. Order Number: '||ORDER_NUMBER||' Dated:'||trunc(BOOKED_DATE)  ||' Product: '||LISTAGG(ITEM_DESCRIPTION||' '||QUANTITY||' '||UOM_CODE, ', ') WITHIN GROUP (ORDER BY ITEM_CODE,UOM_CODE)||' Shah Cement Ind. Ltd.' sms 
    FROM ( 
    SELECT ORG_ID,OPERATING_UNIT,REGION,CUSTOMER_NUMBER,
    CUSTOMER_NAME,ORDER_NUMBER  ,ORDERED_DATE,BOOKED_DATE,
    OFFICER_PHONE_NO,OWNER_PHONE_NO,MANAGER_PHONE_NO ,
    SUM(ORDERED_QUANTITY) QUANTITY,ITEM_CODE,ITEM_DESCRIPTION,UOM_CODE 
    FROM APPS.XXAKG_SCIL_ORDER_SMS_V V 
    WHERE ORDER_STATUS='BOOKED' 
    AND ITEM_CODE NOT  IN ('EBAG.SBAG.0001','EBAG.SBAG.0002','EBAG.PBAG.0001','EBAG.PBAG.0002','EBAG.OBAG.0001','EBAG.CBAG.0001','EBAG.JBAG.0001')  
    AND  trunc(BOOKED_DATE) = '27-AUG-2019' 
    --AND CUSTOMER_NUMBER IN (20072, 20079, 20076, 20075, 20058) 
    GROUP BY ORG_ID,  
    OPERATING_UNIT,REGION,CUSTOMER_NUMBER,CUSTOMER_NAME ,
    ORDER_NUMBER,ORDERED_DATE,BOOKED_DATE,ITEM_CODE,
    ITEM_DESCRIPTION ,UOM_CODE,OFFICER_PHONE_NO, OWNER_PHONE_NO, MANAGER_PHONE_NO ) ORD 
    WHERE 1=1 GROUP BY ORG_ID,OPERATING_UNIT,REGION,CUSTOMER_NUMBER,CUSTOMER_NAME  ,ORDER_NUMBER,
    ORDERED_DATE,BOOKED_DATE,OFFICER_PHONE_NO, OWNER_PHONE_NO,MANAGER_PHONE_NO      
