SELECT 
HOU.NAME ORGANIZATION
,DBM.REGION_NAME
,CUST.CUSTOMER_NUMBER CUSTOMER_NO
,CUST.CUSTOMER_NAME "CUSTOMER NAME"
,CREDIT_LIMIT
,ADDITIONAL_CREDIT_LIMIT
,SPECIAL_CREDIT_LIMIT
,CUST.ADDRESS1 ADDRESS
,CUST.STATUS
--,CUST.SITE_USE_CODE
--,CUST.* 
from
APPS.XXAKG_AR_CUSTOMER_SITE_V CUST
,APPS.HR_OPERATING_UNITS HOU
,APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1 
and CUST.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
AND HOU.ORGANIZATION_ID=CUST.ORG_ID
AND CUST.ORG_ID = 85 
AND SITE_USE_CODE = 'BILL_TO'
--AND SITE_USE_CODE = 'SHIP_TO'
AND PRIMARY_FLAG='Y'
--AND STATUS = 'A'
and DBM.customer_number in('20482')
--and DBM.REGION_NAME NOT IN ('Corporate North','Corporate South','Institutional','MES')
and DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')
order by DBM.CUSTOMER_NUMBER