SELECT distinct DBM.REGION_NAME,to_char(CUST_ACCT.CREATION_DATE,'DD-MON-YYYY')CREATION_DATE,
        CUST_ACCT.CUST_ACCOUNT_ID CUSTOMER_ID,
          CUST_ACCT.ACCOUNT_NUMBER ,
          PARTY.PARTY_NAME CUSTOMER_NAME,
          CUST_ACCT.ACCOUNT_NAME,
          PS.PARTY_SITE_NUMBER RETAILER_NUMBER,
           PARTY.ADDRESS1||PARTY.ADDRESS2||PARTY.ADDRESS3||PARTY.ADDRESS4||PARTY.CITY||PARTY.COUNTRY ADDRESS,CUST_ACCT.STATUS
 from APPS.HZ_CUST_ACCOUNTS CUST_ACCT,
 APPS.HZ_CUST_ACCT_SITES_ALL ACCT_USE,
 APPS.HZ_CUST_SITE_USES_ALL CSUA,
 apps.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
 APPS.HZ_PARTIES PARTY,
 APPS.HZ_PARTY_SITES PS
Where CUST_ACCT.ACCOUNT_NUMBER=DBM.CUSTOMER_NUMBER(+)
AND CSUA.CUST_ACCT_SITE_ID=ACCT_USE.CUST_ACCT_SITE_ID
AND CUST_ACCT.CUST_ACCOUNT_ID = ACCT_USE.CUST_ACCOUNT_ID
and  PARTY.PARTY_ID=CUST_ACCT.PARTY_ID
AND ACCT_USE.PARTY_SITE_ID = PS.PARTY_SITE_ID
AND PS.IDENTIFYING_ADDRESS_FLAG='Y'
AND DBM.REGION_NAME='Institutional'
AND CSUA.SITE_USE_CODE = 'BILL_TO'
--AND CUST_ACCT.PRIMARY_FLAG='Y'
--AND CUST_ACCT.STATUS = 'A'
AND CUST_ACCT.CREATION_DATE BETWEEN '01-JAN-13' AND '01-MAR-18'
and DBM.ORG_ID=85
order by 3


SELECT
*
FROM
APPS.HZ_CUST_ACCOUNTS