SELECT 
HOU.NAME ORGANIZATION,
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (A.CUSTOMER_ID) REGION,
A.CUSTOMER_ID,
A.CUSTOMER_NUMBER,
A.CUSTOMER_NAME,
HCA.ACCOUNT_NAME "Account Description",
A.ADDRESS1 "Address Line 1",
A.ADDRESS2 "Address Line 2",
A.ADDRESS3 "Address Line 3",
A.ADDRESS4 "Address Line 4",
A.LOCATION "Ship/Bill to Location",
A.SITE_USE_CODE,
A.STATUS,
A.SITE_USE_STATUS,
A.ACCT_USE_STATUS,
A.PRIMARY_FLAG,
A.REAILER RETAILER,
A.PARTY_SITE_NUMBER
,A.* 
FROM
APPS.XXAKG_AR_CUSTOMER_SITE_V A,
APPS.HZ_CUST_ACCOUNTS HCA,
APPS.HR_OPERATING_UNITS HOU
WHERE 1=1
AND (:P_ORG_ID IS NULL OR A.ORG_ID = :P_ORG_ID)
AND HOU.ORGANIZATION_ID=A.ORG_ID
AND A.CUSTOMER_ID=HCA.CUST_ACCOUNT_ID
--AND SITE_USE_CODE = 'BILL_TO'
--AND SITE_USE_CODE = 'SHIP_TO'
--AND A.SHIP_TO_ORG_ID='34777'
--AND PRIMARY_FLAG='Y'
--AND STATUS = 'A'
AND     (:P_CUSTOMER_NUMBER IS NULL OR (A.CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER))
--AND CUSTOMER_NUMBER IN ('187056')
AND     (:P_CUST_NAME IS NULL OR (UPPER(A.CUSTOMER_NAME) LIKE UPPER('%'||:P_CUST_NAME||'%') ))
AND     (:P_REAILER_NAME IS NULL OR (UPPER(A.REAILER) LIKE UPPER('%'||:P_REAILER_NAME||'%') ))
--AND A.CUSTOMER_NAME LIKE '%International%Institute%of%Maritime%Technology%'
ORDER BY 2 DESC

-----------------------------****Customer****-------------------------------------------
SELECT 
HOU.NAME ORGANIZATION,
NVL(DBM.REGION_NAME,'Unspecified') REGION,
CA.ACCOUNT_NUMBER,
CA.CUST_ACCOUNT_ID CUSTOMER_ID,
HP.PARTY_NAME CUSTOMER_NAME,
CA.STATUS ACCOUNT_STATUS,
CSUA.STATUS CUSTOMER_SITE_STATUS,
CA.CREATION_DATE "ACCOUNT CREATION DATE",
CASA.CREATION_DATE "ACCOUNT SITE CREATION DATE",
CSUA.SITE_USE_CODE,
CSUA.SITE_USE_ID PARTY_SITE_NUMBER,
CSUA.LOCATION
,HP.CATEGORY_CODE
--,CA.* 
--,CASA.*
--,CSUA.*
--,HOU.*
--,HP.*
--,HPS.*
--,LOC.*
FROM
APPS.HZ_CUST_ACCOUNTS CA,
APPS.HZ_CUST_SITE_USES_ALL CSUA,
APPS.HZ_CUST_ACCT_SITES_ALL CASA
,APPS.HR_OPERATING_UNITS HOU
,APPS.HZ_PARTIES HP
--,APPS.HZ_PARTY_SITES HPS
--,APPS.HZ_LOCATIONS LOC
,APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1 
AND (:P_ORG_ID IS NULL OR CASA.ORG_ID = :P_ORG_ID)
AND DBM.CUSTOMER_NUMBER(+)=CA.ACCOUNT_NUMBER
AND CSUA.CUST_ACCT_SITE_ID=CASA.CUST_ACCT_SITE_ID
AND CA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID
AND HOU.ORGANIZATION_ID=CASA.ORG_ID
--AND CA.STATUS='A'
--AND CSUA.STATUS='A'
AND HP.PARTY_ID=CA.PARTY_ID
--AND HPS.PARTY_ID = HP.PARTY_ID
--AND HPS.LOCATION_ID = LOC.LOCATION_ID
--AND HP.STATUS='A'
--AND HPS.STATUS='A'
--AND HPS.IDENTIFYING_ADDRESS_FLAG='Y'
AND SITE_USE_CODE = 'BILL_TO'
--AND CSUA.BILL_TO_SITE_USE_ID='37644'
--AND CSUA.SITE_USE_ID='34777'
--AND SITE_USE_CODE = 'SHIP_TO'
--AND PRIMARY_FLAG='Y'
--AND STATUS = 'A'
AND     (:P_CUSTOMER_NUMBER IS NULL OR (CA.ACCOUNT_NUMBER = :P_CUSTOMER_NUMBER))
AND     (:P_CUST_NAME IS NULL OR (UPPER(HP.PARTY_NAME) LIKE UPPER('%'||:P_CUST_NAME||'%') ))
--AND UPPER(CA.ACCOUNT_NAME) LIKE UPPER('%'||:P_CUST_NAME||'%') 
--AND ACCOUNT_NUMBER IN ('20072')
--AND DBM.REGION_NAME IN ('Gazipur','Dhaka South','Mymensingh','Rajshahi','Sylhet','Rangpur','Prime Seller','Comilla','Faridpur','Dhaka North','Narayangonj','Khulna','Barisal','Tangail','Bogra','Noakhali','Chittagong')
--AND DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')
--AND DBM.REGION_NAME IS NULL
--AND HP.CATEGORY_CODE IS NULL
ORDER BY ACCOUNT_NUMBER DESC

---------------------------------------***Region***---------------------------------------

SELECT
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (RBC.CUSTOMER_ID) REGION
,RBC.*
FROM
APPS.XXAKG_REGION_BLOCK_CELL_V RBC
WHERE 1=1
AND CUSTOMER_NUMBER='68068'
--AND REGION_NAME='Inter Group'
--AND APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (RBC.CUSTOMER_ID)!=REGION_NAME

SELECT
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (AR_CUST.CUSTOMER_ID) REGION
,APPS.XXAKG_AR_PKG.GET_DIVISION_FROM_CUST_ID (AR_CUST.CUSTOMER_ID) DIVISION
,APPS.XXAKG_AR_PKG.GET_AREA_FROM_CUST_ID (AR_CUST.CUSTOMER_ID) AREA
,APPS.XXAKG_AR_PKG.GET_TERRITORY_FROM_CUST_ID (AR_CUST.CUSTOMER_ID) TERRITORY
,AR_CUST.*
FROM
APPS.XXAKG_AR_CUSTOMER_SITE_V AR_CUST
WHERE 1=1
--AND ORG_ID = 83
AND CUSTOMER_NUMBER='68068'

SELECT
*
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M
WHERE 1=1
AND ORG_ID=85
--AND CUSTOMER_NUMBER='34985'
--AND REGION_NAME='No Region'


SELECT  --DISTINCT org_id
*
FROM
APPS.XXAKG_ONT_REGION_BLOCK_CELL_M
WHERE 1=1
and org_id='85'
--AND REGION_NAME like '%Cox%Bazar'
--AND BLOCK_NAME='B.Baria'
AND CELL_NAME='Abdullahpur'

------------------------------------------Region_Block_Cell---------------------------------
SELECT
R.ORG_ID
,R.ORGANIZATION_NAME
,R.CUSTOMER_NUMBER
,R.CUSTOMER_NAME
,R.REGION_NAME
,B.BLOCK_NAME
,C.CELL_NAME
,C.SHIP_SITE_LOCATION_NAME RETAILER
--,R.*
--,B.*
--,C.*
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M R
,APPS.XXAKG_DISTRIBUTOR_BLOCK_D B
,APPS.XXAKG_RETAILERS_CELL_D C
WHERE 1=1
AND R.ORG_ID=83
AND R.CUSTOMER_NUMBER='134073'
AND R.HEADER_ID=B.HEADER_ID
AND B.LINE_ID=C.LINE_ID

------------------------------------------Region----------------------------------------------
SELECT
*
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_M

------------------------------------------Block------------------------------------------------
SELECT
*
FROM
APPS.XXAKG_DISTRIBUTOR_BLOCK_D

------------------------------------------Cell--------------------------------------------------
SELECT
*
FROM
APPS.XXAKG_RETAILERS_CELL_D

--------------------------------------------------------------------------------
SELECT
*
FROM
APPS.AR_CUSTOMERS