SELECT 
DBM.REGION_NAME,
ACSV.CUSTOMER_NUMBER,
ACSV.CUSTOMER_NAME,
ACSV.ADDRESS1 ADDRESS,
acsv.LOCATION,
acsv.LOCATION_ADDRESS,
acsv.REAILER,
acsv.REAILER_ADDRESS,
to_char(DBM.CREATION_DATE,'DD-MON-YYYY') CREATION_DATE--,
--acsv.PARTY_SITE_NUMBER,
--acsv.SHIP_TO_ORG_ID,
--acsv.status,
--acsv.site_use_status
FROM 
APPS.XXAKG_RETAILERS_CELL_D RCD, 
APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV ,
apps.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE ACSV.ORG_ID=85
AND RCD.CUSTOMER_NUMBER(+)=ACSV.CUSTOMER_NUMBER
and acsv.ship_to_org_id=rcd.ship_site_location(+)
and acsv.site_use_code='SHIP_TO'
AND RCD.SHIP_SITE_LOCATION_NAME IS NULL
and ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
--and DBM.CUSTOMER_NUMBER='32784'
and acsv.SITE_USE_STATUS!='I'
and acsv.STATUS!='I'
--and TRUNC (DBM.CREATION_DATE) between '01-AUG-2011' and '18-NOV-2017'
--and TRUNC (DBM.CREATION_DATE)<=SYSDATE
--AND TO_CHAR (DBM.CREATION_DATE, 'MON-RR') = 'AUG-17'
--and DBM.REGION_NAME NOT IN ('Corporate North','Corporate South','Institutional','MES')
--and DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')