SELECT
CA.ACCOUNT_NUMBER CUSTOMER_NUMBER,
PARTY.PARTY_NAME CUSTOMER_NAME,
CA.STATUS ACCOUNT_STATUS,
NVL(DBM.REGION_NAME,'Unspecified') REGION_NAME,
PARTY.CATEGORY_CODE CUSTOMER_CATEGORY,
DECODE (CA.SALES_CHANNEL_CODE, 'DHAKA', CA.SALES_CHANNEL_CODE,
                                        '-1', 'Unassigned',
                                        NULL,' ') "SALES_CHANNEL"
--,DECODE (party.category_code, 'DISTRIBUTOR', 8, 'DEALER', 8, 'PRIME SELLER', DECODE (ca.sales_channel_code, 'DHAKA', 6, '-1',7,NULL),NULL) commission_rate
    ,CASE 
        WHEN DBM.REGION_NAME IN ('Gazipur','Dhaka South','Mymensingh','Rajshahi','Sylhet','Rangpur','Prime Seller','Comilla','Faridpur','Dhaka North','Narayangonj','Khulna','Barisal','Tangail','Bogra','Noakhali','Chittagong')
            THEN 'Traders'
        WHEN DBM.REGION_NAME IN ('Corporate North','Corporate South','Institutional','MES')
            THEN 'Corporate'
        ELSE 
            NULL
     END
     CUSTOMER_TYPE
--,DECODE (DBM.REGION_NAME, 'Corporate North', 'Corporate','Corporate South', 'Corporate','Institutional', 'Corporate','MES', 'Corporate','Held', ' ',NULL,'Not Defined','Traders') "CUSTOMER_TYPE"                                     
--,(SELECT FFV.FLEX_VALUE FROM APPS.FND_FLEX_VALUE_SETS VAL_SET, APPS.FND_FLEX_VALUES FFV WHERE VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID AND VAL_SET.FLEX_VALUE_SET_NAME='XXAKG_LOCATOR_LOCATION') CUSTOMER_CATEGORY
--,DBM.*
FROM
APPS.HZ_PARTIES PARTY,
APPS.HZ_CUST_ACCOUNTS CA,
--APPS.HZ_CUST_SITE_USES_ALL CSUA,
--APPS.HZ_CUST_ACCT_SITES_ALL CASA,
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM
WHERE 1=1
AND PARTY.PARTY_ID=CA.PARTY_ID
AND CA.ACCOUNT_NUMBER=DBM.CUSTOMER_NUMBER(+)
--AND CSUA.CUST_ACCT_SITE_ID=CASA.CUST_ACCT_SITE_ID
--AND CA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID
--AND nvl(ca.status,'X')='A'
--AND CA.STATUS='A'
--AND CA.ACCOUNT_NUMBER=:P_CUSTOMER_NUM
--AND CSUA.SITE_USE_CODE='BILL_TO'
AND DBM.ORG_ID(+)=85
AND EXISTS (SELECT 1 FROM APPS.HZ_CUST_ACCT_SITES_ALL CASA WHERE CA.CUST_ACCOUNT_ID=CASA.CUST_ACCOUNT_ID AND CASA.ORG_ID=85)


SELECT
FFV.FLEX_VALUE
,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
AND VAL_SET.FLEX_VALUE_SET_NAME='XXAKG_LOCATOR_LOCATION'

SELECT meaning,ARL.*
          FROM APPS.ar_lookups ARL
         WHERE lookup_type = 'CUSTOMER_CATEGORY'

SELECT CUST_ACCT.CUST_ACCOUNT_ID CUSTOMER_ID,
          CUST_ACCT.ACCOUNT_NUMBER CUSTOMER_NUMBER,
          PARTY.PARTY_NAME CUSTOMER_NAME,
          SITE_USE.ORG_ID ORG_ID,
          SITE_USE.LOCATION,
          LOC.ADDRESS2 LOCATION_ADDRESS,
          CUST_ACCT.ORIG_SYSTEM_REFERENCE,
          PARTY.ADDRESS1,
          PARTY.ADDRESS2,
          PARTY.ADDRESS3,
          PARTY.ADDRESS4,
          PARTY.CITY,
          PARTY.COUNTRY,
          PARTY.KNOWN_AS,
          PARTY.PARTY_ID,
          TRIM (CUST_ACCT.ATTRIBUTE1) CREDIT_LIMIT,
          TRIM (CUST_ACCT.ATTRIBUTE2) ADDITIONAL_CREDIT_LIMIT,
          TRIM (CUST_ACCT.ATTRIBUTE3) SPECIAL_CREDIT_LIMIT,
          CUST_ACCT.ATTRIBUTE4 SECURITY_MODE,
          SITE_USE.SITE_USE_CODE,
          SITE_USE.PRIMARY_FLAG,
          SITE_USE.SITE_USE_ID,
          ACCT_USE.PARTY_SITE_ID,
          CUST_ACCT.STATUS,
          SITE_USE.STATUS SITE_USE_STATUS,
          ACCT_USE.STATUS ACCT_USE_STATUS,
          CUST_ACCT.ATTRIBUTE7 OLD_CUSTOMER_NUMBER,
          PARTY.PARTY_TYPE,
          party.category_code,
          LOC.ADDRESS1 REAILER,
          LOC.ADDRESS2 REAILER_ADDRESS,
          LOC.ADDRESS3 PROPRIETOR,
          LOC.ADDRESS4 SALES_REP,
          PS.PARTY_SITE_NUMBER,
          ACCT_USE.ATTRIBUTE2 CAMPAIGN,
          DECODE (CUST_ACCT.ATTRIBUTE_CATEGORY,
                  'SCIL Customer Information', CUST_ACCT.ATTRIBUTE8,
                  NULL)
             MOVING_STATUS
     --ph.PHONE_NUMBER
--     ,PARTY.*
     FROM APPS.HZ_PARTIES PARTY,
          APPS.HZ_CUST_ACCOUNTS CUST_ACCT,
          APPS.HZ_CUST_SITE_USES_ALL SITE_USE,
          APPS.HZ_CUST_ACCT_SITES_ALL ACCT_USE,
          APPS.HZ_PARTY_SITES PS,
          APPS.HZ_LOCATIONS LOC
    --APPS.HZ_CONTACT_POINTS ph
    WHERE     PARTY.PARTY_ID = CUST_ACCT.PARTY_ID
          AND SITE_USE.CUST_ACCT_SITE_ID = ACCT_USE.CUST_ACCT_SITE_ID
          AND CUST_ACCT.CUST_ACCOUNT_ID = ACCT_USE.CUST_ACCOUNT_ID
          AND ACCT_USE.PARTY_SITE_ID = PS.PARTY_SITE_ID
          AND PS.LOCATION_ID = LOC.LOCATION_ID
          AND CUST_ACCT.ACCOUNT_NUMBER='22407'
          AND SITE_USE.SITE_USE_CODE='BILL_TO'
--AND ph.OWNER_TABLE_ID(+) = ps.ORIG_SYSTEM_REFERENCE
--AND PS.LOCATION_ID = LOC.LOCATION_ID
--AND (ph.CONTACT_POINT_TYPE = 'PHONE' OR ph.CONTACT_POINT_TYPE IS NULL)
