/* Formatted on 10/20/2019 12:47:24 PM (QP5 v5.287) */
SELECT APPS.XXAKG_AR_PKG.GET_CUSTOMER_OPEN_BALance (:P_ORG_ID, CUSTOMER_ID, :P_DATE)
          BALANCE
  FROM APPS.AR_CUSTOMERS
 WHERE CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER
 
 
SELECT APPS.XXAKG_AR_PKG.GET_CUST_AR_BALANCE_DATE_RANGE(CUSTOMER_ID, :P_ORG_ID, :P_DATE_FROM, :P_DATE_TO) CLOSING_BALANCE
 FROM APPS.AR_CUSTOMERS
 WHERE CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER