SELECT
*
FROM
APPS.XLA_DISTRIBUTION_LINKS 
WHERE 1=1
--JOINED BY  APPLICATION_ID,AE_HEADER_ID, EVENT_ID,  
--CONDITONED BY AE_LINE_NUM, 
AND ROUNDING_CLASS_CODE NOT IN ('LIABILITY','CASH_CLEARING','PREPAID_EXPENSE','CASH')

SELECT
*
FROM
XLA.XLA_DISTRIBUTION_LINKS
WHERE 1=1
-- JOIN BY APPICATION iD, EVENT_ID, AE_HEADER_ID
AND ROWNUM<=3

SELECT
*
FROM
XLA.XLA_AE_LINES
WHERE 1=1
--JOIN BY AE_HEADER_ID, AE_LINE_NUMBER, APPLICATION_ID, CODE_COMBINATION_ID, PARTY_ID, PARTY_SITE_ID, LEDGER_ID 

SELECT
*
FROM
APPS.CE_BANK_ACCOUNTS  
WHERE 1=1
AND CURRENCY_CODE='BDT'