/* Formatted on 8/27/2019 3:26:48 PM (QP5 v5.287) */
SELECT RCTA.ORG_ID,
       RCTLA.WAREHOUSE_ID,
       HCA.ACCOUNT_NUMBER CUTOMER_NUMBER,
       HP.PARTY_NAME CUSTOMER_NAME,
       --hCA.ACCOUNT_NUMBER,
       HCA.ACCOUNT_NAME,
       HCA.STATUS ACCOUNT_STATUS,
       HCSUA.STATUS CUSTOMER_SITE_STATUS,
       HCSUA.SITE_USE_CODE,
       HZL.ADDRESS1 ADDRESS,
       HCSUA.LOCATION,
       --hCSUA.CUST_ACCT_SITE_ID,
       --hCSUA.SITE_USE_ID,
       --hCASA.CUST_ACCT_SITE_ID,
       --hCASA.PARTY_SITE_ID,
       --CA.CREATION_DATE "ACCOUNT CREATION DATE",
       --CASA.CREATION_DATE "ACCOUNT SITE CREATION DATE",
       --RCTA.BILL_TO_CUSTOMER_ID,
       --RCTA.BILL_TO_SITE_USE_ID,
       --RCTA.SHIP_TO_CUSTOMER_ID,
       --RCTA.SHIP_TO_SITE_USE_ID,
       RCTLA.INVENTORY_ITEM_ID,
       RCTLA.DESCRIPTION ITEM_DESCRIPTION,
       RCTA.TRX_NUMBER RECEIVABLE_TRANSACTION_NUMBER,
       ACRA.AMOUNT RECEIPT_AMOUNT,
       RCTLA.EXTENDED_AMOUNT RECEIVABLE_AMOUNT,
       RCTLA.REVENUE_AMOUNT,
       ACRA.RECEIPT_NUMBER,
       ACRA.STATUS RECEIPT_STATUS,
       ACRA.TYPE RECEIPT_TYPE,
       ACRA.RECEIPT_DATE,
       ACRHA.STATUS RECEIPT_STATUS_TYPE,
       ACRHA.TRX_DATE,
       ACRHA.AMOUNT CASH_RECEIPT_AMOUNT,
       ----------------------------------------------------
       --RTA.ORG_ID,
       DECODE (RCTTA.TYPE,
               'PMT', 'PAYMENT',
               'CM', 'CREDIT MEMO',
               'INV', 'INVOICES',
               'DM', 'DEBIT MEMO',
               'Not Defined')
          "PAYMENT TYPE",
       --RTA.TRX_DATE,
       --RTA.SET_OF_BOOKS_ID,
       RCTA.DOC_SEQUENCE_VALUE RECEIPT_VOUCHER_NUMBER,
       --RTT.NAME,
       RCTTA.DESCRIPTION,
       --RcTTa.TYPE,
       RCTLGDA.AMOUNT GL_AMOUNT,
       TO_CHAR (RCTLGDA.GL_DATE) GL_DATE,
       GCC.SEGMENT2 "Cost Centre",
          GCC.SEGMENT1
       || '.'
       || GCC.SEGMENT2
       || '.'
       || GCC.SEGMENT3
       || '.'
       || GCC.SEGMENT4
          "Account_Code",
       GCC.SEGMENT3 "Natural Account",
       --cust_acct.ACCOUNT_NAME,
       APSA.TRX_NUMBER PAYMENT_TRANSACTION_NUMBER,
       APSA.TRX_DATE PAYMENT_TRANSACTION_DATE,
       --rctla.description,
       FNDU.USER_NAME USER_ID
  FROM APPS.RA_CUST_TRX_TYPES_ALL RCTTA,
       APPS.RA_CUSTOMER_TRX_ALL RCTA,
       APPS.RA_CUSTOMER_TRX_LINES_ALL RCTLA,
       APPS.RA_CUST_TRX_LINE_GL_DIST_ALL RCTLGDA,
       APPS.GL_CODE_COMBINATIONS GCC,
       APPS.HZ_CUST_ACCOUNTS HCA,
       APPS.AR_PAYMENT_SCHEDULES_ALL APSA,
       APPS.HZ_CUST_ACCT_SITES_ALL HCASA,
       APPS.HZ_PARTY_SITES HPS,
       APPS.HZ_PARTIES HP,
       APPS.HZ_LOCATIONS HZL,
       APPS.HZ_CUST_SITE_USES_ALL HCSUA,
       APPS.FND_USER FNDU,
       APPS.AR_CASH_RECEIPTS_ALL ACRA,
       APPS.AR_CASH_RECEIPT_HISTORY_ALL ACRHA,
       APPS.AR_RECEIVABLE_APPLICATIONS_ALL ARA
 WHERE     1 = 1
       --AND ACRA.ORG_ID=85
       AND RCTLA.SET_OF_BOOKS_ID = ACRA.SET_OF_BOOKS_ID
       AND ARA.CASH_RECEIPT_ID = ACRA.CASH_RECEIPT_ID
       AND ARA.APPLIED_CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID
       AND RCTA.BILL_TO_SITE_USE_ID = HCSUA.SITE_USE_ID
       AND RCTA.SHIP_TO_CUSTOMER_ID = RCTLA.SHIP_TO_CUSTOMER_ID
       AND RCTA.SHIP_TO_SITE_USE_ID = RCTLA.SHIP_TO_SITE_USE_ID
       AND ACRA.CASH_RECEIPT_ID = ACRHA.CASH_RECEIPT_ID
       --AND RCTA.TRX_NUMBER='415107660'
       AND APSA.CUSTOMER_ID = HCA.CUST_ACCOUNT_ID
       AND RCTA.ORG_ID = 85
       AND APSA.CUST_TRX_TYPE_ID = RCTTA.CUST_TRX_TYPE_ID
       AND RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID
       AND HP.PARTY_ID = HPS.PARTY_ID
       --AND ps.trx_date <= :p_as_of_date
       --AND ps.CLASS NOT IN ('CM', 'PMT')
       AND HCSUA.SITE_USE_CODE = 'BILL_TO'
       AND HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID
       AND HZL.LOCATION_ID = HPS.LOCATION_ID
       AND NVL (HCSUA.STATUS, 'A') = 'A'
       AND HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
       AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
       AND APSA.CUSTOMER_ID = HCASA.CUST_ACCOUNT_ID
       AND APSA.CUSTOMER_SITE_USE_ID = HCSUA.SITE_USE_ID
       AND RCTA.CUSTOMER_TRX_ID = APSA.CUSTOMER_TRX_ID
       AND RCTA.CUSTOMER_TRX_ID = RCTLGDA.CUSTOMER_TRX_ID
       AND RCTLGDA.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
       AND FNDU.USER_ID = RCTA.LAST_UPDATED_BY
       AND RCTLGDA.ACCOUNT_CLASS = 'REV'
       AND ACRHA.STATUS = 'REMITTED'
       --and rcta.TRX_NUMBER='417425485'
       AND RCTLGDA.GL_DATE BETWEEN '01-FEB-2017' AND '01-FEB-2017';

---------------------------------------------------------------------------------------------------------------------------

SELECT RCTA.ORG_ID,
       RCTLA.WAREHOUSE_ID,
       RCTA.TRX_NUMBER,
       CA.ACCOUNT_NUMBER,
       CA.ACCOUNT_NAME,
       CA.STATUS ACCOUNT_STATUS,
       CSUA.STATUS CUSTOMER_SITE_STATUS,
       CSUA.CUST_ACCT_SITE_ID,
       CSUA.SITE_USE_ID,
       CASA.CUST_ACCT_SITE_ID,
       CASA.PARTY_SITE_ID,
       --CA.CREATION_DATE "ACCOUNT CREATION DATE",
       --CASA.CREATION_DATE "ACCOUNT SITE CREATION DATE",
       CSUA.SITE_USE_CODE,
       CSUA.LOCATION,
       RCTA.BILL_TO_CUSTOMER_ID,
       RCTA.BILL_TO_SITE_USE_ID,
       RCTA.SHIP_TO_CUSTOMER_ID,
       RCTA.SHIP_TO_SITE_USE_ID,
       RCTLA.INVENTORY_ITEM_ID,
       RCTLA.DESCRIPTION,
       ACRA.AMOUNT,
       RCTLA.EXTENDED_AMOUNT RECEIVABLE_AMOUNT,
       RCTLA.REVENUE_AMOUNT,
       ACRA.RECEIPT_NUMBER,
       ACRA.STATUS,
       ACRA.TYPE,
       ACRA.RECEIPT_DATE
  FROM APPS.RA_CUSTOMER_TRX_ALL RCTA,
       APPS.RA_CUSTOMER_TRX_LINES_ALL RCTLA,
       APPS.RA_CUST_TRX_TYPES_ALL RCTTA,
       APPS.AR_CASH_RECEIPTS_ALL ACRA,
       APPS.AR_RECEIVABLE_APPLICATIONS_ALL ARA,
       APPS.HZ_CUST_ACCOUNTS CA,
       APPS.HZ_CUST_SITE_USES_ALL CSUA,
       APPS.HZ_CUST_ACCT_SITES_ALL CASA
 WHERE     1 = 1
       AND ACRA.ORG_ID = 85
       AND RCTA.CUST_TRX_TYPE_ID = RCTTA.CUST_TRX_TYPE_ID
       AND RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID
       AND RCTA.SET_OF_BOOKS_ID = RCTLA.SET_OF_BOOKS_ID
       AND RCTLA.SET_OF_BOOKS_ID = ACRA.SET_OF_BOOKS_ID
       AND ARA.CASH_RECEIPT_ID = ACRA.CASH_RECEIPT_ID
       AND ARA.APPLIED_CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID
       AND CSUA.CUST_ACCT_SITE_ID = CASA.CUST_ACCT_SITE_ID
       AND CA.CUST_ACCOUNT_ID = CASA.CUST_ACCOUNT_ID
       AND RCTA.BILL_TO_SITE_USE_ID = CSUA.SITE_USE_ID
       AND RCTA.SHIP_TO_CUSTOMER_ID = RCTLA.SHIP_TO_CUSTOMER_ID
       AND RCTA.SHIP_TO_SITE_USE_ID = RCTLA.SHIP_TO_SITE_USE_ID
--AND RCTTA.TYPE = 'INV'
--AND RCTA.TRX_NUMBER='415107660'
--AND ARA.STATUS!='APP'
--AND ROWNUM<=2
;

---------------------------------------------------------------------------------------------------------------------------

  SELECT RCT.*,
         TRUNC (RCT.TRX_DATE) TRX_DATE,
         ACR.RECEIPT_NUMBER RECEIPT_NO,
         RCT.TRX_NUMBER INVOICE_NO
    FROM APPS.AR_RECEIVABLE_APPLICATIONS_ALL ARA,
         APPS.AR_CASH_RECEIPTS_ALL ACR,
         APPS.RA_CUSTOMER_TRX_ALL RCT
   WHERE     1 = 1
         AND ARA.STATUS = 'APP'
         AND ARA.CASH_RECEIPT_ID = ACR.CASH_RECEIPT_ID
         AND ARA.APPLIED_CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
         AND ROWNUM <= 4
ORDER BY RCT.CREATION_DATE DESC;