SELECT RCT.ORG_ID,
       RCT.TRX_NUMBER TRANSACTION_NUMBER,
       RCT.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
       RCT.OLD_TRX_NUMBER,
       RCT.TRX_DATE TRANSACTION_DATE,
       RCTL.DESCRIPTION TRANSACTION_DESCRIPTION,
       RCTL.ATTRIBUTE_CATEGORY,
       RCTL.ATTRIBUTE1,
       RCTL.ATTRIBUTE2,
       GCC.SEGMENT2 "Cost Centre" ,
       GCC.SEGMENT1 || '-' || GCC.SEGMENT2 || '-' || GCC.SEGMENT3 || '-' || GCC.SEGMENT4 "Account",
       GCC.SEGMENT3 "Natural Account",
       FFVV.DESCRIPTION "Natural Account Name",
       DECODE (RCTT.TYPE,
               'PMT', 'PAYMENT',
               'CM', 'CREDIT MEMO',
               'INV', 'INVOICES',
               'DM', 'DEBIT MEMO',
               'Not Defined')
          "PAYMENT TYPE",
       RCTT.NAME TRANSACTION_TYPE,
       RGLD.AMOUNT DISTRIBUTION_AMMOUNT
       --,RCT.*
       --,RCTL.*
       --,RCTT.*
       --,RGLD.*
  FROM APPS.RA_CUSTOMER_TRX_ALL RCT,
       APPS.RA_CUSTOMER_TRX_LINES_ALL RCTL,
       APPS.RA_CUST_TRX_TYPES_ALL RCTT,
       APPS.RA_CUST_TRX_LINE_GL_DIST_ALL RGLD,
       APPS.GL_CODE_COMBINATIONS GCC,
       APPS.FND_FLEX_VALUES_VL FFVV
 WHERE     1 = 1
       AND RCT.ORG_ID = 85
       AND RCT.TRX_NUMBER = '418332946'
       AND RCT.CUSTOMER_TRX_ID = RCTL.CUSTOMER_TRX_ID
       AND RCT.CUST_TRX_TYPE_ID = RCTT.CUST_TRX_TYPE_ID
       AND RCT.CUSTOMER_TRX_ID = RGLD.CUSTOMER_TRX_ID
       AND RGLD.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
       AND FFVV.FLEX_VALUE=GCC.SEGMENT3
       --AND TO_CHAR (RCT.CREATION_DATE, 'DD-MON-RR') = '27-AUG-19'
       AND NVL (RCT.COMPLETE_FLAG, 'Y') = 'Y';