SELECT
OOD.OPERATING_UNIT,
CUST.CUSTOMER_NUMBER,
CUST.CUSTOMER_NAME,
WDD.SOURCE_HEADER_TYPE_NAME ORDER_TYPE,
WDD.SOURCE_HEADER_NUMBER ORDER_NO,
WDD.SHIPMENT_PRIORITY_CODE DO_NUMBER,
WDD.ITEM_DESCRIPTION,
WDD.SRC_REQUESTED_QUANTITY_UOM UOM,
WDD.SRC_REQUESTED_QUANTITY QUANTITY,
OOD.ORGANIZATION_NAME,
OOD.ORGANIZATION_CODE
--,WDD.*
--,CUST.*
FROM
APPS.WSH_DELIVERABLES_V WDD
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST
WHERE 1=1
AND WDD.ORGANIZATION_ID=OOD.ORGANIZATION_ID
AND CUST.SHIP_TO_ORG_ID=WDD.SHIP_TO_SITE_USE_ID
AND WDD.CUSTOMER_ID=CUST.CUSTOMER_ID
AND WDD.RELEASED_STATUS='B'
--AND SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND SHIPMENT_PRIORITY_CODE='DO/SCOU/1021767'
--AND SOURCE_LINE_ID='10702768'
--AND SOURCE_HEADER_ID='3727754'
--AND ORGANIZATION_ID='606'
AND WDD.ORG_ID IN (
                                85
--                                ,605
--                                ,83
--                                ,84
                                )


SELECT
*
FROM
APPS.ORG_ORGANIZATION_DEFINITIONS OOD