SELECT DISTINCT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.DO_NUMBER,
--SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
--MOH.MOV_ORDER_NO,
DODL.WAREHOUSE_ORG_CODE,
DODL.SHIP_TO_LOCATION DELIVERY_Address,--- NEW UPDATED
         DODL.ACTUAL_RETAILER_SHIP_TO ACTUAL_RETAILER_SITE, --- NEW UPDATED
         APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION(DODL.SHIP_TO_ORG_ID) DELIVERY_LOCATION
         ,CUST.REAILER_ADDRESS
--         ,CUST.*
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL
,APPS.XXAKG_AR_CUSTOMER_SITE_V CUST
WHERE 1=1
AND DOH.CUSTOMER_NUMBER=CUST.CUSTOMER_NUMBER
AND DODL.SHIP_TO_ORG_ID=CUST.SHIP_TO_ORG_ID
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DODL.DO_NUMBER=:P_DO_NUMBER
AND DODL.WAREHOUSE_ORG_CODE='SCI'
--AND DOH.CUSTOMER_NUMBER IN ('20107','20770','184363') 

