SELECT 
MVH.ORG_ID,
DODL.ORDER_NUMBER,
SOL.ORDERED_QUANTITY,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.UOM_CODE,
SOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
TRUNC (DO_DATE) DO_DATE,
DOH.DO_STATUS,
NVL (LINE_QUANTITY, 0) DO_QUANTITY,
WSHD.RELEASED_STATUS,
WSHD.RELEASED_STATUS_NAME,
SOL.FLOW_STATUS_CODE,
SOL.SHIP_FROM_ORG_ID,
DODL.WAREHOUSE_ORG_ID,
DODL.WAREHOUSE_ORG_CODE,
MVH.MOV_ORDER_NO,
TRUNC (MOV_ORDER_DATE) MOV_ORDER_DATE,
MOV_ORDER_STATUS,
MVH.TRANSPORT_MODE,
SOL.ACTUAL_SHIPMENT_DATE
FROM APPS.XXAKG_DEL_ORD_HDR DOH,
          APPS.XXAKG_DEL_ORD_DO_LINES DODL,
          APPS.XXAKG_MOV_ORD_DTL MVD,
          APPS.XXAKG_MOV_ORD_HDR MVH,
          APPS.OE_ORDER_LINES_ALL SOL,
          --WSH_DELIVERY_DETAILS WSHD
          APPS.WSH_DELIVERABLES_V WSHD
    WHERE     DOH.DO_HDR_ID = DODL.DO_HDR_ID
          AND DOH.ORG_ID = DODL.ORG_ID
          AND DOH.DO_HDR_ID = MVD.DO_HDR_ID
          AND MVH.MOV_ORD_HDR_ID = MVD.MOV_ORD_HDR_ID
          AND MVH.ORG_ID = DOH.ORG_ID
          AND MVD.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
          AND MVH.ORG_ID = SOL.ORG_ID
          AND DODL.ORDER_HEADER_ID = SOL.HEADER_ID
          AND DODL.ORDER_LINE_ID = SOL.LINE_ID
          AND SOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
          AND SOL.LINE_ID = WSHD.SOURCE_LINE_ID
          AND DODL.WAREHOUSE_ORG_ID IN (1345,1346)
   UNION ALL
   SELECT 
   MVH.ORG_ID,
   DODL.ORDER_NUMBER,
   SOL.ORDERED_QUANTITY,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
DODL.UOM_CODE,
SOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
TRUNC (DO_DATE) DO_DATE,
DOH.DO_STATUS,
NVL (LINE_QUANTITY, 0) DO_QUANTITY,
WSHD.RELEASED_STATUS,
WSHD.RELEASED_STATUS_NAME,
SOL.FLOW_STATUS_CODE,
SOL.SHIP_FROM_ORG_ID,
DODL.WAREHOUSE_ORG_ID,
DODL.WAREHOUSE_ORG_CODE,
MVH.MOV_ORDER_NO,
TRUNC (MOV_ORDER_DATE) MOV_ORDER_DATE,
MOV_ORDER_STATUS,
MVH.TRANSPORT_MODE,
SOL.ACTUAL_SHIPMENT_DATE
     FROM APPS.XXAKG_DEL_ORD_HDR DOH,
          APPS.XXAKG_DEL_ORD_DO_LINES DODL,
          APPS.XXAKG_MOV_ORD_DTL MVD,
          APPS.XXAKG_MOV_ORD_HDR MVH,
          APPS.OE_ORDER_LINES_ALL SOL,
          --WSH_DELIVERY_DETAILS WSHD
          APPS.WSH_DELIVERABLES_V WSHD
    WHERE     DOH.DO_HDR_ID = DODL.DO_HDR_ID
          AND DOH.ORG_ID = DODL.ORG_ID
          AND DOH.DO_HDR_ID = MVD.DO_HDR_ID
          AND MVH.MOV_ORD_HDR_ID = MVD.MOV_ORD_HDR_ID
          AND MVH.ORG_ID = DOH.ORG_ID
          AND MVD.DO_NUMBER = SOL.SHIPMENT_PRIORITY_CODE
          AND MVH.ORG_ID = SOL.ORG_ID
          AND DODL.ORDER_HEADER_ID = SOL.HEADER_ID
          AND SOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
          AND SOL.LINE_ID = WSHD.SOURCE_LINE_ID
          AND DODL.WAREHOUSE_ORG_ID IN (1345,1346)
          AND NOT EXISTS
                (SELECT 1
                   FROM XXAKG_DEL_ORD_DO_LINES DOL1
                  WHERE DOL1.ORDER_LINE_ID = SOL.LINE_ID
                        AND DOL1.ORG_ID = SOL.ORG_ID);