SELECT
--DOH.*
--DODL.*
MOH.*
--MODT.*
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.DO_NUMBER=DOH.DO_NUMBER
--------------------------------------DO-------------------------------------------------------
--AND substr(DODL.ITEM_NUMBER,0,3)='TLH'
--AND DODL.ITEM_NUMBER='CMNT.PBAG.0001'
--AND DOH.DO_NUMBER=:P_DO_NUMBER
--AND DODL.ORDER_NUMBER IN ('1697832')
--AND DOH.DO_NUMBER IN ('DO/MOU/17204')
--AND DOH.DO_STATUS IN ('GENERATED')--CONFIRMED
--AND TO_CHAR(DOH.DO_DATE,'DD-MON-RR')='03-APR-18'
--AND DOH.DO_DATE BETWEEN '01-JAN-2010' and '30-APR-2018'
--AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'DEC-17'
--AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2018'
AND DOH.ORG_ID=85
--AND DODL.WAREHOUSE_ORG_CODE='G01'
-------------------------------------MOVE----------------------------------------------------
--AND WAREHOUSE_ORG_CODE='SCI'
--AND MOH.VEHICLE_NO LIKE '%2369%' --IN ('D.M.U-12-1695')
--AND MOH.MOV_ORDER_NO IN ('MO/SCOU/915072')
--AND MOV_ORDER_STATUS IN ('CONFIRMED','GENERATED')
--AND TO_CHAR(MOH.MOV_ORDER_DATE,'DD-MON-RR')='01-SEP-18'
--AND TO_CHAR(MOH.MOV_ORDER_DATE,'MON-RR')='SEP-18'
--AND TO_CHAR(MOH.MOV_ORDER_DATE,'RRRR')='2018'
--AND DOH.DO_DATE BETWEEN '01-JAN-2010' and '30-APR-2018'
--AND TRUNC(MOH.MOV_ORDER_DATE) BETWEEN '01-SEP-2018' and '30-SEP-2018'
--AND MODT.DO_NUMBER IN ('DO/SCOU/959655')
--AND MODT.CUSTOMER_NUMBER IN ('20058')
--AND MOH.GATE_IN IS NULL
--AND MOH.ORG_ID=85
------------------------------------------------------------------------------------------------
--AND EXISTS(SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OOL WHERE DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE AND  OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING')