SELECT
--OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
--MSIB.DESCRIPTION,
--OOL.ORDER_QUANTITY_UOM UOM,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
--OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
--OOH.ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
OOD.ORGANIZATION_CODE
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
--OOL.UNIT_SELLING_PRICE,
--(OOL.UNIT_SELLING_PRICE*SUM(OOL.ORDERED_QUANTITY)) AMOUNT
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
,APPS.MTL_SYSTEM_ITEMS_B MSIB
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=MSIB.INVENTORY_ITEM_ID
AND OOL.SHIP_FROM_ORG_ID=MSIB.ORGANIZATION_ID
AND OOD.ORGANIZATION_ID=MSIB.ORGANIZATION_ID
AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOH.ORDER_TYPE_ID=1099
--AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND OOL.FULFILLMENT_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND TO_CHAR (OOL.FULFILLMENT_DATE, 'MON-RR') = 'FEB-18'
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'MAR-18'
--AND TO_CHAR (DOH.ACTUAL_SHIPMENT_DATE, 'RRRR') = '2017'
--AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
--AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
AND OOH.ORG_ID=85
AND OOD.ORGANIZATION_CODE!='SCI'
AND EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_HDR DOH WHERE DOH.DO_NUMBER=OOL.SHIPMENT_PRIORITY_CODE AND DOH.MODE_OF_TRANSPORT='Company Truck' AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'MAR-18')
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER
GROUP BY
--OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
--MSIB.DESCRIPTION,
--OOL.ORDER_QUANTITY_UOM,
--OOL.SHIPMENT_PRIORITY_CODE ,
--OOH.ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ,
OOD.ORGANIZATION_CODE
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
--OOL.UNIT_SELLING_PRICE,
--OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY
--,OOL.*

SELECT
--ORGANIZATION_NAME,
--ORGANIZATION_CODE,
--ACSV.CUSTOMER_NUMBER,
--ACSV.CUSTOMER_NAME,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
--ORDERED_QUANTITY,
SUM(ORDERED_QUANTITY) ORDERED_QUANTITY,
SUM(SHIPPED_QUANTITY) SHIPPED_QUANTITY,
SUM(INVOICED_QUANTITY) INVOICED_QUANTITY
--SUM(ORDERED_AMT) AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--DO_NUMBER,
--PERIOD
--,ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
,APPS.XXAKG_AR_CUSTOMER_SITE_V ACSV 
WHERE 1=1
AND ORD.ORG_ID=85
AND ACSV.CUSTOMER_ID=ORD.SOLD_TO_ORG_ID
AND ACSV.SHIP_TO_ORG_ID=ORD.SHIP_TO_ORG_ID
AND PERIOD='JUL-18'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
--AND ORGANIZATION_CODE='G32'
AND ACSV.STATUS='A'
--AND ACSV.SITE_USE_CODE='BILL_TO'
--AND ACSV.SITE_USE_CODE='SHIP_TO'
--AND ACSV.PRIMARY_FLAG='Y'
AND ACSV.SITE_USE_STATUS='A'
AND ACSV.ACCT_USE_STATUS='A'
--AND NOT EXISTS (SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE 1=1 AND  ACSV.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER )
AND CUSTOMER_NUMBER='14776'--':P_CUSTOMER_NUMBER
--AND ORD.ORDER_NUMBER IN ('1659352')
--AND ORD.DO_NUMBER=:P_DO_NUMBER
--AND TO_CHAR (ORD.DELIVERY_DATE, 'MON-RR') = 'JUL-18'

