SELECT MOH.ORG_ID,
       DOH.DO_NUMBER "DO/TO_NUMBER",
       MOH.MOV_ORDER_NO "MOV/MTO_NUMBER",
       DOH.MODE_OF_TRANSPORT,
       TO_CHAR (DOH.DO_DATE) "DO/TO_DATE",
       DODL.LINE_QUANTITY QUANTITY,
       DODL.ITEM_DESCRIPTION,
       DOH.DO_STATUS "DO/TO_STATUS",
       MOH.MOV_ORDER_STATUS "MOV/MTO_STATUS",
       TO_CHAR (MOH.MOV_ORDER_DATE) "MOVE/TRANSFER_ORDER_DATE"
       ,(SELECT DISTINCT OOL.FLOW_STATUS_CODE FROM APPS.OE_ORDER_LINES_ALL OOL WHERE 1=1 AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER) "ORDER/TO LINE STATUS" -- AND ROWNUM=1
  FROM XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
       XXAKG.XXAKG_DEL_ORD_HDR DOH,
       XXAKG.XXAKG_MOV_ORD_HDR MOH,
       XXAKG.XXAKG_MOV_ORD_DTL MODT
 WHERE     1 = 1
       AND DODL.DO_HDR_ID = DOH.DO_HDR_ID
       AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
       AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
       AND DOH.DO_STATUS != MOH.MOV_ORDER_STATUS
       AND DOH.DO_STATUS != 'CANCELLED'
       AND MOH.MOV_ORDER_STATUS != 'CANCELLED'
       AND MOH.ORG_ID = 85
       AND DOH.DO_STATUS = 'GENERATED'
       AND MOH.MOV_ORDER_STATUS = 'CONFIRMED'
       AND DODL.LINE_QUANTITY IS NOT NULL
       --AND EXISTS (SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OOL WHERE DODL.ORDER_LINE_ID=OOL.LINE_ID AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING')
       --AND TO_CHAR(MOH.MOV_ORDER_DATE,'RRRR')='2018'
UNION ALL
SELECT TMH.ORG_ID,
       TDL.TO_NUMBER "DO/TO_NUMBER",
       TMH.MOV_ORDER_NO "MOV/MTO_NUMBER",
       TMH.TRANSPORT_MODE "MODE_OF_TRANSPORT",
       TO_CHAR (TDH.TO_DATE) "DO/TO_DATE",
       TDL.QUANTITY QUANTITY,
       TDL.ITEM_DESCRIPTION,
       TDH.TO_STATUS "DO/TO_STATUS",
       TMH.MOV_ORDER_STATUS "MOV/MTO_STATUS",
       TO_CHAR (TMH.MOV_ORDER_DATE) "MOVE/TRANSFER_ORDER_DATE"
       ,TDL.RECORD_STATUS "ORDER/TO LINE STATUS"
  FROM XXAKG.XXAKG_TO_MO_HDR TMH,
       APPS.XXAKG_TO_MO_DTL TMD,
       APPS.XXAKG_TO_DO_HDR TDH,
       XXAKG.XXAKG_TO_DO_LINES TDL
 WHERE     1 = 1
       AND TDH.TO_STATUS != 'CANCELLED'
       AND TMH.MOV_ORDER_STATUS != 'CANCELLED'
       AND TMH.ORG_ID = 85
       AND TMD.TO_HDR_ID = TDL.TO_HDR_ID
       AND TDH.TO_HDR_ID = TDL.TO_HDR_ID
       AND TMD.MOV_ORD_HDR_ID = TMH.MOV_ORD_HDR_ID
       AND TDH.TO_STATUS = 'GENERATED'
       AND TMH.MOV_ORDER_STATUS = 'CONFIRMED'
       --AND TO_CHAR(TMH.MOV_ORDER_DATE,'RRRR')='2018'