------------------------------Order Details---------------------------------------------------
SELECT 
OOH.ORG_ID,
APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (OOH.ORG_ID) OPERATING_UNIT,
APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (OOH.SOLD_TO_ORG_ID) REGION, 
OOH.SOLD_TO_ORG_ID CUSTOMER_ID,
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NUMBER, 
APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (OOH.SOLD_TO_ORG_ID) CUSTOMER_NAME,
OOH.ORDER_NUMBER,
OOH.ORDER_TYPE_ID,
(SELECT OT.NAME FROM APPS.OE_TRANSACTION_TYPES_TL OT WHERE OT.TRANSACTION_TYPE_ID=OOH.ORDER_TYPE_ID) ORDER_TYPE_NAME,
OOH.ORDERED_DATE,
OOH.BOOKED_DATE,
OOH.HEADER_ID,
OOL.LINE_ID,
OOL.INVENTORY_ITEM_ID,
OOL.ORDERED_ITEM ITEM_CODE,
(SELECT DESCRIPTION FROM INV.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID= OOL.SHIP_FROM_ORG_ID) ITEM_DESCRIPTION,
OOL.ORDER_QUANTITY_UOM UOM_CODE,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
APPS.XXAKG_ONT_PKG.GET_MOVE_NUMBER(OOL.SHIPMENT_PRIORITY_CODE) MOVE_ORDER_NO,
OOH.FLOW_STATUS_CODE ORDER_HEADER_STATUS,
OOL.FLOW_STATUS_CODE ORDER_LINE_STATUS,
OOL.ORDERED_QUANTITY,
(CASE 
WHEN  OOL.ORDERED_ITEM='CMNT.OBAG.0004' THEN (OOL.ORDERED_QUANTITY*1000)/50
ELSE DECODE (ORDER_QUANTITY_UOM,'MTN', NVL (ORDERED_QUANTITY, 0) * 20,NVL (ORDERED_QUANTITY, 0))
END) CONVERT_BAG_QTY,
OOL.SHIPPED_QUANTITY,
(CASE 
WHEN  OOL.ORDERED_ITEM='CMNT.OBAG.0004' THEN (OOL.SHIPPED_QUANTITY*1000)/50
ELSE DECODE (ORDER_QUANTITY_UOM, 'MTN', NVL (OOL.SHIPPED_QUANTITY, 0) * 20, NVL (OOL.SHIPPED_QUANTITY, 0))
END) CONVERT_SHIPPED_BAG_QTY,
OOL.INVOICED_QUANTITY,
OOL.ACTUAL_SHIPMENT_DATE,
OOL.UNIT_SELLING_PRICE,
OOL.PRICING_DATE,
OOL.PRICE_LIST_ID,
OOL.ATTRIBUTE10 PRICE_LOCATION,
OOL.ATTRIBUTE11 TRANSPORT_MODE,
OOL.ATTRIBUTE13 DELIVERY_MODE,
OOL.SHIP_TO_ORG_ID,
APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION (OOL.SHIP_TO_ORG_ID) DELIVERY_SITE,
APPS.XXAKG_BI_ONT_PKG.GET_DELIVERY_LOCATION (OOH.ORG_ID,OOH.SOLD_TO_ORG_ID,OOH.ORDER_NUMBER) DELIVERY_LOCATION,
OOL.SHIP_FROM_ORG_ID WAREHOUSE_ORG_ID,
(SELECT OOD.ORGANIZATION_CODE FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD WHERE OOD.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID) ORGANIZATION_CODE,
APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (OOL.SHIP_FROM_ORG_ID) WAREHOUSE_ORG_NAME
,APPS.XXAKG_ONT_PKG.GET_TRANSPORT_NAME_BY_DO(OOH.HEADER_ID) TRANSPORTER_NAME
,APPS.XXAKG_ONT_PKG.GET_MOVE_DATE(OOL.SHIPMENT_PRIORITY_CODE) MOVE_DATE
,APPS.XXAKG_ONT_PKG.GET_EMPTY_BAG_FROM_DO(OOL.SHIPMENT_PRIORITY_CODE,OOH.ORG_ID) EMPTY_BAG  
,APPS.XXAKG_BI_ONT_PKG.GET_VAT_CHALLAN_NO(OOL.LINE_ID) VAT_CHALLAN_NO
,APPS.XXAKG_AR_PKG.GET_CUSTOMER_ADDRESS (OOH.SOLD_TO_ORG_ID) CUSTOMER_ADDRESS  
,APPS.XXAKG_ONT_PKG.GET_CUSTOMER_BILL_TO_SITE(OOH.SOLD_TO_ORG_ID,OOH.ORG_ID) CUSTOMER_BILL_TO_SITE
,APPS.XXAKG_ONT_PKG.GET_ONHAND_QUANTITY(OOL.INVENTORY_ITEM_ID,OOL.SHIP_FROM_ORG_ID) ONHAND_QTY
,APPS.XXAKG_COM_PKG.GET_USER_NAME(OOL.LAST_UPDATED_BY) LAST_UPDATED_BY
,APPS.XXAKG_COM_PKG.GET_EMP_NAME_FROM_USER_ID(OOL.LAST_UPDATED_BY) LAST_UPDATED_USER
,(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) ORDER_VALUE
,APPS.XXAKG_COM_PKG.AMOUNT_IN_WORD(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) ORDER_VALUE_WORD
,APPS.XXAKG_BI_ONT_PKG.GET_TRANSPORT_HIRE_RATE(OOL.LINE_ID) HIRE_RATE
,(APPS.XXAKG_BI_ONT_PKG.GET_TRANSPORT_HIRE_RATE(OOL.LINE_ID)*
(CASE 
    WHEN  OOL.ORDERED_ITEM='CMNT.OBAG.0004' THEN (OOL.SHIPPED_QUANTITY*1000)/50
    ELSE DECODE (ORDER_QUANTITY_UOM, 'MTN', NVL (OOL.SHIPPED_QUANTITY, 0) * 20, NVL (OOL.SHIPPED_QUANTITY, 0))
 END)) INVOICE_AMOUNT
--,OOH.*
--,OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
WHERE 1=1 
AND OOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND TO_CHAR(ORDERED_DATE,'RRRR')=:DATE_REQUIRED
--AND OOL.FLOW_STATUS_CODE=:LINE_STATUS
--AND OOH.ORDER_NUMBER=:ORDER_NUMBER
AND OOL.SHIPMENT_PRIORITY_CODE=:DO_NUMBER
--AND EXISTS(SELECT 1 FROM APPS.XXAKG_MOV_ORD_HDR MOH ,APPS.XXAKG_MOV_ORD_DTL MODT WHERE MOH.MOV_ORDER_NO=:MOVE_NUMBER AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER  )
;

--------------------------------------------------------------------------------SCM DETAILS

SELECT
    DOH.CUSTOMER_NUMBER,
    DOH.CUSTOMER_NAME,
    OOH.ORDER_NUMBER,
    TO_CHAR(OOH.ORDERED_DATE,'DD-MON-YYYY HH24:MI:SS') ORDERED_DATE,
    OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
    OOD.ORGANIZATION_NAME,
    OOD.ORGANIZATION_CODE,
    MOH.MOV_ORDER_NO,
    MOH.TRANSPORT_MODE,
    MOH.VEHICLE_NO,
    OOL.ORDERED_ITEM,
    WSHD.ITEM_DESCRIPTION,
    NVL (OOL.ORDERED_QUANTITY, 0) DO_QUANTITY,
    NVL(WPB.NAME,0) BATCH_NO,
    NVL(TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE),0) INVOICE_DATE,
    NVL(MODT.VAT_CHALLAN_NO,0) VAT_CHALLAN_NO,
    NVL(MODT.CHALLAN_NO,MOH.GATE_PASS_NO) GATE_PASS_NO,
    --TO_CHAR(MODT.VAT_CHALLAN_DATE) VAT_CHALLAN_DATE,
    OOL.FLOW_STATUS_CODE ORDER_LINE_STATUS,
    WSHD.RELEASED_STATUS_NAME DELIVERY_STATUS,
    --DOH.DO_STATUS,
    --MOH.MOV_ORDER_STATUS,
    --TO_CHAR(MOH.MOV_ORDER_DATE) MOVE_ORDER_DATE,
    MTT.TRANSACTION_TYPE_NAME
    ,MMT.SUBINVENTORY_CODE
    ,WSHD.SUBINVENTORY
    --,MTRL.*
    --,MTRH.*
    --,MMT.*
    --,WSHD.*
 FROM 
    APPS.OE_ORDER_HEADERS_ALL OOH,
    APPS.OE_ORDER_LINES_ALL OOL, 
    APPS.XXAKG_DEL_ORD_HDR DOH,
    APPS.XXAKG_MOV_ORD_DTL MODT,
    APPS.XXAKG_MOV_ORD_HDR MOH,
    APPS.WSH_DELIVERABLES_V WSHD,
    APPS.WSH_PICKING_BATCHES WPB,
    APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
    INV.MTL_SYSTEM_ITEMS_B MSI,
    INV.MTL_ITEM_CATEGORIES MIC,
    INV.MTL_CATEGORIES_B MC,
    APPS.MTL_CATEGORY_SETS MCS,
    APPS.MTL_TXN_REQUEST_HEADERS MTRH,
    APPS.MTL_TXN_REQUEST_LINES MTRL,
    APPS.MTL_TXN_REQUEST_HEADERS_V MTRV,
    INV.MTL_MATERIAL_TRANSACTIONS MMT,
    INV.MTL_TRANSACTION_TYPES MTT,
    INV.MTL_TRANSACTION_LOT_NUMBERS MTLN,
    INV.MTL_ITEM_LOCATIONS MIL,
    APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE    1=1
      AND OOH.HEADER_ID=OOL.HEADER_ID
      AND DOH.DO_HDR_ID = MODT.DO_HDR_ID
      AND MOH.MOV_ORD_HDR_ID = MODT.MOV_ORD_HDR_ID
      AND MOH.ORG_ID = DOH.ORG_ID
      AND DOH.DO_NUMBER = OOL.SHIPMENT_PRIORITY_CODE
      AND MOH.ORG_ID = OOL.ORG_ID
      AND DBM.ORG_ID = OOL.ORG_ID
      AND OOL.HEADER_ID = WSHD.SOURCE_HEADER_ID
      AND OOL.LINE_ID = WSHD.SOURCE_LINE_ID
      AND DOH.CUSTOMER_NUMBER=DBM.CUSTOMER_NUMBER
      AND WSHD.BATCH_ID=WPB.BATCH_ID(+)
      AND MMT.TRANSACTION_ID=MTLN.TRANSACTION_ID(+)
      AND MMT.LOCATOR_ID=MIL.INVENTORY_LOCATION_ID(+)
      AND MMT.TRANSACTION_TYPE_ID = MTT.TRANSACTION_TYPE_ID(+)
      --AND MTT.TRANSACTION_TYPE_NAME IN ('Sales Order Pick')
      --AND MTT.TRANSACTION_TYPE_NAME IN ('Sales order issue')
      --AND MTT.TRANSACTION_TYPE_NAME IN ('COGS Recognition')
      AND WSHD.SOURCE_LINE_ID = MMT.TRX_SOURCE_LINE_ID(+)
      AND OOD.ORGANIZATION_ID = MMT.ORGANIZATION_ID(+)
      AND MSI.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID
      AND MSI.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
      AND MSI.INVENTORY_ITEM_ID=MIC.INVENTORY_ITEM_ID
      AND MSI.ORGANIZATION_ID=MIC.ORGANIZATION_ID
      --AND MIC.CATEGORY_SET_ID=1
      AND MCS.CATEGORY_SET_NAME='Inventory' --'Product Categories'
      AND MIC.CATEGORY_SET_ID=MCS.CATEGORY_SET_ID
      AND MIC.CATEGORY_ID=MC.CATEGORY_ID
      AND WSHD.MOVE_ORDER_LINE_ID=MTRL.LINE_ID(+)
      AND WPB.NAME= MTRH.REQUEST_NUMBER(+)
      AND MTRH.HEADER_ID=MTRL.HEADER_ID(+)
      AND MTRH.REQUEST_NUMBER=MTRV.REQUEST_NUMBER(+)
      --------------------------------------------------------------------------
      --AND MTRH.REQUEST_NUMBER=MTRV.REQUEST_NUMBER
      --AND MTRH.ORGANIZATION_ID=MTRL.ORGANIZATION_ID
      --AND TO_CHAR(WPB.BATCH_ID)=TO_CHAR(MTRH.REQUEST_NUMBER)
      --AND MTT.TRANSACTION_SOURCE_TYPE_ID = MMT.TRANSACTION_SOURCE_TYPE_ID
      --AND MMT.TRANSACTION_SOURCE_ID=MTRH.HEADER_ID
      --AND MTRL.LINE_ID=MMT.MOVE_ORDER_LINE_ID
      --AND MTRH.REQUEST_NUMBER=MMT.TRANSACTION_SOURCE_ID
      --------------------------------------------------------------------------
      --AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
      --AND MODT.VAT_CHALLAN_DATE IS NULL
      --AND MOH.GATE_IN IS NULL
      --AND OOD.ORGANIZATION_CODE !='SCI'
      --AND MOH.TRANSPORT_MODE IN ('Company Truck')
      --AND WSHD.RELEASED_STATUS_NAME='Staged/Pick Confirmed'-- IN ('Ready to Release')
      --AND DBM.REGION_NAME='Scrap'
      AND OOL.SHIP_FROM_ORG_ID=OOD.ORGANIZATION_ID
      AND     (:P_ORG_ID IS NULL OR (DOH.ORG_ID=:P_ORG_ID))
--      AND     (:P_WAREHOUSE IS NULL OR (OOD.ORGANIZATION_CODE = :P_WAREHOUSE))
      AND     (:P_REGION_NAME_EXCLUDE IS NULL OR (DBM.REGION_NAME <> :P_REGION_NAME_EXCLUDE))
--      AND     (:P_CUSTOMER_NUMBER IS NULL OR (DOH.CUSTOMER_NUMBER = :P_CUSTOMER_NUMBER))
--      AND     (:P_ORDER_NUMBER IS NULL OR (OOH.ORDER_NUMBER = :P_ORDER_NUMBER))
--      AND     (:P_STATUS IS NULL OR (OOL.FLOW_STATUS_CODE = :P_STATUS))
      AND     (:P_DO_NUMBER IS NULL OR (DOH.DO_NUMBER = :P_DO_NUMBER))
--      AND     (:P_VEHICLE_NUMBER IS NULL OR (MOH.VEHICLE_NO = :P_VEHICLE_NUMBER))
--      AND     (:P_MOV_ORDER_NO IS NULL OR (MOH.MOV_ORDER_NO = :P_MOV_ORDER_NO))
--      AND TRUNC(OOH.ORDERED_DATE) BETWEEN NVL(:P_ORDERED_DATE_FROM,TRUNC(OOH.ORDERED_DATE)) AND NVL(:P_ORDERED_DATE_TO,TRUNC(OOH.ORDERED_DATE))
--      AND TRUNC(OOL.ACTUAL_SHIPMENT_DATE) BETWEEN NVL(:P_INVOICE_DATE_FROM,TRUNC(OOL.ACTUAL_SHIPMENT_DATE)) AND NVL(:P_INVOICE_DATE_TO,TRUNC(OOL.ACTUAL_SHIPMENT_DATE))
--      AND TRUNC(DOH.DO_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(DOH.DO_DATE)) AND NVL(:P_DATE_TO,TRUNC(DOH.DO_DATE))
--      AND TRUNC(MOH.MOV_ORDER_DATE) BETWEEN NVL(:P_MOVE_DATE_FROM,TRUNC(MOH.MOV_ORDER_DATE)) AND NVL(:P_MOVE_DATE_TO,TRUNC(MOH.MOV_ORDER_DATE))
--      AND TRUNC(MOH.CONFIRMED_DATE) BETWEEN NVL(:P_CONFIRMED_DATE_FROM,TRUNC(MOH.CONFIRMED_DATE)) AND NVL(:P_CONFIRMED_DATE_TO,TRUNC(MOH.CONFIRMED_DATE))