SELECT
*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
WHERE 1=1
AND ORG_ID=85
--SEARCH BY  ORDER_NUMBER, ORDERED_DATE, 
--JOINED BY HEADER_ID, SOLD_FROM_ORG_ID, ORDER_NUMBER, SHIP_TO_ORG_ID
--CONDITIONED BY ORDER_TYPE_ID, CANCELLED_FLAG, FLOW_STATUS_CODE
AND ORDER_NUMBER='1639185'



SELECT 
*
FROM
APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND ORG_ID=85
--SEARCH BY SHIPMENT_PRIORITY_CODE, ACTUAL_SHIPMENT_DATE, LINE_TYPE_ID
--ORDER BY UOM, ORDERED_QUANTITY, SHIPPING_QUANTITY, INVOICED_QUANTITY
--JOINED BY HEADER_ID, SHIP_TO_ORG_ID, SOLD_TO_ORG_ID, SHIP_FROM_ORG_ID
--CONNECTED BY LINE_ID
--CONDITIONED BY FLOW_STATUS_CODE, UNIT_SELLING_PRICE
AND HEADER_ID='3270883'


SELECT *
--OOH.ORG_ID,
--OOH.ORDER_NUMBER,
--OOH.ORDER_TYPE_ID,
--OOH.ORDERED_DATE,
--OOL.ORDERED_ITEM,
--OOL.SHIPPED_QUANTITY,
--SUM (OOL.ORDERED_QUANTITY) ORDERED_QUANTITY
FROM
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND ORDER_NUMBER='1639088'

SELECT
OOL.ORG_ID, 
OOH.ORDER_NUMBER,
OOH.ORDER_TYPE_ID,
OOH.ORDERED_DATE,
OOL.HEADER_ID, 
OOL.ORDERED_ITEM, 
OOL.ORDER_QUANTITY_UOM,
--OOL.FLOW_STATUS_CODE, 
SUM(OOL.SHIPPED_QUANTITY) TOTAL_SHIPPED_QUANTITY,
sum(OOL.SHIPPING_QUANTITY) TOTAL_SHIPPING_QUANTITY,
sum(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY
FROM 
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL  OOL
WHERE ORDER_NUMBER=1596934
AND OOL.HEADER_ID=OOH.HEADER_ID
GROUP BY 
OOL.ORG_ID, 
OOH.ORDER_NUMBER,
OOH.ORDER_TYPE_ID,
OOH.ORDERED_DATE,
OOL.HEADER_ID, 
OOL.ORDERED_ITEM, 
OOL.ORDER_QUANTITY_UOM
--OOL.FLOW_STATUS_CODE 


SELECT
*
FROM
XXAKG.XXAKG_DEL_ORD_HDR
WHERE 1=1
--JOINED BY DO_HDR_ID, ORG_ID
--SEARCH BY DO_NUMBER, 
--FIND OUT CUSTOMER_NAME , CUSTOMER_NUMBER, MODE_OF_TRANSPORT, OPERATING_UNIT
--CONDITIONED BY DO_STATUS, 


SELECT
*
FROM
XXAKG.XXAKG_DEL_ORD_DO_LINES
WHERE 1=1
AND ORG_ID=85
--JOINED BY DO_HDR_ID, ORG_ID, ORDER_HEADER_ID, SHIP_TO_ORG_ID, 
--UNIQE COLUMN ORDER_LINE_ID, 
-- SEARCH BY DO NUMBER, 
--FIND OUT ITEM_DESCRIPTION, LINE_QUANTITY, WAREHOUSE_ORG_ID, WAREHOUSE_ORG_CODE, SHIP_TO_LOCATION, ACTUAL_RETAILER_TO_SHIP, ITEM_PRICE_LOCATION
--and DO_NUMBER='DO/SCOU/1015003'
AND ORDER_NUMBER='1639088'

SELECT
*
FROM
WSH.WSH_DELIVERY_DETAILS
WHERE 1=1
AND ORG_ID=85
--CONDITIONED BY RELEASED_STATUS,
--SEARCH BY SHIPMENT_PRIORITY_CODE, DELIVERY_DETAILS_ID
--JOINED BY MOVE_ORDER_LINE_ID, CUSTOMER_ID
--LOT_NUMBER, SUBINVENTORY
--FIND OUT DELIVERED_QUANTITY, SHIPPED_QUANTITY, CANCELLED_QUANTITY, CUSTOMER_PO_NUMBER
and SHIPMENT_PRIORITY_CODE='DO/SCOU/1015003'

SELECT
*
FROM
XXAKG.XXAKG_MOV_ORD_HDR
WHERE 1=1
AND ORG_ID=85
--JOINED BY MOV_ORD_HDR_ID, 
--SEARCH BY VAT_CHALLAN_NO, GATE_PASS_NO, MOV_ORDER_NO, 
--CONDITIONED BY MOV_ORDER_STATUS, GATE_OUT, GATE_IN, 
--FIND OUT FINAL_DESTINATION, WAREHOUSE_ORG_CODE, WAREHOUSE_ORG_ID, TRANSPORT_MODE, VEHICLE_NO, TRANSPORTE_NAME, HIRE_RATE, CONFIRMED_DATE, 


SELECT
*
FROM
XXAKG.XXAKG_MOV_ORD_DTL
WHERE 1=1
--JOINED BY MOVE_ORD_HDR_ID, DO_HDR_ID, DO_NUMBER, CUSTOMER_NUMBER
--FIND OUT CUSTOMER_NO, VAT_CHALLAN_NO, 
AND DO_NUMBER='DO/SCOU/1013764'


SELECT
*
FROM
APPS.ORG_ORGANIZATION_DEFINITIONS
WHERE 1=1
--JOINED BY ORGANIZATION_ID, OPERATING_UNIT, BUSINESS-GROUP_ID
--FIND OUT ORGANIZATION_NAME, ORGANIZATION_CODE, 


SELECT 
DOH.ORG_ID,
OOH.ORDER_NUMBER,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DOH.OPERATING_UNIT,
MOH.WAREHOUSE_ORG_CODE,
DOH.DO_NUMBER,
MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
MOH.VEHICLE_NO,
DOH.DO_DATE,
--OOL.ORDERED_QUANTITY,
--DODL.LINE_QUANTITY,
--WDD.DELIVERED_QUANTITY, 
--WDD.SHIPPED_QUANTITY, 
--WDD.CANCELLED_QUANTITY,
--OOL.INVOICED_QUANTITY,
--sum(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY,
--SUM(OOL.SHIPPED_QUANTITY) TOTAL_SHIPPED_QUANTITY,
--sum(OOL.INVOICED_QUANTITY) TOTAL_ORDERED_QUANTITY,
OOL.FLOW_STATUS_CODE,
DODL.ITEM_NUMBER,
DODL.ITEM_DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
DOH.DO_STATUS,
MOH.MOV_ORDER_STATUS,
--MOH.CONFIRMED_DATE,
OOL.ACTUAL_SHIPMENT_DATE,
--DODL.ITEM_PRICE_LOCATION,
DODL.SHIP_TO_LOCATION,
DOH.FINAL_DESTINATION,
MODT.VAT_CHALLAN_NO,
MOH.GATE_PASS_NO,
WDD.SUBINVENTORY,
MOH.INITIAL_GATE_IN,
MOH.GATE_OUT,
MOH.GATE_IN,
MOH.HIRE_RATE_AP
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_DEL_ORD_HDR DOH,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
WSH.WSH_DELIVERY_DETAILS WDD
WHERE 1=1 
AND OOH.HEADER_ID(+)=DODL.ORDER_HEADER_ID
AND DODL.DO_HDR_ID=DOH.DO_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID(+)
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID(+)
AND WDD.SHIPMENT_PRIORITY_CODE(+)=DOH.DO_NUMBER
AND OOL.HEADER_ID=OOH.HEADER_ID
--AND OOH.ORDER_NUMBER='1639088'
--AND DOH.DO_NUMBER='DO/SCOU/1015003'
AND MOH.MOV_ORDER_NO='MO/SCOU/937633'
--GROUP BY
--DOH.ORG_ID,
--OOH.ORDER_NUMBER,
--DOH.CUSTOMER_NUMBER,
--DOH.CUSTOMER_NAME,
--DOH.OPERATING_UNIT,
--MOH.WAREHOUSE_ORG_CODE,
--DOH.DO_NUMBER,
--MOH.MOV_ORDER_NO,
--DOH.MODE_OF_TRANSPORT,
--MOH.VEHICLE_NO,
--DOH.DO_DATE,
----OOL.ORDERED_QUANTITY,
----DODL.LINE_QUANTITY,
----WDD.DELIVERED_QUANTITY, 
----WDD.SHIPPED_QUANTITY, 
----WDD.CANCELLED_QUANTITY,
----OOL.INVOICED_QUANTITY,
----sum(OOL.ORDERED_QUANTITY) TOTAL_ORDERED_QUANTITY,
----SUM(OOL.SHIPPED_QUANTITY) TOTAL_SHIPPED_QUANTITY,
----sum(OOL.INVOICED_QUANTITY) TOTAL_ORDERED_QUANTITY,
--OOL.FLOW_STATUS_CODE,
--DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
--OOL.ORDER_QUANTITY_UOM,
--DOH.DO_STATUS,
--MOH.MOV_ORDER_STATUS,
----MOH.CONFIRMED_DATE,
--OOL.ACTUAL_SHIPMENT_DATE,
----DODL.SHIP_TO_LOCATION,
--DOH.FINAL_DESTINATION,
--MODT.VAT_CHALLAN_NO,
--MOH.GATE_PASS_NO,
--WDD.SUBINVENTORY,
--MOH.INITIAL_GATE_IN,
--MOH.GATE_OUT,
--MOH.GATE_IN,
--MOH.HIRE_RATE_AP,
--DODL.SHIP_TO_LOCATION
--ORDER BY 
--DODL.SHIP_TO_LOCATION


SELECT
*
FROM
APPS.FND_LOOKUP_VALUES
WHERE 1=1
AND LOOKUP_CODE='DO/SCOU/1015003'


