SELECT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
DODL.UOM_CODE,
MOH.MOV_ORDER_NO INVOICE_NUMBER,
nvl(MODT.VAT_CHALLAN_NO,0) VAT_CHALLAN_NO,
TO_CHAR (MOH.CONFIRMED_DATE, 'DD-MON-YYYY') MOVE_CONFIRM_DATE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.XXAKG_DEL_ORD_DO_LINES DODL,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
AND DODL.DO_NUMBER=MODT.DO_NUMBER
and exists (select 1 from apps.oe_order_lines_all ol,apps.oe_order_headers_all oh where oh.header_id=ol.header_id and ol.header_id=dODl.order_header_id and ol.shipment_priority_code=dOh.do_number and ol.org_id=dOh.org_id and ol.flow_status_code IN ('CLOSED','SHIPPED') and oh.order_type_id=1099 and ol.actual_shipment_date is not null)
--AND DODL.WAREHOUSE_ORG_CODE='SCI'
and MOH.MOV_ORDER_STATUS='CONFIRMED'
--AND MOH.TRANSPORT_MODE='Company Truck'
AND nvl(MODT.VAT_CHALLAN_NO,0)='0'
AND MOH.GATE_OUT='Y'
AND MOH.CONFIRMED_DATE BETWEEN '01-JAN-2017' and '18-NOV-2017'
--AND TO_CHAR (MOH.CONFIRMED_DATE, 'MON-RR') = 'SEP-17'
GROUP BY
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.DO_NUMBER,
DODL.UOM_CODE,
MOH.MOV_ORDER_NO,
MODT.VAT_CHALLAN_NO,
MOH.CONFIRMED_DATE
ORDER BY MOH.CONFIRMED_DATE DESC
