/* Formatted on 6/24/2019 10:52:23 AM (QP5 v5.287) */
SELECT CT.ORG_ID,
       APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (CT.ORG_ID) OPERATING_UNIT,
       APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CT.BILL_TO_CUSTOMER_ID)
          REGION,
       CT.BILL_TO_CUSTOMER_ID CUSTOMER_ID,
       APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (CT.BILL_TO_CUSTOMER_ID)
          CUSTOMER_NUMBER,
       APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (CT.BILL_TO_CUSTOMER_ID)
          CUSTOMER_NAME,
       CL.SALES_ORDER,
       CL.SALES_ORDER_DATE,
       CL.INVENTORY_ITEM_ID,
       CL.DESCRIPTION,
       CL.UOM_CODE UOM,
       CL.QUANTITY_ORDERED,
       (CASE
           WHEN CL.DESCRIPTION = 'Ordinary Portland Cement - Jumbo Bag'
           THEN
              (CL.QUANTITY_ORDERED * 1000) / 50
           ELSE
              DECODE (CL.UOM_CODE,
                      'MTN', NVL (CL.QUANTITY_ORDERED, 0) * 20,
                      NVL (CL.QUANTITY_ORDERED, 0))
        END)
          CONVERT_BAG_QTY,
       CL.QUANTITY_INVOICED,
       CT.TRX_NUMBER TRANSACTION_NUMBER,
       CT.TRX_DATE,
       CT.BILL_TO_CUSTOMER_ID,
       CT.BILL_TO_SITE_USE_ID,
       CT.SHIP_TO_CUSTOMER_ID,
       CT.SHIP_TO_SITE_USE_ID,
       APPS.XXAKG_ONT_PKG.GET_RETAILER_DELIVERY_LOCATION (
          CT.SHIP_TO_SITE_USE_ID)
          DELIVERY_SITE,
       CT.REMIT_TO_ADDRESS_ID,
       (SELECT    ADDRESS1
               || ','
               || ADDRESS2
               || ','
               || ADDRESS3
               || ','
               || ADDRESS4
          FROM APPS.HZ_LOCATIONS LOC
         WHERE LOC.LOCATION_ID = CT.REMIT_TO_ADDRESS_ID)
          ADDRESS,
       CT.SHIP_DATE_ACTUAL,
       CT.DOC_SEQUENCE_VALUE,
       CT.PAYING_CUSTOMER_ID,
       CT.PAYING_SITE_USE_ID--,CL.ORG_ID
       ,
       CL.UNIT_STANDARD_PRICE,
       CL.UNIT_SELLING_PRICE,
       CL.ATTRIBUTE10 PRICE_LOCATION,
       CL.INTERFACE_LINE_ATTRIBUTE2 ORDER_TYPE,
       CL.REVENUE_AMOUNT,
       CL.ATTRIBUTE11 TRANSPORT_MODE,
       CL.ATTRIBUTE13 DELIVERY_MODE,
       CL.WAREHOUSE_ID,
       DECODE (CL.LINE_TYPE,  'LINE', 'LINE_TOTAL',  'TAX', 'TOTAL_TAX')
          LINE_TYPE,
       DST.AMOUNT,
       DST.GL_DATE,
       DST.GL_POSTED_DATE,
       DST.ACCOUNT_CLASS,
       DST.ACCTD_AMOUNT,
       TT.NAME TRANSACTION_NAME,
       TT.DESCRIPTION TRANSACTION_DESCRIPTION,
       (SELECT DESCRIPTION
          FROM APPS.AR_LOOKUPS VAL
         WHERE LOOKUP_TYPE = 'TRANSACTION TYPE' AND LOOKUP_CODE = TT.TYPE)
          TRANSACTION_TYPE
  --,DECODE (TT.TYPE,
  --                 'CB', 'Chargeback',
  --                 'CM', 'Credit Memo',
  --                 'DM', 'Debit Memo',
  --                 'DEP', 'Deposit',
  --                 'GUAR', 'Guarantee',
  --                 'INV', 'Invoice',
  --                 'PMT', 'Receipt',
  --                 'Others'
  --                ) TRANSACTION_TYPE
  --,DST.ORG_ID
  --,CL.SHIP_TO_CUSTOMER_ID CUSTOMER_ID
  --,CL.SHIP_TO_SITE_USE_ID
  --,CL.*
  --,CT.*
  ,DST.*
  --,TT.*
  FROM APPS.RA_CUSTOMER_TRX_ALL CT,
       APPS.RA_CUSTOMER_TRX_LINES_ALL CL,
       APPS.RA_CUST_TRX_LINE_GL_DIST_ALL DST,
       APPS.RA_CUST_TRX_TYPES_ALL TT
 WHERE     1 = 1
       AND ((:P_ORG_ID IS NULL AND CT.ORG_ID IN (83,84,85,605))  OR (CT.ORG_ID=:P_ORG_ID))
       AND (:P_ORDER_NUMBER IS NULL OR (CL.SALES_ORDER=:P_ORDER_NUMBER))
       AND (:P_ORG_ID IS NULL OR (CT.DOC_SEQUENCE_VALUE=:P_VOUCHER_NUM))
       AND CT.CUSTOMER_TRX_ID = CL.CUSTOMER_TRX_ID
       AND CT.CUSTOMER_TRX_ID = DST.CUSTOMER_TRX_ID
       AND DST.CUSTOMER_TRX_LINE_ID = CL.CUSTOMER_TRX_LINE_ID
       AND CT.CUST_TRX_TYPE_ID = TT.CUST_TRX_TYPE_ID
--       AND APPS.XXAKG_AR_PKG.GET_CUSTOMER_NUMBER_FROM_ID (CT.BILL_TO_CUSTOMER_ID)= :P_CUSTOMER_NUMBER
       AND EXISTS(SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE CT.BILL_TO_CUSTOMER_ID=DBM.CUSTOMER_ID AND DBM.REGION_NAME IN ('Rangpur','Prime Seller','Corporate South','Institutional','Rajshahi'))
       AND TRUNC(DST.GL_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(DST.GL_DATE)) AND NVL(:P_DATE_TO,TRUNC(DST.GL_DATE))
       AND TRUNC(DST.LAST_UPDATE_DATE) BETWEEN NVL(:P_UPDATE_FROM,TRUNC(DST.LAST_UPDATE_DATE)) AND NVL(:P_UPDATE_TO,TRUNC(DST.LAST_UPDATE_DATE))
       --AND DST.GL_DATE = TO_DATE ('10-OCT-2019', 'DD-MON-YYYY')
       ;

-------------------------------------------------------------------------------

SELECT  --' ' ztime, ' ' zutime, '100170'  zid,  CR.DOCUMENT_NUMBER xcrnnum,  NVL (CH.GL_DATE, CR.GL_DATE) xdate, CUST.ATTRIBUTE7 xcus, ' ' xcuspo, ' ' xdatecuspo, ' ' xdiv, 'NUL' xsec,' ' xproj, 'Confirmed' xstatusdor, ' ' xcitem, 'BDT' xcur, 1.00 xexch, (NVL (CH.ACCTD_AMOUNT, CR.FUNCTIONAL_AMOUNT)) xtotamt,' ' xvoucher, ' ' zemail,' ' xemail, CR.REMIT_BANK_NAME xdesc01, CR.REMIT_BANK_ACCOUNT_NUM xdesc02,' ' xdesc03,substr(CBA.SECONDARY_ACCOUNT_REFERENCE,1,7) xaccdr, CBA.SECONDARY_ACCOUNT_REFERENCE xsubdr, 'Subaccount' xaccsource, 'Bank' xaccusage, ' ' xallocation, 0 xbalance
        --select distinct CR.REMIT_BANK_ACCOUNT_NUM,CR.REMIT_BANK_ACCOUNT_NAME,CR.REMIT_BANK_NAME,--CR.REMIT_BANK_NAME||'-'||CR.REMIT_BANK_ACCOUNT_NUM ACCOUNT_NAME,CR.*--,
        --apps.XXAKG_CE_PKG.GET_ASSET_CODE_FROM_ACCOUNT_ID (CR.REMIT_BANK_ACCOUNT_ID) Account_Code --count(CR.DOCUMENT_NUMBER)
        CR.RECEIPT_NUMBER
        ,CR.DOCUMENT_NUMBER
        ,APPS.XXAKG_AR_PKG.GET_REGION_FROM_CUST_ID (CUST.CUST_ACCOUNT_ID)
          REGION
        ,CR.GL_DATE
        --,NVL (CH.GL_DATE, CR.GL_DATE) GL_DATE
        ,CR.REMIT_BANK_ACCOUNT_NUM,CR.REMIT_BANK_ACCOUNT_NAME
        ,CR.REMIT_BANK_ACCOUNT_NUM ACCOUNT_NAME
        ,CR.REMIT_BANK_NAME
        ,NVL (CH.ACCTD_AMOUNT, CR.FUNCTIONAL_AMOUNT) AMOUNT
        ,APPS.XXAKG_CE_PKG.GET_ASSET_CODE_FROM_ACCOUNT_ID (CR.REMIT_BANK_ACCOUNT_ID) ACCOUNT_CODE
        ,CUST.ACCOUNT_NUMBER CUSTOMER_NO
        ,APPS.XXAKG_AR_PKG.GET_CUSTOMER_NAME_FROM_ID (CUST.CUST_ACCOUNT_ID) CUSTOMER_NAME
        ,GCC.SEGMENT1||'.'||GCC.SEGMENT2||'.'||GCC.SEGMENT3||'.'||GCC.SEGMENT4||'.'||GCC.SEGMENT5 GL_ACC_CODE
        --,CBA.*
        --,CH.*
        --,CR.*
        ,RA.*
        ,RA.LAST_UPDATE_DATE
 FROM APPS.XXAKG_AR_CASH_RECEIPTS_V CR,
      APPS.AR_CASH_RECEIPT_HISTORY_ALL CH,
      APPS.CE_BANK_ACCOUNTS CBA,
      APPS.AR_RECEIVABLE_APPLICATIONS_ALL RA,
      APPS.HZ_CUST_ACCOUNTS CUST
      ,APPS.GL_CODE_COMBINATIONS GCC
 WHERE 1=1
      AND CR.CASH_RECEIPT_ID = CH.CASH_RECEIPT_ID
      AND CR.REMIT_BANK_ACCOUNT_ID = CBA.BANK_ACCOUNT_ID(+)
      AND CH.CASH_RECEIPT_HISTORY_ID=RA.CASH_RECEIPT_HISTORY_ID(+)
      AND CR.CASH_RECEIPT_ID = RA.CASH_RECEIPT_ID(+)
      AND CR.CUSTOMER_NUMBER = CUST.ACCOUNT_NUMBER(+)
      --AND CH.ACCOUNT_CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID(+)
      AND RA.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID(+)
      AND ((:P_ORG_ID IS NULL AND CH.ORG_ID IN (83,84,85,605))  OR (CH.ORG_ID=:P_ORG_ID))
      --AND CR.BAL_SEG='2110'
      --AND CR.DOCUMENT_NUMBER='519303108'
      --AND GCC.SEGMENT3='1070201'
      --AND CR.LEGAL_ENTITY_ID='23279'
      --AND BB.BRANCH_PARTY_ID(+) = CBA.BANK_BRANCH_ID
      --AND NVL (CH.CURRENT_RECORD_FLAG, 'N') = 'Y'
      --and NVL (CH.GL_DATE, CR.GL_DATE)>='01-JUL-2017'
      --and NVL (CH.GL_DATE, CR.GL_DATE)<='30-JUN-2018'
      --AND NVL (STATE, 'AKG') <> 'REVERSED'
      --AND CR.CASH_RECEIPT_ID='2430286'
      --AND CR.RECEIPT_STATUS != 'REV'
      --AND CR.TYPE = 'CASH'
      --AND CH.gl_date = TO_DATE ('17-JUN-2019', 'DD-MON-YYYY')
      --AND CR.REMIT_BANK_NAME not in ('AP-AR  Netting Bank','CC-29902001914')
      --AND CR.REMIT_BANK_ACCOUNT_NUM = 'STD-2030155672041'--'CC-29902001914'
      AND EXISTS(SELECT 1 FROM APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM WHERE CUST.CUST_ACCOUNT_ID=DBM.CUSTOMER_ID AND DBM.ORG_ID=85 AND DBM.REGION_NAME IN ('Rangpur','Prime Seller','Corporate South','Institutional','Rajshahi'))
       AND TRUNC(RA.GL_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(RA.GL_DATE)) AND NVL(:P_DATE_TO,TRUNC(RA.GL_DATE))
       AND TRUNC(RA.LAST_UPDATE_DATE) BETWEEN NVL(:P_UPDATE_FROM,TRUNC(RA.LAST_UPDATE_DATE)) AND NVL(:P_UPDATE_TO,TRUNC(RA.LAST_UPDATE_DATE))