SELECT GLCC.SEGMENT1 COMPANY, GLCC.SEGMENT2 LOCATION,
       GLCC.SEGMENT3 COST_CENTER, GLCC.SEGMENT4 ACCOUNT,
       GLCC.SEGMENT5 PRODUCT, GLCC.SEGMENT6 CHANNEL, GLCC.SEGMENT7 PROJECT,
       (SELECT FLEX_VALUE || ' ' || FVT.DESCRIPTION
          FROM APPS.GL_CODE_COMBINATIONS GLC,
               APPS.FND_FLEX_VALUES FV,
               APPS.FND_FLEX_VALUES_TL FVT
         WHERE GLC.CODE_COMBINATION_ID = GJL.CODE_COMBINATION_ID
           AND GLC.SEGMENT4 = FV.FLEX_VALUE
           AND FV.FLEX_VALUE_SET_ID = 1002653
           AND FV.FLEX_VALUE_ID = FVT.FLEX_VALUE_ID) CODE_COMBO_DESC,
       GJH.POSTED_DATE POSTED_ON_DT, GJH.JE_SOURCE, GJH.JE_CATEGORY,
       GJB.NAME JE_BATCH_NAME, GJH.NAME JOURNAL_NAME, '' JE_SEQ_NAME,
       '' JE_SEQ_NUM, GJL.JE_LINE_NUM JE_LINE, GJL.DESCRIPTION JE_LINE_DESCR,
       XAL.ENTERED_CR GLOBAL_CR, XAL.ENTERED_DR GLOBAL_DR,
       XAL.CURRENCY_CODE GLOBAL_CUR, AC.CUSTOMER_NAME VENDOR_CUSTOMER,
       RCTA.TRX_NUMBER TRANSACTION_NUM, RCTA.TRX_DATE TRANSACTION_DATE,
       XAL.ACCOUNTING_CLASS_CODE TRANSACTION_TYPE, XAL.ACCOUNTED_CR LOCAL_CR,
       XAL.ACCOUNTED_DR LOCAL_DR, GL.CURRENCY_CODE LOCAL_CUR,
       (NVL (XAL.ACCOUNTED_DR, 0) - NVL (XAL.ACCOUNTED_CR, 0)
       ) TRANSACTION_AMOUNT,
       GL.CURRENCY_CODE TRANSACTION_CURR_CODE, GJH.PERIOD_NAME FISCAL_PERIOD,
       (GB.BEGIN_BALANCE_DR - GB.BEGIN_BALANCE_CR) BEGIN_BALANCE,
       (  GB.PERIOD_NET_DR
        - GB.PERIOD_NET_CR
        + GB.PROJECT_TO_DATE_DR
        - GB.PROJECT_TO_DATE_CR
       ) END_BALANCE,
       GL.NAME LEDGER_NAME
  FROM APPS.GL_JE_HEADERS GJH,
       APPS.GL_JE_LINES GJL,
       APPS.GL_IMPORT_REFERENCES GIR,
       XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       APPS.GL_CODE_COMBINATIONS GLCC,
       XLA.XLA_TRANSACTION_ENTITIES XTE,
       APPS.RA_CUSTOMER_TRX_ALL RCTA,
       APPS.GL_LEDGERS GL,
       APPS.GL_BALANCES GB,
       APPS.AR_CUSTOMERS AC,
       APPS.GL_JE_BATCHES GJB
 WHERE 1 = 1
   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
   AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
   AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
   AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
   AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
   AND XAL.APPLICATION_ID = XAH.APPLICATION_ID
   AND XAL.CODE_COMBINATION_ID = GLCC.CODE_COMBINATION_ID
   AND XTE.ENTITY_ID = XAH.ENTITY_ID
   --AND XTE.ENTITY_CODE !='TRANSACTIONS' --'ADJUSTMENTS' --TRANSACTIONS
   AND XTE.LEDGER_ID = GL.LEDGER_ID
   AND XTE.APPLICATION_ID = XAL.APPLICATION_ID
   AND NVL (XTE.SOURCE_ID_INT_1, -99) = RCTA.CUSTOMER_TRX_ID
   AND GJH.LEDGER_ID = GL.LEDGER_ID
   AND GB.CODE_COMBINATION_ID = GLCC.CODE_COMBINATION_ID
   AND GB.PERIOD_NAME = GJH.PERIOD_NAME
   AND GB.CURRENCY_CODE = GL.CURRENCY_CODE
   AND GJH.JE_BATCH_ID = GJB.JE_BATCH_ID
   AND RCTA.BILL_TO_CUSTOMER_ID = AC.CUSTOMER_ID(+)
   AND GJH.PERIOD_NAME = 'AUG-19'
   --AND GJH.LEDGER_ID=2025
   --AND glcc.segment1='2300'
   --AND glcc.segment4 = '20330'
   AND GJH.JE_SOURCE = 'Receivables'
   --AND gjl.description='419341684'
--and GJH.name = 'NOV-14 Credit Memos GBP'
--AND TO_CHAR (rcta.trx_date, 'DD-MON-RR') = '27-AUG-19'