SELECT FA.APPLICATION_ID,
       FAT.APPLICATION_NAME ,
       FA.APPLICATION_SHORT_NAME,
       FA.BASEPATH
  FROM APPS.FND_APPLICATION     FA,
       APPS.FND_APPLICATION_TL  FAT
 WHERE FA.APPLICATION_ID = FAT.APPLICATION_ID
    --AND FAT.APPLICATION_NAME = 'PAYABLES' 
    --AND FA.APPLICATION_SHORT_NAME='AK' 
 ORDER BY FAT.APPLICATION_NAME;