SELECT
MOH.VEHICLE_NO,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
MOH.WAREHOUSE_ORG_CODE,
MOH.FINAL_DESTINATION,
MOH.TRANSPORT_MODE,
MOH.TRANSPORTER_NAME,
MOH.INITIAL_GATE_IN,
MOH.GATE_OUT,
MOH.GATE_IN,
MOH.READY_FOR_INVOICE,
MOH.GATE_PASS_NO,
MOH.EMPTY_TRUCK_WT,
MOH.SCALE_IN_WT,
MOH.HIRE_RATE_AP,
TO_CHAR(MOH.CONFIRMED_DATE) CONFIRMED_DATE 
FROM
APPS.XXAKG_MOV_ORD_HDR MOH
,APPS.PQP_VEHICLE_REPOSITORY_F VR
WHERE 1=1
AND VR.VEHICLE_STATUS='A'
AND VR.VRE_ATTRIBUTE3='Road Transport'
AND VR.REGISTRATION_NUMBER=MOH.VEHICLE_NO
--AND MOH.CONFIRMED_DATE<= '30-NOV-2017'
AND TRANSPORT_MODE='Company Truck'
AND TO_CHAR (MOH.CONFIRMED_DATE, 'RRRR') = '2017'
AND MOH.GATE_OUT IS NULL
AND MOH.VEHICLE_NO!='SCIL-SCM-0001'
AND MOH.ORG_ID=85
AND MOH.MOV_ORDER_STATUS IN ('GENERATED','CONFIRMED')
--AND GATE_PASS_NO IS NULL
--AND SCALE_OUT_WT IS NULL
ORDER BY MOH.CONFIRMED_DATE DESC



SELECT
TOH.VEHICLE_NO,
TOH.MOV_ORDER_NO,
TOH.MOV_ORDER_STATUS,
TOH.FROM_INV,
TOH.FINAL_DESTINATION,
TOH.TRANSPORT_MODE,
TOH.TRANSPORTER_NAME,
TOH.INITIAL_GATE_IN,
TOH.GATE_OUT,
TOH.GATE_IN,
TOH.GATE_PASS_NO,
TOH.EMPTY_TRUCK_WT,
TOH.FULL_TRUCK_WT,
TOH.HIRE_RATE_AP,
TO_CHAR(TOH.GATE_OUT_DATE) OUT_DATE 
FROM
XXAKG.XXAKG_TO_MO_HDR TOH
,APPS.PQP_VEHICLE_REPOSITORY_F VR
WHERE 1=1
AND VR.VEHICLE_STATUS='A'
AND VR.VRE_ATTRIBUTE3='Road Transport'
AND VR.REGISTRATION_NUMBER=TOH.VEHICLE_NO
AND TOH.TRANSPORT_MODE='Company Truck'
AND TOH.VEHICLE_NO!='SCIL-SCM-0001'
--AND MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND GATE_OUT IS NULL
AND GATE_IN IS NULL
AND INITIAL_GATE_IN='Y'
--AND AP_FLAG IS NULL
AND ORG_ID=85
--AND VEHICLE_NO=:P_VEHICLE_NO--'D.M.U-11-0949'


SELECT
*
FROM
XXAKG.XXAKG_TO_MO_HDR