SELECT 'MOVE Order' Move_Type,
MOH.MOV_ORD_HDR_ID HEADER_ID,
MOH.MOV_ORDER_NO"MOVE/TRANSFER ORDER NO",
VR.REGISTRATION_NUMBER VEHICLE_NO
--,,TO_CHAR(MOH.MOV_ORDER_DATE,'MON-RR') MOVE_ORDER_DATE
FROM
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.PQP_VEHICLE_REPOSITORY_F VR
WHERE 1=1
AND VR.REGISTRATION_NUMBER=MOH.VEHICLE_NO
AND UPPER(VR.REGISTRATION_NUMBER) LIKE UPPER('%'||:P_Vehicle_No||'%') 
--AND VR.REGISTRATION_NUMBER like ('%'||:p_vehicle||'%')
--AND MOH.VEHICLE_NO=:P_VEHICLE_NO--'D.M.U-11-0949'--'D.M.U-11-1118'--
--AND MOH.MOV_ORDER_DATE BETWEEN '01-OCT-2017' AND '28-OCT-2017'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.GATE_OUT IS NULL
AND MOH.GATE_IN IS NULL
AND MOH.ORG_ID=85
--AND MOH.TRANSPORT_MODE='Company Truck'
--AND MOH.FINAL_DESTINATION IN ('For Loading','AKCL Workshop')
AND VR.VEHICLE_STATUS='A'
--AND VR.VRE_ATTRIBUTE3='Road Transport'
UNION ALL
SELECT 'MOVE Transfer Order' Move_Type,
TOH.MOV_ORD_HDR_ID HEADER_ID,
TOH.MOV_ORDER_NO "MOVE/TRANSFER ORDER NO",
VR.REGISTRATION_NUMBER
--,TO_CHAR(TOH.MOV_ORDER_DATE,'MON-RR') MOVE_ORDER_DATE
FROM
XXAKG.XXAKG_TO_MO_HDR TOH,
APPS.PQP_VEHICLE_REPOSITORY_F VR
WHERE 1=1
AND VR.REGISTRATION_NUMBER=TOH.VEHICLE_NO
AND VR.VEHICLE_STATUS='A'
--AND VR.VRE_ATTRIBUTE3='Road Transport'
AND UPPER(VR.REGISTRATION_NUMBER) LIKE UPPER('%'||:P_Vehicle_No||'%') 
--AND VR.REGISTRATION_NUMBER like ('%'||:p_vehicle||'%')
--AND TOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND GATE_OUT IS NULL
AND GATE_IN IS NULL
AND INITIAL_GATE_IN='Y'
AND ORG_ID=85
--AND VEHICLE_NO=:P_VEHICLE_NO--'D.M.U-11-0949'


