/* Formatted on 9/22/2019 4:29:15 PM (QP5 v5.287) */
SELECT AIA.ORG_ID,
       APS.SEGMENT1 VENDOR_NUMBER,
       APS.VENDOR_NAME,
--       CUST_ACCT.ACCOUNT_NUMBER CUTOMER_NUMBER,
--       PARTY.PARTY_NAME CUSTOMER_NAME,
--       DECODE (RTT.TYPE, 'PMT', 'PAYMENT',
--                                    'CM', 'CREDIT MEMO',
--                                    'INV', 'INVOICES',
--                                    'DM', 'DEBIT MEMO',
--                                       'Not Defined') "PAYMENT TYPE",
       AIA.INVOICE_NUM,
       AIA.INVOICE_AMOUNT,
       AIA.INVOICE_DATE,
       AIA.INVOICE_TYPE_LOOKUP_CODE,
       AIA.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
       TO_CHAR (AIA.GL_DATE) GL_DATE,
       AIA.DESCRIPTION,
--       AIA.CANCELLED_DATE,
       GCC.SEGMENT2 "Cost Centre",
          GCC.SEGMENT1
       || '.'
       || GCC.SEGMENT2
       || '.'
       || GCC.SEGMENT3
       || '.'
       || GCC.SEGMENT4
          "Account",
       GCC.SEGMENT3 "Natural Account",
--       CUST_ACCT.ACCOUNT_NAME,
--       APSA.TRX_NUMBER,
--       APSA.TRX_DATE,
--       LOC.ADDRESS1 ADDRESS,
--       FNDU.USER_NAME USER_ID
       AILA.OVERLAY_DIST_CODE_CONCAT,
       AILA.DESCRIPTION LINE_DESCRIPTION,
--       AIPA.ACCOUNTING_DATE,
--       AIPA.AMOUNT PAYMENT_AMOUNT,
--       AIPA.PERIOD_NAME,
--       AIPA.BANK_ACCOUNT_NUM
--       APSA.GROSS_AMOUNT
--       APSA.PAYMENT_STATUS_FLAG
--       APSA.HOLD_FLAG
--       APSA.PAYMENT_METHOD_CODE
--       ACA.AMOUNT CHECK_AMOUNT,
--       ACA.BANK_ACCOUNT_NAME,
--       ACA.CHECK_DATE
       ASSA.ADDRESS_LINE1 ADDRESS,
       FNDU.USER_NAME USER_ID
  --,AIDA.*
  FROM APPS.AP_INVOICES_ALL AIA,
       APPS.AP_INVOICE_LINES_ALL AILA,
       APPS.AP_SUPPLIERS APS,
       APPS.AP_SUPPLIER_SITES_ALL ASSA,
       --       APPS.AP_PAYMENT_SCHEDULES_ALL APSA,
       --       APPS.AP_INVOICE_PAYMENTS_ALL AIPA,
       --       APPS.AP_CHECKS_ALL ACA
       APPS.AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
       APPS.GL_CODE_COMBINATIONS GCC,
       APPS.FND_USER FNDU
 -------------------------------------------------------
 -- APPS.HZ_CUST_ACCOUNTS CUST_ACCT,
 -- APPS.HZ_CUST_ACCT_SITES_ALL ACCT_SITE,
 -- APPS.HZ_PARTY_SITES PARTY_SITE,
 -- APPS.HZ_PARTIES PARTY,
 -- APPS.HZ_LOCATIONS LOC,
 -- APPS.HZ_CUST_SITE_USES_ALL SITE_USES,
 WHERE     1 = 1
       AND AIA.INVOICE_ID = AILA.INVOICE_ID
       AND AIA.VENDOR_ID = APS.VENDOR_ID
       AND AIA.VENDOR_SITE_ID = ASSA.VENDOR_SITE_ID
       AND APS.VENDOR_ID = ASSA.VENDOR_ID
       --       AND AIA.INVOICE_ID = APSA.INVOICE_ID
       --       AND AIPA.INVOICE_ID = AIA.INVOICE_ID
       --       AND ACA.CHECK_ID(+) = AIPA.CHECK_ID
       AND AIA.INVOICE_ID = AIDA.INVOICE_ID
       AND AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
       AND FNDU.USER_ID = AIA.LAST_UPDATED_BY
       --AND ACA.STATUS_LOOKUP_CODE <> 'VOIDED'
       AND AIA.ORG_ID = 85
       AND AIA.INVOICE_NUM = 'MO/SCOU/1390558'
--       AND INVOICE_TYPE_LOOKUP_CODE not IN ('MIXED','CREDIT','PREPAYMENT','STANDARD','PAYMENT REQUEST','DEBIT','EXPENSE REPORT')
--       AND ac.check_date BETWEEN TO_DATE ('01-Apr-2014', 'DD-MON-YYYY') AND TO_DATE ('30-Jun-2014 23:59:59', 'DD-MON-YYYY HH24:MI:SS')