SELECT
OOH.ORG_ID,
OOD.ORGANIZATION_NAME,
OOD.ORGANIZATION_CODE,
--RT.ORGANIZATION_ID,
--OOH.ORDER_TYPE_ID,
OOH.ORDER_NUMBER,
TO_CHAR(OOH.ORDERED_DATE,'DD-MON-YYYY HH24:MI:SS') ORDERED_DATE,
OOL.ORDERED_ITEM,
--OOL.INVENTORY_ITEM_ID,
RSL.ITEM_DESCRIPTION,
--RT.UOM_CODE,
RSL.UNIT_OF_MEASURE,
OOL.ORDERED_QUANTITY,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT,
OOL.INVOICED_QUANTITY,
TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'DD-MON-RR HH24:MI:SS') INVOICE_DATE,
OOL.FLOW_STATUS_CODE,
RSH.RECEIPT_NUM "RECEIPT/GRN NUMBER",
TO_CHAR (RSL.CREATION_DATE,'DD-MON-RR HH24:MI:SS') GRN_DATE,
--RSL.QUANTITY_SHIPPED,
--RSL.QUANTITY_RECEIVED,
RT.TRANSACTION_TYPE,
--RT.QUANTITY,
RT.SUBINVENTORY
--,RT.DESTINATION_CONTEXT
--RT.CUSTOMER_ID
--RT.CUSTOMER_SITE_ID
--,RSH.EMPLOYEE_ID
--,RSH.CUSTOMER_ID
,(CASE WHEN RT.TRANSACTION_TYPE='RECEIVE' THEN NVL(RT.QUANTITY,0)
     END) Received_Quantity
,(CASE WHEN RT.TRANSACTION_TYPE='ACCEPT' THEN NVL(RT.QUANTITY,0)
     END) Accepted_Quantity
,(CASE WHEN RT.TRANSACTION_TYPE='DELIVER' THEN NVL(RT.QUANTITY,0)
     END) Delivered_Quantity
,(CASE WHEN RT.TRANSACTION_TYPE='TRANSFER' THEN NVL(RT.QUANTITY,0)
     END) Transfered_Quantity
,(CASE WHEN RT.TRANSACTION_TYPE='REJECT' THEN NVL(RT.QUANTITY,0)
     END) Rejected_Quantity
,RSL.SHIPMENT_LINE_STATUS_CODE
,(SELECT EMPLOYEE_NUM FROM APPS.HR_EMPLOYEES EMP WHERE EMP.EMPLOYEE_ID=RT.EMPLOYEE_ID) EMPLOYEE_NUM
,(SELECT FULL_NAME FROM APPS.HR_EMPLOYEES EMP WHERE EMP.EMPLOYEE_ID=RT.EMPLOYEE_ID) FULL_NAME
--,RT.INTERFACE_TRANSACTION_ID
--,RT.TRANSACTION_ID
--,MIL.*
FROM
APPS.RCV_TRANSACTIONS RT,
APPS.RCV_SHIPMENT_HEADERS RSH,
APPS.RCV_SHIPMENT_LINES RSL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.OE_ORDER_LINES_ALL OOL
--,APPS.MTL_ITEM_LOCATIONS MIL
--,APPS.MTL_TRANSACTIONS_INTERFACE MTI
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 1=1
AND RSH.ORGANIZATION_ID=OOD.ORGANIZATION_ID
--AND RT.LOCATION_ID=MIL.INVENTORY_LOCATION_ID
AND RT.SHIPMENT_HEADER_ID=RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID=RSL.SHIPMENT_HEADER_ID
AND RT.OE_ORDER_HEADER_ID=OOH.HEADER_ID
AND RT.OE_ORDER_LINE_ID=OOL.LINE_ID
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=RSL.ITEM_ID
--AND MTI.TRANSACTION_INTERFACE_ID=RT.INTERFACE_TRANSACTION_ID
--AND OOL.INVENTORY_ITEM_ID=MTI.INVENTORY_ITEM_ID
--AND OOH.ORDER_TYPE_ID='1014'
AND RSH.ORGANIZATION_ID=606
--AND RSH.RECEIPT_NUM=16231
--AND RSH.RECEIPT_NUM=:P_RECEIPT_NUM
AND OOH.ORDER_NUMBER IN ('197000030')--=:P_ORDER_NUMBER
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
--AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'OCT-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-RR') = '27-SEP-18'
AND RT.SOURCE_DOCUMENT_CODE='RMA'
AND TRANSACTION_TYPE IN ('ACCEPT','DELIVER','RECEIVE','TRANSFER','REJECT')
ORDER BY RT.TRANSACTION_DATE



------------------------------------------------------------------------------------------------


SELECT
ORG_ID,
CUSTOMER_ID,
CUSTOMER,
CUSTOMER_SITE_ID,
--TO_ORGANIZATION_ID,
ORGANIZATION_ID,
TRANSACTION_DATE,
TRANSACTION_TYPE,
PRIMARY_UOM,
ITEM_ID,
ITEM_DESC,
DESTINATION_TYPE_CODE,
SHIP_TO_LOCATION,
EMPLOYEE_ID,
RECEIVER,
SOURCE_DOC_CODE,
SUBINVENTORY,
SOURCE_DOC_QTY,
SOURCE_TYPE,
INSPECTION_STATUS_CODE,
RECEIPT_NUM,
RECEIPT_DATE,
ORDER_NUM,
QUANTITY_ORDERED,
ROUTING
FROM
APPS.RCV_VRC_TXS_V
WHERE 1=1
AND RECEIPT_NUM='1095'
AND ORGANIZATION_ID='606'
