/* Formatted on 10/11/2018 10:29:07 AM (QP5 v5.136.908.31019) */
SELECT *
  FROM APPS.RCV_VRC_TXS_CUST_V
 WHERE 1 = 1 
 AND RECEIPT_NUM = '1095' 
 AND ORGANIZATION_ID = '606'
 
SELECT
*
FROM
APPS.RCV_VRC_TXS_V
WHERE 1=1
AND RECEIPT_NUM='1095'
AND ORGANIZATION_ID='606'
AND ROWNUM<=3


SELECT
*
FROM
APPS.RCV_VRC_HDS_V
WHERE 1=1
AND RECEIPT_NUM='1095'
AND ORGANIZATION_ID='606'
AND ROWNUM<=3


SELECT
--OOH.*,
OOL.*
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOH.ORDER_NUMBER IN ('197000305')
--AND OOL.FLOW_STATUS_CODE NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND ROWNUM<=2
--AND OOL.SHIPMENT_PRIORITY_CODE='DO/MOU/13984'


SELECT
--              PHA.PO_HEADER_ID,
--              PHA.SEGMENT1 "po number",
--              RSH.RECEIPT_NUM "receipt number"
RSL.*
FROM
--APPS.PO_HEADERS_ALL PHA,
          APPS.RCV_SHIPMENT_LINES  RSL,
          APPS.RCV_SHIPMENT_HEADERS RSH
WHERE  1=1
--AND     PHA.PO_HEADER_ID=RSL.PO_HEADER_ID
AND     RSL.SHIPMENT_HEADER_ID=RSH.SHIPMENT_HEADER_ID
--AND     PHA.SEGMENT1='200300' --PO NUMBER
AND RSH.RECEIPT_NUM='1080'
AND SOURCE_DOCUMENT_CODE='RMA'
--AND SHIPMENT_LINE_ID='1315959'
AND RSH.SHIPMENT_HEADER_ID='850030'

SELECT
*
FROM
APPS.RCV_SHIPMENT_HEADERS
WHERE 1=1
AND RECEIPT_NUM=1095
AND ORGANIZATION_ID=606
--JOINED BY SHIPMENT_HEADER_ID, RECEIPT_SOURCE_CODE, VENDOR_ID, VENDO_SITE_ID, ORGANIZATION_ID, SHIPMENT_NUM, RECEIPT_NUM,
--FIND OUT EMPLOYEE_ID, CUSTOMER_ID

SELECT
*
FROM
APPS.RCV_SHIPMENT_LINES RSL
WHERE 1=1
--AND SHIPMENT_LINE_ID='1315959'
AND RSL.SHIPMENT_HEADER_ID='850030'


SELECT
*
FROM
APPS.RCV_TRANSACTIONS
WHERE 1=1
--JOINED BY TRANSACTION_ID, QUANTITY, SHPMENT_HEADER_ID, SHIPMENT_LINE_ID, EMPLOYEE_ID, VENDOR_ID, VENDOR_SITE_ID,
--SEARCH BY TRANSACTION_TYPE,
--FIND OUT UINIT_OF_MEASURE, SUBINVENTORY,


SELECT
*
FROM
APPS.MTL_TRANSACTIONS_INTERFACE MTI
WHERE 1=1
--AND MTI.TRANSACTION_INTERFACE_ID=2827173






SELECT
*
FROM
APPS.ORG_ORGANIZATION_DEFINITIONS
WHERE 1=1
--OPERATING UNIT: LEDGER_ID--MASTER_ORG
--ORGANIZATION_NAME--ORGANIZATION_CODE
--ORGANIZATION_ID: SUB-LEDGER_ID
--BUSINESS_GROUP_ID: INVENTORY_ID