SELECT
MODIFIER_NAME
,PRODUCT_ATTRIBUTE_TYPE
,PRODUCT_ATTR_VALUE ITEM_CATEGORY
,MOD_LINE_NO
,ADJUST_RATE
,ARITHMETIC_OPERATOR
,START_DATE
,END_DATE
--,DIS.*
FROM
APPS.XXAKG_QP_MODIFIER_DISCOUNT_V DIS
WHERE 1=1
AND MODIFIER_NAME IN ('CER General Commission','CER Year End Commission','CER Broken Commission','CER Viola Commission','CER WC & WT Commission for B Grade')
--='CER WC & WT Commission for B Grade'-- 
AND END_DATE IS NULL
--AND TO_CHAR(START_DATE,'DD-MON-RRRR')='11-JUN-219'
AND AUTOMATIC_FLAG='Y'
AND SOURCE='Line'
--AND PRODUCT_ATTR_VALUE=:P_ITEM_CATEGORY