SELECT
OOL.LINE_ID LINE_NUMBER,
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
TO_CHAR(OOH.ORDERED_DATE)ORDERED_DATE,
OOD.ORGANIZATION_CODE,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*SUM(OOL.ORDERED_QUANTITY)) AMOUNT
,TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE) INVOICE_DATE
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
,APPS.MTL_SYSTEM_ITEMS_B MSIB
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=MSIB.INVENTORY_ITEM_ID
AND OOL.SHIP_FROM_ORG_ID=MSIB.ORGANIZATION_ID
AND OOD.ORGANIZATION_ID=MSIB.ORGANIZATION_ID
AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOH.ORDER_TYPE_ID=1173--1099
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JAN-18'
--AND TO_CHAR (DOH.OR, 'RRRR') = '2017'
AND OOH.ORG_ID=83
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER
GROUP BY
OOL.LINE_ID,
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE ,
OOH.ORDERED_DATE,
OOD.ORGANIZATION_CODE,
OOL.UNIT_SELLING_PRICE,
OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY
,OOL.ACTUAL_SHIPMENT_DATE


--------------------------------------------------------------------------------------


SELECT
ORGANIZATION_NAME,
ORGANIZATION_CODE,
--ORDERED_DATE,
--ORDER_NUMBER,
--ORDERED_ITEM,
--ORDER_QUANTITY_UOM,
--UNIT_SELLING_PRICE,
--UNIT_LIST_PRICE,
--ORDERED_QUANTITY,
SUM(INVOICED_QUANTITY) QUANTITY,
SUM(ORDERED_AMT) AMOUNT
--DELIVERY_DATE,
--FLOW_STATUS_CODE,
--DO_NUMBER,
--PERIOD
--,ORD.*
FROM
APPS.XXAKG_HEADER_DETAIL_V ORD
WHERE 1=1
AND ORG_ID=83
AND PERIOD='JAN-18'
AND FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
ORGANIZATION_NAME,
ORGANIZATION_CODE


-------------------------------SALES_RETURN_AMOUNT---------------------------------

SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY ,
OOL.ORDER_QUANTITY_UOM,
--OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
TO_CHAR(OOH.ORDERED_DATE) ORDERED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
,TO_CHAR(OOL.ACTUAL_SHIPMENT_DATE) INVOICE_DATE
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
--AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOH.ORDER_TYPE_ID=1177--1173
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JAN-18'
--AND TO_CHAR (DOH.OR, 'RRRR') = '2017'
--AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
--AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
AND OOH.ORG_ID=83
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER
