SELECT
ORGANIZATION_NAME,
ORGANIZATION_CODE,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
--OOH.ORDER_NUMBER,
--DOH.DO_NUMBER,
(SELECT DESCRIPTION FROM INV.MTL_SYSTEM_ITEMS_B MSI WHERE MSI.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID= OOL.SHIP_FROM_ORG_ID) ITEM_DESCRIPTION,
SUM(OOL.ORDERED_QUANTITY) QUANTITY
--(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT,
--OOL.ORDER_QUANTITY_UOM UOM_CODE,
--MOH.MOV_ORDER_NO,
--MODT.VAT_CHALLAN_NO,
--NVL(MODT.CHALLAN_NO,MOH.GATE_PASS_NO)  "Delivery Challan NO"
--,TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'DD-MON-YYYY') INVOICE_DATE
--OOD.*
FROM
APPS.XXAKG_DEL_ORD_HDR DOH,
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH,
APPS.XXAKG_MOV_ORD_HDR MOH,
APPS.XXAKG_MOV_ORD_DTL MODT
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 1=1
AND DOH.ORG_ID=84
AND OOD.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=MODT.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND OOH.HEADER_ID=OOL.HEADER_ID 
AND OOL.SHIPMENT_PRIORITY_CODE=DOH.DO_NUMBER 
AND OOL.ORG_ID=DOH.ORG_ID   
--AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-JAN-2017' and '31-JAN-2019'
AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'JUN-19'
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'RRRR') = '2019'
--AND OOL.SHIP_FROM_ORG_ID='201'
--AND OOD.ORGANIZATION_CODE IN ('RMT','RMV') --RMC
and MOH.MOV_ORDER_STATUS='CONFIRMED'
AND DOH.DO_STATUS='CONFIRMED'
--AND MOH.MOV_ORDER_NO=:P_MOV_ORDER_NO
--AND MOH.CONFIRMED_DATE BETWEEN '05-NOV-2016' and '16-JUL-2017'
--AND DOH.CUSTOMER_NUMBER IN ('183720')
--AND OOH.ORDER_TYPE_ID=1099
AND OOL.FLOW_STATUS_CODE IN ('CLOSED','SHIPPED')
GROUP BY
ORGANIZATION_NAME,
ORGANIZATION_CODE,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME
,OOL.INVENTORY_ITEM_ID
,OOL.SHIP_FROM_ORG_ID
--OOH.ORDER_NUMBER,
--DOH.DO_NUMBER,
--OOL.ORDER_QUANTITY_UOM,
--MOH.MOV_ORDER_NO,
--MODT.VAT_CHALLAN_NO,
--MOH.GATE_PASS_NO
--,(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY)
--,MODT.CHALLAN_NO
--,OOL.ACTUAL_SHIPMENT_DATE
--ORDER BY OOL.ACTUAL_SHIPMENT_DATE DESC