SELECT 
DBM.REGION_NAME,
DBM.CUSTOMER_NUMBER,
DBM.CUSTOMER_NAME,
DOH.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) QUANTITY,
MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
MOH.VEHICLE_NO,
DODL.ITEM_DESCRIPTION
FROM 
APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
XXAKG.XXAKG_MOV_ORD_HDR MOH,
XXAKG.XXAKG_MOV_ORD_DTL MODT,
XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1
AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_NUMBER=MODT.DO_NUMBER
AND DOH.DO_NUMBER=DODL.DO_NUMBER
AND DBM.REGION_NAME!='Scrap'
AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
AND DOH.ORG_ID=84
AND DOH.ORG_ID=MOH.ORG_ID
AND DOH.DO_STATUS='CONFIRMED'
AND MOH.MOV_ORDER_STATUS='CONFIRMED'
AND EXISTS (SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OOL WHERE OOL.LINE_ID=DODL.ORDER_LINE_ID AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING')
--AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2017'
AND TO_CHAR (DOH.DO_DATE, 'MON-RR') = 'FEB-18'
--AND DOH.DO_DATE<=SYSDATE
GROUP BY 
DBM.REGION_NAME,
DBM.CUSTOMER_NUMBER,
DBM.CUSTOMER_NAME,
DOH.DO_NUMBER,
MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
MOH.VEHICLE_NO,
DODL.ITEM_DESCRIPTION