SELECT
OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
OOL.ORDER_QUANTITY_UOM UOM,
SUM(OOL.ORDERED_QUANTITY) QUANTITY,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
TO_CHAR(OOH.ORDERED_DATE,'DD-MON-YYYY HH24:MI:SS') ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
OOD.ORGANIZATION_CODE,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*SUM(OOL.ORDERED_QUANTITY)) AMOUNT
,MMT.TRANSACTION_DATE
--,OOL.*
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
,APPS.MTL_SYSTEM_ITEMS_B MSIB
,APPS.MTL_MATERIAL_TRANSACTIONS MMT
WHERE 1=1
AND MMT.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
AND MMT.SOURCE_LINE_ID=OOL.LINE_ID
AND MMT.INVENTORY_ITEM_ID=OOL.INVENTORY_ITEM_ID
AND OOL.SHIPMENT_PRIORITY_CODE=:P_SHIPMENT_PRIORITY_CODE
AND MMT.SOURCE_CODE='ORDER ENTRY'
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.INVENTORY_ITEM_ID=MSIB.INVENTORY_ITEM_ID
AND OOL.SHIP_FROM_ORG_ID=MSIB.ORGANIZATION_ID
AND OOD.ORGANIZATION_ID=MSIB.ORGANIZATION_ID
AND OOL.FLOW_STATUS_CODE IN ('SHIPPED','CLOSED')--='AWAITING_SHIPPING'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOH.ORDER_TYPE_ID=1105--1099
--AND OOL.ACTUAL_SHIPMENT_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND MMT.TRANSACTION_DATE BETWEEN '01-FEB-2018' AND '19-FEB-2018'
--AND TO_CHAR (MMT.TRANSACTION_DATE, 'DD-MON-RR') = '19-FEB-18'
--AND TO_CHAR (MMT.TRANSACTION_DATE, 'MON-RR') = 'FEB-18'
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'FEB-18'
--AND TO_CHAR (DOH.ACTUAL_SHIPMENT_DATE, 'RRRR') = '2017'
--AND OOL.ACTUAL_SHIPMENT_DATE IS NOT NULL
--AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
AND OOH.ORG_ID=84
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER
GROUP BY
OOH.ORDER_NUMBER,
--OOL.ORDERED_ITEM,
MSIB.DESCRIPTION,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE ,
OOH.ORDERED_DATE,
--OOL.SHIP_FROM_ORG_ID ,
OOD.ORGANIZATION_CODE,
--OOL.FLOW_STATUS_CODE,
--OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY
,MMT.TRANSACTION_DATE
--,OOL.*