SELECT
RT.ORGANIZATION_ID,
RSL.QUANTITY_SHIPPED,
RSL.QUANTITY_RECEIVED,
--RSL.UNIT_OF_MEASURE,
RSL.ITEM_DESCRIPTION,
RT.TRANSACTION_TYPE,
RT.QUANTITY,
RT.UOM_CODE,
RT.SUBINVENTORY,
--,RT.DESTINATION_CONTEXT
--RT.CUSTOMER_ID
--RT.CUSTOMER_SITE_ID
--,RSH.EMPLOYEE_ID
--,RSH.CUSTOMER_ID
RSH.RECEIPT_NUM
--,RT.INTERFACE_TRANSACTION_ID
--,RT.TRANSACTION_ID
,RT.*
FROM
APPS.RCV_TRANSACTIONS RT,
APPS.RCV_SHIPMENT_HEADERS RSH,
APPS.RCV_SHIPMENT_LINES RSL
--,APPS.MTL_MATERIAL_TRANSACTIONS MMT
--APPS.MTL_SYSTEM_ITEMS_B MSI
--,APPS.PO_HEADERS_ALL PHA
--,APPS.PO_LINES_ALL PLA
--,APPS.MTL_TRANSACTIONS_INTERFACE MTI
WHERE 1=1
--AND MMT.TRANSACTION_ID(+)=RT.TRANSACTION_ID
--AND RT.PO_HEADER_ID=PHA.PO_HEADER_ID
--AND PLA.PO_HEADER_ID=PHA.PO_HEADER_ID
--AND RT.PO_LINE_ID=PLA.PO_LINE_ID
--AND RT.ORGANIZATION_ID=MSI.ORGANIZATION_ID
AND RT.SHIPMENT_HEADER_ID=RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID=RSL.SHIPMENT_HEADER_ID
--AND MSI.INVENTORY_ITEM_ID=RSL.ITEM_ID
--AND MTI.TRANSACTION_INTERFACE_ID=RT.INTERFACE_TRANSACTION_ID
--AND OOL.INVENTORY_ITEM_ID=MTI.INVENTORY_ITEM_ID
--AND OOH.ORDER_TYPE_ID='1014'
AND RSH.ORGANIZATION_ID=95
--AND RSH.RECEIPT_NUM=1072
AND RSH.RECEIPT_NUM=:P_RECEIPT_NUM
--AND TRANSACTION_TYPE IN ('TRANSFER','ACCEPT','DELIVER','RECEIVE','REJECT','RETURN TO VENDOR','CORRECT','RETURN TO RECEIVING','UNORDERED','RETURN TO CUSTOMER')
--AND RT.SOURCE_DOCUMENT_CODE='PO'


SELECT
*
FROM
APPS.MTL_MATERIAL_TRANSACTIONS
WHERE 1=1
AND TRANSACTION_ID=32008
--32008