--------------------------------------------------------------------------------
SELECT
--TDL.TO_NUMBER,
--TDH.TO_STATUS,
TMH.MOV_ORDER_NO,
TO_CHAR(TMH.MOV_ORDER_DATE) MOV_ORDER_DATE,
TMH.MOV_ORDER_STATUS,
TDL.TO_INV TO_WAREHOUSE,
APPS.XXAKG_COM_PKG.GET_ORGANIZATION_NAME (TDL.TO_ORGANIZATION_ID) TO_WAREHOUSE_NAME,
TMH.FINAL_DESTINATION,
--TMH.FROM_INV MOVE_WH_ORG_CODE,
TMH.TRANSPORT_MODE,
TMH.GATE_OUT,
TMH.GATE_IN,
TMH.READY_FOR_INVOICE
--TDL.ITEM_NUMBER,
--TDL.ITEM_DESCRIPTION,
--TDL.UOM_CODE,
--TMH.VEHICLE_NO
--TMH.INITIAL_GATE_IN,
--,TO_CHAR(TDH.TO_DATE) To_DATE
--,TDL.FROM_SUBINV
--,TDL.TO_SUBINV
--,TDL.QUANTITY
--,TDH.TO_STATUS
--,TMH.MOV_ORDER_STATUS
--,NVL(TMD.CHALLAN_NO,TMH.GATE_PASS_NO) CHALLAN_NUMBER
--,TMH.*
--,TDL.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH,
APPS.XXAKG_TO_MO_DTL TMD,
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
WHERE 1=1
AND TMH.ORG_ID=85
AND TMD.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
--AND TDH.TO_STATUS='GENERATED'
AND TMH.MOV_ORDER_STATUS='CONFIRMED'
--AND TMH.MOV_ORDER_NO='MTO/SCOU/054916'
--AND TDL.TO_NUMBER='TO/SCOU/087983'
--AND  TMH.TRANSPORT_MODE='Company Barge'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND NVL(TMH.GATE_PASS_NO,0)='0'
--AND TMH.GATE_PASS_NO IS NOT NULL
--AND TMH.FROM_INV='SCI'
--AND TDL.TO_INV='G10'
--AND TMH.GATE_IN='Y'
--AND TMH.GATE_OUT!='Y'
AND TMH.READY_FOR_INVOICE='N'
--AND TMH.VEHICLE_NO='D.M.U-11-1034'
AND EXISTS (SELECT 1 FROM INV.MTL_MATERIAL_TRANSACTIONS MMT WHERE MMT.SHIPMENT_NUMBER=TDL.TO_NUMBER AND TRUNC(MMT.TRANSACTION_DATE)<=NVL(:P_DATE_UPTO,SYSDATE))
ORDER BY GATE_IN_DATE DESC;



--------------------------------------------------------------------------------
SELECT
--TDL.TO_NUMBER,
--TDH.TO_STATUS,
TMH.MOV_ORDER_NO,
TO_CHAR(TMH.MOV_ORDER_DATE) MOV_ORDER_DATE,
TMH.MOV_ORDER_STATUS,
TMH.FINAL_DESTINATION,
TMH.FROM_INV MOVE_WH_ORG_CODE,
TMH.TRANSPORT_MODE,
TMH.GATE_OUT,
TMH.GATE_IN,
TMH.READY_FOR_INVOICE
,TMH.HIRE_RATE_AP
--,TMH.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH
WHERE 1=1
AND TMH.ORG_ID=85
--AND TMH.MOV_ORDER_STATUS='GENERATED'
AND TMH.MOV_ORDER_STATUS='CONFIRMED'
AND TMH.READY_FOR_INVOICE='N'
--AND TMH.MOV_ORDER_NO='MTO/SCOU/054916'
--AND TDL.TO_NUMBER='TO/SCOU/087983'
--AND  TMH.TRANSPORT_MODE='Company Barge'
AND TRUNC(TMH.MOV_ORDER_DATE)<=NVL(:P_DATE_UPTO,SYSDATE)
--AND TRUNC(TMH.MOV_ORDER_DATE)<='31-JUL-2019'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND NVL(TMH.GATE_PASS_NO,0)='0'
--AND TMH.GATE_PASS_NO IS NOT NULL
--AND TMH.FROM_INV='SCI'
--AND TMH.GATE_IN='Y'
--AND TMH.GATE_OUT!='Y'
--AND TMH.VEHICLE_NO='D.M.U-11-1034'
ORDER BY GATE_IN_DATE DESC

