----------------------*****TO*****----------------------------------------------
SELECT
TDL.TO_NUMBER
,TDH.TO_STATUS
,TDL.ITEM_NUMBER
,TDL.ITEM_DESCRIPTION
,TDL.QUANTITY
,TDL.UOM_CODE
,'SCI' FROM_INV
,TDL.FROM_SUBINV
,TDL.TO_INV
,TDL.TO_SUBINV
,TO_CHAR(TDH.TO_DATE) To_DATE
--,TDH.*
--,TDL.*
FROM
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
WHERE 1=1
AND TDH.ORG_ID=85
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_STATUS='GENERATED'   --GENERATED --CONFIRMED
--AND TO_CHAR (TDH.TO_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TDH.TO_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TDH.TO_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND TDH.PLANNING_STATUS!='Planned'
--AND TDL.TO_NUMBER='TO/SCOU/092959'
ORDER BY TDH.TO_DATE DESC

---------------------*****MTO*****----------------------------------------------
SELECT
TMH.MOV_ORDER_NO,
TMH.MOV_ORDER_STATUS,
TMH.FROM_INV,
TMH.FINAL_DESTINATION,
TMH.TRANSPORT_MODE,
TMH.VEHICLE_NO
,TO_CHAR(TMH.MOV_ORDER_DATE) MTO_DATE
,TMH.INITIAL_GATE_IN
,TMH.GATE_OUT
,TMH.GATE_IN
,TMD.TO_NUMBER
,TMD.TO_INV
,TMD.CHALLAN_NO
--,TMH.*
,TMD.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH
,APPS.XXAKG_TO_MO_DTL TMD
WHERE 1=1
AND TMH.ORG_ID=85
AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
AND TMH.MOV_ORDER_STATUS='CONFIRMED'  --GENERATED --CONFIRMED
--AND TMH.MOV_ORDER_NO='MTO/SCOU/054916'
--AND  TMH.TRANSPORT_MODE='Company Barge'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND NVL(TMH.GATE_PASS_NO,0)='0'
--AND TMH.GATE_PASS_NO IS NOT NULL
--AND TMH.FROM_INV='SCI'
--AND TMH.GATE_IN='Y'
AND TMH.GATE_OUT!='Y'
--AND TMH.VEHICLE_NO='D.M.U-11-1034'
ORDER BY GATE_IN_DATE DESC

---------------------*****TO-MTO-VIEW*****--------------------------------------
SELECT TO_CHAR(MTO.MOV_ORDER_DATE) MOV_ORDER_DATE,
TO_STATUS,
TRANSFER_ORDER_NO,
MOV_ORDER_NO,
MOV_ORDER_STATUS
FROM
APPS.XXAKG_TO_MO_DETAIL_CEMENT MTO
WHERE 1=1
AND TO_STATUS='GENERATED'
AND MOV_ORDER_STATUS='CONFIRMED'
AND TO_CHAR(MTO.MOV_ORDER_DATE,'RRRR')='2018'


---------------------*****MTO DETAILS*****--------------------------------------
SELECT
*
FROM
XXAKG.XXAKG_TO_MO_HDR
--JOIN BY MOV_ORD_HDR_ID, ORG_ID, MOV_ORDER_NO, 
--FIND OUT GATE_PASS_NO, FINAL_DESTINATION, FROM_INV, TRANSPORT_MODE, VEHICLE_NO, HIRE_RATE
--CONDITIONED_BY GATE_OUT, GATE_IN, VEHICLE_TYPE, TRNASPORTER_NAME, INITIAL_GATE_IN, EMPTY_TRUCK_WT, FULL_TRUCK_WT, 


SELECT
*
FROM
XXAKG.XXAKG_TO_MO_DTL
--JOINED BY MOVE_ORD_HDR_ID, MOV_ORD_DTL_ID, TO_HDR_ID, TO_NUMBER,
--FIND OUT TO_INV, FROM_INV, VAT_CHALLAN_NO,
--CONDITIONED BY CONFIRM_FLAG, TRANSFER_LOADING_FLAG, TRUCK_LOADING_FLAG, VAT_RECEIVED_FLAG, CHALLANED_FLAG, VAT_IN_FLAG

