SELECT
TDL.TO_NUMBER,
--TDH.TO_STATUS,
TMH.MOV_ORDER_NO,
--TMH.MOV_ORDER_STATUS,
TDL.ITEM_NUMBER,
TDL.ITEM_DESCRIPTION,
--TDL.UOM_CODE,
--TMH.FROM_INV,
TDL.TO_INV,
TMH.FINAL_DESTINATION,
TMH.TRANSPORT_MODE,
TMH.VEHICLE_NO
--TMH.INITIAL_GATE_IN,
--TMH.GATE_OUT,
--TMH.GATE_IN
,TO_CHAR(TDH.TO_DATE) To_DATE
,TO_CHAR(TMH.MOV_ORDER_DATE) MTO_DATE
,TDL.FROM_SUBINV
,TDL.TO_SUBINV
,TDL.QUANTITY
,TDH.TO_STATUS
,TMH.MOV_ORDER_STATUS
,NVL(TMD.CHALLAN_NO,TMH.GATE_PASS_NO) CHALLAN_NUMBER
,TMH.GATE_OUT
,TMH.GATE_IN
,TMH.READY_FOR_INVOICE
,(SELECT TO_CHAR(MMT.CREATION_DATE,'DD-MON-YYYY HH24:MI:SS') FROM INV.MTL_MATERIAL_TRANSACTIONS MMT WHERE MMT.SHIPMENT_NUMBER=TDL.TO_NUMBER AND MMT.ORGANIZATION_ID=TDL.FROM_ORGANIZATION_ID) CONFIRMED_DATE
--,TMH.*
--,TMD.*
--,TDH.*
--,TDL.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH,
APPS.XXAKG_TO_MO_DTL TMD,
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
WHERE 1=1
AND TMH.ORG_ID=85
AND TMD.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
--AND NVL(TDL.RECORD_STATUS,TDH.TO_STATUS)='CONFIRMED'
--AND TDH.TO_STATUS='CONFIRMED'
--AND TMH.MOV_ORDER_STATUS='GENERATED'
AND     (:P_TO_NUMBER IS NULL OR (TDH.TO_NUMBER = :P_TO_NUMBER))
AND     (:P_MTO_NUMBER IS NULL OR (TMH.MOV_ORDER_NO = :P_MTO_NUMBER))
AND     (:P_VEHICLE_NO IS NULL OR (TMH.VEHICLE_NO = :P_VEHICLE_NO))
--      AND TRUNC(TDH.TO_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(TDH.TO_DATE)) AND NVL(:P_DATE_TO,TRUNC(TDH.TO_DATE))
      AND TRUNC(TMH.MOV_ORDER_DATE) BETWEEN NVL(:P_MOVE_DATE_FROM,TRUNC(TMH.MOV_ORDER_DATE)) AND NVL(:P_MOVE_DATE_TO,TRUNC(TMH.MOV_ORDER_DATE))
      --AND TRUNC(TMH.CONFIRMED_DATE) BETWEEN NVL(:P_CONFIRMED_DATE_FROM,TRUNC(TMH.CONFIRMED_DATE)) AND NVL(:P_CONFIRMED_DATE_TO,TRUNC(TMH.CONFIRMED_DATE))
--AND TMH.MOV_ORDER_NO IN ('MTO/SCOU/076719')
--AND TDL.TO_NUMBER IN ('TO/SCOU/087983')
--AND  TMH.TRANSPORT_MODE IN ('Company Barge')
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND NVL(TMH.GATE_PASS_NO,0)='0'
--AND TMH.GATE_PASS_NO IS NOT NULL
--AND TMH.FROM_INV='SCI'
--AND TDL.TO_INV='G10'
--AND TMH.INITIAL_GATE_IN='Y'
--AND TMH.GATE_IN IS NULL
--AND TMH.GATE_OUT!='Y'
--AND TMH.READY_FOR_INVOICE!='Y'
--AND TMH.VEHICLE_NO='D.M.U-11-1034'
--AND TMD.CHALLAN_NO IN ('SCI/TO/115467')
--AND NOT EXISTS (SELECT 1 FROM APPS.AP_INVOICES_ALL AIA WHERE AIA.INVOICE_NUM=TMH.MOV_ORDER_NO)
AND EXISTS (SELECT 1 FROM INV.MTL_MATERIAL_TRANSACTIONS MMT WHERE MMT.SHIPMENT_NUMBER=TDL.TO_NUMBER)
ORDER BY GATE_IN_DATE DESC


