----------------------------------TO_GENERATED----------------------------------
SELECT
TDL.TO_NUMBER,
TDH.TO_STATUS,
--TMH.MOV_ORDER_NO,
--TMH.MOV_ORDER_STATUS,
TDL.ITEM_NUMBER,
TDL.ITEM_DESCRIPTION,
TDL.UOM_CODE,
TDL.FROM_INV,
TDL.TO_INV
--TMH.FINAL_DESTINATION,
--TMH.TRANSPORT_MODE,
--TMH.VEHICLE_NO
--TMH.INITIAL_GATE_IN,
--TMH.GATE_OUT,
--TMH.GATE_IN
,TO_CHAR(TDH.TO_DATE) To_DATE
--,TO_CHAR(TMH.MOV_ORDER_DATE) MTO_DATE
,TDL.FROM_SUBINV
,TDL.TO_SUBINV
,TDL.QUANTITY
,TDH.TO_STATUS
--,TMH.MOV_ORDER_STATUS
,TDH.*
FROM
--XXAKG.XXAKG_TO_MO_HDR TMH,
--APPS.XXAKG_TO_MO_DTL TMD,
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
WHERE 1=1
AND TDH.ORG_ID=85
--AND TMD.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
--AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
AND TDH.TO_STATUS='GENERATED'
--AND TMH.MOV_ORDER_STATUS='CONFIRMED'
--AND TMH.MOV_ORDER_NO='MTO/SCOU/061900'
--AND TDL.TO_NUMBER='TO/MOU/000003'
--AND  TMH.TRANSPORT_MODE='Company Barge'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND TMH.FROM_INV='SCI'
--AND TDL.TO_INV='G10'
--AND TDH.TO_DATE<='31-MAY-2019'
AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_TO_MO_DTL TMD WHERE TMD.TO_HDR_ID=TDL.TO_HDR_ID)
ORDER BY TDL.TO_NUMBER DESC

------------------------------TO_MTO_GENERATED----------------------------------
SELECT
TDL.TO_NUMBER,
TDH.TO_STATUS,
TMH.MOV_ORDER_NO,
TMH.MOV_ORDER_STATUS,
TDL.ITEM_NUMBER,
TDL.ITEM_DESCRIPTION,
TDL.UOM_CODE,
TDL.FROM_INV,
TDL.TO_INV,
TMH.FINAL_DESTINATION,
TMH.TRANSPORT_MODE,
TMH.VEHICLE_NO
--TMH.INITIAL_GATE_IN
--TMH.GATE_OUT,
--TMH.GATE_IN
,TO_CHAR(TDH.TO_DATE) To_DATE
,TO_CHAR(TMH.MOV_ORDER_DATE) MTO_DATE
,TDL.FROM_SUBINV
,TDL.TO_SUBINV
,TDL.QUANTITY
--,TDH.*
FROM
XXAKG.XXAKG_TO_MO_HDR TMH,
APPS.XXAKG_TO_MO_DTL TMD,
APPS.XXAKG_TO_DO_HDR TDH,
XXAKG.XXAKG_TO_DO_LINES TDL
WHERE 1=1
AND TDH.ORG_ID=85
AND TMD.TO_HDR_ID=TDL.TO_HDR_ID
AND TDH.TO_HDR_ID=TDL.TO_HDR_ID
AND TMD.MOV_ORD_HDR_ID=TMH.MOV_ORD_HDR_ID
AND TDH.TO_STATUS='GENERATED'
AND TMH.MOV_ORDER_STATUS='GENERATED'
--AND TMH.MOV_ORDER_NO='MTO/SCOU/061900'
--AND TDL.TO_NUMBER='TO/MOU/000003'
--AND  TMH.TRANSPORT_MODE='Company Barge'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'DD-MON-RR') ='08-AUG-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TMH.MOV_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'
--AND TMH.FROM_INV='SCI'
--AND TDL.TO_INV='G10'
ORDER BY TDL.TO_NUMBER DESC