select * from apps.XXAKG_TO_MO_DETAIL_CEMENT

SELECT mhdr.MOV_ORD_HDR_ID,
          mhdr.ORG_ID,
          mhdr.MOV_ORDER_NO,
          mhdr.MOV_ORDER_DATE,
          mhdr.MOV_ORDER_STATUS,
          mhdr.MOV_ORDER_TYPE,
          mhdr.FINAL_DESTINATION,
          mhdr.FROM_INV,
          mhdr.TRANSPORT_MODE,
          mhdr.VEHICLE_NO,
          mhdr.GATE_OUT,
          mhdr.GATE_OUT_DATE,
          mhdr.GATE_IN,
          mhdr.GATE_IN_DATE,
          mhdr.CREATION_DATE,
          mhdr.CREATED_BY,
          mhdr.LAST_UPDATE_DATE,
          mhdr.LAST_UPDATED_BY,
          mhdr.VEHICLE_TYPE,
          mhdr.TRANSPORTER_NAME,
          mhdr.TRANSPORTER_VENDOR_ID,
          mhdr.TRANSPORTER_VENDOR_SITE_ID,
          mhdr.INITIAL_GATE_IN,
          mhdr.INITIAL_GATE_IN_DATE,
          mhdr.EMPTY_TRUCK_WT,
          mhdr.EMPTY_TRUCK_WT_DATE,
          mhdr.DRIVER_NAME,
          mhdr.DRIVER_MOBILE,
          mhdr.FULL_TRUCK_WT,
          mhdr.FULL_TRUCK_WT_DATE,
          mhdr.HIRE_RATE_AP,
          mhdr.HIRE_RATE_AR,
          mdtl.TO_NUMBER TRANSFER_ORDER_NO,
          mdtl.TO_INV,
          mdtl.CONFIRM_DATE,
          mdtl.TRANSFER_LOADING_DATE,
          mdtl.TRUCK_LOADING_DATE,
          mdtl.VAT_RECEIVED_DATE,
          mdtl.VAT_CHALLAN_NO,
          mdtl.VAT_CHALLAN_DATE,
          mdtl.VAT_IN_DATE,
          thdr.TO_STATUS,
          thdr.OPERATING_UNIT,
          thdr.TO_DATE TRANSFER_ORDER_DATE,
          thdr.MODE_OF_TRANSPORT,
          thdr.TRANSFER_DATE,
          thdr.HAND_OVER_DATE,
          thdr.DELIVERY_MODE,
          thdr.CUSTOMER_ID,
          thdr.CUSTOMER_NAME,
          tlin.ITEM_NUMBER,
          tlin.ITEM_DESCRIPTION,
          tlin.QUANTITY,
          tlin.UOM_CODE,
          tlin.FROM_SUBINV,
          tlin.TO_SUBINV,
          tlin.REMARKS,
          tlin.REMARKS_DATE,
          tlin.TERRITORY,
          tlin.FROM_ORGANIZATION_ID,
          tlin.TO_ORGANIZATION_ID
     --decode (ITEM_NUMBER,'CMNT.SBAG.0001', 'SPECIAL','CMNT.PBAG.0001', 'POPULER') ITEM_GROUP
     FROM XXAKG.XXAKG_TO_MO_HDR mhdr,
          XXAKG.XXAKG_TO_MO_DTL mdtl,
          XXAKG.XXAKG_TO_DO_HDR thdr,
          XXAKG.XXAKG_TO_DO_LINES tlin
    WHERE     mhdr.MOV_ORD_HDR_ID = mdtl.MOV_ORD_HDR_ID
          AND mdtl.TO_HDR_ID = thdr.TO_HDR_ID(+)
          AND thdr.TO_HDR_ID = tlin.TO_HDR_ID(+);