SELECT
OPERATING_UNIT,
MOV_ORDER_NO MOVE_TRANSFER_ORDER,
TO_CHAR(CONFIRM_DATE) CONFIRM_DATE,
TRANSFER_ORDER_NO,
TO_CHAR(TRANSFER_ORDER_DATE) TO_DATE,
FINAL_DESTINATION,
TO_INV ORG_CODE,
TO_SUBINV SUB_INVENTORY,
ITEM_DESCRIPTION,
QUANTITY
--,TO_MTO.*
FROM 
APPS.XXAKG_TO_MO_DETAIL_CEMENT TO_MTO
WHERE 1=1
AND TO_INV=:P_TRANSFER_ORG
AND MOV_ORDER_STATUS='CONFIRMED'
AND TO_CHAR (TRANSFER_ORDER_DATE, 'MON-RR') =:P_PERIOD_NAME-- 'JAN-18'
--AND TO_CHAR (TRANSFER_ORDER_DATE, 'RRRR') =:P_YEAR-- '2018'