SELECT
VAL_SET.FLEX_VALUE_SET_NAME,
FFV.FLEX_VALUE
,FFV.DESCRIPTION
--,FFV.*
--,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES_VL FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_Company'
--AND VAL_SET.FLEX_VALUE_SET_ID='1014887'
--AND FFV.FLEX_VALUE='GHAT51'


--------------------------------------------------------------------------------
SELECT
FLEX_VALUE_SET_NAME
,FFV.FLEX_VALUE_MEANING NATURAL_ACCOUNT
,FFV.DESCRIPTION NATURAL_ACCOUNT_NAME
--,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES_VL FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
--AND FFV.FLEX_VALUE='4020106'
--AND FFV.FLEX_VALUE_SET_ID=1014889
AND FFV.DESCRIPTION LIKE '%On%Account%'
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_Natural Accounts'

--------------------------------------------------------------------------------
SELECT
FLEX_VALUE_SET_NAME
,FFV.FLEX_VALUE_MEANING NATURAL_ACCOUNT
,FFV.DESCRIPTION NATURAL_ACCOUNT_NAME
--,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES_VL FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
--AND FFV.FLEX_VALUE='4020106'
--AND FFV.FLEX_VALUE_SET_ID=1014889
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_CostCentre'

--------------------------------------------------------------------------------


SELECT
VAL_SET.FLEX_VALUE_SET_NAME,
FFV.FLEX_VALUE
,FFV.*
--,FFV.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_Natural Accounts'
--AND VAL_SET.FLEX_VALUE_SET_ID='1014887'
AND FFV.FLEX_VALUE='4020106'

SELECT
*
FROM
APPS.gl_code_combinations gcc