------------------------SCRAP Order Pending Issue-------------------------
SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID,
OOL.FLOW_STATUS_CODE,
OOH.FLOW_STATUS_CODE ORDER_STATUS,
OOL.UNIT_SELLING_PRICE,
(OOL.UNIT_SELLING_PRICE*OOL.ORDERED_QUANTITY) AMOUNT
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
--AND OOH.FLOW_STATUS_CODE='BOOKED'
AND OOH.ORDER_TYPE_ID=1101
--AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
--AND OOL.SHIPMENT_PRIORITY_CODE IS NULL
AND OOH.ORG_ID=85
--AND OOH.ORDER_NUMBER=:P_ORDER_NUMBER

------------------------SCRAP Move Confirmed But Not Invoiced-------------------------
SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR(MOH.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID
,OOD.ORGANIZATION_CODE
--,NVL(SUM(MOQD.PRIMARY_TRANSACTION_QUANTITY),0)  ONHAND_QUANTITY
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_MOV_ORD_HDR MOH
,APPS.XXAKG_MOV_ORD_DTL MODT
,APPS.ORG_ORGANIZATION_DEFINITIONS OOD
--,INV.MTL_SYSTEM_ITEMS_B MSI
--,INV.MTL_ONHAND_QUANTITIES_DETAIL MOQD
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER
AND MOH.MOV_ORD_HDR_ID=MODT.MOV_ORD_HDR_ID
AND OOL.SHIP_FROM_ORG_ID=OOD.ORGANIZATION_ID
--AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
--AND MSI.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
--AND OOL.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
--AND OOL.ORDER_QUANTITY_UOM=MSI.PRIMARY_UOM_CODE
--AND MOQD.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
--AND MOQD.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('SCRP.TYRE.0001')
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
AND OOH.ORDER_TYPE_ID=1101
AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
GROUP BY
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.SHIPMENT_PRIORITY_CODE,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR(MOH.CONFIRMED_DATE),
OOL.SHIP_FROM_ORG_ID
,OOD.ORGANIZATION_CODE


--------------------------SCRAP Required Quantity in Stock---------------------------------
SELECT 
REQUESTED.ORDERED_ITEM,
--REQUESTED.ORDERED_QUANTITY,
REQUESTED.ORDER_QUANTITY_UOM,
--REQUESTED.DO_NUMBER,
--REQUESTED.MOV_ORDER_NO,
--REQUESTED.MOV_ORDER_STATUS,
--REQUESTED.MOVE_CONFIRMED_DATE,
REQUESTED.ORGANIZATION_ID,
(SELECT ORGANIZATION_CODE FROM APPS.ORG_ORGANIZATION_DEFINITIONS ORG WHERE ORG.ORGANIZATION_ID=REQUESTED.ORGANIZATION_ID) WAREHOUSE_ORG_CODE,
SUM(REQUESTED.ORDERED_QUANTITY) REQUESTED_QUANTITY,
NVL(STOCK.ONHAND_QUANTITY,0) ONHAND_QUANTITY,
(SUM(REQUESTED.ORDERED_QUANTITY)-NVL(STOCK.ONHAND_QUANTITY,0)) REQUIRED_QUANTITY
FROM
(SELECT
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
OOL.INVENTORY_ITEM_ID,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR(MOH.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_MOV_ORD_HDR MOH
,APPS.XXAKG_MOV_ORD_DTL MODT
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER
AND MOH.MOV_ORD_HDR_ID=MODT.MOV_ORD_HDR_ID
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
AND OOH.ORDER_TYPE_ID=1101
--AND OOL.ORDERED_ITEM=:P_ORDERED_ITEM
AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL) REQUESTED,
(SELECT 
SUM(MOQD.PRIMARY_TRANSACTION_QUANTITY)  ONHAND_QUANTITY, 
MOQD.ORGANIZATION_ID, 
MOQD.INVENTORY_ITEM_ID 
FROM 
INV.MTL_ONHAND_QUANTITIES_DETAIL MOQD 
WHERE 1=1
GROUP BY MOQD.ORGANIZATION_ID, MOQD.INVENTORY_ITEM_ID  ) STOCK
WHERE 1=1
AND STOCK.INVENTORY_ITEM_ID(+)=REQUESTED.INVENTORY_ITEM_ID
AND STOCK.ORGANIZATION_ID(+)=REQUESTED.ORGANIZATION_ID
GROUP BY 
REQUESTED.ORDERED_ITEM,
--REQUESTED.ORDERED_QUANTITY,
REQUESTED.ORDER_QUANTITY_UOM,
--REQUESTED.DO_NUMBER,
--REQUESTED.MOV_ORDER_NO,
--REQUESTED.MOV_ORDER_STATUS,
--REQUESTED.MOVE_CONFIRMED_DATE,
REQUESTED.ORGANIZATION_ID,
NVL(STOCK.ONHAND_QUANTITY,0)


------------------------------------------------------------------------------------------------

SELECT
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) QUANTITY
FROM
APPS.OE_ORDER_LINES_ALL OOL,
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
,APPS.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1 
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DODL.SHIP_TO_ORG_ID=OOL.SHIP_TO_ORG_ID
AND DODL.ORDER_NUMBER=OOH.ORDER_NUMBER
AND DODL.ORDER_LINE_ID IS NULL
AND DODL.ORDER_HEADER_ID IS NOT NULL
AND DODL.ORDERED_ITEM_ID=OOL.INVENTORY_ITEM_ID
--AND CUST.CUSTOMER_NUMBER IN ('20058','33530','20061','20059','20062','23688','23691','23868','35499','20069','20068','23811')
AND OOH.HEADER_ID=OOL.HEADER_ID
--AND OOH.ORDER_NUMBER =:P_ORDER_NUMBER 
--AND OOH.ORDER_NUMBER IN ('1706069')
--AND OOL.ORDER_QUANTITY_UOM='MTN'
--AND OOL.ORDERED_ITEM='SCRP.CAN0.0001'
AND OOH.FLOW_STATUS_CODE IN ('CLOSED','BOOKED')
AND OOL.FLOW_STATUS_CODE!='CANCELLED'-- NOT IN ('CLOSED','CANCELLED','ENTERED','AWAITING_SHIPPING','AWAITING_RETURN_DISPOSITION','AWAITING_RETURN','BOOKED','SHIPPED','FULFILLED','RETURNED')
--AND OOL.SHIPMENT_PRIORITY_CODE=:P_DO_NUMBER
--AND TO_CHAR (OOL.ACTUAL_SHIPMENT_DATE, 'MON-RR') = 'APR-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'MON-RR') = 'SEP-18'
--AND TO_CHAR (OOH.ORDERED_DATE, 'RRRR') = '2018'
AND ORDER_TYPE_ID=1101
AND OOH.ORG_ID=85
--AND OOH.SHIP_FROM_ORG_ID=1346
--AND NOT EXISTS(SELECT 1 FROM APPS.XXAKG_DEL_ORD_DO_LINES DODL WHERE DODL.ORDER_NUMBER=OOH.ORDER_NUMBER)
GROUP BY 
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME
,DODL.DO_NUMBER
,OOH.ORDERED_DATE 
--ORDER BY OOH.ORDERED_DATE DESC
