-------------------------------------------------SCRAP-----------------------------------------------

SELECT 
--DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
SUM(DODL.LINE_QUANTITY) QUANTITY,
--MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
--MOH.TRANSPORTER_NAME,
DODL.ITEM_DESCRIPTION
,DOH.DO_STATUS
,DODL.WAREHOUSE_ORG_CODE
FROM 
--APPS.XXAKG_DISTRIBUTOR_BLOCK_M DBM,
--XXAKG.XXAKG_MOV_ORD_HDR MOH,
--XXAKG.XXAKG_MOV_ORD_DTL MODT,
XXAKG.XXAKG_DEL_ORD_DO_LINES DODL,
XXAKG.XXAKG_DEL_ORD_HDR DOH
WHERE 1=1
--AND MODT.MOV_ORD_HDR_ID=MOH.MOV_ORD_HDR_ID
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
--AND DOH.DO_NUMBER=MODT.DO_NUMBER
--AND MODT.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
AND DOH.DO_NUMBER=DODL.DO_NUMBER
--AND DBM.REGION_NAME='Scrap'
--AND DBM.CUSTOMER_NUMBER=DOH.CUSTOMER_NUMBER
--AND DOH.DO_NUMBER=:P_DO_NUMBER
AND DOH.ORG_ID=85
--AND DOH.ORG_ID=MOH.ORG_ID
AND DOH.DO_STATUS='GENERATED'
--AND MOH.MOV_ORDER_STATUS='GENERATED'
AND EXISTS (SELECT 1 FROM APPS.OE_ORDER_LINES_ALL OOL, APPS.OE_ORDER_HEADERS_ALL OOH WHERE OOL.HEADER_ID=OOH.HEADER_ID AND DODL.ORDER_NUMBER=OOH.ORDER_NUMBER AND OOH.HEADER_ID=DODL.ORDER_HEADER_ID  AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING' AND OOH.ORDER_TYPE_ID=1101)
--AND TO_CHAR (DOH.DO_DATE, 'RRRR') = '2017'
GROUP BY 
--DBM.REGION_NAME,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DOH.DO_NUMBER,
--MOH.MOV_ORDER_NO,
DOH.MODE_OF_TRANSPORT,
--MOH.TRANSPORTER_NAME,
DODL.ITEM_DESCRIPTION
,DOH.DO_STATUS
,DODL.WAREHOUSE_ORG_CODE