SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
OOL.ORDER_QUANTITY_UOM,
MSI.PRIMARY_UOM_CODE,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR(MOH.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID
,NVL(STOCK.ONHAND_QUANTITY,0) ONHAND_QUANTITY
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_MOV_ORD_HDR MOH
,APPS.XXAKG_MOV_ORD_DTL MODT
,INV.MTL_SYSTEM_ITEMS_B MSI
,(SELECT SUM(MOQD.PRIMARY_TRANSACTION_QUANTITY) ONHAND_QUANTITY, ORGANIZATION_ID, INVENTORY_ITEM_ID FROM INV.MTL_ONHAND_QUANTITIES_DETAIL MOQD GROUP BY ORGANIZATION_ID, INVENTORY_ITEM_ID) STOCK
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER
AND MOH.MOV_ORD_HDR_ID=MODT.MOV_ORD_HDR_ID
AND MSI.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
AND OOL.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
AND STOCK.ORGANIZATION_ID(+)=OOL.SHIP_FROM_ORG_ID
AND STOCK.INVENTORY_ITEM_ID(+)=MSI.INVENTORY_ITEM_ID
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('SCRP.TYRE.0001')
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
AND OOH.ORDER_TYPE_ID=1101
AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL


-----------------------------------------------------------------------------------------------------------------------


SELECT
OOH.ORDER_NUMBER,
OOL.ORDERED_ITEM,
OOL.ORDERED_QUANTITY,
(OOL.UNIT_SELLING_PRICE_PER_PQTY*OOL.ORDERED_QUANTITY) AMOUNT,
OOL.ORDER_QUANTITY_UOM,
MSI.PRIMARY_UOM_CODE,
OOL.SHIPMENT_PRIORITY_CODE DO_NUMBER,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR(MOH.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,
OOL.SHIP_FROM_ORG_ID ORGANIZATION_ID
,NVL(STOCK.ONHAND_QUANTITY,0) ONHAND_QUANTITY
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
,APPS.XXAKG_MOV_ORD_HDR MOH
,APPS.XXAKG_MOV_ORD_DTL MODT
,INV.MTL_SYSTEM_ITEMS_B MSI
,(SELECT SUM(MOQD.PRIMARY_TRANSACTION_QUANTITY) ONHAND_QUANTITY, ORGANIZATION_ID, INVENTORY_ITEM_ID FROM INV.MTL_ONHAND_QUANTITIES_DETAIL MOQD GROUP BY ORGANIZATION_ID, INVENTORY_ITEM_ID) STOCK
WHERE 1=1
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER
AND MOH.MOV_ORD_HDR_ID=MODT.MOV_ORD_HDR_ID
AND MSI.ORGANIZATION_ID=OOL.SHIP_FROM_ORG_ID
AND OOL.INVENTORY_ITEM_ID=MSI.INVENTORY_ITEM_ID
AND STOCK.ORGANIZATION_ID(+)=OOL.SHIP_FROM_ORG_ID
AND STOCK.INVENTORY_ITEM_ID(+)=MSI.INVENTORY_ITEM_ID
--AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('SCRP.TYRE.0001')
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
AND OOH.ORDER_TYPE_ID=1101
AND OOL.ACTUAL_SHIPMENT_DATE IS NULL
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL

