
select
dl.ORDER_NUMBER,dl.ITEM_NUMBER,dl.ITEM_DESCRIPTION,dl.LINE_QUANTITY DO_Quantity,dl.UOM_CODE,dh.DO_NUMBER,to_char(dh.DO_DATE) DO_DATE,mh.MOV_ORDER_NO,to_char(mh.CONFIRMED_DATE) MOVE_CONFIRMED_DATE,dl.WAREHOUSE_ORG_CODE
from
apps.xxakg_mov_ord_hdr mh,apps.xxakg_mov_ord_dtl md,
apps.xxakg_del_ord_hdr dh,apps.xxakg_del_ord_do_lines dl
where mh.mov_ord_hdr_id=md.mov_ord_hdr_id
and md.do_hdr_id=dh.do_hdr_id
and dh.do_hdr_id=dl.do_hdr_id
and exists (select 1 from apps.oe_order_lines_all ol,apps.oe_order_headers_all oh where oh.header_id=ol.header_id and ol.header_id=dl.order_header_id and ol.shipment_priority_code=dh.do_number and ol.org_id=dh.org_id and ol.flow_status_code='AWAITING_SHIPPING' and oh.order_type_id=1101)
and mh.org_id=85
and dl.WAREHOUSE_ORG_CODE in ('SCI','PSU')
and mh.mov_order_status='CONFIRMED'









----------------------------------------------------------------------------------------------------------
SELECT
ORDER_ALL.ORG_ID,
ORDER_ALL.ORDER_NUMBER,
ORDER_ALL.ORDERED_DATE,
ORDER_ALL.ORDERED_QUANTITY,
ORDER_ALL.ORDERED_ITEM,
DO_ALL.CUSTOMER_NUMBER,
DO_ALL.CUSTOMER_NAME,
DO_ALL.DO_NUMBER,
DO_ALL.DO_DATE,
DO_ALL.DO_STATUS,
DO_ALL.DO_QUANTITY,
DO_ALL.MODE_OF_TRANSPORT,
DO_ALL.UOM_CODE,
DO_ALL.WAREHOUSE_ORG_CODE,
MOH.MOV_ORDER_NO,
MOH.MOV_ORDER_STATUS,
TO_CHAR (MOH.CONFIRMED_DATE, 'DD-MON-YYYY') CONFIRMED_DATE
FROM
(SELECT
OOH.HEADER_ID,
OOH.ORG_ID,
OOH.ORDER_NUMBER,
TO_CHAR (OOH.ORDERED_DATE, 'DD-MON-YYYY') ORDERED_DATE,
SUM(OOL.ORDERED_QUANTITY) ORDERED_QUANTITY,
OOL.ORDERED_ITEM,
OOL.ORDERED_ITEM_ID,
OOL.FLOW_STATUS_CODE,
OOL.SHIPMENT_PRIORITY_CODE
FROM
APPS.OE_ORDER_HEADERS_ALL OOH
,APPS.OE_ORDER_LINES_ALL OOL
WHERE 1=1
AND OOH.ORG_ID=85
AND OOH.HEADER_ID=OOL.HEADER_ID
AND OOL.FLOW_STATUS_CODE='AWAITING_SHIPPING'
AND OOH.ORDER_TYPE_ID='1101'
AND OOL.SHIPMENT_PRIORITY_CODE IS NOT NULL
GROUP BY 
OOH.HEADER_ID,
OOH.ORG_ID,
OOH.ORDER_NUMBER,
ORDERED_DATE,
OOL.ORDERED_ITEM_ID,
OOL.ORDERED_ITEM,
OOL.FLOW_STATUS_CODE,
OOL.SHIPMENT_PRIORITY_CODE) ORDER_ALL,
(SELECT 
DODL.ORDER_HEADER_ID,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER ORDER_NO,
DODL.DO_NUMBER,
TO_CHAR (DOH.DO_DATE, 'DD-MON-YYYY') DO_DATE,
DOH.DO_STATUS,
SUM(DODL.LINE_QUANTITY) DO_QUANTITY,
DODL.ORDERED_ITEM_ID,
DOH.MODE_OF_TRANSPORT,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE
FROM
APPS.XXAKG_DEL_ORD_HDR DOH
,APPS.XXAKG_DEL_ORD_DO_LINES DODL
WHERE 1=1
AND DOH.ORG_ID=85
AND DOH.DO_HDR_ID=DODL.DO_HDR_ID
AND DOH.DO_STATUS='CONFIRMED'
--AND DOH.DO_DATE BETWEEN '01-JAN-2017' and '08-OCT-2017'
GROUP BY 
DODL.ORDER_HEADER_ID,
DOH.CUSTOMER_NUMBER,
DOH.CUSTOMER_NAME,
DODL.ORDER_NUMBER,
DODL.DO_NUMBER,
DO_DATE,
DOH.DO_STATUS,
--DODL.ITEM_NUMBER,
--DODL.ITEM_DESCRIPTION,
DODL.ORDERED_ITEM_ID,
DOH.MODE_OF_TRANSPORT,
DODL.UOM_CODE,
DODL.WAREHOUSE_ORG_CODE) DO_ALL,
APPS.XXAKG_MOV_ORD_DTL MODT,
APPS.XXAKG_MOV_ORD_HDR MOH
WHERE 1=1
AND ORDER_ALL.ORDERED_ITEM_ID=DO_ALL.ORDERED_ITEM_ID
AND ORDER_ALL.SHIPMENT_PRIORITY_CODE=DO_ALL.DO_NUMBER
AND MODT.MOV_ORD_HDR_ID = MOH.MOV_ORD_HDR_ID
AND ORDER_ALL.SHIPMENT_PRIORITY_CODE=MODT.DO_NUMBER



